### ISSUE TITLE
Changing the focal point on an image

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#100]
I tested the ability to change the image position in the hero for the our team page.  I wanted the position of this image to look the same way it does in the pattern library.  I tried a few different times to move the image focal point using the tool in the CMS but I don't think that any changes were coming through.

**Comment by akmiller01** [comment]
This is being deployed right now @k8hughes . Do you want to give it a test and then close this issue if all is good? I've added closer cropping to the focalpoint.

Also, the image may not look the same as it does in the Pattern Library if you're missing hero-text. The height of that div is set by the amount of text, so quite a bit of the hero image is missing if you don't also have lorum ipsum in the hero text.

**Comment by k8hughes** [comment]
LGTM - I've moved the focal point a few different ways and now it works perfectly.

**Comment by akmiller01** [comment]
Brilliant. Now in future, if ever we want to make images more responsive to focal-point adjustments the way is `-c100`
