### ISSUE TITLE
Chapter summary B template

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#1001]
**Sketch:** https://marvelapp.com/prototype/3j51290/screen/79875843

**Design:** https://development-initiatives.surge.sh/page-templates/14a-publication-summary-v2

### Summary

We've prepared a "B" template for an A/B test on the chapter summary. Then plan is to implement and use this in an A/B test on the upcoming 2021 GHA report. 

There are two updates to the template: 

#### 1. We've included three buttons to the header

• ‘Read the report’ – jumps to the start of content
• ‘Download options’ – jumps to the bottom of the page where the downloads are
• ‘Order a hard copy of the report’ - jumps the user to the call to action module

In the design I've added an id of `hardcopy` to the CTA block, and linked to that.

#### 2. We've updated the chapter blocks to include a list of their sections with a show/hide function

When adding the lists, you need to add data attributes to the `<ul>`. The JS automatically creates the "show/hide" button. 

Note, I've included a class of `space-section-bottom--small` on the last list item, to space the button away from the list. 

---

### Original brief from Simon:

- Part 1
Adding two additional action button boxes so they sit on the hero image (see PDF1). The three button boxes to read

• ‘Read the report’
• ‘Download options’
• ‘Order a hard copy of the report’

All these options should follow the current ‘download’ button’s behaviour – jumping the user down the page.

• ‘Read the report’ – jumps to the start of content
• ‘Download options’ – jumps to the bottom of the page where the downloads are
• ‘Order a hard copy of the report’ – jumps the user to the call to action module (NB we’re currently working on amending the code for this so it can be positioned anywhere on the page – we’ll let you know if we need help with that!) (NB2 – we might not always want this third button box to say ‘order a hard copy of the report’ button will be very rarely used, so it might make more sense to add code to the call to action module so we can choose (1) if we want it to appear as a button box option at the top and (2) what text we’d want it to show.

Part 2 (PDF 2)
We’d like to incorporate the pop-up menu’s feature (showing all the chapters’ subsections) into the current chapter summaries. We’d like seeing these to be an option the user selects – boxes that grow and close on click to help the user browse deeper into the content. I don’t think the text is quite right in the PDF – perhaps better to go with ‘See more’ and ‘See less’ (or another suggestion).
This won’t replace the ‘Read chapter one’ box button, which should remain separate and take the user to the top of the chapter page. If the users clicks see more, the section titles they see should ‘go bold’ when the mouse hovers over them (as per the current menu) and should take the user to that section of a chapter page.

We’re not planning on having individual PDF downloads or data downloads per chapter, which should make these sections of the page less busy

Obviously the bottom right menu would no longer be needed on this version of the summary page

**Comment by benjamincoleman** [comment]
@SimonMurphyDI this is ready for you to review :)

**Comment by SimonMurphyDI** [comment]
Thanks @benjamincoleman 

My feedback is

- The 'read the report' button should jump the user down so the the first chapter module is at the top of their screen
- The space between the buttons should be the same as the space between the Read/Download buttons on the current report summary page
- Clicking on the 'Show/hide chapter' content buttons causes the image to jump, which is distracting. The image should be anchored to the module title and retain its position and size.
- The 'Show/hide chapter' buttons should all feature the same sized text, and be wider to accept the text
- The 'Show/hide chapter' buttons should both be the same text and background colour as the 'Read chapter' button
- When you click 'Read the report' the button stays the highlight colour. It should return to the original state.
- I assume that a report chapter without any subheadings (ie the foreword) would only have the 'Read chapter'?
- Would the 'request a hard copy' button be customisable? (May be that's an element that would be built up by the devs.)
- Can the first box say 'Read online' rather than 'Read the report.'?

Thanks!
S

**Comment by benjamincoleman** [comment]
@SimonMurphyDI

We've updated the template, some comments on some of the change requests though: 

**Clicking on the 'Show/hide chapter' content buttons causes the image to jump, which is distracting. The image should be anchored to the module title and retain its position and size.**

There's nothing we can do about this at the moment without an overhaul of the way both this and the current summary templates are built. As we're testing we've not done this at this point, but can in the future. 

**I assume that a report chapter without any subheadings (ie the foreword) would only have the 'Read chapter'?**

We can make sure this happens, but it's a development issue.

**Would the 'request a hard copy' button be customisable? (May be that's an element that would be built up by the devs.)**

Again, dev issue, but yes this is possible

**Comment by SimonMurphyDI** [comment]
Looks good - thanks @benjamincoleman!

@edwinmp, did you and Kate speak about the process for using A/B testing to trial this?

Best
Simon

**Comment by edwinmp** [comment]
@SimonMurphyDI, yes she did ... let me know when you want us to get started

**Comment by SimonMurphyDI** [comment]
@edwinmp sounds good! You're happy to build Ben's design now, and I can test it?

**Comment by edwinmp** [comment]
Sure, @SimonMurphyDI ... will start on it tomorrow.

**Comment by SimonMurphyDI** [comment]
Hello both - I'm on leave from next Wednesday - is it possible that we could have this up and running by then?
Best
Simon

**Comment by edwinmp** [comment]
Hi @SimonMurphyDI ... we'll have this done by end of day tomorrow.

**Comment by SimonMurphyDI** [comment]
fabulous - thanks! I'm off tomorrow - have a great weekend

**Comment by edwinmp** [comment]
@SimonMurphyDI this is ready for testing on dev ... let me know when you have some time for a call to take you briefly through Google Optimize

**Comment by SimonMurphyDI** [comment]
thanks @edwinmp! Will book one in

**Comment by SimonMurphyDI** [comment]
Hi @edwinmp  thanks so much for doing this! Can't wait to trial it. 

Top boxes - please can the 'o' of 'Read online' be lower case? 

(On desktop view) When clicking on the 'Show chapter content' button, the image loses its alignment and jumps down, which is distracting.
 
After clicking on 'Show chapter content' the 'hide chapter content' button remains highlighted red until you click off it. After you click the 'hide chapter content' button the 'show chapter content' button remains highlighted 

The boxes don't quite align (top and bottom) but this is a (tiny) issue with the current page
![image](https://user-images.githubusercontent.com/22001094/125594811-1af0b933-1706-4a51-9bde-1f486d02789a.png)

There's no option to 'download a chapter' but i guess that would be the case if there were individual chapters uploaded?

Let me know if any of those is unclear and I can share my screen

S

**Comment by davidebukali** [comment]
Hi @SimonMurphyDI to feedback on your comment, yes we can update the 'o' of Read online to be lower case. There is a field in the CMS provided to edit most of hero button titles.

On the image losing its alignment, Ben says in this [comment](https://github.com/devinit/DIwebsite-redesign/issues/1001#issuecomment-862433504) would require a large overhaul of the entire template.

@Ben what do you think about the `Show chapter contents` button having persistent highlights after clicking. Also misalignment of the boxes shown in attached image.  

@SimonMurphyDI there is a list of chapter downloads at the end of the summary page; Did you need individual chapter downloads for each section next to `Show chapter contents` ?

**Comment by SimonMurphyDI** [comment]
Thanks @davidebukali 

To help us make a decision about the images losing their alignment, can you estimate the time it would take to change the code, and any risks associated with that? If you had any suggested workarounds we'd be happy to consider them. 

I'll let you know about the downloads suggestion/question

Thanks!
Simon

**Comment by edwinmp** [comment]
> To help us make a decision about the images losing their alignment, can you estimate the time it would take to change the code, and any risks associated with that? If you had any suggested workarounds we'd be happy to consider them.

@benjamincoleman ^^

**Comment by benjamincoleman** [comment]
@SimonMurphyDI @edwinmp 

I think we could update the pattern library JS / CSS to alter the image positioning when the list is opened. Probably 1-2 hours of time to test I would say.

**Comment by SimonMurphyDI** [comment]
Thanks - I don't think we need to fix the jumping images for this test run. If we decide to switch over to the new template, then we can spend this time updating the pattern library. 

@davidebukali  - it would be good to keep the functionality of "chapter downloads" for each section next to Show chapter contents button, but again, not needed for A/B testing as we don't have individual chapter downloads for this GHA#

Thanks!

**Comment by alice-mcandrew-development-initatives** [comment]
@benjamincoleman @davidebukali, I can review anything while Simon is away next week if needed.
Is the issue of the button having persistent highlights after clicking being resolved for the test run? 
And would the misalignment of the boxes be fixed as part of fixing the image jump, which wouldn't be needed until after testing?

**Comment by davidebukali** [comment]
Thank you @alice-mcandrew-development-initatives, am not sure if the design team got a green light to work on these tasks, @benjamincoleman ^^

**Comment by benjamincoleman** [comment]
@davidebukali 

Sorry, I missed your earlier comments.  

> @benjamincoleman what do you think about the Show chapter contents button having persistent highlights after clicking. 

This is the button maintaining its Focus state, so semantically it's probably appropriate. We could remove it with CSS though. What do you think? 

> Also misalignment of the boxes shown in attached image of the previous comment.

We've fixed this on the `patterns` branch

Is there anything else you needed us to look at?

**Comment by alice-mcandrew-development-initatives** [comment]
@davidebukali, I think you're OK to proceed with setting up the A/B testing? Let me know if there's any support I can offer though

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives great, will deploy live later today and set up the A/B testing latest tomorrow morning.

**Comment by SimonMurphyDI** [comment]
Thanks @edwinmp, you're a star! I've just checked in on this and we've only had 37 sessions in 34 days - this seems quite low. Is there a way to increase the number of users the A/B testing considers? 
Cheers
Simon

**Comment by edwinmp** [comment]
@SimonMurphyDI so sorry, with so much pulling at me, I forgot to deploy this. Also, the existing optimise session was for testing dev. I'm creating another for live.

**Comment by SimonMurphyDI** [comment]
That's ok! Do not worry at all - so much going on at the moment, and everyone is getting pulled in every direction. Thanks again :)

**Comment by edwinmp** [comment]
@SimonMurphyDI I've created a new optimize experiment for the live site ... it'll run till November 10th

**Comment by edwinmp** [comment]
For clarity, @SimonMurphyDI, you want the `Jump to Section` feature to be available for both versions? After which, we run another Google Optimise A/B test ...

**Comment by SimonMurphyDI** [comment]
Thanks Edwin - what do you think? Given that the new design doesn't take any features away, but provides new featured, and that the AB testing hasn't given us particularly large sample sizes, would you be comfortable pushing it live and seeing how users respond via the full analytics data?

**Comment by SimonMurphyDI** [comment]
@edwinmp I guess we should set up a tag for 'show chapter contents', and keen to check that 'request a hard copy' in the banner is optional (as we won't always have one)

![image](https://user-images.githubusercontent.com/22001094/196898682-472f32ed-0031-4073-b93f-c537e6f8f90d.png)

**Comment by SimonMurphyDI** [comment]
(and yes, we'd like the 'jump to section' to be included as well) - thanks!

**Comment by edwinmp** [comment]
@SimonMurphyDI one of the differences is the absence of the download button for template B. Do I leave that out here or have it as below?
<img width="934" alt="image" src="https://user-images.githubusercontent.com/5672438/197073546-19e6958a-47be-47a4-856f-4f0ab3666977.png">

You can test the full template [here](https://dev.devinit.org/resources/global-humanitarian-assistance-report-2021/)

**Comment by SimonMurphyDI** [comment]
Thanks - let's keep it for now. Once the page launches we can turn hotjar onto this page and see whether it's being used on the heatmaps, and then remove if we want to

**Comment by edwinmp** [comment]
@SimonMurphyDI this is now live ... let me see if @davidebukali  can do some magic on the analytics. Could you please write something up in a comment that covers all you need monitored.
