### ISSUE TITLE
Adding section sharing feature for case studies.

### ISSUE THREAD

**Issue by LouiseSummerlring** [devinit/DIwebsite-redesign#1013]
**Is your feature request related to a problem? Please describe.**
Not a problem, just something nice to have.

**Describe the solution you'd like**
Users are currently able to share sections of our reports, as well as individual figures. On the website, these functions are named 'Share section' and 'Share chart'. We would like for users to be able to share case studies in the same way. This would mean adding the same functionality whenever a case study is uploaded as part of a wider report upload in the CMS. The wording for this should be 'Share box'. 

**Describe alternatives you've considered**
We don't currently have this functionality, and that's not necessarily a problem - it would just be nice for users to be able to share case studies.

**Additional context**
If anything is unclear, please just let me know.

**Requested Delivery Date:** 
Not urgent, no specific delivery date required.

**Comment by benjamincoleman** [comment]
@LouiseSummerlring @edwinmp Do you want us to pick up this to create sketches / designs?

**Comment by edwinmp** [comment]
Not at the moment, @benjamincoleman, thanks for asking ... will let you know when we need a hand :)

**Comment by ThatcherK** [comment]
Hi @LouiseSummerlring  this feature is ready for testing on https://dev.devinit.org/

**Comment by LouiseSummerlring** [comment]
@ThatcherK Sorry, I missed this! I've tested the 'Share box' functionality and it looks great, thanks so much! I'm happy for it to go ahead. Let me know if you need anything further from me.
