### ISSUE TITLE
Search on DI site is quite sentitive

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#1031]
**Is your feature request related to a problem? Please describe.**

I think the search function on the site brings up any results with the search terms in the content - this means you often get loads and loads of hits for quite general searches. 

Could we amend the search so it only returns results that include the search terms in the resource title, or in the meta-description category?

Not urgent (It would be good to have this in addition to the promoted search function.)

Thanks!
Simon

**Comment by davidebukali** [comment]
@SimonMurphyDI this is ready for testing on [staging](https://dev.devinit.org/)

**Comment by SimonMurphyDI** [comment]
Thanks @davidebukali - on the whole this is much better.

Occasionally searches return some results I don't understand - for example, searching 'humanitarian' returns 'Adapting aid to end poverty' - this paper doesn't feature 'humanitarian' in the title, the hero text or the metadescription.

Also, searching for 'data' returns the 2021 GHA report - this paper doesn't feature 'data' in the title, the hero text or the metadescription.

It would be great to know what elements of a resource page the searches are set to consider, as that could explain why these pages are being returned?

**Comment by davidebukali** [comment]
@SimonMurphyDI ^^

**Comment by SimonMurphyDI** [comment]
Thanks @akmiller01  and @davidebukali 

After speaking to the team about this - we felt that the best option would be to trust the work we do getting key search terms into titles and meta-descriptions. So, our suggestion is to amend the search settings so that:
- only titles, meta-descriptions and heroes are searched (for short publications, and publication pages (including their children))
- 'newest first' remains the default search setting.

I guess we'd want to make it so that a search hit in the title/hero/meta-descr of a publication page's child page returns the parent publication as a search response. For example, at the moment if I search for "Humanitarian and wider crisis financing" (the title of a GHA chapter) the GHA parent publication is not returned as a result.

How do you feel about that? We can use analytics to see how this change affects users' behaviour after a few months. 

Best
Simon

**Comment by akmiller01** [comment]
Yep sounds good. I'll leave the code changes to you, @davidebukali!

**Comment by edwinmp** [comment]
@davidebukali please update the status of this ticket

**Comment by davidebukali** [comment]
@edwinmp thanks for the flag, @SimonMurphyDI this is ready for testing on [staging](https://dev.devinit.org/resources/)

**Comment by davidebukali** [comment]
@edwinmp this still needs some work, at the moment it returns executive summaries before the parent publications.

**Comment by akmiller01** [comment]
I think there was some misunderstanding here. Search results are contingent on child pages, but the child pages themselves are not meant to show up in the search index. They don't have a _score annotation and therefore throw a 500 err when sorted by relevance.

**Comment by davidebukali** [comment]
@SimonMurphyDI this is ready for testing on [dev](https://dev.devinit.org/resources/?nav=header)

**Comment by SimonMurphyDI** [comment]
Hello @davidebukali just had a look and not seeing any resources at all on Dev....

**Comment by davidebukali** [comment]
Hi @SimonMurphyDI sorry I just got back today after 1 week on leave; kindly log into the website and try again, appears that private pages are visible to only logged in users.

**Comment by SimonMurphyDI** [comment]
Hi @davidebukali - it looks like this has been pushed to the main site and is live there? It seems to be working well :)
