### ISSUE TITLE
505 from copying a short publication in data section

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#1032]
## I'm submitting a ...
[X] Bug

**Describe the issue**
I copied the [real-time aid tracker](https://devinit.org/data/tracking-aid-flows-in-light-of-the-covid-19-crisis/).
![image](https://user-images.githubusercontent.com/55877063/127980368-f81ae637-0086-49f4-8186-a8bbe6f6ad35.png)

But was unable to amend the URL or title when creating the new page (even though I could amend to not publish). 
![image](https://user-images.githubusercontent.com/55877063/127980595-d9b61dc3-f65b-4cf9-94b4-daa4867f3482.png)

The page was created (as a direct duplicate) and I got a 505 error message. And when I try to amend the URL or title now I still get the same error message.
![image](https://user-images.githubusercontent.com/55877063/127979575-124f9d66-85ed-4fc5-990d-5c6980eb7993.png)
![image](https://user-images.githubusercontent.com/55877063/127979619-65043931-e934-4809-84b3-e00f12f3d53a.png)

**Expected behaviour**
I would expect to be able to edit core fields before creating the duplicate page.

**To reproduce**
https://devinit.org/admin/pages/715/

**Desktop**
 - Browser: chrome

**Additional context**
We would like to have a privately published duplicate page of the [real-time aid tracker](https://devinit.org/data/tracking-aid-flows-in-light-of-the-covid-19-crisis/) so that analysts can plug in data from the test repository before working on the live version, which needs to be updated at the end of each month.

**Requested delivery date**
23/08/2021 to enable time for use of duplicate page before the end of the month, but this is low priority, as the process for the last two months has been to simply update the live page

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives this is caused by the `uuid` that's used to generate short links ... there's a uniqueness conflict ... will make time and look into a fix for it.

**Comment by alice-mcandrew-development-initatives** [comment]
Thanks @edwinmp but, as noted on Slack, if you have other important deadlines there's no problem in delaying this job as we can just do the August update without the duplicate if needed :)

**Comment by edwinmp** [comment]
@wakibi what's the status of this?

**Comment by wakibi** [comment]
@edwinmp reproducing this is a bit of a problem. I have failed miserably on my local machine

**Comment by alice-mcandrew-development-initatives** [comment]
Working perfectly on staging @edwinmp
