### ISSUE TITLE
Making pages on our site quiker to load (Largest contentful paint load time issue)

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#1036]
Dear @devinit/di-website-internal 

**Is your feature request related to a problem? Please describe.**

At the moment, many of our website pages take over 4 seconds to load. This is probably contributing to poor user experience and increased bounce rates among mobile phone users.

**Describe the solution you'd like**

We'd like users to have the best possible experience of our websites. I've been looking into the issue, and I wonder if there's a way to integrate a content delivery network into out site to help with these load-time issues we're seeing? Such as this: https://imageengine.io/what-is-an-image-cdn

We already compress the JPEGs we use as image for the pages.

**Requested Delivery Date:** 

I think we should aim to have reduced the time users on mobile phones have to wait for a page to load to ideally less than 2.5 seconds across the site by the end of 2021. 

best
Simon

**Comment by edwinmp** [comment]
@wakibi how far did we get with cloudflare?

**Comment by akmiller01** [comment]
Hi @k8hughes , if I'm reading the issue correctly, it will be more than just updating DNS entries? We'd need to setup a Cloudflare account, move our name server, and import all of the DNS records into Cloudflare.

Would you be able to setup a DI Cloudflare account, if we don't already have one? And then I can look into further setup from there?

**Comment by wakibi** [comment]
Hi @akmiller01, most of this is already done. Sharing cloudflare details via Slack.

**Comment by SimonMurphyDI** [comment]
thanks so much everyone! Can't wait to see :)
