### ISSUE TITLE
Move visualisation page resources to the `di-charts-boilerplate` repository

### ISSUE THREAD

**Issue by edwinmp** [devinit/DIwebsite-redesign#1064]
Data branches include

- [patch/advanced-chart-resources](https://github.com/devinit/DIwebsite-redesign/tree/patch/advanced-chart-resources)

**Comment by edwinmp** [comment]
@ThatcherK Move all the files [here](https://github.com/devinit/DIwebsite-redesign/tree/patch/advanced-chart-resources/data) to [this](https://github.com/devinit/di-website-data) repo under a 2021 folder. Then update the data viz pages that use this on live to point to the new location ... links are below

https://devinit.org/admin/pages/2220/edit/
https://devinit.org/admin/pages/2221/edit/
https://devinit.org/admin/pages/2222/edit/

Test to make sure charts are still functional. If so, close [this](https://github.com/devinit/DIwebsite-redesign/pull/970) PR and delete the attached branch

**Comment by ThatcherK** [comment]
@edwinmp organisation dashboard page isn't part of the links listed above, yet there's a csv for it, is it to be changed as well?

**Comment by edwinmp** [comment]
@ThatcherK Delete that CSV ... not required
