### ISSUE TITLE
Error when filtering by reports on the data/datasets page for some filters

### ISSUE THREAD

**Issue by edwinmp** [devinit/DIwebsite-redesign#1066]
## I'm submitting a ...
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
An error email came through on the [data/datasets](https://devinit.org/data/datasets) page

- [This](https://devinit.org/data/datasets/?report=interviewees&source=brazil-abc&country=) filter results in an 500 error
- I'm not sure if this is a bug as well, but the reports filter has a lot of duplicate fields. @SimonMurphyDI could you please have a look and let me know if that's expected

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'https://devinit.org/data/datasets'
2. Click on 'All reports' filter
3. Scroll down to 'Interviewees' and select it
4. Click on the 'Filter' button

**Expected Behaviour**
No error on filtering

**Additional Context**

![image](https://user-images.githubusercontent.com/5672438/137861117-b9d67e96-6e43-4ca1-8e22-060366343412.png)

**Comment by SimonMurphyDI** [comment]
Thanks @edwinmp and @davidebukali.

I can see the issue - but the behaviour itself isn't what we'd expect. 

When you click on the 'all reports' filter, you should see a drop-down list of all the reports titles that we've published data sets for, but here we're seeing a mixture of report titles (ie Uganda’s loans from international financial institutions (IFIs), 2018–2021) and also page-titles from multi-page reports (such as 'People and crisis' from the GHA).

This is possibly a bit confusing as we'll end up with loads of chapters with non specific titles 'conclusion' and we won't know which multi-page report they pertain to. 

I suggest we amend this so we just short data sets for
- short publications
- publications (but not the child pages of publications to avoid the confusion noted above)

Lastly, I can see some of the chapter titles in the list repeat - but if we make the change suggested above, this shouldn't be an issue if we make the amend noted above.

Best, 
Simon
