### ISSUE TITLE
improving bottom right menu in multi chapter publications

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#1079]
**Is your feature request related to a problem? Please describe.**
At the moment, users reading multi-chapter reports get slightly inconsistent options when browsing between chapters using the bottom right menu on both the DI and GNR websites. Although they can jump left and right between chapters, they can't get to the foreword or the executive summary - the publication appears to start at chapter 1.

![image](https://user-images.githubusercontent.com/22001094/143914602-7b157ba2-af83-426e-a724-8abd6afac998.png)

**Describe the solution you'd like**
We'd like the bottom menu in chapters to include a left arrow that lets the user reach the child pages that sit before chapter one. Likewise, we'd like the foreword and executive summary to feature arrows where appropriate to help readers browse the publication, like below

![image](https://user-images.githubusercontent.com/22001094/143915094-acd36229-d3c6-41ab-a993-15b6614b91f4.png)
 

**Describe alternatives you've considered**
This matches page elements we already have

**Additional context**
Would be good to have a chat so I can explain when we would and wouldnt need arrows (most publications have executive summaries, but not all have forewords)

**Requested Delivery Date:** 
Would be nice to have in 2022?

**Comment by SimonMurphyDI** [comment]
@ThatcherK did you need a bit more info about this? Keen to have it completed in the next two weeks for an upcoming report :)
thanks!
Simon

**Comment by edwinmp** [comment]
@SimonMurphyDI With the open delivery date (sometime in 2022), it wasn't considered a priority ... we'll add it to the current sprint.

**Comment by SimonMurphyDI** [comment]
Thanks, my bad!

*Our offices are currently open and partially staffed. We continue to work at home wherever possible and you can get in touch here<https://www.devinit.org/contact-us/>*
Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK
T: +44 (0) 1179 272 505

DISCLAIMER: This email and any attachments are confidential and intended solely for the use of the individual or organisation to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Development Initiatives. If you have received this email in error, please delete it and notify the sender.

**Comment by edwinmp** [comment]
@SimonMurphyDI this feature and its entire language is about chapters. If I'm to change that (I'm guessing you'll want me to include appendixes as well), I may need to change the language as well. e.g. The label only shows a count of chapters and it may seem strange when a user has `Chapter 9 of 9` but still has a forward button. This also applies to the foreword & executive summary.
I don't want to change the chapter count, so I'm suggesting that for such situations, instead of showing an arrow, we show a label of the the page before or after the chapters - see screenshot

![image](https://user-images.githubusercontent.com/5672438/158560332-dbfc291a-20a4-4504-ba67-5989e5209751.png)

**Comment by SimonMurphyDI** [comment]
Thanks @edwinmp - I think this would lead to a very long bar (by the time you'd added foreword, executive summary, and any number of appendces)

**Comment by edwinmp** [comment]
@SimonMurphyDI yes, that would do nicely & requires less work than my suggestion ... thanks ... @ThatcherK, back to you for implementation.

**Comment by SimonMurphyDI** [comment]
@edwinmp @ThatcherK thank you! 

There's another change I'd like which I think fits in with this (I thought I'd opened an issue but can't see it). At the moment the following are child page options for publications:

**Comment by edwinmp** [comment]
> * publication introduction (just one)
>   This can be just the same as the foreword - we just need an additional module for the introduction

Not directly related - please create a separate ticket for it.
I don't think simply increasing the publication foreword count to 2 would do as there's implications in other areas like the Jump to Section.

**Comment by ThatcherK** [comment]
@SimonMurphyDI this is ready for review on staging !

**Comment by EmmawDI** [comment]
Hi @edwinmp @ThatcherK - thank you both for your work on this. It looks really good to me - the only change I'd request is that instead of "The Foreword", "The Executive Summary", we just have "Foreword", "Executive Summary" etc, for consistency with how the pages themselves are titled? Do let me know if this would be an issue. Thanks!

**Comment by edwinmp** [comment]
Thanks @EmmawDI it won't be an issue at all.

**Comment by EmmawDI** [comment]
@edwinmp thank you - can you also tweak the chapter text so that they use 1, 2, 3 etc rather than "one", "two", "three"?

**Comment by EmmawDI** [comment]
Hi @edwinmp @ThatcherK - I noticed on the GHA 2021 page this morning that this change has been deployed - do you know when you might be able to make the changes discussed above, to remote "the" from "the executive summary"/"the foreword" and change the "one", "two" etc to 1, 2? Thank you

**Comment by edwinmp** [comment]
Hi @EmmawDI ... Thatcher is away for an extended leave, so @davidebukali will be taking this on. It's a really easy update so we can deploy it today. Wasn't intentional to get this on live before that - must have snuck in with some other code. Will try to make sure that doesn't happen again.

**Comment by davidebukali** [comment]
@EmmawDI this is ready for testing on [staging](https://dev.devinit.org/resources/supporting-longer-term-development-crises-nexus-lessons-bangladesh-2/executive-summary/)

**Comment by EmmawDI** [comment]
@davidebukali looks perfect, thank you. Happy for this to be promoted to live.

**Comment by edwinmp** [comment]
@EmmawDI this has been deployed live.

**Comment by EmmawDI** [comment]
Thank you Edwin!
