### ISSUE TITLE
amending the order content appears on 'team member' page

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#1080]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
A clear and concise description of what the issue is.

On the team member pages, content is currently ordered by format (blog/report, etc), which means the newest content is not always at the top. 

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.

Go to: https://www.devinit.org/who-we-are/our-team/bill-anderson/

**Expected Behaviour**
A clear and concise description of what you expected to happen

Please can we amend the code so the content is ordered so the most recent publications are at the top? We'd like this to apply to all the members of the 'our team' page

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.

See how the newest content is buried by older content

![image](https://user-images.githubusercontent.com/22001094/148100911-c64bd5fb-24bc-4a95-8055-eda0782788ee.png)

Requested Delivery Date: Not urgent

**Comment by edwinmp** [comment]
@SimonMurphyDI this is ready for review on [dev](https://dev.devinit.org/who-we-are/our-team/bill-anderson/)

**Comment by SimonMurphyDI** [comment]
thanks @edwinmp
