### ISSUE TITLE
Making some details on role profiles optional to avoid gaps on the vacancy listing page

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#1084]
**Is your feature request related to a problem? Please describe.**
We're currently getting a lot of role profiles for the website that don't have 
- closing dates
- salary scales
This means we have blank categories on[ the vacancies listing page](https://devinit.org/work-for-us/vacancies/), which doesn't look good. 

**Describe the solution you'd like**
It would be great if those two categories were optional, or did not appear on the vacancies listing page if there was no information entered. 

**Describe alternatives you've considered**
I don't think there are any good alternatives.

**Additional context**

Here's how a current vacancy looks - almost appears there's an error.

![image](https://user-images.githubusercontent.com/22001094/148544052-1b9a222f-de0b-4997-b158-f14e0883a28a.png)

**Requested Delivery Date:** 
Happy for you to do this when you can, as what's there is not wrong, it just doesn't look good.

Thank you!

**Comment by edwinmp** [comment]
@SimonMurphyDI this is fixed on dev - please review

**Comment by SimonMurphyDI** [comment]
thanks @edwinmp
