### ISSUE TITLE
Replace Table A1 on Covid Tracker Page

### ISSUE THREAD

**Issue by bill-anderson** [devinit/DIwebsite-redesign#1089]
https://www.devinit.org/data/tracking-aid-flows-in-light-of-the-covid-19-crisis 
Table A1: Key bilateral donors, IFIs and multilateral institutions used in the analysis of IATI disbursements and commitments is currently static text.

This table should be read from a csv in github that is updated by Analysts from the DDW IATI PUBLISHERS table whenever changes are made.

**Comment by dean-breed** [comment]
Thanks for making this unstale @akmiller01 - I suggest once we have these data quality checks automated, we should do this

**Comment by akmiller01** [comment]
@edwinmp is there any way we can add dev.devinit and devinit to the CORS policy of the DDW? Tried pulling in a live CSV and got this:
```
Access to XMLHttpRequest at 'https://ddw.devinit.org/api/export/1240/' from origin 'https://devinit.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by akmiller01** [comment]
In this case @edwinmp , we were interested in pulling a CSV straight from the CSV export of the DDW so the data could be dynamic. And the CORS policy of the DDW disallowed `https://dev.devinit.org` and `https://devinit.org`

We probably need to explicitly allow CORS from `*.devinit.org` in the NGINX config for the DDW if we want to allow this.

**Comment by edwinmp** [comment]
> In this case @edwinmp , we were interested in pulling a CSV straight from the CSV export of the DDW so the data could be dynamic. And the CORS policy of the DDW disallowed `https://dev.devinit.org` and `https://devinit.org`
> 
> We probably need to explicitly allow CORS from `*.devinit.org` in the NGINX config for the DDW if we want to allow this.

No worries ... will add that to the todo (had gone with what was in the original ticket description) ... it shouldn't affect the implementation.

**Comment by dean-breed** [comment]
This table is ready to go for when we can run the query on the DDW to get the data.

**Comment by edwinmp** [comment]
[Here's](https://dev.devinit.org/admin/pages/2455/edit/) a basic implementation of the table. It's wider than the usual version for this page type but that could be preferred sometimes, so I'll add a toggle for the size.
Let me know if there's anything else you need changed or added.

StreamField
![image](https://user-images.githubusercontent.com/5672438/150331479-9c793edc-b4cd-457b-8be9-074698fe24a0.png)

**Comment by dean-breed** [comment]
@edwinmp - Sorry, I didn't make it clear but we had already started this. It's here! https://dev.devinit.org/data/tracking-aid-flows-in-light-of-the-covid-19-crisis/

**Comment by edwinmp** [comment]
That's alright in this case @dean-breed as it's not a single use thing. Close when done to your satisfaction.

**Comment by dean-breed** [comment]
Yeah, I really like these features @edwinmp - I will use them in future, for sure!
