### ISSUE TITLE
T19 Vacancy single

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#11]
Sketch: https://marvelapp.com/3j51290/screen/57215565

Design: http://development-initiatives.surge.sh/page-templates/19-vacancy-single

Functional Spec: 

**The vacancies section is almost identical to the one we've recently released for GNR, so it's best to copy it from there**

The single view shows: 

Hero - job title

Under the hero it goes through each of the different pieces of information about the role. We've done his in GNR, including an optional extra label / text option to add flexibility. Ask @urlsangel if you need any guidance here. 

We then have vacancy content, followed by a link to a team story. 

On the right at the top of the page there's details on applying for this position. We've built this in GNR to have one piece of centrally managed content that can then be overridden on a single vacancy page. 

Then there are links to three downloads, for each download there will be multiple file formats for accessibility (PDF's are very rarely accessible). There could be fewer than three, there might even be more, so it should be flexible.

**Comment by urlsangel** [comment]
@k8hughes @benjamincoleman 

The GNR `vacancies` app is here:

https://github.com/devinit/gnr-website/tree/master/vacancies

It has a couple of dependencies on other apps, but should be straightforward - give me a shout if you need any help.

**Comment by edwinmp** [comment]
@k8hughes @akmiller01  do we seem ourselves ever needing to add more options on a vacancy post besides the usual ones (duration, salary scale, start date, application close date, location, interview start date).
I'm wondering if I need to build an option for adding dynamic key-value options as required.

**Comment by benjamincoleman** [comment]
@edwinmp this should already be in the build if you took it from the GNR website.

**Comment by k8hughes** [comment]
http://178.128.102.213/current-vacancies/data-scientist/ 

LGTM.

**Comment by edwinmp** [comment]
@k8hughes could you add some files for downloading as well; see if that LGTY :)
