### ISSUE TITLE
[Gates Page] Dashboard Feedback

### ISSUE THREAD

**Issue by edwinmp** [devinit/DIwebsite-redesign#1110]
- [x] Calculations seem to use CRS data which has already been rounded to 2dp i.e  each individual line in the CRS is rounded before calculations, instead of rounding the final total. This leads to variation in results in comparison to CRS interface totals. This applies for most countries except the US, where I still get slight differences when using rounded to 2dp CRS data. 
- [x] Rounding is slightly inconsistent with some figures having no decimal places (for example: United States RH 2017).
- [x] For the sunburst chart, there seems to be an overlap on the legend and the chart for this one
- [ ] Consider a third drop-down option of Reproductive Health Care and Family Planning combined for the channel and aid type chart, as done for top recipients.
- [x] Standardise ‘dashboard’ with lower case ‘d’.

OECD Dashboard

- [ ] Adding section titles would create the pop up menu, which would be a handy navigation tool
- [x] Units in first table could be in the title rather than the notes to it’s clear upfront what you’re looking
- [x] Colours perhaps too similar - use most different shade from brand book
- [x] (Tooltips) Can we switch the order to match the order the bars are stacked in
- [x] (Tooltips) Add units beside figures in tool tips
- [x] Remove dotted line up the middle of each stacked bar when using the tool tips
- [x] Thousand separator missing in columns
- [x] Y axis title: Change to ‘US$’ (instead of ‘USD$’)
- [ ] Add ‘Table 1’ and ‘Figure 1’ above the relevant sections - so too for later charts
- [x] Have the ‘US$ millions, constant 2019 prices as a consistent subtitle’ below the tables
- [x] Amend hyphen to en-rule in second table heading
- [x] Make OECD CRS source consistent in notes
- [x] Capitalise Recipients
- [x] Make ‘purpose code’ lower case
- [x] (Channels) Do these all need to be upper case?
- [x] (Channels) Confusing decimal places on the %s
- [x] (Channels) Suggest Total: all channels (to match other tables)
- [x] (Sunburst) Breakdown not BREAKDOWN
- [x] Give US$ unit
- [x] Czech republic - family planning - no data? Explain why no graphic
- [x] Outer ring shows the same colours, and some black with no data label
- [x] Clicking into the segments - this feels like unnecessary interactivity - you click and the vie changes but the data doesn't.
- [x] Grand total - can just be Total 
- [x] Save as image (not saveAsImage)
- [x] In table ‘ODA by aid type 2019. Czech view Mixture of 0 = 0% and 100% - but in the chart below there is data 
- [x] Remove sharing/section sharing option?
- [ ] Check DRC is ‘Democratic Republic of the Congo’ throughout
- [x] Table 2 - when clicking from a donor with lots of data to a donor with limited data, you get a white space

IATI  version

- [x] ‘Select donor’ isn’t a hovering bar here. 
- [x] Drop down starts alphabetically, but that changes midway through 
- [x] Add section titles to match the OECD version -
- [x] Figure 1 - tool tip goes to 3dp - not the same as the rest of chart or dashboard. Should table 1 go to 2dp to match the figure?
- [ ] Table 2 (bottom) use total, rather than ‘sum’. Mixture of decimal places
- [ ] Number of data labels - unspecified,, developing countries, unspecified, might need more info?

**Comment by edwinmp** [comment]
@SimonMurphyDI I've processed all the cosmetic changes for the OECD dashboard (checked above) - please take a look.

**Comment by SimonMurphyDI** [comment]
Hi @edwinmp Is this the correct link to use? https://dev.devinit.org/gates-dashboard/oecd/

I can't see that changes have been made on it recently

![image](https://user-images.githubusercontent.com/22001094/155519275-54b5c0e0-8966-436c-b241-fe1c99b78066.png)

**Comment by SimonMurphyDI** [comment]
@edwinmp thanks so much, this is looking even better!

Here is some feedback - the ones marked !! I think it might be worth considering before initial submission. I think a couple are for Duncan's info? (Marked DK) - I'm happy to pass these on to him

**https://devinit.org/rhfp-team-data-dashboard/**
-!! Small text edits needed - can I make these?

**https://devinit.org/rhfp-team-data-dashboard/oecd/**
-!! Small text edits needed - can I make these?
-!! Share function not removed from section title - looks like we aren't using section titles? If so suggest we just edit the text so it's a heading, not a section title?
- tooltips: the order the data appears should match the order they appear in the chart  

- !! Korea - is this DPR Korea, or North Korea? [DK]

Channel of delivery 
- check capitalisation throughout [DK]
-!! remove '?' in think?tank [DK]
- I get a lot of jump using the channel graphic, and I can't have the graphic and the breakdown legend on the screen at once

https://devinit.org/rhfp-team-data-dashboard/iati/

not working yet

**Comment by edwinmp** [comment]
@SimonMurphyDI yes, you can make any of the text edits yourself. Let me know if you need any help, though I think this should all be familiar.

> * tooltips: the order the data appears should match the order they appear in the chart

I think they already do. Let me know if you catch one that doesn't.


> * I get a lot of jump using the channel graphic, and I can't have the graphic and the breakdown legend on the screen at once

I'm going to give it a minimum height that should fix this.


The IATI dashboard is now live - Dean is still working on the last two visualisations (for channels), and we still need to add the copy (I may have added the wrong text from the Google doc). Feel free to do this if you have time @SimonMurphyDI, otherwise I'm happy to give it a go.

**Comment by Duncan-Knox** [comment]
Hi both, the Korea here is referring to South Korea. 

The points on:

check capitalisation throughout [DK]
-!! remove '?' in think?tank [DK]

Were fixed in the naming of the newly submitted DDW reference files. These don't seem to be available on the UI yet. To get them on the Dashboard we'd need to refresh the relevant queries and put this new data on once the reference files are up. Alternatively I can just provide the updated naming for the channel of delivery and aid type charts here if preferred?

**Comment by edwinmp** [comment]
> Were fixed in the naming of the newly submitted DDW reference files. These don't seem to be available on the UI yet. To get them on the Dashboard we'd need to refresh the relevant queries and put this new data on once the reference files are up. Alternatively I can just provide the updated naming for the channel of delivery and aid type charts here if preferred?

@Duncan-Knox If updating the DDW queries will fix this, please let me know when you've done that and reshare the links ... I'll download and update the CSVs

**Comment by Duncan-Knox** [comment]
Noted @edwinmp thanks. We've added the reference files here https://github.com/devinit/ddw-data-update-configs/issues/12 and updated the meta file here: https://github.com/devinit/ddw-data-update-configs/blob/master/manual/CSV/meta.csv. These are not showing on the DDW so cannot be brought into an updated query. I'm not sure if there are any updates here @wakibi, you mentioned you would have a go at it, but let me know if I can do anything to help. If this is not possible then I can add a mapping based on the names that are currently shown.

**Comment by edwinmp** [comment]
> * On my version I have orange above red on the bars, and red above orange on the tooltip. On the legend, red appears first. It would be ideal if the same colour was first on the legend, the column and the tooltip.

Stacked charts a draw bottom to top, with the first item drawn first & the others stacked on top of it in the order they appear. So the chart is showing as it should be.

> First section of tables and charts is missing a title

Let me add these as they've been shared on the feedback doc.

> * is the date on the title wrong? Can only see data for 2019-2021

Copy/paste error ... will fix

**Comment by edwinmp** [comment]
@SimonMurphyDI finished with the OECD. Waiting on Dean for the last two IATI visualisation data sources before I can update the IATI dashboard as well.

**Comment by Duncan-Knox** [comment]
Hi @edwinmp the change for the label on the channels chart: 'University, College Or Other Teaching Institution, Research Institute Or Think?Tank' could be fixed with: 'University, other teaching institution, research institute or think-tank'.

**Comment by dean-breed** [comment]
@edwinmp Change the year limit in IATI aid type chart to 2019 and then change text to be 2019-2021

**Comment by edwinmp** [comment]
@dean-breed @Duncan-Knox I've made the above updates ... please review

**Comment by Duncan-Knox** [comment]
Thanks @edwinmp the channel name fix looks ok.

**Comment by dean-breed** [comment]
Cheers @edwinmp - looks good!

**Comment by dean-breed** [comment]
@edwinmp We need to change the "No data" to 0 in the recipients tables, and just in general. Both for IATI and CRS. Me and @Duncan-Knox agree I believe

**Comment by edwinmp** [comment]
> Me and @Duncan-Knox agree I believe
@Duncan-Knox ?

**Comment by edwinmp** [comment]
@dean-breed just to be absolutely sure, you don't want me to leave them blank but instead set them to 0?

**Comment by dean-breed** [comment]
@edwinmp It doesn't matter to me really. I would prefer 0 as that is consistent with what we have done elsewhere. It just can't be "No data" because that suggests there is no reporting/data on the code which is not really true. They have made an active decision not to use said code

**Comment by edwinmp** [comment]
Does any of this translate to the charts as well? Cos we're showing a `No Data` view for filters without data.

**Comment by dean-breed** [comment]
Okay, so as I see it, if the selection has some reporting to something in the table, the others are 0s and not "no data". If there is no reporting at all to this field (such as Canada for IATI aid type), it should all be "no data". What do you think @Duncan-Knox ?

**Comment by Duncan-Knox** [comment]
> @edwinmp It doesn't matter to me really. I would prefer 0 as that is consistent with what we have done elsewhere. It just can't be "No data" because that suggests there is no reporting/data on the code which is not really true. They have made an active decision not to use said code

Agree with this point, so fine for the data tables to be changed from 'no data' to '0'.

For the chart spaces in these cases, I don't mind "no data" but "no disbursements" is perhaps a bit clearer @dean-breed?

**Comment by dean-breed** [comment]
No disbursements is fine for OECD if that is what it means. Happy to go with you on that @Duncan-Knox 

For IATI, they are just not included if there are no disbursements so that wouldn't apply. If there are no rows in a given dataset for a reporter, all cells and charts should be "No data", not 0. Does that make sense @edwinmp?

**Comment by edwinmp** [comment]
Updated with the initial 0 instead of `No data` requirement for tables... we'll work out the rest after the presentation - it is supposed to be a prototype :)

**Comment by dean-breed** [comment]
Thanks @edwinmp

**Comment by dean-breed** [comment]
While I'm thinking, we'll need to add a table like the one for the tracker (but shorter) soon. This will identify which agencies have been used for each aggregation.

**Comment by edwinmp** [comment]
I'm closing this - any new feedback item should be added as it's own GitHub ticket.
