### ISSUE TITLE
RichText Anchor button results in a cryptic error

### ISSUE THREAD

**Issue by edwinmp** [devinit/DIwebsite-redesign#1123]
## I'm submitting a ...
<pre><code>
[*] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
_From Slack_
Hi [@didevs](https://devinitorg.slack.com/admin/user_groups) - just wanted to flag that I've been trying to add an anchor to a Case Study block in a short publication page on the DI site and every time I click the anchor icon, the editor crashes and I get this message. Could this be a bug? FYI just tested and same also occurs in WYSIWYG block.

**Expected Behaviour**
I expect to be able to configure and add an anchor

**Screenshots/GIF**
![image](https://user-images.githubusercontent.com/5672438/158531175-b34dfe5c-890b-40b9-81ae-5532f8fe3f58.png)

![image](https://user-images.githubusercontent.com/5672438/158531258-99af6169-82ab-4569-a0b1-3b01ea366ef1.png)

Requested Delivery Date: ASAP

**Comment by k8hughes** [comment]
@SimonMurphyDI can you check this for us...hopefully it is now working

**Comment by edwinmp** [comment]
@SimonMurphyDI While I fixed it, I don't recommend using this button anymore ... Wagtail provides an anchor button that makes this one redundant.

**Comment by SimonMurphyDI** [comment]
Thanks @edwinmp can you let us know how to use this at some point as I've never really understood - sorry!
