### ISSUE TITLE
Gates dashboard feedback - add detail to index page

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#1128]
On the index page, give details of the categoris per dashboard.

The only constructive feedback is that on the index page it would be good to already include the different categories per dashboard i.e. OECD:  [how much donor countries gave](https://devinit.org/rhfp-team-data-dashboard/oecd/#oda); [who are the largest recipients](https://devinit.org/rhfp-team-data-dashboard/oecd/#largest-recipients); [which channels were used](https://devinit.org/rhfp-team-data-dashboard/oecd/#oda-by-channels); [aid types](https://devinit.org/rhfp-team-data-dashboard/oecd/#oda-by-aid-type).

**Comment by edwinmp** [comment]
If I've understood it correctly, this can be done directly via the CMS & would take a few minutes to implement. Created a [draft](https://devinit.org/admin/pages/2556/edit/) of the changes for OECD - I hope that's what's expected.
<img width="917" alt="image" src="https://user-images.githubusercontent.com/5672438/160837739-6d4102a1-ebcb-4ac6-9093-9466efac3681.png">

**Comment by edwinmp** [comment]
@k8hughes done for both OECD and IATI.

**Comment by k8hughes** [comment]
LGTM
