### ISSUE TITLE
Spotlight analytics not loading properly

### ISSUE THREAD

**Issue by wakibi** [devinit/DIwebsite-redesign#1146]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
Google analytics does not appear to be loading properly.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to ['link'](https://devinit.org/data/spotlight-kenya?t=kenya_population&i=spotlight_on_kenya_2017.kenya_total_pop&y=2025) with the debug console open
2. You should be able to see errors

**Expected Behaviour**
Analytics should be loading properly

**Screenshots/GIF**
<img width="1030" alt="Screenshot 2022-05-19 at 14 35 35" src="https://user-images.githubusercontent.com/12862946/169284868-5d53a9b7-9722-472e-b353-c65297f36966.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox

**Smartphone (please complete the following information):**

**Comment by edwinmp** [comment]
@wakibi I've updated the title ... this is a spotlight issue and we'll fix it in the spotlight [repo](https://github.com/devinit/data-hub-spotlights). Ofc we should manage it here as it'll just be forgotten in the spotlight repo :)
