### ISSUE TITLE
Related content 

### ISSUE THREAD

**Issue by EmmawDI** [devinit/DIwebsite-redesign#1147]
**Is your feature request related to a problem? Please describe.**
The Related Content section on our resource/blog pages becomes out of date quickly and needs to be manually updated to direct users to more recent content. As a result, users are unlikely to discover more recent content relevant to their search/interest, instead only being directed to older (and therefore potentially less useful) resources. 

**Describe the solution you'd like**

We have been thinking about how we can ensure that the Related Content on resource/blog pages on the website can be kept relevant and up to date, to make sure that users are directed to our most recent content. 
Would it be possible to change the current Related Links block in the CMS, so that instead of Page being the only option, we can either:
-	Manually select a page, as we can currently, or
-	Choose a country (from the Snippet list), so the site displays the most recent content tagged with that country, or
-	Choose a topic (from the Snippet list), so the site displays the most recent content tagged with that topic
Does this sound feasible?
 

![image](https://user-images.githubusercontent.com/101582869/169798308-0ac0c5c6-91e1-4133-be53-babddc1df7e8.png)

**Describe alternatives you've considered**
The only real alternative to achieve the same result is to manually update each page in the CMS.

**Comment by pauline-n** [comment]
<img width="423" alt="Screenshot 2022-06-30 at 14 05 27" src="https://user-images.githubusercontent.com/71310090/176662385-b060016a-8ecc-404b-ba98-15dd0a15941a.png">
Something like this? @EmmawDI

**Comment by EmmawDI** [comment]
Hi @davidebukali - thank you - I can't seem to log into the staging site currently, is this something you can help with so I can have a look?

**Comment by davidebukali** [comment]
@EmmawDI sure thing, which email do you prefer to use ...

**Comment by EmmawDI** [comment]
emmaw@devinit.org please!

**Comment by davidebukali** [comment]
Sent you mail with details

**Comment by SimonMurphyDI** [comment]
Hello @davidebukali Just used this and it's working well - there's one small change I suggest. At the moment the content is ordered older to newer (left to right) - can we swap this so the newest bit of the content is on the left hand side, so it's the first thing users see?

Thanks!

![image](https://user-images.githubusercontent.com/22001094/204751975-93d9b148-15a0-41d6-857d-4ebc688430ca.png)

**Comment by davidebukali** [comment]
@SimonMurphyDI I've created an issue [here](https://github.com/devinit/DIwebsite-redesign/issues/1269)

**Comment by SimonMurphyDI** [comment]
Hello @davidebukali 
Also on this - when we use the automatic 'topic' tag, it's not pulling through the most recent outputs - do you need me to explain that in more detail or is it clear?
![image](https://user-images.githubusercontent.com/22001094/217495315-e8b3cb9d-df8c-460d-bd16-3d7924a5d3cd.png)

**Comment by davidebukali** [comment]
@SimonMurphyDI does this mean you would like the automatic option to order by recent content first ... kindly explain more if this is not accurate.

**Comment by davidebukali** [comment]
@SimonMurphyDI yes manual related content works with a fixed set of pages and would definitely get outdated with time. Maybe we could scrap it and add other criteria for content other than topic and country. Happy to chat and get more detail when you are available.

**Comment by SimonMurphyDI** [comment]
Thanks @davidebukali 
We'd like there to be a manual option to add related content, OR the option to make related content automatic, so users see the most recent outputs (filtered either by Topic or Country - this should be a setting we can choose when applying automatic related content).
I'll pop some time in the diary :)

this to be an 'automatic' option for related content, 

so that users always see the most recent content. But we want that content to

**Comment by edwinmp** [comment]
@SimonMurphyDI the automatic option is already there (by country or topic). Perhaps the change you need is that these two options always show the most recent matching publications.

**Comment by edwinmp** [comment]
I'm closing this again. If there's a specific update required, please create a separate ticket for it.
