### ISSUE TITLE
Add Twitter conversion tracking

### ISSUE THREAD

**Issue by Tim-Molyneux** [devinit/DIwebsite-redesign#1151]
Hi all - I think it would be good idea to add conversion tracking for twitter to our website, which would help us better track conversion from Twitter ads to visits to your page or other specific actions - Here's a vid explaining it https://business.twitter.com/en/help/campaign-measurement-and-analytics/conversion-tracking-for-websites.html

Please could you help set this up? For now we could try adding this to the DI site but in future we may want to add it to the GNR page too. Thanks.

**Comment by edwinmp** [comment]
@Tim-Molyneux this will require access to the DI twitter account - you can go through the Twitter steps and share the code snippet. With that, we'll only need to update Google Tag Manager.

**Comment by edwinmp** [comment]
@davidebukali reopen if there's anything else still pending on this.
