### ISSUE TITLE
Unable to add related content to the end of executive summary page types - regression?

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#1170]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X ] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
A clear and concise description of what the issue is.

When I try to add related content to executive summary pages, I'm not given the option. 

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to '...' https://devinit.org/resources/supporting-longer-term-development-crises-nexus-lessons-bangladesh/executive-summary/
2. open the editable version of the page
3. Scroll down to bottom
4. try to add related content

**Expected Behaviour**
A clear and concise description of what you expected to happen
To be able to add related content

Requested Delivery Date: 11.7.22

It would be good to have this ready for the GHA launch if possible

**Comment by edwinmp** [comment]
@SimonMurphyDI this is feature request as summary pages have never supported related content ... would you like this done for the GNR as well?

**Comment by SimonMurphyDI** [comment]
No thanks - Just DI site please!

**Comment by edwinmp** [comment]
Hi @SimonMurphyDI this is deployed on dev... please test.
