### ISSUE TITLE
Adding accordion feature to the DI site

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#1181]
**Is your feature request related to a problem? Please describe.**
I love the accordion feature on the GNR site - you can see it in action here: https://globalnutritionreport.org/resources/naf/faqs/

**Describe the solution you'd like**
We'd like the capacity to use this on the DI site, on the following page types
- audio and visual media page (priority)
- short publication page
- the child pages of the publications page
It might be we need it on other pages, but I think it's worth adding it as we find we need it

It would be good if these can use the DI website font and colours (nb the feature might need to be designed in six colours so it can work on the resource pages)

**Requested Delivery Date:** Ideally we'd like to use this to host some long transcripts of podcasts - if it were possible to do over the next few weeks that would be wonderful, but I understand you might have other priorities

**Comment by edwinmp** [comment]
@SimonMurphyDI we've split the design bit into its own ticket #1183

**Comment by SimonMurphyDI** [comment]
Thanks Edwin

Happy for you to do whichever is easiest - either using the GNR or DI version. 

Whichever you build

**Comment by edwinmp** [comment]
@wakibi ^^

**Comment by SimonMurphyDI** [comment]
@wakibi - I also wondered if there is any "cut-off" for the total number of words that can be held in an accordion? (Would be handy to know for DI site and also GNR site
Thanks!

**Comment by edwinmp** [comment]
@wakibi this has been active forever. If there's a branch with some work on it, please push. I'll have someone else complete it so u can focus on IATI.

**Comment by SimonMurphyDI** [comment]
Hello @ThatcherK  - we've been asked for an ETA for this - please can you provide? Thanks!

**Comment by edwinmp** [comment]
@SimonMurphyDI this is done and should be available for testing on staging ...

**Comment by SimonMurphyDI** [comment]
Great thanks!

**Comment by SimonMurphyDI** [comment]
Hi Edwin - thanks for this. We'd like the WYSIWYG capacity for accordions - sharing the GNR back end, which works really well. 
![image](https://user-images.githubusercontent.com/22001094/195090417-1b81e0e4-ac54-41c7-be03-fc061ae5e8ec.png)

**Comment by edwinmp** [comment]
@SimonMurphyDI the implementation on dev does have WYSIWYG capacity ... more Wagtail 4 changes on how that works.

<img width="900" alt="image" src="https://user-images.githubusercontent.com/5672438/195104844-d087416a-6369-4244-b1a7-606b63154b13.png">

I don't understand what you mean by note numbers.

**Comment by SimonMurphyDI** [comment]
Ah great, looks good then!

By note numbers, I mean these
![Uploading image.png…]()
