### ISSUE TITLE
Issue when adding 'internal participant' to audio visual media pages (child of resources)

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#1182]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
A clear and concise description of what the issue is.
You have the option to add internal and external participants to audio visual media pages, but when you add an internal participant, their name doesn't form a hyperlink. I'd expect it to create a hyperlink that you can use to visit their bio on the DI webpage (this is the behaviour you get with resources)

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to '...' https://devinit.org/resources/how-can-data-better-support-disability-advocacy-east-africa/
2. Click on '....' see claudia's and Martha's names aren't clickable 

![image](https://user-images.githubusercontent.com/22001094/178313605-3820ec8f-71e5-4c6a-b5d6-6c8ea4745c48.png)

**Expected Behaviour**
A clear and concise description of what you expected to happen
Clickable, hyperlinked names to the staff bio.

Requested Delivery Date: not urgent - you can create them as 'external participants and link that way, but it's a bit annoying to do that

**Comment by edwinmp** [comment]
Hi @SimonMurphyDI this has been deployed live.
