### ISSUE TITLE
Amending the audio/visual resource pages so we can embed content from buzzsprout player

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#1192]
@edwinmp 

**Is your feature request related to a problem? Please describe.**
We're hosting a new series of podcasts on a site called buzzsprout, and we'd like to embed the podcast on our own site too. But buzzsprout isn't a player supported by Wagtail. 

**Describe the solution you'd like**
@akmiller01  has written a bit of code that should function as a workaround and allow us to embed this content 
Here's the link: 

https://github.com/devinit/DIwebsite-redesign/pull/1191

Ideally, we'd like the first podcast to go live on Monday -- it would be beyond-super-amazing if a dev could review this quickly?

**Requested Delivery Date:** 22/7/2022 - if possible!

**Comment by SimonMurphyDI** [comment]
One question on how this looks/works - ideally it would allow us to embed content where we'd like it to appear in the text block (a bit like the current embed function). But it's not mission-critical, and I realise didn't make that clear to Alex yesterday!

![image](https://user-images.githubusercontent.com/22001094/180400970-97b3af79-60aa-41ab-83b6-3d61dbb32c45.png)

**Comment by davidebukali** [comment]
@SimonMurphyDI @edwinmp Alex's PR works okay. It loads a buzzsprout player after adding a valid url (from 'Embed this one episode' in buzzsprout).

**Comment by edwinmp** [comment]
@davidebukali approve, merge to dev and alert Simon for testing when that's done.

**Comment by edwinmp** [comment]
@davidebukali take note of @SimonMurphyDI's question above.

**Comment by davidebukali** [comment]
@SimonMurphyDI the textblock embed works for sites like youtube that support [oembed](https://oembed.com/). Buzzsprout doesnot hence Alex's PR creating a custom embed.

**Comment by davidebukali** [comment]
@SimonMurphyDI Alex's PR is ready for testing on [dev](https://dev.devinit.org)

**Comment by akmiller01** [comment]
It's easier to implement as a section block, rather than a button in the text editor @SimonMurphyDI . So you'd need to split text around it into two different sections, if that's okay.

**Comment by SimonMurphyDI** [comment]
absolutely on board with that - thanks!

**Comment by edwinmp** [comment]
Deployed!
