### ISSUE TITLE
Add 'podcast subscribe (listen on)' buttons to DI web pages for the Good with data podcast

### ISSUE THREAD

**Issue by Tim-Molyneux** [devinit/DIwebsite-redesign#1194]
I would like to add these buttons to the pages for each episode of the Good with data podcast please. This article has instructions: https://www.buzzsprout.com/help/64-podcast-subscribe-buttons. I suggest just adding buttons for Apple, Spotify, Google and Amazon for now. We will be creating pages for new episodes on an ongoing basis, so it would be helpful to have this added as a feature that the comms team can use to add these buttons to other podcast pages in the future if possible please.

The existing pages that need these buttons so far are here:

Episode 1: https://devinit.org/resources/inequality-good-with-data-episode-1/

Ep 2 (not live yet): https://devinit.org/admin/pages/2644/edit/ 

Ep3 (not live yet): https://devinit.org/admin/pages/2645/edit/

**Comment by edwinmp** [comment]
This is already available on the buzzsprout widget. The other buttons are accessible when you click "more"
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/5672438/192136625-8c2bbcaa-89fb-4cd1-a384-e8717c1d77ae.png">

**Comment by Tim-Molyneux** [comment]
Unfortunately this isn't obvious to a viewer, so it would be an improvement if we could add the buttons to the page, please could someone do this if you have capacity? It's not a high priority, but would be good. Thanks

**Comment by edwinmp** [comment]
> Unfortunately this isn't obvious to a viewer, so it would be an improvement if we could add the buttons to the page, please could someone do this if you have capacity? It's not a high priority, but would be good. Thanks

Ah, so these can be added separate from the player. That's neat ... yes, we'll move this into rotation.

**Comment by edwinmp** [comment]
Hi @Tim-Molyneux ... here's a screenshot of the result.

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/5672438/192992447-f44227cd-b745-4dfb-9171-7f0d968c302e.png">

The Podcast options can be configured in the CMS under snippets.

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/5672438/192992973-fa4da593-4798-4f6d-9c29-9bdfa6a5aacb.png">

They'll be added under every Buzzsprout podcast embed.

**Comment by Tim-Molyneux** [comment]
Thanks Edwin! I can’t see this in Snippets in the CMS, should it be working now?

Tim Molyneux | Senior Communications Officer
Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK
T: +44 (0) 1179 272 505
devinit.org<http://www.devinit.org/> | @devinitorg<https://twitter.com/devinitorg>
Sign up<https://us11.list-manage.com/subscribe?u=a829237ca0cf1470615c7f059&id=ce30e2af0f> to our newsletter and topic updates


At DI we value and respect flexible work arrangements. I choose to work flexibly and sometimes send emails outside normal working hours – no need to respond outside yours.
***@***.***

Read more about our work and its impact<https://devinit.org/what-we-do>
Development Initiatives is the trading name for: Development Initiatives Poverty Research Ltd, a not-for-profit company. Company No. 06368740 and DI International Ltd. Company No. 5802543, both registered in the UK.  Registered Address: First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK.
Development Initiatives Poverty Research America Inc, is a 501(c)3 charity registered in the US. Registration number 5737757. Registered Address: 1209 Orange Street, Wilmington, New Castle County, Delaware 19801, US.
DISCLAIMER: This email and any attachments are confidential and intended solely for the use of the individual or organisation to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Development Initiatives. If you have received this email in error, please delete it and notify the sender.

**Comment by edwinmp** [comment]
The deployment is done, so you should see them now. Here's a draft test page https://dev.devinit.org/admin/pages/2497/view_draft/

**Comment by Tim-Molyneux** [comment]
Hi Edwin,

I still couldn’t see it in the cms, so I logged out and tried logging back in, and now I can’t login; the system says my password and email don’t match. I tried setting a new password but I’m still getting the same error. Do you have any idea why that could be?

Tim

Tim Molyneux | Senior Communications Officer
Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK
T: +44 (0) 1179 272 505
devinit.org<http://www.devinit.org/> | @devinitorg<https://twitter.com/devinitorg>
Sign up<https://us11.list-manage.com/subscribe?u=a829237ca0cf1470615c7f059&id=ce30e2af0f> to our newsletter and topic updates


At DI we value and respect flexible work arrangements. I choose to work flexibly and sometimes send emails outside normal working hours – no need to respond outside yours.
***@***.***

Read more about our work and its impact<https://devinit.org/what-we-do>
Development Initiatives is the trading name for: Development Initiatives Poverty Research Ltd, a not-for-profit company. Company No. 06368740 and DI International Ltd. Company No. 5802543, both registered in the UK.  Registered Address: First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK.
Development Initiatives Poverty Research America Inc, is a 501(c)3 charity registered in the US. Registration number 5737757. Registered Address: 1209 Orange Street, Wilmington, New Castle County, Delaware 19801, US.
DISCLAIMER: This email and any attachments are confidential and intended solely for the use of the individual or organisation to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Development Initiatives. If you have received this email in error, please delete it and notify the sender.
