### ISSUE TITLE
Adding link functionality to endnotes 

### ISSUE THREAD

**Issue by EmmawDI** [devinit/DIwebsite-redesign#1199]
**Is your feature request related to a problem? Please describe.**
Plain URLs are not ideal in terms of their accessibility, as link text should always be unique and descriptive, so having lists beginning "https://www..." gives a difficult user experience. If we could apply links to text in the endnote box, as in the normal WYSIWYG editor, we could hyperlink the name of the source instead of leaving the URL as-is.

**Describe the solution you'd like**
To be able to format endnote text like paragraph text in the WYSIWYG editor. Rather than plain text, to have the option to apply hyperlinks to the text.

This relates to 2.4.9 of the WCAG 2.1 accessibility criteria. 

**Requested Delivery Date:** 31/Oct/2022

**Comment by edwinmp** [comment]
@EmmawDI could you please share a link to a page where you want this changed made.

**Comment by EmmawDI** [comment]
Any resource page type - so factsheet, report, briefing etc. But this page would be a good test - https://devinit.org/resources/oda-2020-2021-key-trends-before-during-emerging-crises/

**Comment by edwinmp** [comment]
**Implementation Details**

- Under `di_website/footnotes/forms.py`, import `from wagtail.admin.rich_text import DraftailRichTextArea`
- Replace the widget on the text form field from `forms.TextArea` to `DraftailRichTextArea`
- Edit `di_website/templates/publications/footnotes.html` to handle richtext content
- You'll need to change the parent component from a paragraph to a div or the footnotes won't render correctly.

**Comment by edwinmp** [comment]
@EmmawDI this is deployed for testing on [dev](https://dev.devinit.org/admin/). We couldn't add a WYSIWYG editor to it, so the only way to allow richtext features for this is to use Markdown syntax.
So for the links you want to change, e.g. https://google.com - you'll need to rewrite that as `[Google](https://google.com)`.
i.e The text you want to show on the footnotes is in the square brackets while the actual link is in parentheses. A better explanation can be found [here](https://www.markdownguide.org/basic-syntax#links) as well as the full list of Markdown syntax.

**Comment by EmmawDI** [comment]
Apologies I had not had a chance to look at this before - I think the principle of this is good, but on the Dev site it doesn't seem to be working for me. I've tested it here https://dev.devinit.org/admin/pages/2245/edit/

**Comment by edwinmp** [comment]
@EmmawDI  You left spaces. I've fixed the one you added. Please test again elsewhere and be sure not to have any spaces between the `[]()`. The containing text within the brackets can have spaces, but there can be no spaces between the square brackets and the curved brackets.

**Comment by EmmawDI** [comment]
Ah great - thanks so much. I think this is a really useful option to have for endnotes, so it would be great if you could deploy to the live site when you have a chance?

**Comment by edwinmp** [comment]
It was closed before, so it should already be live. Please close the ticket once you confirm.
