### ISSUE TITLE
T12 Blog single

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#12]
Sketch: https://marvelapp.com/3j51290/screen/57215560

Design: http://development-initiatives.surge.sh/page-templates/12-blog-single

Functional spec: 

In the hero we have the post title, the post date, and a label 'blog'. Then we have the author on the right. For this we want to have two options: 

1. Select a team member, show their details, and link to their page. 

2. Add details for a guest author - you can see that template variation here: #56 

Then we have post content - richtext, images with captions, videos. 

Then at the bottom we have related content - the approach to take with this is to allow admins to select up to 3 other blog posts, events, or publications to link to. If the admin selects none, or less than three, then fetch another blog post to add in here to make up the numbers to three. We'll have code in GNR to help with this is you want to get a head start.

**Comment by k8hughes** [comment]
http://178.128.102.213/blog/blog-title-test/

The bug here is that the authors image is not pulling though from the person's profile page, it is repeating the photo from the hero of the blog.

![Screenshot 2019-07-24 at 15 41 35](https://user-images.githubusercontent.com/36768381/61803146-9482c100-ae29-11e9-9ba9-04bc4b852095.png)

**Comment by edwinmp** [comment]
Ahh, I see ... the user `Alex` has no image, so it defaults to the last image that was set. I'll add the placeholder here as well.

**Comment by edwinmp** [comment]
Ahh, @akmiller01 already fixed it in his latest pull request.

**Comment by k8hughes** [comment]
LGTM - the place holder image for Alex is working now.
