### ISSUE TITLE
People grid items not equal height

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#120]
http://development-initiatives.surge.sh/page-templates/01d-media-center

Chrome/Mac

#### People grid items not equal height when differing content length

![Screenshot 2019-08-01 at 16 45 37](https://user-images.githubusercontent.com/560463/62307708-fcfe1d80-b47b-11e9-804a-ed49dd18ca7c.png)

**Comment by benjamincoleman** [comment]
Wontfix
