### ISSUE TITLE
Analytics for GHA map

### ISSUE THREAD

**Issue by davidebukali** [devinit/DIwebsite-redesign#1211]
We would like to capture the data below for interactive GHA map.

Which filter is clicked at the top?
Which country is clicked on for the popup?

**Comment by ThatcherK** [comment]
Hi @EmmawDI could you test to see that the analytics for the interactive map [here](https://dev.devinit.org/data/international-humanitarian-assistance-donors-channels-and-recipients/)before we push to live

**Comment by k8hughes** [comment]
@EmmawDI or @SimonMurphyDI can someone review so we can deploy?

**Comment by SimonMurphyDI** [comment]
Not sure what we're reviewing - the list from David is correct. Would be good also to know if users are opening the instructions (that's recorded for other charts)
Thanks
Simon

**Comment by SimonMurphyDI** [comment]
Also spotted on the current analytics we have events for "Recipient chart" and "Recipients chart"  if they are the same, can we combine? Thanks!

**Comment by ThatcherK** [comment]
Am going to push the map analytics, the rest will be handled in a different ticket

**Comment by SimonMurphyDI** [comment]
Thanks so much!

**Comment by ThatcherK** [comment]
Analytics for the map are now live! @SimonMurphyDI
