### ISSUE TITLE
DI website links not loading images on Twitter 

### ISSUE THREAD

**Issue by Tim-Molyneux** [devinit/DIwebsite-redesign#1216]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X ] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
A clear and concise description of what the issue is.

When posting links from the DI site on Twitter, Twitter usually loads an image associated with the page in the Tweet, like this: https://twitter.com/devinitorg/status/1567882045812088832?s=20&t=_OQdj7D0GM0OvQ4lYjTBEg

But this isn't working for any DI pages at the moment. Linkedin is working fine, and other pages are working fine on Twitter (GNR for example), and my colleague is also experiencing the same issue. I tried emptying caches. Is there an issue with the DI page?

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to '...' Twitter
2. Click on '....' Paste a link to a DI resource
3. Scroll down to '....' you will see no image loads. Compare it to a GNR link and see what happens

**Expected Behaviour**
A clear and concise description of what you expected to happen

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.
<img width="823" alt="GNR link" src="https://user-images.githubusercontent.com/93325315/191240047-a52018ac-039e-4a09-80cb-98054cabd572.PNG">
<img width="834" alt="DI link" src="https://user-images.githubusercontent.com/93325315/191240054-fdcb7420-715d-4e0a-b0cf-cc6f0911b32c.PNG">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: dd/MMM/YYYY ASAP - we would like to post multiple things on Twitter today around UNGA so please could you look into this as soon as you can? Thanks

**Comment by edwinmp** [comment]
@akmiller01 we've failed to fix this and could use another set of eyes ... could you please take a look when u have a moment.

**Comment by akmiller01** [comment]
@edwinmp are you sure this isn't working? Card validators are showing the large preview:

![image](https://user-images.githubusercontent.com/2836840/191507434-f4ca7333-9044-45df-8c41-4021cc6ed7d3.png)

**Comment by akmiller01** [comment]
Okay, seems to be on a page-by-page basis: 

![image](https://user-images.githubusercontent.com/2836840/191507976-6de269e8-fb5c-4d54-8158-9b0696bd6cec.png)

**Comment by edwinmp** [comment]
Twitter's validator doesn't show previews, but that's cos they recommend that we should use twitter itself to test this. Previews don't work on twitter.

**Comment by edwinmp** [comment]
> Okay, seems to be on a page-by-page basis:
> 
> ![image](https://user-images.githubusercontent.com/2836840/191507976-6de269e8-fb5c-4d54-8158-9b0696bd6cec.png)

This is better than it was yesterday, which was showing nothing.

**Comment by akmiller01** [comment]
One thing I've noted is that the `summary_large_image` format expects a 2:1 aspect ratio, and we're feeding it 800:450, which is slightly off. Could be one of the things upsetting Twitter...

```
Images for this Card support an aspect ratio of 2:1 with minimum dimensions of 300x157 or maximum of 4096x4096 pixels. Images must be less than 5MB in size. JPG, PNG, WEBP and GIF formats are supported.
```

That Crisis page is working on my personal twitter now. I think the Twitterbot is just taking a moment to scrape the image, and maybe resizing the aspect ratio takes a while:

![image](https://user-images.githubusercontent.com/2836840/191508906-04a63584-1314-408b-97d7-bb41363e24d7.png)

**Comment by edwinmp** [comment]
I'd adjusted the size to match the GNR which has no trouble showing previews. This was also a change from what was there before, which was using the original images which are rather big in size.

**Comment by edwinmp** [comment]
You can adjust it here and see if the expected aspect ratio could do the trick  https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/settings/base.py#L327

**Comment by akmiller01** [comment]
If this is useful, on the cards that are working, Twitter resizes them to 680x383

![image](https://user-images.githubusercontent.com/2836840/191511129-b6d891a4-df35-40cb-b0f7-d2c2444be98f.png)

**Comment by Tim-Molyneux** [comment]
This page is now showing a kind of preview but with no image, as opposed to showing no preview at all yesterday https://devinit.org/resources/ukraine-crisis-diverted-aid-what-we-know/
<img width="723" alt="snip" src="https://user-images.githubusercontent.com/93325315/191511228-f9d8fc53-623d-4ca8-aa76-1acabc871dfc.PNG">

**Comment by Tim-Molyneux** [comment]
Hmm, Twitter has always done this sometimes, but my understanding was that this was due to image optimisation issues on the relevant page. Interestingly My Twitter isn't behaving in the same way as yours; now, when I add the link to a draft Tweet it does show the preview before tweeting, maybe something they were updating on their end? 

<img width="746" alt="Capture 2" src="https://user-images.githubusercontent.com/93325315/191520739-1bc7480c-c6ab-4774-8a16-6fc789381906.PNG">

**Comment by akmiller01** [comment]
I think Twitter is just being opportunistic with fetching images. If someone posts and then expands a card (as I did for the content above), then for future cards it will be expanded automatically because Twitter has already fetched it.

**Comment by edwinmp** [comment]
Interesting ... that seems to be it since the link above expanded for me ... could we test it with another one just to be sure. https://devinit.org/resources/global-disability-financing-in-the-context-of-covid-19/

**Comment by akmiller01** [comment]
Did you already Tweet that one @edwinmp ? It's auto-expanding for me:

![image](https://user-images.githubusercontent.com/2836840/191530488-136fa798-6551-43db-8aff-dda9cd5d6a38.png)

**Comment by edwinmp** [comment]
Yes... I guess that confirms it then ... I hope this helps you @Tim-Molyneux. Guess you'll have to expand the links after posting.

**Comment by Tim-Molyneux** [comment]
Thanks guys! Will let you know if the problem happens again.

Tim Molyneux | Senior Communications Officer
Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK
T: +44 (0) 1179 272 505
devinit.org<http://www.devinit.org/> | @devinitorg<https://twitter.com/devinitorg>
Sign up<https://us11.list-manage.com/subscribe?u=a829237ca0cf1470615c7f059&id=ce30e2af0f> to our newsletter and topic updates


At DI we value and respect flexible work arrangements. I choose to work flexibly and sometimes send emails outside normal working hours – no need to respond outside yours.
***@***.***

Read more about our work and its impact<https://devinit.org/what-we-do>
Development Initiatives is the trading name for: Development Initiatives Poverty Research Ltd, a not-for-profit company. Company No. 06368740 and DI International Ltd. Company No. 5802543, both registered in the UK.  Registered Address: First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK.
Development Initiatives Poverty Research America Inc, is a 501(c)3 charity registered in the US. Registration number 5737757. Registered Address: 1209 Orange Street, Wilmington, New Castle County, Delaware 19801, US.
DISCLAIMER: This email and any attachments are confidential and intended solely for the use of the individual or organisation to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Development Initiatives. If you have received this email in error, please delete it and notify the sender.
