### ISSUE TITLE
URL redirects

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#124]
I know that this is assumed to be part of the work flow, but Anna has specifically flagged that she would like to see this logged in a git issues.

URLs need to be mapped and redirected to the new site so that we mitigate drops in SEO.

**Comment by benjamincoleman** [comment]
@k8hughes do you want me to pick this up? I would usually produce a redirects spreadsheet using a template we have.

**Comment by k8hughes** [comment]
That would be excellent!  Thanks Ben.

**Comment by benjamincoleman** [comment]
👍

**Comment by benjamincoleman** [comment]
Spreadsheet set up from current sitemap - http://devinit.org/sitemap.xml

Will need some completion after the build when we can confirm actual URLs

https://docs.google.com/spreadsheets/d/18qI1Ui0oeFV8GIW4ZIxPE3u13Hx7PmMnNV-Iez-OzNY/

**Comment by akmiller01** [comment]
Hi @benjamincoleman just saw your comments on this issue.

I've actually coded dynamic redirects for all migrated blogs, news, and publications. You can see an example here: https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/common/management/commands/importwp.py#L87-L91

It will be good to get a sense of what needs to be redirected outside of blogs, news, and publications. But those will probably be special circumstances (about pages, etc) where content wasn't migrated but created afresh.

**Comment by benjamincoleman** [comment]
@akmiller01 Good to hear you've set up the redirects - let me know when the content has been sorted out by the comms team and I'll complete the redirection list for you

**Comment by k8hughes** [comment]
@AnnaHope your team can add redirets here:  http://159.65.56.142/admin/redirects/ for any of the page relationships that were not captured by the scripts.

**Comment by AnnaHope** [comment]
All redirects needing to be manually set up are now done. These are marked up in Ben's spreadsheet to reflect that.
