### ISSUE TITLE
Excluding main office IP addresses from analytics

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#1248]
**Is your feature request related to a problem? Please describe.**
We currently don't know to what degree we're inflating our analytics, which means we might be making decisions without correct data  

**Describe the solution you'd like**
For us to limit our own impact on analytics 

**Describe alternatives you've considered**
Not sure there are any

**Additional context**
I'm not sure how easy this would be to develop

**Requested Delivery Date:** 01.01.2023
It would be nice to start the new year with data that we can compare back to!

**Comment by edwinmp** [comment]
Since a lot of us work from home as a lot, we'll need to exclude those as well. As practice, we'll also make sure to clean any test data for when we make such changes. @SimonMurphyDI in case we forget, feel free to raise it on any analytics tickets before approving.

**Comment by edwinmp** [comment]
[Resource](https://www.analyticsmania.com/post/how-to-exclude-internal-traffic-in-google-analytics-4/) - Step 2 seems to fit our use case @davidebukali @ThatcherK

**Comment by edwinmp** [comment]
@davidebukali is this published? If so, could you write a brief comment on how it was accomplished, for posterity. Then close to ticket.

**Comment by davidebukali** [comment]
@edwinmp this has been resolved
