### ISSUE TITLE
Featured work grid

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#125]
http://development-initiatives.surge.sh/page-templates/02-homepage

IE11/Win 7

#### Featured work grid listing broken

![Screenshot 2019-08-02 at 14 07 17](https://user-images.githubusercontent.com/560463/62372346-29bf3d00-b52f-11e9-8d38-4d037202b75a.png)

http://development-initiatives.surge.sh/page-templates/02c-homepage-1-publication

IE11/Win 7

#### Single column grid has broken background colour

![Screenshot 2019-08-02 at 14 13 17](https://user-images.githubusercontent.com/560463/62372662-f3ce8880-b52f-11e9-8894-e636d392eb92.png)

![Screenshot 2019-08-02 at 14 16 33](https://user-images.githubusercontent.com/560463/62372735-28dadb00-b530-11e9-8425-20d8167ec6b6.png)

**Comment by BenDarby** [comment]
Can't replicate, looks okay on my windows laptop

**Comment by benjamincoleman** [comment]
Not an issue on Win 11 / IE 7 laptop I have
