### ISSUE TITLE
Amending resources so the hero shows on the resource page itself, not just the listing 

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#1254]
**Is your feature request related to a problem? Please describe.**
At the moment, the hero for a short publication appears on the listing page, [like this](https://devinit.org/resources/?nav=header), but it's not then visible to users who have gone to the page directly - say from a tweet or email link. This is a missed opportunity to give readers an idea of what content there is in our short publications, and why they might want to read it. 

**Describe the solution you'd like**
We'd like the same behavior as blogs, which show the hero text on the listing page, and when you click through https://devinit.org/blog/?nav=header 

**Describe alternatives you've considered**

**Additional context**

**Requested Delivery Date:** dd/MMM/YYYY
It would be nice to start the new year with this in place

**Comment by edwinmp** [comment]
Hi @SimonMurphyDI this should be available for testing on dev & is probably live 😅
