### ISSUE TITLE
Urgent (needed for Thurs 17th Nov): Please add table content blocks to blog pages

### ISSUE THREAD

**Issue by LCowie** [devinit/DIwebsite-redesign#1259]
Please can you add table content blocks as an option on blog pages? At the moment tables can only be uploaded to blogs in the infographic content block and this requires an image to be uploaded as well as the data for the table.

Requested delivery date: by the 17/11/2022

We are in the process of uploading a blog with a table and the intended publication date of the blog is this Thursday 17th November so it would be very helpful if the table content block could be added by then. 

Many thanks,

Lucy

**Comment by edwinmp** [comment]
@davidebukali @ThatcherK could one of you look into this.

**Comment by ThatcherK** [comment]
Hi @LCowie this is done and ready for testing on staging

**Comment by LCowie** [comment]
Brilliant, thank you. Please can you send me a link and a password for the staging site?

All best,

Lucy

Lucy Cowie | Content & Publications Officer

I work Mondays, Tuesdays and Thursdays
Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK
T: +44 (0) 1179 272 505

At DI we value and respect flexible work arrangements. I choose to work flexibly and sometimes send emails outside normal working hours – no need to respond outside yours.
***@***.***

Read more about our work and its impact<https://devinit.org/what-we-do>
Development Initiatives is the trading name for: Development Initiatives Poverty Research Ltd, a not-for-profit company. Company No. 06368740 and DI International Ltd. Company No. 5802543, both registered in the UK.  Registered Address: First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK.
