### ISSUE TITLE
Reducing space between accordions/anchor links and surrounding text

### ISSUE THREAD

**Issue by LCowie** [devinit/DIwebsite-redesign#1261]
In the current page layout, there are large spaces between accordion blocks and surrounding text. This also applies to anchor links - there are large spaces between anchor links and surrounding text too.

Please can you reduce the size of the spacing between accordions/anchor links and the text that precedes or follows them? This will make outputs appear more compact visually. 

Requested Delivery Date: as soon as possible or 24/11/2022

**Comment by k8hughes** [comment]
@LCowie do you know what budget code we should be charging this work to?

**Comment by SimonMurphyDI** [comment]
@k8hughes 
Sorry - we don't have a code yet. Have you and Anna heard back from Anthony? If there's no code then I guess we have to pause website improvements like this, because we won't know where to timesheet the work. 
If that's the case, I can go through all the tickets we've raised and ask them to pause
Best
Simon

**Comment by k8hughes** [comment]
I haven't had any communication about budgets so I will chase Anthony.  I was hoping comms colleagues had heard and I'd just missed something!  Don't pause it all yet, wait till I speak to Anthony.

**Comment by edwinmp** [comment]
@LCowie not yet. A bot had closed the ticket. I've pinned it so the bot won't close it again.

**Comment by LCowie** [comment]
Hi Edwin,

Thanks for the update, it would be great to get this issue fixed so that we can use accordions and anchor links more effectively in our outputs.

All the best,

Lucy

Lucy Cowie | Content & Publications Officer

I work Mondays, Tuesdays and Thursdays
Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK
T: +44 (0) 1179 272 505

At DI we value and respect flexible work arrangements. I choose to work flexibly and sometimes send emails outside normal working hours – no need to respond outside yours.
***@***.***

Read more about our work and its impact<https://devinit.org/what-we-do>
Development Initiatives is the trading name for: Development Initiatives Poverty Research Ltd, a not-for-profit company. Company No. 06368740 and DI International Ltd. Company No. 5802543, both registered in the UK.  Registered Address: First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK.

**Comment by davidebukali** [comment]
@LCowie kindly include a screenshot or link with a page affected by this issue; Are the accordions showing `Our Expertise` on [this](https://devinit.org/what-we-do/?nav=header) page affected ?

**Comment by LCowie** [comment]
Hi David,

Thanks for your email. The accordions on ‘Our expertise’ page look more tightly aligned to the title above. But there’s a large space between the accordions in the multidimensional poverty guide and the preceding text (please see attached screengrab) that it would be great to reduce.

All best,

Lucy

Lucy Cowie | Content & Publications Officer

I work Mondays, Tuesdays and Thursdays
Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK
T: +44 (0) 1179 272 505

At DI we value and respect flexible work arrangements. I choose to work flexibly and sometimes send emails outside normal working hours – no need to respond outside yours.
***@***.***

Read more about our work and its impact<https://devinit.org/what-we-do>
Development Initiatives is the trading name for: Development Initiatives Poverty Research Ltd, a not-for-profit company. Company No. 06368740 and DI International Ltd. Company No. 5802543, both registered in the UK.  Registered Address: First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK.

**Comment by davidebukali** [comment]
Hi @LCowie, thank you for sharing, seems the spacing comes from surrounding text. We are working on this now.

**Comment by LCowie** [comment]
Brilliant, thanks David.

Lucy Cowie | Content & Publications Officer

I work Mondays, Tuesdays and Thursdays
Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK
T: +44 (0) 1179 272 505

At DI we value and respect flexible work arrangements. I choose to work flexibly and sometimes send emails outside normal working hours – no need to respond outside yours.
***@***.***

Read more about our work and its impact<https://devinit.org/what-we-do>
Development Initiatives is the trading name for: Development Initiatives Poverty Research Ltd, a not-for-profit company. Company No. 06368740 and DI International Ltd. Company No. 5802543, both registered in the UK.  Registered Address: First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK.

**Comment by edwinmp** [comment]
@LCowie just a reminder to test.

@davidebukali I have a feeling this has been deployed before @LCowie tested. With tag release, we don't need to merge into develop to test out features.

**Comment by davidebukali** [comment]
Thank you Edwin for reminder to use tag releases in functional testing. Lucy actually tested, we had a conversation via email.

**Comment by edwinmp** [comment]
Great ... if it's done and deployed, please close.
