### ISSUE TITLE
Relatively high priority - changing width of infographic content block within Case Study block

### ISSUE THREAD

**Issue by EmmawDI** [devinit/DIwebsite-redesign#1262]
Hello -- as you can see from the below screengrabs, there is an issue when using Infographic content blocks within Case Study content blocks, as the former are much wider and therefore disrupt the flow of the box. At 100% there is a lot of blank space, so it doesn't seem that the image is the issue. Would it be possible to limit the width of the Infographic content block **within the Case Study block** to the same width as the Case Study WYSIWYG editor? The normal Infographic content block does not need to be changed. 

This change is fairly high priority as this report is being published on Monday 21 November, however it will not stop us publishing. It would be good to know how soon this could be actioned please. Happy to discuss if you need further details. Thanks!

![image](https://user-images.githubusercontent.com/101582869/202475392-3e733bba-04bd-41e6-b9a8-cc2fb7ae1c54.png)
![image](https://user-images.githubusercontent.com/101582869/202475639-4a02f0d4-8ba9-4fd8-a61f-d4f81ab8034e.png)

**Comment by edwinmp** [comment]
@EmmawDI infographics where always designed to take up more space than their surrounding text. See the original publication page design [here](https://development-initiatives.surge.sh/page-templates/14-1-publication-long-form).
I need to be sure that you want this to be a permanent change for all pages. If not, I suggest a less permanent option which is to add a config on the CMS that gives u control on whether the infographic is full-width or not.

**Comment by EmmawDI** [comment]
Hi @edwinmp thank you for getting to this so quickly - I'm happy to explore the less permanent option as we don't have infographics in case study blocks very often

**Comment by k8hughes** [comment]
@EmmawDI sorry we couldn't get to this in time for your report launch today.  @ThatcherK is going to work on it later today and will be in touch.

**Comment by EmmawDI** [comment]
@k8hughes that's ok - publication has actually been pushed to tomorrow (not because of this) but it's not a roadblock on publishing either way. Thank you for the update!

**Comment by ThatcherK** [comment]
Hi @EmmawDI this is ready for testing on staging [here](https://dev.devinit.org/), there is a field that has been added to the infographic called Full width, it's checked by default, but if you want the infographic width to match the other content you will have to uncheck it.

**Comment by EmmawDI** [comment]
Hi @ThatcherK thank you - this looks really helpful and I think it will help this issue, please deploy  when you can :)
