### ISSUE TITLE
Update order of related content

### ISSUE THREAD

**Issue by davidebukali** [devinit/DIwebsite-redesign#1269]
**Is your feature request related to a problem? Please describe.**
We would like related content to be ordered from newest to oldest. More [here](https://github.com/devinit/DIwebsite-redesign/issues/1147#issuecomment-1331831573)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Requested Delivery Date:** dd/MMM/YYYY

**Comment by davidebukali** [comment]
@SimonMurphyDI related content for publications is now ordered with newest items first, kindly test [here](https://dev.devinit.org/resources/)

**Comment by SimonMurphyDI** [comment]
@davidebukali how did it go with the changes we talked about to this? Let us know when the code is updated so we can test it :)

**Comment by davidebukali** [comment]
@SimonMurphyDI this is in progress, will let you know when its ready for testing. Created an issue [here](https://github.com/devinit/DIwebsite-redesign/issues/1306)

**Comment by davidebukali** [comment]
@SimonMurphyDI country and topic options now pull the most recent content. Kindly see link for testing on [staging](https://dev.devinit.org/data/tracking-aid-flows-in-light-of-the-covid-19-crisis/)
