### ISSUE TITLE
Share module misaligned

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#128]
http://development-initiatives.surge.sh/page-templates/14-1a-publication-short-form

IE11/Win 7

#### Share module misaligned

![Screenshot 2019-08-02 at 14 45 50](https://user-images.githubusercontent.com/560463/62374691-65a8d100-b534-11e9-8eab-9ef7646ec876.png)

**Comment by BenDarby** [comment]
I can't see this either, maybe another virtual machine thing?

**Comment by benjamincoleman** [comment]
I am seeing the same thing on the VM. I'll see if I can boot Briony's old PC to check there.

**Comment by urlsangel** [comment]
@BenDarby 

Are you definitely testing with IE11, and not Edge?

**Comment by benjamincoleman** [comment]
@BenDarby So with this one it's a real thing on IE11 / Win 7

To fix, 

on `.share__item` add `vertical-align: top`

on the img icon add `height: 40px` or whatever the height is supposed to be of that image.

**Comment by BenDarby** [comment]
@benjamincoleman I'm not seeing this on IE11 on my windows machine but I added those CSS properties just in case
