### ISSUE TITLE
Staff pages only show blog work, not all resources

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#1280]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[ ] Bug report 
[x] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**

When I look at (e.g. Euan's page: https://devinit.org/who-we-are/our-team/euan-ritchie/), at the bottom I can only see his blogs, not all his reports - this used to work but isn't now working. 

To be clear, any blog or resource should show up, with the newest content shown first. 

Best
Simon

**To Reproduce**
1. Go to '...' https://devinit.org/who-we-are/our-team/euan-ritchie/

**Expected Behaviour**

All blogs and resources, newest first (regardless of type)

**Comment by edwinmp** [comment]
@SimonMurphyDI this is ready for testing on dev. You can compare [here](https://dev.devinit.org/who-we-are/our-team/bernard-sabiti/) for staging and [here](https://devinit.org/who-we-are/our-team/bernard-sabiti/) for live.

**Comment by edwinmp** [comment]
Deployed live.
