### ISSUE TITLE
Request for new Google tags to capture info on the popularity of shared content

### ISSUE THREAD

**Issue by LCowie** [devinit/DIwebsite-redesign#1283]
Please can you create two new Google tags so that shares capture the name of the page, section, box or chart that’s shared? This will enable us to know which elements of content (for example, of the GHA) are the most popular with users.

**Requested Delivery Date:** 09/01/2023

**Comment by davidebukali** [comment]
@LCowie this is ready for testing. We added a tag `Share section` to capture name of shared charts and figures. It works for GHA and publication sections. The previous tag was also updated to run only when the entire page is shared.

**Comment by LCowie** [comment]
Thanks for the update David!

Lucy Cowie | Content & Publications Officer

I work Mondays, Tuesdays and Thursdays
Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK
T: +44 (0) 1179 272 505

At DI we value and respect flexible work arrangements. I choose to work flexibly and sometimes send emails outside normal working hours – no need to respond outside yours.
***@***.***

Read more about our work and its impact<https://devinit.org/what-we-do>
Development Initiatives is the trading name for: Development Initiatives Poverty Research Ltd, a not-for-profit company. Company No. 06368740 and DI International Ltd. Company No. 5802543, both registered in the UK.  Registered Address: First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK.

**Comment by LCowie** [comment]
Thanks David, please can you make this change live?

All best,

Lucy

Lucy Cowie | Content & Publications Officer

I work Mondays, Tuesdays and Thursdays
Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK
T: +44 (0) 1179 272 505

At DI we value and respect flexible work arrangements. I choose to work flexibly and sometimes send emails outside normal working hours – no need to respond outside yours.
***@***.***

Read more about our work and its impact<https://devinit.org/what-we-do>
Development Initiatives is the trading name for: Development Initiatives Poverty Research Ltd, a not-for-profit company. Company No. 06368740 and DI International Ltd. Company No. 5802543, both registered in the UK.  Registered Address: First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK.

**Comment by davidebukali** [comment]
@LCowie this has been deployed to live

**Comment by LCowie** [comment]
Thanks David!

Lucy Cowie | Content & Publications Officer

I work Mondays, Tuesdays and Thursdays
Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK
T: +44 (0) 1179 272 505

At DI we value and respect flexible work arrangements. I choose to work flexibly and sometimes send emails outside normal working hours – no need to respond outside yours.
***@***.***

Read more about our work and its impact<https://devinit.org/what-we-do>
Development Initiatives is the trading name for: Development Initiatives Poverty Research Ltd, a not-for-profit company. Company No. 06368740 and DI International Ltd. Company No. 5802543, both registered in the UK.  Registered Address: First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK.
