### ISSUE TITLE
Download report module

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#129]
http://development-initiatives.surge.sh/page-templates/14-publication-summary

IE11/Win 7

#### Download report module displaying image and with no padding

![Screenshot 2019-08-02 at 14 54 03](https://user-images.githubusercontent.com/560463/62375133-7d348980-b535-11e9-90e2-5efc02124470.png)

**Comment by BenDarby** [comment]
Maybe this a virtual machine issue, looks good on my windows laptop.

**Comment by urlsangel** [comment]
@benjamincoleman 

Do you have an IE11 VM you can test this and the other issues with?

**Comment by benjamincoleman** [comment]
Not an issue on my Win 7 / IE11 machine
