### ISSUE TITLE
Adding code so the website automatically converts images to webp 

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#1290]
**Is your feature request related to a problem? Please describe.**
Currently, our website fails Google's Core Web Vitals Assessment (for mobile users). This page lists some changes we could make to improve performance, which is the area that lets us down. (https://pagespeed.web.dev/report?url=https%3A%2F%2Fwww.devinit.org%2F&form_factor=mobile)

**Describe the solution you'd like**
Alex has suggested a range of approaches that might help us crack this. One is that we add some code like this 
https://github.com/IATI/IATI-Standard-Website/blob/master/iati/settings/base.py#L635-L642
so that our images are slowly converted to webp

**Describe alternatives you've considered**
None known

**Additional context**
None

**Requested Delivery Date:** dd/MMM/YYYY
A third of the users on our site are mobile users, and it would be good to try and get the website passing core vitals for them, so that they're getting the best possible experience. 

Can we look to try and implement the suggestions from the pagespeed report in Q1?

Thanks so much
Simon

**Comment by edwinmp** [comment]
@SimonMurphyDI this would take about 2hrs (with testing). Do we proceed?
