### ISSUE TITLE
Update to Focus Area page type

### ISSUE THREAD

**Issue by EmmawDI** [devinit/DIwebsite-redesign#1295]
We’re looking to change the contents of [this page](https://devinit.org/what-we-do/what-we-are-working-on/?nav=header) and its child pages. It would be great if you could provide us with an estimate for how long this work will take and whether it will be possible to **complete it before 3 March** (we would need time to upload content before the planned launch of one of these pages on International Women’s Day, 8 March). 
What we’d need: Focus Area page type changes
-	Our plan for the revised structure would involve Focus Area pages at two levels of site navigation – the current “what we are working on” page, and as child pages of that page. 
-	Currently, within each Focus Area, it’s only possible to link to Project page types in the Projects section. We would like this to be changed so that we can link to any page type, including resources. 
-	Can we apply the same logic as the [related content feature](https://github.com/devinit/DIwebsite-redesign/issues/1147)? In the child Focus Area pages, we would like to have the option for the “Project” sections to automatically populate with resource pages tagged with a specific topic. 
Happy to discuss this if it’s easier.

**Comment by edwinmp** [comment]
> * Our plan for the revised structure would involve Focus Area pages at two levels of site navigation – the current “what we are working on” page, and as child pages of that page.

So you need the `Focus Area Page` type to allow children of its own type?
This is an easy change.


> * Currently, within each Focus Area, it’s only possible to link to Project page types in the Projects section. We would like this to be changed so that we can link to any page type, including resources.

Pages added to this section are titled `Key Projects`. I recommend that we make this configurable in the CMS since this will now be linking to more than just projects.
Both are easy updates.


> * Can we apply the same logic as the [related content feature](https://github.com/devinit/DIwebsite-redesign/issues/1147)? In the child Focus Area pages, we would like to have the option for the “Project” sections to automatically populate with resource pages tagged with a specific topic.

This will be tougher. These pages were never meant to connect in this way. Still, we'll manage, though it'll need a great deal of testing. For clarity, you only want the two options i.e. `manual` & `topic`? Or do we replace the `manual` option with the `topic` option.


Overall, the changes above shouldn't take longer than 3 days (including reviews & testing).

**Comment by EmmawDI** [comment]
Hi Edwin, thank you so much for your response. 

1 - yes, exactly. 
2 - making the title configurable sounds ideal, thank you
3 - Ideally we would have manual and topic options.  If it would be helpful for someone on our team to help with testing, do let us know and I'm sure we can plan some time. 
 
Do you think it's feasible for this work to be completed before 3 March? Thanks again for your quick and detailed response

**Comment by edwinmp** [comment]
Hi @EmmawDI, we can meet that deadline. On what budget line do we put this work?

**Comment by EmmawDI** [comment]
Thank you - it will be this budget line 
![image](https://user-images.githubusercontent.com/101582869/220681128-650db33e-3b0a-463a-906a-96bd925a9fce.png)
Do you know what your cost per day is? Thanks

**Comment by edwinmp** [comment]
> Do you know what your cost per day is? Thanks

No clue :) ... @davidebukali will be the one working on this though. I don't think either of us has that budget line.

**Comment by SimonMurphyDI** [comment]
Hello @davidebukali  - can you please give an estimate as to when this will be ready for testing, and an update on the hours you've spent so far?
thanks
Simon

**Comment by davidebukali** [comment]
Hello @SimonMurphyDI, I estimate a test page will be ready by tomorrow noon Kampala time - I have spent 10hrs.

**Comment by SimonMurphyDI** [comment]
@davidebukali you are a total hero

**Comment by davidebukali** [comment]
Hi @SimonMurphyDI please find a test page for this feature [here](https://dev.devinit.org/admin/pages/609/edit/). All configurations are within Focus Areas section. Selecting `manual` displays the user selected pages while `topic` displays resources or project pages with topics matching the relevant focus area page.

**Comment by EmmawDI** [comment]
Thanks so much @davidebukali - just looking at this now. Can you confirm if it will be possible to have a focus area page as a child page of the above? If I click "add a child page" now it just gives Project or General as options

**Comment by davidebukali** [comment]
@SimonMurphyDI yes it will be possible to have child focus area pages - adding this now

**Comment by davidebukali** [comment]
@SimonMurphyDI just deployed to staging, kindly test [here](https://dev.devinit.org/admin/pages/609/edit/) if you can add child focus area pages

**Comment by EmmawDI** [comment]
@davidebukali looks great and can confirm child focus area pages works - thank you for actioning that so quickly

**Comment by EmmawDI** [comment]
@davidebukali good morning - will it be possible to promote these updates to the page type to the live site today?

**Comment by davidebukali** [comment]
Good morning @EmmawDI sure thing, we are deploying this today

**Comment by edwinmp** [comment]
Hi @EmmawDI ... unfortunately, we cannot deploy this today. It's too risky to deploy on a Friday in case anything goes wrong. We'll deploy first thing Monday morning.

**Comment by EmmawDI** [comment]
@edwinmp OK thank you for letting us know - @SimonMurphyDI FYI

**Comment by edwinmp** [comment]
Hi @EmmawDI this has beed deployed live.

**Comment by edwinmp** [comment]
@EmmawDI @SimonMurphyDI what's the project code to log time on for this?

**Comment by EmmawDI** [comment]
Thanks so much @edwinmp  - should be this one but Fionna may need to add you
![image](https://user-images.githubusercontent.com/101582869/223054940-3fef8253-a128-4f19-9bd1-015e66631ca2.png)

**Comment by edwinmp** [comment]
Thanks ... let me ping her to add David and I.
