### ISSUE TITLE
GHA report 2023 website updates

### ISSUE THREAD

**Issue by EmmawDI** [devinit/DIwebsite-redesign#1296]
Hello - as we approach the GHA report this year (launching mid-June), there's a few website updates we'd like to explore making to support some changes to the report structure this year. It would be great to have a sense of how long you'd estimate each of these to take, and whether you think the team will have capacity to include these tasks in sprints over the next month or two. 

1. “So what”/impact boxes
Specific requirements tbc, but will involve adapting the current case study content block to have a different background (ie not the colour of the page header, but possibly an opaque pattern to contrast with normal case study blocks) and use the author box from blog pages. 

2.	‘About this report’ page type
Similar to ‘About this report’ page of GNR. 

3.	Interactive charts page updates - we're not planning any major changes to the functionality or contents of the page this year, just updating the data, but it would be good to explore improving the links between the report pages and the interactive charts.
- Updating data
- Ability to add link to the interactive data page from the report landing page, so it's listed like a chapter of the report
- Option to navigate from static to interactive - we would like to make it easier for users to move from the static version of a chart to the interactive version, where available. We haven't got far with developing this idea, but it would need to be an optional bar underneath certain charts which could contain a link and an icon. Ideally the link would open in a new window or tab to avoid taking the user away from the report completely. 

Let me know if you need any more details on the above in order to be able to estimate time needed and/or whether you have capacity in the team. I will hopefully be able to provide more specific requirements for #1 in the next few days. Thank you!

**Comment by edwinmp** [comment]
Hi @EmmawDI let me look into this and get back to you asap.

**Comment by edwinmp** [comment]
Hi @EmmawDI, I'm reluctant to give any estimates based off this ticket. This will need a call to make sure we're on the same page.

**Comment by EmmawDI** [comment]
Hi @edwinmp no problem - let me set up a meeting

**Comment by edwinmp** [comment]
Hi @EmmawDI 

1. "So What" Boxes - **4 days (2 for learning SVG)**
       - Author section
       - Instead of solid background, have a pattern (preferably stripes) - https://globalnutritionreport.org/022d34#e4d850cf
       - Needs to be responsive
2. Add new publication page type for showing `About this report`, similar to [this](https://globalnutritionreport.org/reports/2022-global-nutrition-report/about-this-report/) - **4hrs**
3. Add a button on static visualisations (infographics) that allows users to navigate to an interactive version - **4hrs**

That's about 5 days. I'd add a 2 day buffer, so **7 days**.

I'll work on 1 & 3 since they have a design element, and Thatcher will work on 2.

How soon do you need this, cos with the GNR handover looming, my availability this month is a little uncertain.

**Comment by EmmawDI** [comment]
@edwinmp thank you - I have passed this to the PM and will update you asap. This isn't very urgent - I think ideally we would have the updates ready by mid-May (I will have to find out when we could have the data ready to update the interactive charts)

**Comment by EmmawDI** [comment]
@edwinmp Hi, hope you're well. Just to update you:
1 - this can go ahead whenever you have time. 
2 - we no longer need this update - we've decided to integrate this content into another page. 
3 - this can also go ahead whenever you have time - I will find out when the dataset will be ready for the charts to be updated, and we will also need to coordinate a time around publication (w/c 19 June) to launch the updated interactives.

**Comment by EmmawDI** [comment]
Hi @edwinmp - just one thing I want to check in relation to this. What is the best way for you to receive the data for the interactive charts - csv, github, excel etc?

**Comment by edwinmp** [comment]
@EmmawDI CSV is best. You can share the file here (best for tracking) or directly with @ThatcherK on Slack. We'll add it to the GitHub repo ourselves.

**Comment by EmmawDI** [comment]
@edwinmp thank you - I'll pass this on to the team

**Comment by EmmawDI** [comment]
Hi @edwinmp - hope you are well. I was just hoping for an update on when you think these pieces of work might be completed - mainly #1? Thanks in advance

**Comment by ThatcherK** [comment]
Hi @EmmawDI I will start working on this today, so by end of week it will be finished!

**Comment by EmmawDI** [comment]
@ThatcherK that's brilliant, thank you. Let me know if you need anything in the way of testing from me

**Comment by ThatcherK** [comment]
@EmmawDI I need a bit of clarity, is the Author box supposed to be part of the 'so what' box?

**Comment by EmmawDI** [comment]
@ThatcherK Ideally yes. We want it to be clear that DI didn't write these pieces

**Comment by ThatcherK** [comment]
Also do you prefer horizontal, vertical or diagonal stripes? @EmmawDI

**Comment by EmmawDI** [comment]
@ThatcherK Diagonal would be my preference if that's ok

**Comment by ThatcherK** [comment]
@EmmawDI  The two features requested are ready for testing on staging

- The So what boxes can be found under content in the publication pages
- The Navigation link from infographics to interactive charts can also be added for each infographic

**Comment by EmmawDI** [comment]
@ThatcherK , you are brilliant. Going to test this afternoon, thank you!!!

**Comment by EmmawDI** [comment]
@ThatcherK getting a 500 error when I try to preview the page where I'm testing it? https://dev.devinit.org/admin/pages/2589/edit/

**Comment by EmmawDI** [comment]
Thanks Thatcher. Works really well. One thing:
- This "Insight" label is hard to read with the pattern in the background. Is it possible to add a white background to the section label field?
![image](https://github.com/devinit/DIwebsite-redesign/assets/101582869/db9f3e97-d543-475a-a8ed-60ca9562662a)

**Comment by ThatcherK** [comment]
Yes I will change that

**Comment by EmmawDI** [comment]
Thank you

On the interactive chart link - I really like the functionality. When we discussed this with @edwinmp , he suggested it could look the same as the "share chart" link and appear next to it. Do you think that would work?

**Comment by ThatcherK** [comment]
Hi @EmmawDI I have made the changes requested, please take another look

**Comment by EmmawDI** [comment]
HI @ThatcherK thank you so much - with the author box, is there any flexibility on where it's placed? Could it be at the top of the box, under the title?

**Comment by EmmawDI** [comment]
Interactive chart navigation looks great

**Comment by ThatcherK** [comment]
Hi @EmmawDI I have changed the position of the author box

**Comment by ThatcherK** [comment]
@EmmawDI The transparency is now fixed

**Comment by EmmawDI** [comment]
this is perfect! thank you so much

**Comment by edwinmp** [comment]
@EmmawDI @ThatcherK the share box seems off - ?
<img width="1349" alt="image" src="https://github.com/devinit/DIwebsite-redesign/assets/5672438/2c46553b-1673-46d2-ace4-8a24b4ab4836">

**Comment by ThatcherK** [comment]
Oh hadn't noticed that, thanks

**Comment by ThatcherK** [comment]
Fixed!

**Comment by EmmawDI** [comment]
Thanks so much - when will this be OK to promote to the live site?

**Comment by ThatcherK** [comment]
@edwinmp please test the share boxes again, it should be fixed now

**Comment by edwinmp** [comment]
> @edwinmp please test the share boxes again, it should be fixed now

Yup, it's all good now.

**Comment by ThatcherK** [comment]
@EmmawDI this should be ready by COB today

**Comment by EmmawDI** [comment]
@ThatcherK thank you so much - again, let me know if you need another pair of hands testing afterwards
