### ISSUE TITLE
Our story carousel

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#131]
http://development-initiatives.surge.sh/page-templates/04-our-story

IE11/Win 7

#### Our story carousel doesn't work

![Screenshot 2019-08-02 at 15 08 38](https://user-images.githubusercontent.com/560463/62375980-81fa3d00-b537-11e9-93c4-d7314ccae4dc.png)

**Comment by BenDarby** [comment]
Can't replicate, looks okay on my windows laptop

**Comment by BenDarby** [comment]
@benjamincoleman I just noticed these issues are related to Win7, I don't have access to this OS. But from the screenshot above it could be an issue with the JS as it's not firing to load any of the navigation elements or overflowing the content?
