### ISSUE TITLE
Adding video content option to Publication Foreword page type

### ISSUE THREAD

**Issue by EmmawDI** [devinit/DIwebsite-redesign#1314]
Hi - apologies - I should have noticed this sooner. 

We are having a video foreword for the GHA report this year in place of a written one. I've just noticed that it's currently not possible to add video (as embed link) to the Publication Foreword page type. Would it be possible for this to be changed please? This would be high priority and need to be done by w/c 15 June. Apologies again for not raising this sooner.

**Comment by edwinmp** [comment]
@EmmawDI just to clarify, you'd like the content to allow `Video`, `Audio` and the `Custom Embed` options, as they appear for the Audio & Visual Media page type?

**Comment by EmmawDI** [comment]
@edwinmp thank you for responding so quickly - we only need Video as we will be embedding a YouTube link

**Comment by ThatcherK** [comment]
Hi @EmmawDI this feature is ready for testing on staging

**Comment by edwinmp** [comment]
@ThatcherK if this is now on live, please close this.
