### ISSUE TITLE
Change to author box in So What content block

### ISSUE THREAD

**Issue by EmmawDI** [devinit/DIwebsite-redesign#1320]
Hi @ThatcherK - as discussed over Slack, it would be great if you could make a change to the author box within the So What content block to remove the default "Guest author / Written by" text. Ideally this would be prioritised as it's for the GHA report, but it won't stop us publishing if not. Thanks!

**Comment by ThatcherK** [comment]
Hi @EmmawDI , i made the these changes, you can check it out on staging!

**Comment by EmmawDI** [comment]
Hi @ThatcherK - do you think it will be possible for this to be promoted this week? Thanks!

**Comment by ThatcherK** [comment]
Yes this was meant to be deployed yesterday, but we had some issues with the process, hopefully, it will be sorted by day end today

**Comment by ThatcherK** [comment]
@EmmawDI this is now on the live site!

**Comment by EmmawDI** [comment]
@ThatcherK this is perfect, thank you so much
