### ISSUE TITLE
Focus area page type issue

### ISSUE THREAD

**Issue by EmmawDI** [devinit/DIwebsite-redesign#1331]
## I'm submitting a ...
<pre><code>
[ x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
As raised on Slack - https://devinitorg.slack.com/archives/CCG8Y0YJG/p1687343308969089 - the focus area blocks on focus area page types are no longer showing in the same order on the frontend as in the CMS. Ideally these would be configurable in the backend, to be able to change the order without having to delete and reinsert focus areas, but at the least it would be good to have matching orders in the CMS and frontend. 

**Links to pages**
https://devinit.org/what-we-do/what-we-are-working-on/
https://devinit.org/what-we-do/what-we-are-working-on/global-humanitarian-assistance/
Other focus area page types

**Environment/Server:**
<pre><code>
- [ x] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

**Requested Delivery Date:**
Not urgent

**Comment by ThatcherK** [comment]
@EmmawDI this is now fixed, the focus areas are ordered as they appear in the CMS!
