### ISSUE TITLE
Climate finance interactive

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#1337]
The detailed brief is here: https://docs.google.com/document/d/1JtTxIvIF94WYg1olJRj8sqimvb3-Q27r51TH_UXoiUo/edit#heading=h.i6dwxsuq4z6x 

@danjwalton can you share the data on this thread? It would also be good to get the details of the key things we want users to be able to easily see in the charts.

@akmiller01 it would be good to grab 10mins with you next week to pick your brains about things you've already done chart wise that might be similar to this.

**Comment by akmiller01** [comment]
Brief sounds good. I think it's something we could create either out of the DI Chart Boilerplate, or just a little bit of custom D3.
