### ISSUE TITLE
updates to the what we are working on page

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#1347]
hello - sorry this is a very late request and a bit of a priority 

I'd like to add a new focus area on 'what we are working on' page [https://www.devinit.org/what-we-do/what-we-are-working-on/?nav=header] but the page is limited so I can't add more. Are we able to remove the limit easily? Ideally we'd have an additional focus area added this week 

Best, and thanks and apologies for not getting this sorted earlier 
Simon

**Comment by SimonMurphyDI** [comment]
@k8hughes this has been assigned to Edwin - is that right?

**Comment by k8hughes** [comment]
It says you assigned it to him!! I'll take him off the ticket so Thatcher or Chris can pick it up.

**Comment by SimonMurphyDI** [comment]
I know, but I didn’t – honest! So weird

Simon Murphy | Content Strategist & Managing Editor
Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK
T: +44 (0) 1179 272 505

At DI we value and respect flexible work arrangements. I choose to work flexibly and sometimes send emails outside normal working hours – no need to respond outside yours.
DISCLAIMER: This email and any attachments are confidential and intended solely for the use of the individual or organisation to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Development Initiatives. If you have received this email in error, please delete it and notify the sender.

**Comment by edwinmp** [comment]
> I know, but I didn’t – honest! So weird

Sorry Simon, I'd set this to auto assign to me so I'd properly get notified of new tickets.
@ThatcherK @wakibi will need to change the [assignee](https://github.com/devinit/DIwebsite-redesign/tree/develop/.github/ISSUE_TEMPLATE) on the issue templates.

**Comment by ThatcherK** [comment]
Is this still  a priority? @SimonMurphyDI

**Comment by SimonMurphyDI** [comment]
Yes please, if you have time and budget, but it's not urgent if there are other time sensitive items to work on

**Comment by SimonMurphyDI** [comment]
HI @ThatcherK - is there an estimated date we might see this change?

**Comment by ThatcherK** [comment]
Sorry it's been a busy couple of days with all day meetings. Is next week okay? Most probably earlier in the week?

**Comment by SimonMurphyDI** [comment]
Of course - that's perfect :) thank you @ThatcherK

**Comment by ThatcherK** [comment]
@SimonMurphyDI This has been done and it'd now live!
