### ISSUE TITLE
Pagination update

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#135]
> Alex 13:26
> Hi @Ben, just working on pagination and I noticed that there's no mechanism for users to see the total number of pages. Would it be possible to have a solution similar to what we did for IATI standard website? With the page count underneath? I added the same HTML but it needs a bit of formatting:

> ![image-1](https://user-images.githubusercontent.com/64877/62613535-880a6800-b901-11e9-9425-a37727f8cf44.png)

So, based on @akmiller01's request, we want to improve the pagination to show the last page too. Something like this would work well: 

- Previous
- 1
- 2
- 3
- 4
- 5
- ...
- 41
- Next

---

We've implemented this: 

<img width="546" alt="Screen Shot 2019-08-07 at 10 50 37" src="https://user-images.githubusercontent.com/64877/62613592-abcdae00-b901-11e9-86ef-526f58f89aae.png">

It will apply to all listing pages: 

* #29 News Listing 
* #30 Events Listing
* #3 Blog Listing
* #15 Publications

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/158
