### ISSUE TITLE
Update to buttons on banner blocks

### ISSUE THREAD

**Issue by GeorgeCarver** [devinit/DIwebsite-redesign#1354]
**Is your feature request related to a problem? Please describe.**
When using the 'light' option for a banner block (which is an option within 'sections' on the homepage) the button option stays light too, which is really hard to see.

**Describe the solution you'd like**
It would be good if the button option instead goes dark. Please can this change be made to any similar banner blocks across the website as well. 

**Project**
Growth and external relations --> Website content updates.

**Tags**

**Budget Code**
P0589-2.01.02.03 or P0589-2.01.02.02

**Additional context**
![Banner block](https://github.com/devinit/DIwebsite-redesign/assets/62111796/deab7858-bfa8-4212-86ee-b5e3c6146514)

**Requested Delivery Date:**
By 24/11/2023 if possible, as this is a priority for COP28.

**Comment by ThatcherK** [comment]
@GeorgeCarver , @SimonMurphyDI this is now ready for testing on the dev site https://dev.devinit.org

**Comment by SimonMurphyDI** [comment]
This is perfect, thanks!

**Comment by SimonMurphyDI** [comment]
@ThatcherK
