### ISSUE TITLE
Mouseflow is not collecting data from the DI website 

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#1367]
Our Mouseflow account isn't capturing user data from visits to the site. I think this occurred due to the switch to GA4
We'd like this to establish 
1. if there are any pain points for the new homepage 
2. if there are any pain points for the climate interactive 

Here's a link that apparently explains the change we need to make 

https://rednavelconsulting.com/questions/send-mouseflow-event-to-ga4/

It would be great to make this a priority, as we're likely to get most traffic to these pages during COP

Best
Simon

**Comment by SimonMurphyDI** [comment]
@ThatcherK  still not seeing any recordings - do you want to screenshare and look at how this is set up in Mouseflow?

**Comment by ThatcherK** [comment]
Yes that would be helpful
