### ISSUE TITLE
T2: Homepage

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#14]
Sketch: https://marvelapp.com/3j51290/screen/57215549

Design: http://development-initiatives.surge.sh/page-templates/02-homepage

With variants for different numbers of publications; 

- http://development-initiatives.surge.sh/page-templates/02b-homepage-2-publications
- http://development-initiatives.surge.sh/page-templates/02c-homepage-1-publication

**Functional specification**

**Hero**

The hero of the homepage will always feature a publication. As such, it's probably ok to nominate a publication and pull this information from there, maybe with the potential to override the image. 

We have: 

**Hero:** 

- `type of publication` e.g. FACTSHEET. This is not present in GNR. This also is shown in the #15 Publication template. 
- `title`
- `Button` - links through to the publication

**Who we are / What we do**

Two modules to introduce two sections of the website, each comprising of: 

- Title
- Content
- Button link to each section

**Featured work**

This allows an admin to link to a number of content types: 

- Publications
- News
- Events
- Blog posts
- Projects (sub page of Focus Areas)

For each we show: 

- Type of thing, see list above. 
- Image
- Date of publishing
- Title
- Summary - should be custom, and then fallback to the summary of the item, then fallback to xx words from the content

**Call to action module**

- Image
- Image credit (capable of having a link in it)
- Module title
- Module content - rich text so can include links
- Module button - link location for the button
- Module button label - the text label of the button

**Comment by benjamincoleman** [comment]
Change subheading ‘our work’ to ‘what we do’ so that it tallies with what that section’s content relates to for consistency

**Comment by benjamincoleman** [comment]
Changes from latest design review: 

- Remove the three focus areas

- Who we are and What we do pieces should be side by side

- Adjust buttons to 'find out more about who we are' 

- Featured work - think we made this up to 6, and we should show content of the following types there: 

    - News
    - Publication
    - Blog
    - Event
    - Project

**Comment by benjamincoleman** [comment]
@BenDarby 

The event features is missing a tab to say what it is.

**Comment by k8hughes** [comment]
http://178.128.102.213/ 

I am not seeing what I wuld expect to see on the homepage.  I thought this wouldnt be made in the CMS, it would be hardcoded.  Is this not the case?

**Comment by k8hughes** [comment]
I have tried to add a few publications but none of them display.  I tried a legacy and I tried a new one, neither of them are showing on the homepage after I add them.

Also, as a user my most likely workflow is:
1.  Add a new publication to wagtail
2. Go to homepage and select the new publication to show on the homepage
Currently the list of publication orders oldest first, and there are 11 pages with no way to skip to the last page so I have to click through all 11 pages to get the page I need.

Can you check if the publication showing on the homepage is a bug and re order the publication list or add a button so I can skip to the last page of publications in one click please?

**Comment by edwinmp** [comment]
Hi @k8hughes ... Your configured items are showing on the Home Page. What's broken is the featured publication that's supposed to be showing up on the Hero.

![image](https://user-images.githubusercontent.com/5672438/66744578-7dca9400-ee85-11e9-8bfc-ebbc285c3cba.png)

**Comment by k8hughes** [comment]
Now the publication is displaying in the hero as intended.

**Comment by alice-mcandrew-development-initatives** [comment]
@k8hughes Is there a way to change the order of the homepage menu? (It doesn't match the AI at the moment) I tried to untick/retick 'add to menus' in correct order to no avail. Also, something odd is going on in the upper left with the logo.

What it looks like:
![Homepage](https://user-images.githubusercontent.com/55877063/67578428-55228400-f73a-11e9-80d9-4a2ded3d994f.JPG)

**Comment by alice-mcandrew-development-initatives** [comment]
@k8hughes, I'm not sure how to select anything other than a publication to feature on the homepage hero:

![Homepage](https://user-images.githubusercontent.com/55877063/69169375-2953ad80-0af0-11ea-86c0-8b12c37448e2.JPG)

@AnnaHope FYI ^

**Comment by k8hughes** [comment]
@benjamincoleman should the implementation of the design allow for content other than publications to feature on the homepage?

**Comment by benjamincoleman** [comment]
For the hero: 

> The hero of the homepage will always feature a publication. As such, it's probably ok to nominate a publication and pull this information from there, maybe with the potential to override the image.

For the Featured Work module: 

> This allows an admin to link to a number of content types:

> Publications
> News
> Events
> Blog posts
> Projects (sub page of Focus Areas)

**Comment by k8hughes** [comment]
@alice-mcandrew-development-initatives so what the developers have done is correct and it follows the design.  Is the design wrong?  What do you want to feature on the hero of the homepage?

**Comment by alice-mcandrew-development-initatives** [comment]
@AnnaHope was expecting content other than publications to be an option for the hero.
At the moment we can't have news, events, blogs or projects:
![image](https://user-images.githubusercontent.com/55877063/69258852-35557300-0bb5-11ea-8841-f6463bc45c3b.png)

**Comment by alice-mcandrew-development-initatives** [comment]
For feature content, we have these options which I think is fine:
![image](https://user-images.githubusercontent.com/55877063/69259023-7f3e5900-0bb5-11ea-92a2-d7f986056e25.png)

**Comment by alice-mcandrew-development-initatives** [comment]
@benjamincoleman I think something must have been lost in communication for the desired functionality of the homepage hero?

**Comment by edwinmp** [comment]
@benjamincoleman would anything need to change in the design to support having the other content types on the home page hero?

**Comment by benjamincoleman** [comment]
@alice-mcandrew-development-initatives I'm pretty sure we agreed we'd have publications there - the 'always feature a publication' line came from me asking the question whether you'd have enough publications to consistently fill that hero space throughout the year. 

@edwinmp We would need to have design variants. As things are the implementation is not right - the class 'hero--minor' needs to be removed.

**Comment by benjamincoleman** [comment]
@BenDarby 

We need homepage hero variations to feature the following types of content: 

* news
* blogs
* events 
* projects

I'll produce sketch variants and post them here.

**Comment by benjamincoleman** [comment]
Sketches are here: https://marvelapp.com/3j51290/screen/64145645

**Comment by AnnaHope** [comment]
@edwinmp @akmiller01 the designs you need to change the homepage hero are here:

Publication: http://development-initiatives.surge.sh/page-templates/02-homepage
News: http://development-initiatives.surge.sh/page-templates/02d-homepage-news
Blog: http://development-initiatives.surge.sh/page-templates/02e-homepage-blog
Event: http://development-initiatives.surge.sh/page-templates/02f-homepage-event
Project: http://development-initiatives.surge.sh/page-templates/02g-homepage-project

**Comment by edwinmp** [comment]
Great, @AnnaHope ... let me implement them ... will let you know when they're on staging.

**Comment by edwinmp** [comment]
Hi @AnnaHope the home page hero designs are now available on staging.
