### ISSUE TITLE
T21 Data Section

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#145]
**Sketch:** https://marvelapp.com/3j51290/screen/59725627

**Design:** http://development-initiatives.surge.sh/page-templates/21-data-section

**Functional specification:** 

The hero has the usual layout, but also a "Datasets" button that will take you to the Datasets listing page. 

Then we have the sidebar menu, linking to other pages in this section. 

Also some Rich Text Editor content. 

Then we have a section with a quote and number of datasets in it. We're envisaging multiple quotes here, so want to show one at random when the page loads. 

The number of datasets will come from the actual number of datasets in the system, and the "view datasets" button underneath will link to the Datasets listing page. 

Data Support Services is a call to action - we're trying to generate leads for data support consultancy work to earn money for DI. 

Lastly we have the standard "More About" section that will have appeared on other pages in the site, so you should be able to extend it to here.

**Comment by benjamincoleman** [comment]
Design is here: http://development-initiatives.surge.sh/page-templates/21-data-section

Changes: 

- [ ] Remove "Our Skills section" - https://cloudup.com/cgOUu3WM2pm

**Comment by benjamincoleman** [comment]
@BenDarby changes following review: 

- [ ] add "view datasets" button to the hero 

> can the 'view datasets' call to action be added to the hero/banner image overlaid - it seems quite hidden at the moment so having it in both places (like publication downloads) would be good.

**Comment by k8hughes** [comment]
http://178.128.102.213/data/domestic-resources-vs-international-finance-flows-developing-countries/

It currently doesn't pull through the report names that we have in the publications section.  Should it be doing that? @davidebukali @Napho @edwinmp

**Comment by k8hughes** [comment]
http://159.65.56.142/data/ 
@alice-mcandrew-development-initatives this now needs correct content to be added.

**Comment by alice-mcandrew-development-initatives** [comment]
This content have been added @k8hughes
