### ISSUE TITLE
T21.1 Dataset listing

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#146]
**Sketch:** https://marvelapp.com/3j51290/screen/59725629

**Design:** http://development-initiatives.surge.sh/page-templates/21-1-dataset-listing

**Functional specification:**

This page uses the fallback hero pattern, so there's no image, and the class `` is used to control the height. 

Then we have the sidebar menu, linking to other pages in this section.

Also some Rich Text Editor content.

There are 4 filters which filter the datasets to show relevant datasets. The filter relationship should be AND - we may want to change that to OR though, so please bear that in mind. 

Values for the filters are: 

**Report**

* Global Humanitarian Assistance
* Investments To End Poverty
* Global Nutrition Report
* Something else

**Data Source**

Latest thinking is: 

- UN OCHA - FTS
- OECD - CRS
- World Bank - PovCalNet
- World Bank - Data Bank
- World Bank - LSMS
- World Bank - CCKP
- UNICEF - MICS
- IMF - WEO
- N/A - DHS
- N/A - INFORM
- DFID - N/A
- UNDP - HDI
- N/A - IPUMS
- N/A - IDMC
- FCA - N/A
- IFRC
- ACAPS
- UNHCR

**Country**

Same as #15 

http://development-initiatives.surge.sh/page-templates/13-publications

**Topic** 

Latest thinking is: 

- Poverty
- Aid/ODA
- Humanitarian finance
- Domestic finance
- Development finance
- Transparency
- Data use
- About Development Initiatives

Then we have the list of datasets. For each dataset we are showing: 

- a small tab with the publication, and the figure this dataset relates to. 
- title
- release date

Each dataset links through to a single page about that dataset. 

Lastly we have the standard "More About" section that will have appeared on other pages in the site, so you should be able to extend it to here.

**Comment by benjamincoleman** [comment]
@BenDarby can you make some updates for me? 

For each dataset in the listing, replace "updated" with "released".

In the filters, can you sort the first two filters for Report and Data Source alphabetically

The titles of the datasets are looooooong I'm afraid. For example: 

> ITEP 2018 Figure 3.1. Domestic resources in developing countries are 12 times larger than international finance flows to developing countries, of which commercial sources of finance dominate 

I'll get some more examples into a model for you.

**Comment by benjamincoleman** [comment]
@BenDarby can you add the text "released: " infront of the date on the listing items please? 

> For each dataset in the listing, replace "updated" with "released".

**Comment by benjamincoleman** [comment]
Design: http://development-initiatives.surge.sh/page-templates/21-1-dataset-listing

Changes:

- [ ] Sort "Topic" filter alphabetically
- [ ] Change "Countries" label and name to "Geography"
- [ ] Add "All countries in {{Continent}}" as the first item in each `<optiongroup>`

I've updated the model to:

1. make sure the little tab reads "ITEP 2018 - FIGURE 3.1" as it does on the single page
2. reduce the number of datasets visible to a sensible number (18) using a show / hide attribute of each dataset in the model

**Comment by benjamincoleman** [comment]
@BenDarby changes from design review:

- [ ] use same no image style of hero as on the Single. There's notes on what I've done to that one here: https://github.com/devinit/DIwebsite-redesign/issues/147#issuecomment-523616862

> Can we have the same approach of no image on this page too?

**Comment by k8hughes** [comment]
In the design the banner strip for ```Data Support Service``` is a link to an internal page rather than just a banner block.

![Screenshot 2019-10-31 at 10 05 46](https://user-images.githubusercontent.com/36768381/67926069-196a3d00-fbc6-11e9-942b-8d22073f3b62.png)

Current implementation in the CMS assumes this is just a banner.

**Comment by edwinmp** [comment]
> In the design the banner strip for `Data Support Service` is a link to an internal page rather than just a banner block.
> 
> ![Screenshot 2019-10-31 at 10 05 46](https://user-images.githubusercontent.com/36768381/67926069-196a3d00-fbc6-11e9-942b-8d22073f3b62.png)
> 
> Current implementation in the CMS assumes this is just a banner.

@k8hughes guess this should be on issue #145 ... instead of coding an entirely new widget for a clickable banner, I think simply adding a button for navigating to the Data Support page will do here.

![image](https://user-images.githubusercontent.com/5672438/68210452-9b070400-ffe6-11e9-89c9-0ef59e9178db.png)

**Comment by k8hughes** [comment]
Yes, just having the button is enough.
