### ISSUE TITLE
T21.2 Dataset single

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#147]
**Sketch:** https://marvelapp.com/3j51290/screen/59725631

There are three screens showing the contents of the tabs, so you can click on them in the Marvel link above and see them. 

**Design:** http://development-initiatives.surge.sh/page-templates/21-2-dataset-single

**Functional specification:** 

**Hero:**  

- Small tab with the Publication and the Figure in.
- Dataset title
- Optional description

Under the hero we have the Release date of the dataset

Then we have Wysiwyg content

There is an optional Alert to show if there is a more up to date version of this dataset, with a link to said dataset. 

Download module variant - note the explanation as to format types and what they are suitable for.

Analyst - would be DI team member, so can use the existing design pattern for authors. 

The content underneath the DI team member about contacting people will be standard text across all datasets

**Metadata tabs:** 

Will be accordion on mobile, tabs on large screens - let me know if you need JS help here. 

Tab 1 - Description
All Wysiwyg fields, but will be 5 separate blocks. The last 4 for provenance, variables, geography and topics will only show if they are completed. 

Tab 2 - Sources
Will be a list of links to other data sources - so a variant of the dataset design pattern. They have for each a name of the dataset, which is a combination of the organisation providing it and the specific dataset name. Then there's the access date, which is **not the same** as the released date. On some of these we have buttons to link to the dataset which could be in this website, or could be an external URL. 

Tab 3 - Licence and suggested citation
Text content for each - will be separate fields. 

**References to charts etc.** 

We use this section to link to where the dataset is used. 

Each shows the report image, date and title - this is what we list on the publications screen. 

Then for each publication it shows the list of links to figures that use this dataset.

**Related datasets**

Will link to other datasets in the system - so same design here as the listing page. 

---

It's worth looking at the microformats in designing and developing this page, as we would love this data to be discoverable / machine readable. https://developers.google.com/search/docs/data-types/dataset

**Comment by benjamincoleman** [comment]
Have a content model which has been included in the IA and the Sketch. 

I've also developed a template to gather real content for the design to use: https://docs.google.com/document/d/1N7Pwn8j6cNjrBoubS-0OCBamV4BOYgxPccetoeMOu7o/

**Comment by benjamincoleman** [comment]
@BenDarby looks lovely mate, really good. 

I have some edits: 

Alert alignment is somewhat off: 

<img width="116" alt="Screen Shot 2019-08-19 at 10 03 41" src="https://user-images.githubusercontent.com/64877/63252914-ac9f0200-c268-11e9-963f-51e75539cda2.png">

Add a short para after main content "Data in US$ billions. Data is for the most recent available year across all categories."

Tab 1 - For explanations on Domestic and Official resources data used refer to ITEP methodology page: http://devinit.org/wp-content/uploads/2018/10/Investments-to-End-Poverty-2018_Methodology.pdf
Can you make the 'ITEP methodology page' the link please and remove the URL

Tab 2 - Need "released:" before the data as mentioned in the listing template: https://github.com/devinit/DIwebsite-redesign/issues/146#issuecomment-521976155

Tab 3 - Remove the content on the right, but make sure the links are the same in the content on the left. So this text should be linked: 

- Development Initiatives Poverty Research Limited
- Creative Commons Attribution 4.0 International License

**Comment by benjamincoleman** [comment]
Design: http://development-initiatives.surge.sh/page-templates/21-2-dataset-single

Changes: 

- [ ] Release date: 1.1.2018 could be more prominent
- [ ] Tab - Description - 'Topics' should be an unordered list
- [ ] Tab - Sources - Datasets here are not DI datasets. Look at the sketch - https://marvelapp.com/3j51290/screen/60266696 It's clearly different content, and should look visually different too. 
- [ ] Missed out this piece from previous round of amends: 

> Tab 3 - Remove the content on the right, but make sure the links are the same in the content on the left. So this text should be linked:

> Development Initiatives Poverty Research Limited
> Creative Commons Attribution 4.0 International License

**Comment by benjamincoleman** [comment]
@BenDarby On the dataset single I forgot to mention to remove the picture from the hero. 

So, I did this and it seemed very deep. The `--minor` modifier class was set to only do something when up to the `menu` breakpoint. 

So, I added another modifier class `--short`: 

```
&--short {
    padding: 8em 0 15em 0;
}
```

I'm not sure if you want to factor this into other places, but in general, if we don't have an image it might be an idea to make the hero a little shorter. I'll leave this to you to decided though.

**Comment by BenDarby** [comment]
@benjamincoleman cool, the --minor modifier just needed adding with different padding at a larger breakpoint, so I renamed --short to --minor after $e-vp and all good :) I've set in the includes and model that when there is no image applied to the hero use the --minor modifier

**Comment by benjamincoleman** [comment]
-  [ ] Change the wording in the dataset alert message to "There is more recent data available relating to this dataset".

>  @Ben it isn't that there is a more up to date version of the data set, its that there is more recent data than what they are looking at. e.g. the dataset is 'Poverty levels 2002-2005' and we have one that is 2006, the dataset '2002-2005' is still the most up to date version of that dataset. I think it should say 'there is more recent data available relating to this dataset'
 
- [ ] Also make the icon something time based. What has happened is that we don't want it to feel like a warning that the data might be bad / wrong.

**Comment by k8hughes** [comment]
http://178.128.102.213/data/domestic-resources-vs-international-finance-flows-developing-countries/domestic-resources-vs-international-finance-flows-developing-countries/

Let's wait for the test with actual data from Box to mark this as done

**Comment by k8hughes** [comment]
http://159.65.56.142/data/datasets/proportions-of-cash-and-vouchers-in-humanitarian-cash-and-voucher-assistance-20152018/#description 

All the text in the meta data tab is incorrectly formatted, it is coming out very small. @edwinmp

**Comment by akmiller01** [comment]
This PR makes the metadata fields RichText, which wraps them in <p> elements and makes the font-sizes bigger: https://github.com/devinit/DIwebsite-redesign/pull/402

It's on Develop now if you want to test @k8hughes http://178.128.102.213/data/datasets/proportions-of-cash-and-vouchers-in-humanitarian-cash-and-voucher-assistance-20152018/ 

There's another bug now where related pages have duplicates, but that's fixed in #404

**Comment by k8hughes** [comment]
So the foprmatting of the text now looks correct, but I've noticed another issue, that might be content rather than code, you'll have to tell me which it is.

The URL here isn't appearing as a link, how do we fix this?
![Screenshot 2019-11-19 at 14 51 29](https://user-images.githubusercontent.com/36768381/69156928-1800a600-0adc-11ea-9c1a-4c571002cca6.png)

**Comment by akmiller01** [comment]
@k8hughes It's because it was pulled through as text from the XLSX spreadsheet. In code, we could autoformat all URLs as hyperlinks, but that could potentially have unintended consequences. If we want, that field is editable as richtext in the CMS, but since it's a citation, I think it's fine that it's not actually a hyperlink.

I imagine the use-case for most suggested citations is copying and pasting them into Word documents.

**Comment by urlsangel** [comment]
@akmiller01 @k8hughes 

You could add [Django's `urlize` filter](https://docs.djangoproject.com/en/2.2/ref/templates/builtins/#urlize) to make these into clickable links.

**Comment by akmiller01** [comment]
Yep, that's an easy fix @urlsangel https://github.com/devinit/DIwebsite-redesign/pull/493

![image](https://user-images.githubusercontent.com/2836840/69159461-f391d300-0ab5-11ea-9572-fbabaad8b830.png)

I was worried that it would try and doubly-anchor already existing anchors, but it doesn't.

**Comment by k8hughes** [comment]
![Screenshot 2019-11-25 at 12 38 26](https://user-images.githubusercontent.com/36768381/69541224-8af89980-0f80-11ea-8c55-ad194e7fac5d.png)
@akmiller01 notice how the link here sites the old word press address, will this be changed automatically?

**Comment by akmiller01** [comment]
Yep, you can check to see just by swapping http://devinit.org with http://159.65.56.142

In this case: http://159.65.56.142/wp-content/uploads/2019/09/GHA-report-2019_Chapter-5.pdf

**Comment by k8hughes** [comment]
Ok I think I understand, so /wp-content/ doesn't mean the old site - it means the wp-content folder on the new site.  Sorry for being a total dufus.
