### ISSUE TITLE
Author block bug

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#149]
> Hi @Ben ... this is what happens when job titles or names are too long... any chance we could make that horizontally stretchy? 

![image-1](https://user-images.githubusercontent.com/64877/62620880-59e15400-b912-11e9-9ddf-bc596f4b4d7f.png)

The stretchy idea is not a bad one - could have a min-width / max-width and then make sure we have wrapping in place. Maybe abs position on the image and then a padding-left to control the text position?

**Comment by BenDarby** [comment]
@benjamincoleman fix pushed
