### ISSUE TITLE
T13 Publications

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#15]
Sketch: https://marvelapp.com/3j51290/screen/57564426

Design: 

Normal: http://development-initiatives.surge.sh/page-templates/13-publications

Filtered: http://development-initiatives.surge.sh/page-templates/13a-publications-filtered

Functional spec:

Code for country filter is something like this - so we are using option groups. 

```
<select>
  <option>Region</option>
  <option value="global">Global</option>
  <optgroup label="Africa">
    <option value="volvo">Kenya</option>
    <option value="saab">Uganda</option>
  </optgroup>
  <optgroup label="Asia">
    <option value="mercedes">Nepal</option>
  </optgroup>
</select>
```

For the topics filter we have the following topics and you can see them in a design for the data section listing here: http://development-initiatives.surge.sh/page-templates/21-1-dataset-listing

Worth noting that the Topic taxonomy will also be used by datasets.

- About Development Initiatives
- AID/ODA
- Data use
- Development finance
- Domestic finance
- Humanitarian finance
- Poverty
- Transparency

For each publication we are showing: 

- Type of publication e.g. FACTSHEET / REPORT / BACKGROUND PAPER ← This is not present in GNR so will need to be created. 
- Image same as the hero image for the publication summary page, or short publication
- Title
- Published date
- Excerpt - should be a custom field, then fall back to shortening some content. I think you've used this approach in the blog / news section.

**Comment by benjamincoleman** [comment]
@BenDarby Can we do a variation of this when filtered to have a title underneath the filter to say:

"Showing page 2 of 24 results"

**Comment by benjamincoleman** [comment]
@akmiller01 I've just updated the functional spec with more information on the Topics filter for this template. Moving onto the others now

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/299
