### ISSUE TITLE
T14 Publication long form - summary

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#16]
Will have multiple authors

Sketch: https://marvelapp.com/3j51290/screen/57790096

Design here: http://development-initiatives.surge.sh/page-templates/14-publication-summary

Functional Specification:

The publications section can be copied across from the GNR website and the templates are broadly very similar in the content and functionality they have. 

**Hero:** 

- `type of publication` e.g. FACTSHEET. This is not present in GNR. This also is shown in the #15 Publication template. 
- `title`
- `Publication downloads button` - this links you down to the "Publication downloads" section right at the bottom of this template. 

**Authors**

After the hero we have a space to name the `authors` of the publication. This is not present in the GNR work, so will be new functionality. In some cases they may be DI Staff, in which case we want to link to their profile, and in other cases it will just be a name with no link. 

**Sections**

Each chapter in a long form publication is a separate page. For each of these pages we have a summary section in this template. You can see this on the GNR website here: https://globalnutritionreport.org/reports/global-nutrition-report-2018/ 

We have the following in this template: 

1. Introduction 
2. Chapter 1
3. Chapter 2
4. Chapter 3
5. Several pages after that such as: 
    - Report data and metadata
    - 2018 Global Nutrition Report methodology
    - Appendix A
    - Appendix B

items 1-4

- `title`
- `Read the summary` - link to the page
- `Download the summary` - list of download options - this is used for languages. If there's only one language available, it would probably be good to just show a button as we do for `Read the summary`
- `Download data` - will be a link to a dataset in the new Data Section I expect. Might be worth checking this with @k8hughes and Anna / Claudia though in case this launches first. In that case it might be a file download. 

on items 3-4 where we're showing chapters, we also have a small piece of text like 'CHAPTER 1' above the title

Items 5

We also have several pages for things like methodologies and appendices that follow the publication sections. These have: 

- `title`
- `description` - an excerpt, so custom text which falls back to a certain numbers of words from the content. 
- `button` - links through to the page

Following this we have: 

- Sharing module - should just work if it's brought across from GNR
- Publication downloads - these are for the whole publication, rather than the individual chapters. Again, check on the data downloads as that is again likely to need to point at a specific dataset in the new Data Section. 
- Large CTA to download the report - slightly repetitious, but we have a space to have a CTA to show an image, content and download button for the whole report.

**Comment by k8hughes** [comment]
http://178.128.102.213/publications/new-long-publication/summary-report/ 

@akmiller01 authors are not pulling through, otherwise it seems to work.

**Comment by k8hughes** [comment]
Hmmmm, I have now gone and added two chapters to this report and I expeted them to show up on the sumary like this design, but they do not.  
http://development-initiatives.surge.sh/page-templates/14-publication-summary

**Comment by akmiller01** [comment]
Chapters and authors appear on the PublicationPage: http://178.128.102.213/publications/new-long-publication/

**Comment by akmiller01** [comment]
Template 14-Publication-Summary maps to `PublicationPage` despite its name. The template for `PublicationSummaryPage` is the same as long form.

**Comment by k8hughes** [comment]
http://178.128.102.213/publications/new-long-publication/ 

The summary page is looking good but the author names now apear in too many places.  We only need them once at the top of the page, not at the header section of each chapter.

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/228/files Quick template fix here.

**Comment by k8hughes** [comment]
This is now correct.

**Comment by alice-mcandrew-development-initatives** [comment]
@k8hughes 
I used green to test this template with the GHA Report 2019: http://159.65.56.142/publication/global-humanitarian-assistance-report-2019/

1) There still appears to be red sections
2) 'The summary' is not editable but should be 'the executive summary' or at least 'the summary'

![GHA page](https://user-images.githubusercontent.com/55877063/67869793-d5276000-fb25-11e9-925b-8e111efe968c.JPG)

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/344

**Comment by akmiller01** [comment]
As for red sections when `body--leaf` is selected @benjamincoleman

**Comment by akmiller01** [comment]
@alice-mcandrew-development-initatives in the above PR I've changed the label from `The summary` to `the executive summary`

**Comment by k8hughes** [comment]
@benjamincoleman I think the bug that Alice has logged is either not a bug and a deliberate design choice or a mistake in the pattern library as it is not on our side.  Can either you or @BenDarby advise please?

**Comment by alice-mcandrew-development-initatives** [comment]
@akmiller01 Thanks. Let me know when the 'the executive summary' should be appearing.
Also, thanks @k8hughes

**Comment by benjamincoleman** [comment]
@BenDarby there are some red elements remaining when a publication summary is switched to another colour. 

You can see a live example here: https://github.com/devinit/DIwebsite-redesign/issues/16#issuecomment-547949063

And this applies to this template: http://development-initiatives.surge.sh/page-templates/14-publication-summary

It looks a little odd, was it a deliberate design choice, or should they be re-coloured to match the publication colour scheme choice? I think we're leaning towards the latter here

**Comment by BenDarby** [comment]
@benjamincoleman Yeah these should be coloured to match as well, I missed these. Updated and pushed to PL

**Comment by k8hughes** [comment]
@edwinmp can you pull this through?

**Comment by alice-mcandrew-development-initatives** [comment]
This looks great, thank you all!

**Comment by alice-mcandrew-development-initatives** [comment]
Contrary to the pattern library, we probably don't need to display sample text for the appendixes, as this looks odd when it pulls through if you have tables and/or paragraph breaks in first few lines, which will often be the case for appendixes (as these will likely include references and acronyms):
![image](https://user-images.githubusercontent.com/55877063/69973483-789bd400-151b-11ea-8106-16aef9b2e8ad.png)
You can find an example of this here: http://159.65.56.142/publications/multi-year-humanitarian-funding-planning-jordan-and-lebanon/

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/611

This way, Appendix will only have text if typed into the hero text field
