### ISSUE TITLE
T14.1a Publication short form

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#17]
Sketch: https://marvelapp.com/3j51290/screen/57853947

Design: http://development-initiatives.surge.sh/page-templates/14-1a-publication-short-form

Functional Specification: 

The publications section can be copied across from the GNR website and the templates are broadly very similar in the content and functionality they have. 

This template is also very very similar to the one for a long form publication chapter - #36 . I think the only difference may be the nav menu in the bottom right of the screen and how that works. 

**Hero:** 

- `type of publication` e.g. FACTSHEET. This is not present in GNR. This also is shown in the #15 Publication template. 
- `title`
- `Publication downloads button` - this links you down to the "Publication downloads" section right at the bottom of this template. 

**Content:**

This uses a large streamfield which allows you to insert multiple types of content. We've deliberately kept the functionality here the same to hopefully make it importable from GNR with zero issues. I've mentioned footnote seperately, but this functionality is presnet here, and is less portable / more complicated. We've had a call about that, and if you need support do please reach out as we're more than happy to help. 

**Downloads:**

There may be specific downloads for this chapter. Again, this will also need to accept links to pages in the new Data Section when that is built. 

**Sharing**

This should just work I hope. It's common to #16 and #17 

**Publication Downloads**

This layout differs from the long form publication, as we don't have the main report CTA. Instead we've spread the downloads out over two columns with the data downloads on the right. 

The downloads on the left would be PDF downloads of the publication in different languages. Any other download files should be entered into the Downloads section I mentioned previously. 

For the data downloads, this will also need to accept links to pages in the new Data Section when that is built. 

**Footnotes**

We allow users to add footnotes and recently built some really innovative functionality to help with this. We've had a call about this, and if you need help do please say so and we'll be able to assist.

**Related content**

The ability to link to up to three other pages of content - could be publications, could be other types of content from within the website such as News, Blog etc. 

**Section navigation**

We have the section navigation in the bottom right of the screen that is very similar to the Chapter Navigation I mentioned in #36  

<img width="224" alt="Screen Shot 2019-08-27 at 11 54 56" src="https://user-images.githubusercontent.com/64877/63765694-81985c00-c8c1-11e9-8525-98661fcf653f.png">

This is slightly different to the GNR menu, in that it works by just taking the sections from this short form publications page and showing them in a menu: 

<img width="1440" alt="Screen Shot 2019-08-27 at 11 55 48" src="https://user-images.githubusercontent.com/64877/63765756-a391de80-c8c1-11e9-9a71-839d38df57c5.png">

**Comment by benjamincoleman** [comment]
@BenDarby I think we need to re-design this. As things stand when this opens we can't see the page, and so when we hit the menu item we wont know anything has moved, unless the whole thing disappears afterwards. I don't think that's particularly elegant or usable. 

So, I'd suggest we show a sidebar nav instead. Something like this: 

![image](https://user-images.githubusercontent.com/64877/62035614-1d15ae80-b1e8-11e9-8b6e-1ab7fc1192fd.png)

**Comment by benjamincoleman** [comment]
@urlsangel On this one, we have "jump to section" button at the bottom right. When you open it you should be able to click on an item in the list which causes: 

1. The menu to close
2. The page to smoothly scroll to that section heading

**Comment by urlsangel** [comment]
@benjamincoleman 

Re this comment: https://github.com/devinit/DIwebsite-redesign/issues/17#issuecomment-517272475

This isn't currently hooked up in the PL, all the links in the nav are "#" rather than unique ids.

On first impression, I find the nav having the same grey background as the page is disorientating.

**Comment by k8hughes** [comment]
http://178.128.102.213/publications/purple-short-pub/ 

@akmiller01 can you let me knwo when the change is made so I can add multiple countries?

**Comment by k8hughes** [comment]
Oh one other thing I've noticed @akmiller01 the authors are not appearing on the page, though I have added them in the CMS...

**Comment by akmiller01** [comment]
Yep. Okay fixed the author bug. It was using the same template as Chapters and I didn't anticipate a chapter page having a separate author.

**Comment by akmiller01** [comment]
Merged in @k8hughes https://github.com/devinit/DIwebsite-redesign/pull/224

**Comment by k8hughes** [comment]
http://178.128.102.213/publications/test-short-publication-page/ 

When testing the tables I couldn't work out how to add more rows.  I assume the CS user will need to be able to add collumns and rows so the table i the right size.

**Comment by akmiller01** [comment]
Right click: 
![image](https://user-images.githubusercontent.com/2836840/65598429-5f9a0400-df69-11e9-8c85-b848535c1f91.png)

**Comment by k8hughes** [comment]
Ah good stuff.  I didn't know that.

**Comment by alice-mcandrew-development-initatives** [comment]
@akmiller01 and @AnnaHope I thought there was an issued raised for this but I can't find it if there is... It looks like the bottom-right menu on the short publication still needs to be looked at:
![image](https://user-images.githubusercontent.com/55877063/69631612-feb0aa00-1045-11ea-9e26-b3a68b8e930e.png)
This page: http://159.65.56.142/publications/preliminary-oda-data-2018-total-falls-for-second-consecutive-year/
This template: http://development-initiatives.surge.sh/page-templates/14-1a-publication-short-form

**Comment by AnnaHope** [comment]
@alice-mcandrew-development-initatives what exactly the issue? Is it that is is called 'contents' instead of 'jump to section'?

**Comment by alice-mcandrew-development-initatives** [comment]
@AnnaHope Yes, and it shouldn't have the numbers above the section names (as this only makes sense for chapters)

**Comment by AnnaHope** [comment]
Ah ok. @akmiller01 is it possible to hide the numbering as per the template? 
![image](https://user-images.githubusercontent.com/16958942/69641272-d0d46100-1057-11ea-9f66-c804efadbddd.png)

**Comment by akmiller01** [comment]
Yep! This should make it appear just like the pattern library for short publications: https://github.com/devinit/DIwebsite-redesign/pull/591

**Comment by k8hughes** [comment]
Since thi fix has been deployed now those headings are no longer clickable, so we got a regression since removing the numbering.  Example of a page with this problem:  http://159.65.56.142/publications/preliminary-oda-data-2018-total-falls-for-second-consecutive-year/

**Comment by alice-mcandrew-development-initatives** [comment]
@k8hughes Sorry, I misread this! I thought it was in 'Comms Review' but not working, but I see it was 'In progress'

**Comment by akmiller01** [comment]
Hi @benjamincoleman I'm afraid despite all my tinkering I cannot get the chapterNav.js to work with the altered chapter nav in Short Publications. Does it need altering on your end? http://development-initiatives.surge.sh/page-templates/14-1a-publication-short-form

**Comment by benjamincoleman** [comment]
Sure, the JS will be in the pattern library. I can ask @urlsangel to have a look.

**Comment by akmiller01** [comment]
Should fix the JS https://github.com/devinit/DIwebsite-redesign/pull/612
