### ISSUE TITLE
Filter misaligned on publications

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#172]
http://development-initiatives.surge.sh/page-templates/13-publications

IE11/Win 7

#### Filter misaligned on publications

![Screenshot 2019-08-13 at 15 02 53](https://user-images.githubusercontent.com/560463/62948052-9b26a780-bddb-11e9-9d44-c136ea1f1037.png)

**Comment by urlsangel** [comment]
@BenDarby 

This is still an issue on IE11/Win 10.

**Comment by BenDarby** [comment]
@urlsangel fixed now, @edwinmp pull from `pattern_library to apply css changes
