### ISSUE TITLE
Publications chapter nav out of alignment

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#179]
http://development-initiatives.surge.sh/page-templates/14-1-publication-long-form

The left side and right side are misaligned

**Comment by BenDarby** [comment]
@benjamincoleman need more info if that's okay

**Comment by benjamincoleman** [comment]
I can't see the problem now.

**Comment by benjamincoleman** [comment]
![Screen Shot 2019-08-27 at 10 07 19](https://user-images.githubusercontent.com/64877/63757714-7e49a400-c8b2-11e9-9e9b-9a9deb4a6652.png)

**Comment by BenDarby** [comment]
@benjamincoleman the content is positioned using percentage, so when you resize the browser the menu on the right moves into position, I was seeing this when resizing screen on through my TV but after releasing my mouse from resizing it would then move into place. My only thought was that the the menu didn't move into place when you resized browser for some reason. Maybe it was a one off incident? As it's using css properties that are well supported.

**Comment by benjamincoleman** [comment]
I'll try and reproduce and record it - it's definitely happened twice though.

**Comment by benjamincoleman** [comment]
The content on the left is fixed to to the top. The content on the right is centred. Should be the same no? https://files.slack.com/files-pri/TGD7UN2C8-FMSSGJKCM/download/kapture_2019-08-28_at_12.27.03.mp4
