### ISSUE TITLE
T12b Event single

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#18]
Sketch: https://marvelapp.com/3j51290/screen/57228255

Design: http://development-initiatives.surge.sh/page-templates/12b-event-single

For an event, in the hero we have the post title, and label 'event'. In this case there is no image, to show you what a fallback hero would look like. But, we should have an image here. You can use examples for #12 or #21 to help here. 

Under the hero we have some key event information: 

* Event start date - end date including the year e.g. Dec 10 - Dec 12, 2019. If the start year is different to the end year, it should show both e.g. Dec 10, 2019 - Jan 12, 2020. I would use date pickers for the dates, rather than free text.
* Start time - end time. I would use free text for the start time - end time, and for the location.
* Location. free text again.
* Register button - this would go to an external URL. If the admin enters one, show the button, if they don't then don't show the button. 

Next we have a standard rich text section. 

Lastly we have related content - the approach to take with this is to allow admins to select up to 3 other blog posts, events, or publications to link to. If the admin selects none, or less than three, then fetch another blog post to add in here to make up the numbers to three. We'll have code in GNR to help with this is you want to get a head start.

**Comment by k8hughes** [comment]
http://178.128.102.213/events/here-another-test-event/

The size of the block quote font seems to have come out very very small.  Is this a user error or a bug?

**Comment by k8hughes** [comment]
User error apparently, so this LGTM

**Comment by benjamincoleman** [comment]
The quote contents of `<blockquote>` should be in `<p>` tags as below. 

```
<blockquote>
    <p>“A blockquote! Lorem ipsum dolor sit amet, consectetur  adipiscing elit. Vivamus magna. Cras in mi at felis aliquet congue. Ut a  est eget ligula molestie gravida.”</p>
</blockquote>
```
