### ISSUE TITLE
T1: General Template

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#19]
Sketch: https://marvelapp.com/3j51290/screen/57215544

Design: http://development-initiatives.surge.sh/page-templates/01-general-page

Functional Specification:

This pages is used in several pages across the IA in: 

1. Our Strategy - Who we are > 
2. Consultancy work examples - What we do > Consultancy Services > 
3. Data support services - What we do > 
4. How we work, and sub pages of that page
5. Team stories - Work for us > 
6. Sub pages in the new Data Section (just out of design now)

**Hero**

- Image
- Image credit (capable of having a link in it)
- Title
- Subtitle

**Side navigation**

Shows pages in this section

Following the hero / sidebar nav we'd like a streamfield that can show the following items: 

- Content
- CTA module with quote
- Image and text module
- Video and text module
- Large image

I'll go through each in turn

**Content**

Under the hero we have a rich text editor content section

**CTA module with quote**

This same module is used on other templates such as #5 

- Image
- Image credit (capable of having a link in it)
- Module title
- Module content - rich text so can include links
- Module button - link location for the button
- Module button label - the text label of the button

**More content**

Following the CTA module, there's another section of rich text editor content

**Image / Video & Text modules**

Following the second set of content there's two examples of modules that have either a video, or an image, with accompanying text: 

<img width="1204" alt="Screen Shot 2019-08-27 at 15 44 30" src="https://user-images.githubusercontent.com/64877/63781419-a6043080-c8e1-11e9-9937-14c7cf28448e.png">

In each case there's the media item, and then on the right just a rich text block where the admins can enter headings, paragraph, links and formatting. 

**Large image with caption**

- Image
- Image credit (capable of having a link in it)

---

old content ⏬ 

# 🎯 Template Purpose

The general template is the base for all templates besides the Publications and Contact Us templates. 

# 🗂 Template details

**Template Number**

T1 General 

**Sketch:**

~~https://marvelapp.com/1b2f486g/screen/51364164~~

# 📋 Template spec

**Modules (as per spec for this template in IA):**

**Side menu**
* 4-6 Sub-menu items
* Active page - highlighted

**Page title**

*  Succinct one line overview or page title (See examples in [P1.0](~~https://marvelapp.com/1b2f486g/screen/51358448~~), P1.1, P1.2)

**WYSIWYG - sections with alternating background colour**

* The purpose of the alternating background colour is to help users understand that groups of content are related and when we're moving onto content that is different in some way e.g. DI's core grant work vs DI's consultancy work
* Level 2+3 headings
* Copy
* Image (optional caption) - full width or centred (no align L/R)
* Video
* Primary CTA
* Secondary CTA
* Blockquote: quote, name and credential, optional headshot

**Alternative links to featured page sub-menu items - located above footer**

* Client to choose sub-pages to feature here, fall back is top 4 in the submenu excluding the current page
* Heading: Title of top-level page e.g. Who we are, What we do
* For each link: image (no images currently specified), page title and link to the page

**Comment by benjamincoleman** [comment]
Subnav - `more in` ← implies we’re in this page, but we need to be implicit about all. So change to ‘More about:'.

**Comment by k8hughes** [comment]
http://178.128.102.213/how-we-work/#

It is currently repeating the title from the Hero in the first para of copy.  I can't see this in the design.  Is it intended?

**Comment by edwinmp** [comment]
@k8hughes you used a `Standard Page` instead of a `General Page` ... honestly though, the only difference between those two is that one has breadcrumbs and the other doesn't.

**Comment by k8hughes** [comment]
I wanted to add this page as a child of `who we are` but I am not allow.  I think there are some issues still with parent/child relationship.

**Comment by edwinmp** [comment]
> I wanted to add this page as a child of `who we are` but I am not allow. I think there are some issues still with parent/child relationship.

@k8hughes what page did you want to build under `who we are` that required a general page?

**Comment by k8hughes** [comment]
![Screenshot 2019-09-25 at 12 09 56](https://user-images.githubusercontent.com/36768381/65595803-6cc8ea00-df8d-11e9-9a34-2c659f50bce1.png)


Under who we are we will need to have team pages, strategy and finances

**Comment by alice-mcandrew-development-initatives** [comment]
@k8hughes I think this seems fine but I will confirm once we've got more content in place
