### ISSUE TITLE
Ask questions before data download

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#191]
Want to ask people: 

- Who they are
- Where they work / what they do
- What they will do with this dataset

Set a cookie to not ask again. But they may have different uses for different downloads. So could set cookie expiry for 2 weeks? 

Want to set up proper Analytics here

http://development-initiatives.surge.sh/page-templates/21-2-dataset-single

---

Sketch: https://marvelapp.com/3j51290/screen/61274030

--- 

Code for Google Form integration: 

```
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdlVbapY33-yT13my5Fr5ZRuJ6ySR7-ohcCmFtwAOByvdaNYQ/viewform?embedded=true" width="640" height="698" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>
```

Data Download Survey - Google Forms: https://docs.google.com/forms/d/1U09rnFJolZNZg80LCRmq4vNzFoQW6sQpbWyMvnDEq3c/edit

Data Download Survey (Responses) - Google Sheets: https://docs.google.com/spreadsheets/d/1MWFmEKT-77K1x25J5evo0lbUkzuAqYQat9OYIcQ8vQk/edit#gid=207705057

--- 

Potential for modal behaviour: https://github.com/kylefox/jquery-modal

**Comment by benjamincoleman** [comment]
```
.modal {
		position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0,0,0,.3);
    z-index: 8;
    cursor: pointer;
}
```

**Comment by benjamincoleman** [comment]
@BenDarby You asked

> +ben@bteam.co What element in this template is the trigger for the modal opening?

It's the two links to dataset downloads: 

- Filename - XLS 1.8mb
- Filename - CSV 1.8mb

**Comment by BenDarby** [comment]
@benjamincoleman it might be better to do js then I can finish off the styling as I think the JS is responsible for some of the styles showing eg, positioning. 
As when I force show the modal with css it doesn't display the same as their example.

**Comment by benjamincoleman** [comment]
Ok cool

**Comment by benjamincoleman** [comment]
@BenDarby so this is looking good, but we could do with some better CSS on the responsive side of things. 

- the google forms element has a defined width and height in HTML, which we should remove.
- on smaller screens it should probably take the whole window, and have `overflow-y:scroll` on it to make sure people can see the whole form

**Comment by benjamincoleman** [comment]
https://basecamp.com/1931476/projects/15759410/messages/87280708

**Comment by BenDarby** [comment]
@benjamincoleman I can remove the width and height for the form embed, but if this an element that will be content managed wouldn't they need to remember to do the same?
