### ISSUE TITLE
Content shifts out of view when expanding metadata section

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#199]
http://development-initiatives.surge.sh/page-templates/21-2-dataset-single

Safari/iPhone X

#### Content shifts out of view when expanding metadata section

As the accordion-style interface closes other opened sections when expanding a new section, the heading and content jump up the page and out of view.

Would suggest leaving expanded sections open to mitigate this, or use JS to make sure that the page is scrolled to the opened section in the viewport.

**Comment by BenDarby** [comment]
@benjamincoleman the showing and hiding of content for this is controlled by the JS library, I tried to look at the JS to figure out how to get to work as Russell has suggested but it's out of my expertise.
