### ISSUE TITLE
T16 Work for us

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#20]
Sketch: https://marvelapp.com/3j51290/screen/57853949

Design: http://development-initiatives.surge.sh/page-templates/16-work-for-us

Functional Specification: 

Has a variation on the standard here where we have: 
- title
- subtitle
- button linking to current vacancies, which is a list at the bottom of this page so it links to the ID `vacancies` - http://development-initiatives.surge.sh/page-templates/16-work-for-us#vacancies

Beneath the hero we have some standard content editor content. 

Then, the benefits section. This has two columns. 

The column on the left has a list of benefits, for each benefit there is: 

- title
- image
- content

The column on the right has a number of logos, which are able to be uploaded. 

**Our values**

Has a title, introduction content and then a list of values. For each value we have: 
- title
- description

**Team stories**

Has a title, intro content and then a list of team stories. 

Links to all team stories pages, which sit under this page in the IA: 

![Screen Shot 2019-07-26 at 13 32 10](https://user-images.githubusercontent.com/64877/61951733-ccb10d80-afa9-11e9-9821-ed277d6f76dc.png)

**Latest vacancies**

Has a title, intro content and then a list of all available vacancies. 

For each vacancy we show: 
- role type (e.g. full time / permanent) 
- page title
- location
- salary information
- closing date

**Comment by benjamincoleman** [comment]
@BenDarby we need the logos on the right to not have the whitespace in the image. As a rule assume clients have no image editing capabilities on things like this.

**Comment by k8hughes** [comment]
http://178.128.102.213/work-us/ 

There seem to be a few visual bugs on this page.  
`Benefits of working at DI` section:
* The grey boxes bleed into one large box, instead of being distinct.
* The data validation forces you to have a logo, but int he designs the logos are not displayed for every benifit, this needs to be optional.

![Screenshot 2019-09-25 at 09 59 41](https://user-images.githubusercontent.com/36768381/65585946-37b39c00-df7b-11e9-8834-a592977bbfd7.png)

**Comment by benjamincoleman** [comment]
@k8hughes the benefits are unrelated to the logos - the logos should be an independent stack on the right hand side.

**Comment by edwinmp** [comment]
@k8hughes fixed the benefits issues, and others I discovered here. Please retest.

**Comment by k8hughes** [comment]
LGTM

**Comment by alice-mcandrew-development-initatives** [comment]
The benefits section looks good. I'll leave this open for now though as we haven't uploaded all the content yet for this page (i.e. the child pages have not been made).
