### ISSUE TITLE
Publications colour variations

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#201]
Need to add background colour variations for `.hero__title span` when there is no `hero--image` class as it still uses the dark red colour, rather than dark green / blue etc.

**Comment by akmiller01** [comment]
Slight riff on this. It appears we're missing ico variants for some of the colours as well. So far `poppy` and `bluebell` work. But `sunflower` and potentially others don't. Template shows them all as bluebell, regardless of page colour. 

I've worked a method into the template to substitute in the body colour: `file='ico-link-'|add:page.colour` would it be possible to add all colour variants to the assets?

![image](https://user-images.githubusercontent.com/2836840/64879055-08b83480-d623-11e9-9a9b-bf52e3f09c6a.png)

**Comment by benjamincoleman** [comment]
Hi @Ben the default for 14-1-Publication-Long-Form is blue, and there are actually several sub-elements on the page that remain blue even when `body--bluebell` is absent, or when I change the body class to `body--poppy`.

E.g. with `body--poppy` the text doesn't alternate correctly. You get some unreadable buttons:

![image](https://user-images.githubusercontent.com/64877/64976716-e84ddb80-d8a9-11e9-805e-961b35169e73.png)

Easy way to test is to go to template 14 and change the body class from `body--bluebell` to `body--poppy` Things like the share bar remain blue, despite it changing for rose, or sunflower to the appropriate colour:

![image-1](https://user-images.githubusercontent.com/64877/64976754-01568c80-d8aa-11e9-8f91-f9712497f16e.png)

**Comment by SimonMurphyDI** [comment]
@edwinmp 
Just spotted that the shortform publication hero text font display is incorrect colour (grey, rather than white) - this is true for all colour variations. 
![image](https://user-images.githubusercontent.com/22001094/69051237-acdfa280-09fb-11ea-8a8d-a91df32f5db4.png)
(FYI I'll be moving this example, the ITEP3 page into a legacy publication) - this is fine on some other shortform publications...
Cheers
Simon

**Comment by edwinmp** [comment]
@SimonMurphyDI could you please share the link to that page. I haven't been able to replicate it in other short publication pages

**Comment by SimonMurphyDI** [comment]
@edwinmp neither can I now - sorry, will keep an eye out and let you know if it occurs again
Best
Simon
