### ISSUE TITLE
Hosting the content for download in box.

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#202]
some of the data section has excel and CSV files, it would be easiest to link this to a box account so that box can serve the content.  Priority level: High

**Comment by k8hughes** [comment]
@Napho have you been working on this one already?

**Comment by akmiller01** [comment]
@k8hughes we ended up using the Box API as the connection between the website and the content, but in the end, the website required file types, file names, and file size metadata, all of which was most easily accessed by downloading the files from Box and hosting them on the website.

In the future, when this gets connected to the DDW, it may make sense to refactor it all to be links to Box or SQL, but for the moment the content is hosted on the website.
