### ISSUE TITLE
Incorporate Publication pages into lots of Related Page sections

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#203]
Incorporate Publication pages into lots of Related Page sections, Author pages, Home page.  There is already to do flag in the code where this is needed. Eg Team member pages. Priority level: high

**Comment by akmiller01** [comment]
Hmmm... @edwinmp might have hit a hard wall on this with regards to filtering on the `other_authors` or `authors` StreamFields in Blogs and Publications. Basically seems like filtering based on a StreamField is not supported and considered "hacky." https://github.com/wagtail/wagtail/issues/3735#issuecomment-396704626

**Comment by akmiller01** [comment]
Might have actually found a way: https://github.com/devinit/DIwebsite-redesign/commit/ebb67baa177869ab7069a7aba676e46a4f29b728

**Comment by akmiller01** [comment]
Okay, so StreamField content just needs to be filtered like text, instead of a JSON field. Which is a shame, but doable: https://github.com/devinit/DIwebsite-redesign/commit/7403e4bfb5a99b1c7eac8471d4867a9b1a5e3f66

![image](https://user-images.githubusercontent.com/2836840/65072235-7aafb700-d95e-11e9-9465-eb4c29fffd11.png)

**Comment by k8hughes** [comment]
@akmiller01  can you comment on the status of this issue?

**Comment by akmiller01** [comment]
Publications were incorporated into the author pages, but not elsewhere. Just added them everywhere they could be needed here: https://github.com/devinit/DIwebsite-redesign/pull/268

**Comment by k8hughes** [comment]
Does this mean we can move this issue to done? @akmiller01

**Comment by akmiller01** [comment]
Yep! Done and merged.
