### ISSUE TITLE
Plug in for checking if links are broken

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#205]
Simon has requested this feature, email with further info was circulated.

**Comment by k8hughes** [comment]
I don't think I can test this in the CMS - or should I add a broken link somewhere and see if soeone gets an alert?

**Comment by k8hughes** [comment]
![Screenshot 2019-10-11 at 10 12 02](https://user-images.githubusercontent.com/36768381/66639846-9d588700-ec0f-11e9-8aff-b34c539da6d3.png)
I get a 502 error when trying to use the link checker.
@davidebukali

**Comment by edwinmp** [comment]
@davidebukali what's the status of this?

**Comment by akmiller01** [comment]
Link checker is incorporated, but relies on `celery` service to be built into deployment process.

**Comment by akmiller01** [comment]
This is in progress. @Napho how long will it take to get celery incorporated into deployment properly?

**Comment by akmiller01** [comment]
Think this should sort us: https://github.com/devinit/DIwebsite-redesign/pull/456

**Comment by akmiller01** [comment]
As long as your Env variables are correct @Napho :P Relying on the CELERY_BROKER_URL to be formatted correctly, but I cannot see what you set it as.

**Comment by akmiller01** [comment]
@Napho can you please double-check the format of CELERY_BROKER_URL? This is the err I'm getting now:
```
Exchange.declare: (403) ACCESS_REFUSED - access to exchange 'reply.celery.pidbox' in vhost 'myvhost' refused for user 'di_website'
```
