### ISSUE TITLE
Simon’s request for something that will tell him when to check a page is up to date.

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#206]
There doesn't seem to be a plug in for this, so first step to starting the task is to have a conversation with Simon to fully understand the feature needs.  There is an email with some more detail that has been circulated but probably not enough detail.

**Comment by edwinmp** [comment]
I added a Notification section to each page (the ones that were built at the time). You can write a message, specify the emails to send it to as well as the date/time. A cronjob on the server checks every hour and sends the emails that have reached their deadline.

I guess the only missing feature I can think of is recurrence, but so far, this should do. I ran it by Simon.

![image](https://user-images.githubusercontent.com/5672438/66553794-78eba480-eb54-11e9-8085-921ed01ee8c3.png)


![image](https://user-images.githubusercontent.com/5672438/66553815-83a63980-eb54-11e9-9506-f8c468312fc7.png)

**Comment by k8hughes** [comment]
I've just set a notification, I'll check this off when I recieve the email.

**Comment by k8hughes** [comment]
http://178.128.102.213/admin/pages/1310/edit/ 
att 11am I set an email to come at 12, but no email came. @edwinmp

**Comment by k8hughes** [comment]
I got the emails in the end. LGTM.

**Comment by alice-mcandrew-development-initatives** [comment]
I tried this and didn't receive the email, not sure why if it worked for Kate...

**Comment by alice-mcandrew-development-initatives** [comment]
Simon is happy with that ^

**Comment by edwinmp** [comment]
@Napho has the script and cronjob for this been setup on `pre-production`?

**Comment by alice-mcandrew-development-initatives** [comment]
I just got an email notification...
![image](https://user-images.githubusercontent.com/55877063/69557279-3c59f800-0f9e-11ea-8138-baa20b74d7ef.png)
....which I was meant to get a while ago. This is what was set up in the cms:
![image](https://user-images.githubusercontent.com/55877063/69557325-4ed43180-0f9e-11ea-831c-9a6500d81720.png)

Is there a reason for this?
@k8hughes  I can set up another test?

**Comment by k8hughes** [comment]
Yes, please set up another test and see what happens

**Comment by alice-mcandrew-development-initatives** [comment]
Doesn't seem to be working

**Comment by akmiller01** [comment]
First things first, the cronjob file wasn't even executable!
```
root@ubuntu-s-1vcpu-1gb-lon1-01:~# /home/di_website/send_page_notifications.sh
-bash: /home/di_website/send_page_notifications.sh: Permission denied
root@ubuntu-s-1vcpu-1gb-lon1-01:~# chmod +x /home/di_website/send_page_notifications.sh
root@ubuntu-s-1vcpu-1gb-lon1-01:~# /home/di_website/send_page_notifications.sh
```

That seems to have fixed it. Let me know if you get your email @alice-mcandrew-development-initatives

**Comment by alice-mcandrew-development-initatives** [comment]
I received a test email last night at the wrong time. And, I set one up a moment ago which hasn't arrived yet.

**Comment by akmiller01** [comment]
> I received a test email last night at the wrong time. And, I set one up a moment ago which hasn't arrived yet.

Not at the wrong time. It arrived exactly when I fixed it! Now if you haven't received your second test, we can conclude there's something going wrong with cron rather than the script that cron is trying to run.

**Comment by akmiller01** [comment]
Documenting potential issue here. Changed the shell script so we're now referencing the absolute path of docker-compose https://github.com/docker/compose/issues/2293

**Comment by alice-mcandrew-development-initatives** [comment]
I received a test email at the time I set :) Yay! Thanks @akmiller01

**Comment by alice-mcandrew-development-initatives** [comment]
Not sure whether to close because of  your comment above ^ @akmiller01

**Comment by akmiller01** [comment]
Yep, just documenting what the fix was in case we encounter it again and wonder how we solved it :P Feel free to close if this feature is now working for you.
