### ISSUE TITLE
T12a News single

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#21]
Sketch: https://marvelapp.com/3j51290/screen/57215884

Design: http://development-initiatives.surge.sh/page-templates/12a-news-single

Functional spec: 

Hero has the post title, post date and the label 'news'. 

Then there's richtext content. 

Then at the bottom we have related content - the approach to take with this is to allow admins to select up to 3 other blog posts, events, or publications to link to. If the admin selects none, or less than three, then fetch another blog post to add in here to make up the numbers to three. We'll have code in GNR to help with this is you want to get a head start.

**Comment by edwinmp** [comment]
Hi @benjamincoleman ... you still have this in your design project, but had authorised and moved the news listing to the `Content Management` project. Should I move this one in too (if done)?

**Comment by benjamincoleman** [comment]
@edwinmp I've been keeping cards in both projects, but we can make them only appear in one if that makes more sense project management wise.

**Comment by edwinmp** [comment]
I don't mind them appearing in both. It's just that this one was still only in your project, so I assumed you still have some work to do on it.

**Comment by benjamincoleman** [comment]
@edwinmp sorry about the late addition to this template - we need something added as a control or taxonomy to allow news posts to appear on the #32 page: 

> We then have a list of press releases, which are actually selected news posts. The news posts themselves would need a control to say "this post is a press release" and then allow it to be automatically shown in this template.

**Comment by k8hughes** [comment]
There is some sort of error:  http://178.128.102.213/news/using-oda-blending-good-use-scarce-concessional-resources/

**Comment by edwinmp** [comment]
Should be fixed in PR #115 ... @k8hughes  will let you know when merged.

**Comment by edwinmp** [comment]
@k8hughes the fix has been deployed.

**Comment by k8hughes** [comment]
Excellent now I can see the page and it all looks good.
