### ISSUE TITLE
Display publication author title in singular tense when only one author

### ISSUE THREAD

**Issue by edwinmp** [devinit/DIwebsite-redesign#235]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the bug**
Can we automatically change Authors to Author if just one person is listed?

**To Reproduce**
Steps to reproduce the behaviour:
![Bug on Pubs pages](https://user-images.githubusercontent.com/5672438/65767648-1e574f00-e137-11e9-97ca-64e0c4a2112a.PNG)

**Comment by edwinmp** [comment]
@akmiller01 any chance this is already fixed, or it's an FF thing?

**Comment by akmiller01** [comment]
FF thing @edwinmp . The CSS turns the author UL into comma separated box.

**Comment by edwinmp** [comment]
@benjamincoleman

**Comment by benjamincoleman** [comment]
@BenDarby can we remove the comma from after every author please? 

```
.m-authors__list li:after {
    content: ",";
}
```

**Comment by BenDarby** [comment]
@benjamincoleman updated markup and css to be like this now
```
<div class="m-authors">
    <h3 class="m-authors__title">Authors</h3>
    <p class="m-authors__copy"><a href="#">Emily Underhill</a>, Joe Bloggs, <a href="#">Amanda Hughes Reilley</a></p>
</div>
```

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/273

**Comment by alice-mcandrew-development-initatives** [comment]
Looks great @akmiller01
