### ISSUE TITLE
Add download button to the hero for LegacyPublicationPage

### ISSUE THREAD

**Issue by edwinmp** [devinit/DIwebsite-redesign#237]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the issue**
The `Publication downloads` shown in the screenshot below is missing for legacy publications

**Screenshots/GIF**
![image](https://user-images.githubusercontent.com/5672438/65875170-83a57d00-e38f-11e9-81ab-b3dc0c935a07.png)

**Comment by alice-mcandrew-development-initatives** [comment]
@edwinmp I think this seems also to be applicable to new publication pages (as it looks like you can only link to pages as the call to action)
