### ISSUE TITLE
Captions for all images

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#24]
So, where we have:

* Hero image
* Main content image

We'll need an image credit. I've included this in the sketches now, and it would be a link of text which can have a link.
To do,Visual design,move-to-github

**Comment by alice-mcandrew-development-initatives** [comment]
@k8hughes Were there ever any plans for a caption line (beyond photo credit) for images? E.g. here (http://159.65.56.142/what-we-do/our-focus-areas/improving-understanding-humanitarian-assistance/) there is no option to add a caption line, so you have to use paragraph block, which looks clunky. Would it be difficult to add something similar to what we have for infographics (where you can add a caption for notes/sources below the image)?

**Comment by k8hughes** [comment]
@benjamincoleman this is a question for you not me I think!!!

**Comment by BenDarby** [comment]
@k8hughes @alice-mcandrew-development-initatives we have a styles in place for captions on images, you can see examples in the publication single template on the pattern library: http://development-initiatives.surge.sh/page-templates/14-1-publication-long-form

**Comment by benjamincoleman** [comment]
@k8hughes @alice-mcandrew-development-initatives in this case the streamfield would need updating to change the markup to use the HTML `<figure>` element that supports `<figcaption`. 

Current HTML is:

```
<div class="media-figure">
	<img alt="inline image" height="500" src="/media/images/Angus-Urquhart-ECOSOC-June-2019.2e16d0ba.fill-800x500.jpg" width="800">
</div>
```

The FigCaption HTML is: 

```
<figure class="media-figure">
	<img alt="inline image" height="500" src="/media/images/Angus-Urquhart-ECOSOC-June-2019.2e16d0ba.fill-800x500.jpg" width="800">
	<figcaption class="media-figure__caption">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante.</figcaption>
</figure>
```

**Comment by k8hughes** [comment]
Ok so this is one for the developers...

**Comment by akmiller01** [comment]
Image captions added here: https://github.com/devinit/DIwebsite-redesign/pull/353

**Comment by riahasler-DI** [comment]
@benjamincoleman or @edwinmp we're still having some issues with the figure captions - the captions are sitting on the image rather than starting below, which is what I expected. On this page: http://159.65.56.142/what-we-do/our-focus-areas/strengthening-knowledge-humanitarian-assistance/ the image caption takes up too much space and doesn't look right. 

Sorry for tagging both of you - I'm not too sure who was best to ask

**Comment by benjamincoleman** [comment]
Hi @riahasler-DI. 

The design is as intended there, although it looks like it needs some spacing out between the image/caption and the blockquote underneath. 

@BenDarby can we add some spacing to the top of the blockquote to prevent this please?

**Comment by riahasler-DI** [comment]
Hi @BenDarby were you able to add some spacing to blockquote?

**Comment by BenDarby** [comment]
@riahasler-DI I've added some more spacing to blockquote

**Comment by k8hughes** [comment]
@riahasler-DI please can you check the changes and close this issue if you are happy or add a comment if the problems are still not fixed.
