### ISSUE TITLE
Change dimensions of section marker

### ISSUE THREAD

**Issue by AnnaHope** [devinit/DIwebsite-redesign#243]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
The coloured block that acts as a marker on the left hand side for every new section is much longer and thinner than the design.
![image](https://user-images.githubusercontent.com/16958942/66132579-2f97d400-e5ed-11e9-902e-d99572bce60c.png)

**Expected Behaviour**
![image](https://user-images.githubusercontent.com/16958942/66132616-3d4d5980-e5ed-11e9-9d95-ac9fa12ae682.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] microsoft
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] unsure!

**Comment by akmiller01** [comment]
@AnnaHope those red bars actually grow and shrink with the width of your browser window. This is a CSS design choice from @benjamincoleman

**Comment by AnnaHope** [comment]
@akmiller01 ah ok, I guess these are the design elements that you don't spot so easily when reviewing templates! Leave as it then I think, even though I prefer it being a bit less intrusive, it isn't a biggy.
