### ISSUE TITLE
Increase font size for section headers to be in line with template design

### ISSUE THREAD

**Issue by AnnaHope** [devinit/DIwebsite-redesign#244]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x ] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
The font size of section headers appears a few sizes larger in the template design to the previews of publications on the new site. This makes it hard to tell it is a section heading as it should stand out more against text below.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
![image](https://user-images.githubusercontent.com/16958942/66132930-c2387300-e5ed-11e9-84ad-9c253adf8469.png)

**Expected Behaviour**
A clear and concise description of what you expected to happen
![image](https://user-images.githubusercontent.com/16958942/66132967-ce243500-e5ed-11e9-9355-15d8bf218078.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] microsoft
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] unsure

**Comment by akmiller01** [comment]
The section heading implementation matches the pattern library, but the paragraph below had a few extra classes that were causing the larger font. Fixed here: https://github.com/devinit/DIwebsite-redesign/pull/238/commits/fa9b7073b0cd5bc7679f62bb10a30a83857cf317

**Comment by AnnaHope** [comment]
Brill, thank you. So NFA? Or is the way we are inputting into the CMS a problem?

**Comment by akmiller01** [comment]
This should match the template once deployed. We can figure out after that point whether we need more changes.
