### ISSUE TITLE
Add option for a subtitle on all figures

### ISSUE THREAD

**Issue by AnnaHope** [devinit/DIwebsite-redesign#245]
**Is your feature request related to a problem? Please describe.**
With the GHA report there are both messaging and descriptive titles, yet the CMS and design only allow for one title. 

**Describe the solution you'd like**
We would like a subtitle field to be made available when adding figures. This should display as the same font size but no bold.

**Describe alternatives you've considered**
Putting descriptive titles within jpegs of charts is the other option. We may still do this for future publications, but we would need to go back and amend every single chart we have for previous reports we want in this style because none of them contain titles. This would entail a big workload. It also means the words can't be detected for SEO.

**Additional context**
![image](https://user-images.githubusercontent.com/16958942/66133762-227be480-e5ef-11e9-8b17-66c6e33d35f8.png)

-->

**Comment by akmiller01** [comment]
Is this on `CaptionedImage` or `Infographic` models @AnnaHope ?

**Comment by AnnaHope** [comment]
Is it easy enough to have for both? I think we are starting to move DI in the direction of having more messaging that helps readers understand the meaning behind what they are seeing, but always having the more objective description to ensure people get that core info too.

**Comment by akmiller01** [comment]
Done, but will require some testing: https://github.com/devinit/DIwebsite-redesign/pull/238/commits/e8c86d6f012b4c2add967752f4e6bcc8c4535730

**Comment by k8hughes** [comment]
I have tested this in an abstract way but I think it will need actual use by the comms team for us to know if this is correct.

**Comment by alice-mcandrew-development-initatives** [comment]
http://159.65.56.142/publication/global-humanitarian-assistance-report-2019/chapter-1-people-crisis-and-assistance/
![Infographic](https://user-images.githubusercontent.com/55877063/67579746-fc081f80-f73c-11e9-944c-f0c51e6f59ca.JPG)

@akmiller01 
Almost there
The descriptive text needs to be (left) aligned with the infographic heading
Also, are we able to increase the size and change the weight of the descriptive text? (I just want to know feasibility for this - I'll see if Anna thinks it'd be an improvement) 

@AnnaHope 
I think the descriptive heading for infographics should be larger than the paragraph body - do you agree? Perhaps it should also be bold (although I'm less sure about this)?

**Comment by akmiller01** [comment]
@BenDarby I think we may need help with styling this new text.

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives did you get confirmation on the change to font-size and font-weight for the descriptive text?

**Comment by alice-mcandrew-development-initatives** [comment]
@edwinmp, sorry for the delay on getting back on this! I've talked to Anna.

Can we have the messaging title (e.g. 'Figure 1.1: Countries...') not in bold?
And please can you check the run-on for the descriptive title (e.g. 'Proportion of...'), as it looks slightly odd at the moment. Apart from that, we'll leave the descriptive title as it is.

![Capture](https://user-images.githubusercontent.com/55877063/68582975-f7997180-0473-11ea-92fd-159c1a5abe71.JPG)


Thank you!

**Comment by k8hughes** [comment]
@BenDarby if the request is about having something not in bold then I think it is for you ^^^

**Comment by alice-mcandrew-development-initatives** [comment]
@k8hughes It's not bold in the pattern library

**Comment by alice-mcandrew-development-initatives** [comment]
Also, the links to the different sections don't seem to be working in the menu bar at the bottom. 
E.g. if you click 1.3 you get the top of the page (1.1),

**Comment by edwinmp** [comment]
> And please can you check the run-on for the descriptive title (e.g. 'Proportion of...'), as it looks slightly odd at the moment.

@alice-mcandrew-development-initatives just to clarify, you'd like the descriptive title to not wrap too early?

**Comment by alice-mcandrew-development-initatives** [comment]
@edwinmp, yes exactly, thank you

**Comment by k8hughes** [comment]
@alice-mcandrew-development-initatives can you check this is correct and close the issue if you are happy?
