### ISSUE TITLE
Make 'case study' label within publications editable, but compulsory

### ISSUE THREAD

**Issue by AnnaHope** [devinit/DIwebsite-redesign#246]
**Is your feature request related to a problem? Please describe.**
We have boxes to highlight content, but currently they are called case studies and this can't be amended. In the GHA report we use boxes to highlight issues etc, not just to host case studies. 

**Describe the solution you'd like**
By having the 'case study' label editable in the CMS, we can call it whatever we need it to be so it works for all our content. We would want it to be a compulsory field to ensure whatever is in a box necessitates a clear label as to what it is.

**Describe alternatives you've considered**
The only option would be to create jpegs of content to sit on the page to make them feel like box-outs, without them actually being so. This isn't ideal though from an accessibility or aesthetic perspective.

**Additional context**
![image](https://user-images.githubusercontent.com/16958942/66134270-f876f200-e5ef-11e9-9be5-e0ae4b8ad876.png)

**Comment by akmiller01** [comment]
Done: https://github.com/devinit/DIwebsite-redesign/pull/238/commits/5e3efe96d16fa99b6020bb9b1781efbfd7a2484a

**Comment by AnnaHope** [comment]
amazing!
