### ISSUE TITLE
No child pages in the correct templates under 'who we are' except our story

### ISSUE THREAD

**Issue by AnnaHope** [devinit/DIwebsite-redesign#248]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x ] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
We can't add any child pages because the templates needed for them are not listed.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to the who we are page in the CMS
2. Click on child page
3. see that the only option is 'our story' when we need our team (already migrated and currently in the wrong place), then strategy, then finances.

**Expected Behaviour**
All the child page templates we need for the who we are section to be available

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] microsoft
 - Browser [e.g. chrome, safari] chrome

**Environment/Server:**

- [ ] Staging

**Comment by edwinmp** [comment]
The current state of the staging contains both a fix for this and a regression i.e under `Who We Are`, a user can create a `General Page` but can no longer create a `Our Story Page`.

**Comment by k8hughes** [comment]
Was this fixed under issue #255 already?
@edwinmp

**Comment by edwinmp** [comment]
> Was this fixed under issue #255 already?
> @edwinmp

Nope ... the full fix for this is in PR #260
