### ISSUE TITLE
Our team is in the wrong place in the hierarchy

### ISSUE THREAD

**Issue by AnnaHope** [devinit/DIwebsite-redesign#249]
Our team is a child page of 'who we are'. it is currently in the CMS as a parent page and displaying in the main banner on the homepage when you view it as live. It needs to become a child page of Who We Are.

**Comment by edwinmp** [comment]
@Napho pulling in the dev changes to the new server should fix this. Let me know when its done so I can confirm.

**Comment by edwinmp** [comment]
@AnnaHope this has been deployed to staging. Please test.

**Comment by alice-mcandrew-development-initatives** [comment]
This is still where it was before (i.e. where it should _not_ be):
![Capture3](https://user-images.githubusercontent.com/55877063/66837156-70cba480-ef5a-11e9-9d67-1032951176c1.JPG)

I've added a child page here, which is where it should be:
![Capture4](https://user-images.githubusercontent.com/55877063/66837286-a96b7e00-ef5a-11e9-8062-cd1380eaae39.JPG)
^ Please delete this draft and start from scratch if needed

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives that's not necessarily a bug. It'd be a bug if it's possible to create another `Our Team` page in the same place. For this, you can simply move it to right place in the hierarchy, but I think we've fixed it so that you can't create anymore `Our Team` pages under the `Home Page`.

**Comment by alice-mcandrew-development-initatives** [comment]
How do we move it? It should be under Who we are

**Comment by edwinmp** [comment]
More -> Move

![image](https://user-images.githubusercontent.com/5672438/66838391-3f100900-ef6d-11e9-93c4-234ac0306ffc.png)

**Comment by alice-mcandrew-development-initatives** [comment]
Amazing! Problem solved.
(Do you want me to close when happy an issue has been resolved, such as in this instance?)

**Comment by edwinmp** [comment]
Yup ... close away :)
