### ISSUE TITLE
Images in banner blocks are not displaying correctly

### ISSUE THREAD

**Issue by AnnaHope** [devinit/DIwebsite-redesign#250]
The image that goes with banner blocks should be quite square and fill most of the left side of the block, however they are being compressed and made more horizontal. This does not improve even when I shrink my browser window down to try and force the image to expand more so I think is a problem in the back-end.

How it is:

![image](https://user-images.githubusercontent.com/16958942/66403672-e249a700-e9de-11e9-8657-6f193dff2b08.png)

How it should be:
![image](https://user-images.githubusercontent.com/16958942/66403714-f55c7700-e9de-11e9-942d-55edc526d530.png)

**Comment by edwinmp** [comment]
@akmiller01 did PR #252 fix this issue, or it was about something else?

**Comment by akmiller01** [comment]
Yes it did. Are we waiting for a comms review before closing issues?

**Comment by edwinmp** [comment]
Yes @akmiller01 ... @Napho is working in a separate CI process to auto-update the comms staging for issues we've signed off on `develop`.

**Comment by edwinmp** [comment]
@AnnaHope a fix for this has been deployed. Please test.

**Comment by alice-mcandrew-development-initatives** [comment]
This still doesn't look right.
http://159.65.56.142/who-we-are/ 

![Capture](https://user-images.githubusercontent.com/55877063/66836730-c6ec1800-ef59-11e9-83ce-9434626f76eb.JPG)

**Comment by alice-mcandrew-development-initatives** [comment]
Also, the template makes it look like there should be an image credit/URL box for this:
http://development-initiatives.surge.sh/page-templates/03-who-we-are

![Capture2](https://user-images.githubusercontent.com/55877063/66836881-0b77b380-ef5a-11e9-9bc6-ea07b0c0ab55.JPG)

Do you want this flagged as a separate issue?

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives ah, nope ... lets just keep this issue open until it's fixed.

**Comment by akmiller01** [comment]
@alice-mcandrew-development-initatives could you try deleting the image and re-adding it? My fix should have worked, but it's still using the fill version of the image instead of the width one:

![image](https://user-images.githubusercontent.com/2836840/66841079-238a0b80-ef37-11e9-9419-41951e073eb7.png)

**Comment by alice-mcandrew-development-initatives** [comment]
@akmiller01 Do you mean delete from the images library? I tried to replace on page and it made no difference.

**Comment by akmiller01** [comment]
Not sure why the src would be right, but the srcset would be behind. Any idea @edwinmp ?

**Comment by akmiller01** [comment]
> @akmiller01 Do you mean delete from the images library? I tried to replace on page and it made no difference.

No, just replacing it on the page should be enough. I think we may also need to edit the `global.banner_srcs` which seems to be causing this issue.

**Comment by akmiller01** [comment]
Fix here. Going to test locally right now https://github.com/devinit/DIwebsite-redesign/pull/269

**Comment by akmiller01** [comment]
![image](https://user-images.githubusercontent.com/2836840/66842448-487f7e00-ef39-11e9-9f0c-9a1e70441970.png)

Here's how it appears with an edited srcset.

**Comment by akmiller01** [comment]
Only issue is that the image can be longer than the banner.

**Comment by alice-mcandrew-development-initatives** [comment]
According to template it shouldn't overlap on the bottom:
![Capture2](https://user-images.githubusercontent.com/55877063/66842588-711c6d80-ef63-11e9-95c0-bb5323ca74fb.JPG)
This means that it mirrors the red box on the opposite corner.

Is that what you mean by the above comment?

**Comment by akmiller01** [comment]
We may want to go back to Fffunction on this point. We've reached a styling impasse.

Either the image needs to be a set height, at which point it can behave predictably with regards to where the image starts and stops. Or it can have a variable height, at which point we can start it or stop it at a predictable space, but we cannot control the other end.

**Comment by edwinmp** [comment]
I don't see how we're going to overcome this with css ... We could agree to only use images of a certain dimension here, but then the text also affects the size of the banner and could get the image out of alignment.

**Comment by k8hughes** [comment]
@benjamincoleman what do you advise?

**Comment by benjamincoleman** [comment]
The image size is causing the problem - its dimensions should be 512px by 512px. 

In this case there's no need for using SRCSET, as the image size doesn't vary all that much across screen sizes.

**Comment by alice-mcandrew-development-initatives** [comment]
Sorry, I'm am not sure whether I am 100% following this (or whether I need to be exactly).
Is the implication that we can only upload images with dimensions 512px by 512px for banner blocks? This would mean we'd have to crop images before adding them to the image library? If so, was this planned/discussed with Anna?

**Comment by k8hughes** [comment]
@benjamincoleman I don't think that we have restricted images size anywhere else on the site.  Is there a work around here?

**Comment by benjamincoleman** [comment]
@alice-mcandrew-development-initatives @k8hughes 

The image should be cropped by Wagtail. You should be able to put an image which has dimensions that are larger than 512px in both width and height, select a focus area, and then the CMS will crop it for you.

**Comment by k8hughes** [comment]
@akmiller01 @edwinmp  does this mean the issue is in the code on our en then and the cropping is not happening?

**Comment by akmiller01** [comment]
@k8hughes we can crop the image however. At which point CMS users will need to set a focal point to avoid cropping faces (like the image that spawned this issue). But if there isn't much text content in the banner, the image will still overflow the banner as shown above.

**Comment by k8hughes** [comment]
@alice-mcandrew-development-initatives just wanted to check that you have seen this.  As a CMA user you need to crop the images in Wagtail.

**Comment by alice-mcandrew-development-initatives** [comment]
I added a focus area (as I presumed that is what you meant by 'crop') but it still looks odd:
![Pin banner](https://user-images.githubusercontent.com/55877063/67388876-6aa87a00-f591-11e9-8208-3906f813735b.JPG)

**Comment by akmiller01** [comment]
@BenDarby I think this may be a pattern library issue. The image width is capped at 400 px, and the height is just slightly longer than that. There doesn't seem to be any mechanism by which the height of the banner is elongated to match the height of the image.

**Comment by k8hughes** [comment]
@benjamincoleman is this a problem with the pattern library?

**Comment by benjamincoleman** [comment]
@BenDarby can you have a look at this please? Not quite sure what's causing the difference between live - http://159.65.56.142/who-we-are/ and the pattern library template - http://development-initiatives.surge.sh/page-templates/03-who-we-are

**Comment by BenDarby** [comment]
@benjamincoleman @akmiller01 The markup on the live site is slightly wrong. There is an extra `<div class="media-wrapper">` around the `img` element. This doesn't need to be used, the `<div class="banner__media">` handles the style for the `img` so the full markup from the pattern library is:
```
<div class="banner">
                <div class="l-banner">
                    <div class="l-banner__aside">
                        <div class="banner__media">
                            <img src="/assets/img/pin.jpg" alt="alt tag">
                            <span class="banner__credit">Image by <a href="#">Credit name</a></span>
                        </div>
                    </div>
                    <div class="l-banner__main">
                        <p class="banner__excerpt">"The driving force behind our work is a passion for ending poverty. We want every penny intended to end poverty and build resilience to be directed and spent effectively so that every person has the opportunity to make meaningful choices that can improve their life in a lasting way. We know that finding a sustainable solution is complicated. So we are committed to uncovering evidence that will help all actors, from local to international, find new solutions that will lift vulnerable people permanently out of poverty and promote inclusion."</p>
                        <span class="banner__meta">- Harpinder Collacott - Executive Director</span>
                        <a href="#" class="button button--reverse">Meet the team</a>
                    </div>
                </div>
            </div>
```

**Comment by edwinmp** [comment]
@BenDarby after reviewing the existing usages for banners, I've noticed that the `media-wrapper` div is mostly added for embedded videos, but not for images. Is that how it should be? Would hate to remove it and then have embeds break.

**Comment by k8hughes** [comment]
This is working now.

**Comment by alice-mcandrew-development-initatives** [comment]
There doesn't appear to be the option to add a photo credit to images in banner blocks:
![Banner block image credit](https://user-images.githubusercontent.com/55877063/69045751-65ebb000-09ef-11ea-8266-19ea5f6b6b2b.JPG)

This is from the cms for this page: http://159.65.56.142/how-we-work/partnerships-and-collaboration/

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives that's done via the `Meta` field on the banner block ...

![image](https://user-images.githubusercontent.com/5672438/69046122-4eb9bc00-0a09-11ea-985b-0e32f2a0cdb3.png)

**Comment by edwinmp** [comment]
Oh, or is that only for the text ... hmm... let me verify.

**Comment by edwinmp** [comment]
Yup, only for the text ... alright, will add a credit field for the image... thanks for logging :) @alice-mcandrew-development-initatives

**Comment by alice-mcandrew-development-initatives** [comment]
Great, thanks @edwinmp

**Comment by k8hughes** [comment]
I can see this in the CMS now for the banner block of a general page

**Comment by alice-mcandrew-development-initatives** [comment]
@edwinmp I think we need an additional URL line so that the image credit text forms a hyperlink (as elsewhere)
![Capture](https://user-images.githubusercontent.com/55877063/69161271-cf002000-0ae2-11ea-8397-0b2ba4f3b091.JPG)
At the moment I have nowhere to put the URL for the image credit ^

**Comment by riahasler-DI** [comment]
@k8hughes Hi Kate, I think this issue still exists! I can't see where we can add the URL for the image credit
![image](https://user-images.githubusercontent.com/56585598/69530920-df911a00-0f6a-11ea-825f-0922ca136655.png)

**Comment by edwinmp** [comment]
Ah, sorry @riahasler-DI ... I built it incorrectly... Going to follow the style of the hero, if that's fine... it has a provision for credit text and a URL.

**Comment by k8hughes** [comment]
LGTM

**Comment by k8hughes** [comment]
@riahasler-DI back to you for checking.

**Comment by edwinmp** [comment]
Will move it once it's deployed to staging ...

**Comment by k8hughes** [comment]
@riahasler-DI back to you for checking...

**Comment by riahasler-DI** [comment]
@k8hughes think it all looks good! all the issues above have been resolved so am happy to close the issue!
