### ISSUE TITLE
do not appear to be able to add the location map or office addresses in 'who we are'

### ISSUE THREAD

**Issue by AnnaHope** [devinit/DIwebsite-redesign#251]
The design for the who we are parent page has a section under 'our values' called 'our offices' and contains what appears to be an interactive map, and then blocks underneath where our addresses should be input. There doesn't appear to be any way to add this via the CMS and the page just ends at 'our values'. Sorry if we are just not seeing it in there, but it appears to be missing.

what should be displaying/possible to add
![image](https://user-images.githubusercontent.com/16958942/66404238-f80b9c00-e9df-11e9-9612-b1f1eb6ff720.png)

what we see in the CMS (no option to add any new sections below our values) it just jumps straight to the 'related pages' to select. 

![image](https://user-images.githubusercontent.com/16958942/66404310-1a051e80-e9e0-11e9-990e-cd6beb274e2d.png)

**Comment by akmiller01** [comment]
Office locations are added here: http://159.65.56.142/admin/snippets/vacancies/officelocation/

**Comment by AnnaHope** [comment]
@akmiller01 thank you that's really helpful - how do i tell the CMS to make that snippet appear on the who we are page? i can't see the option to 'add snippet' there?

**Comment by akmiller01** [comment]
The connection between the two pages is automatic. I'm not sure if there's a good way to express that in the page itself, but every office location snippet added will automatically appear on the map. It's unfortunately one of the quirks of Wagtail when you want an element to appear on multiple pages. They will automatically populate the Contact Us and What We do pages as well.

**Comment by edwinmp** [comment]
Hi @AnnaHope ... did you manage to get the locations showing?

**Comment by alice-mcandrew-development-initatives** [comment]
@akmiller01 and @edwinmp do the offices appear in the order they do on the page because the snippets were created in this order? (this would be useful to know going forward)

**Comment by akmiller01** [comment]
Yes they appear in the order in which the snippets are added. Wagtail does not support reordering snippets at the moment, but you can always remove some and re-add them in the order you want them to appear.
