### ISSUE TITLE
Document download link for page body on 'Work for the us' page

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#253]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
On the 'Work for the us' page, there doesn't seem to be the option to add a document download link to the page body section

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to http://159.65.56.142/admin/pages/605/edit/
2. Go to 'PAGE BODY'
3. Add 'Paragraph block'

**Expected Behaviour**
There should be a button in the toolbar for the paragraph block to add a 'Document'

**Comment by akmiller01** [comment]
I think this is caused because it's expecting `document-link` here instead of `document` pushed here https://github.com/devinit/DIwebsite-redesign/pull/257/commits/bb158a9828ca641a781f94cd7f728c9dc8f1320c

**Comment by k8hughes** [comment]
http://178.128.102.213/work-us/data-scientist/ 

LGTM

**Comment by alice-mcandrew-development-initatives** [comment]
I'm now able to add a document link in the page body. Thank you :)
