### ISSUE TITLE
Forced to add three logos along listed benefits on 'Work for us' page

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#254]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
It's compulsory to add a logo alongside each listed 'Benefits' on the 'Work for us' page (but there are only two logos to add). I can't save/publish the page without uploading them. For now I have added the second one twice. 

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to http://159.65.56.142/admin/pages/605/edit/
2. Go to 'BENEFITS'
2. Go to 'Logos: *'

**Expected Behaviour**
It should not be compulsory to add a logo alongside each of the Benefits.

**Screenshots/GIF**
![Benefits logos](https://user-images.githubusercontent.com/55877063/66494028-e9d88100-eaae-11e9-96e4-342c753abf2e.JPG)

**Comment by akmiller01** [comment]
Okay, it's a required field in the code. I've made it non-required here: https://github.com/devinit/DIwebsite-redesign/pull/257

**Comment by alice-mcandrew-development-initatives** [comment]
All good now! Thank you!
