### ISSUE TITLE
No option to select type of page for 'Work for us' child pages

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#255]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
When you add a new child page to 'Work for us' you automatically get a 'Vacancy Index Page'

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to http://159.65.56.142/admin/pages/605/
2. Click on 'ADD CHILD PAGE'

**Expected Behaviour**
You should have the option to select a template when creating a child page.

**Comment by k8hughes** [comment]
LGTM

**Comment by alice-mcandrew-development-initatives** [comment]
Perfect. There's an option for this now.
