### ISSUE TITLE
Work for us / Vacancies page

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#256]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
For the 'Work for us' page there doesn't seem to be the option anywhere at the bottom to add recruitment packs to download

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to http://159.65.56.142/admin/pages/605/edit/

**Expected Behaviour**
The ability to add recruitment packs in the same way you can add team stories

**Comment by akmiller01** [comment]
Once VacancyPages are added as children of a VacancyIndexPage, they should autopopulate the section at the bottom https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/workforus/models.py#L113

But again, this is blocked by the deployment of the new child page deployment.

**Comment by alice-mcandrew-development-initatives** [comment]
A) I don't think the Vacancy Index Page is working as it should be?

- This is what I see:
![Vacancy Index Page](https://user-images.githubusercontent.com/55877063/66846976-8a74e800-ef6a-11e9-93a7-c1a8eb4616df.JPG)
(not many options)

- But the template looks like this:
http://development-initiatives.surge.sh/page-templates/18-vacancy-listing

B) Also, the page doesn't seem to pull through to the Work for us page:

- This is the page:
![Work for us](https://user-images.githubusercontent.com/55877063/66847254-feaf8b80-ef6a-11e9-9b7f-bdf711aa584f.JPG)

- But the template shows this:
http://development-initiatives.surge.sh/page-templates/16-work-for-us
(the title for vacancies is missing)

**Comment by alice-mcandrew-development-initatives** [comment]
It might help to rename or re-add this issue?

**Comment by akmiller01** [comment]
Renaming may help.

Also, most Index pages don't have much content unto themselves. Index pages automatically generate content from their children. In this case you need to create VacancyPages under the Vacancy Index Page.

**Comment by alice-mcandrew-development-initatives** [comment]
@akmiller01 I have created the vacancies page but the title doesn't appear on the work for us page

**Comment by akmiller01** [comment]
Not sure if I follow. Isn't it appearing here? 
![image](https://user-images.githubusercontent.com/2836840/66849816-98644200-ef45-11e9-84b9-3c53d268a0a4.png)

**Comment by alice-mcandrew-development-initatives** [comment]
This bit is missing:
![Vacancies](https://user-images.githubusercontent.com/55877063/66850171-2bb26d00-ef70-11e9-8ed5-b701e4ef32fd.JPG)

I think it should say 'Current vacancies' though

**Comment by akmiller01** [comment]
Ah okay. You get to title that section through the CMS on the Work For Us page:

![image](https://user-images.githubusercontent.com/2836840/66850397-bda58000-ef46-11e9-929b-2768de64c19e.png)

**Comment by alice-mcandrew-development-initatives** [comment]
@akmiller01 Ah, sorry! I missed this! So, once I've added the team stories this should look perfect.
