### ISSUE TITLE
Two columns at bottom of 'Consultancy services' page

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#258]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
A) I'm not sure it's possible to add the text at the bottom of the 'Consultancy services' page in two columns, as per template design.
B) Also, oddly. the text that I have added in for this (for 'Our principles' and 'How we work') does not appear when viewing the published page.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to http://159.65.56.142/admin/pages/622/edit/
2. Scroll to 'SECTIONS'

**Expected Behaviour**
http://development-initiatives.surge.sh/page-templates/09-consultancy-services

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives I added the `Richtext Columns` section to handle this.

![image](https://user-images.githubusercontent.com/5672438/66764521-9d2be600-eeb2-11e9-8d4f-2baa9b65ae79.png)

![image](https://user-images.githubusercontent.com/5672438/66764541-acab2f00-eeb2-11e9-87b2-a368aaa41ca1.png)

**Comment by alice-mcandrew-development-initatives** [comment]
Perfect. I've added the content and it looks good! Thank you.
