### ISSUE TITLE
Press releases in media library

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#259]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
It's unclear how to add press releases to the Media centre

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to http://159.65.56.142/admin/pages/606/edit/

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives press releases are new stories. To mark a news story as a press release, you have to edit a specific news story and mark it as a press release

http://159.65.56.142/admin/pages/302/edit/
![image](https://user-images.githubusercontent.com/5672438/66564347-74c98200-eb68-11e9-9212-e57f53ce91a6.png)

**Comment by alice-mcandrew-development-initatives** [comment]
Great :) that makes sense, thanks for confirming. Once we've marked these I will check they have pulled through and populated the page.

**Comment by edwinmp** [comment]
Hi @alice-mcandrew-development-initatives did you finally get this working?

**Comment by alice-mcandrew-development-initatives** [comment]
Yes, this appears to be working fine! Thanks v much
