### ISSUE TITLE
Hero image caption on homepage

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#265]
## I'm submitting a ...
Bug or question

**Describe the Issue**
There's nowhere to add a hero image caption/URL for the 'Homepage'

**To Reproduce**
1. Go to http://159.65.56.142/admin/pages/3/edit/

**Expected Behaviour**
On the 'Our story' page you can:
![E g  our story hero image caption](https://user-images.githubusercontent.com/55877063/66818929-fe48cd80-ef35-11e9-845e-b4ca5bfb03fc.JPG)

**Screenshots/GIF**
But you can't on the 'Homepage':
![No option to add hero credit on home page](https://user-images.githubusercontent.com/55877063/66818942-043eae80-ef36-11e9-86c4-bef3853889a2.JPG)

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives this was supported to be pulled from the featured publication itself, but that's broken at the moment.

**Comment by alice-mcandrew-development-initatives** [comment]
Ok, I think I misunderstood. I don't think we've set a featured publication yet so can see if this works when we get to that!

**Comment by alice-mcandrew-development-initatives** [comment]
Should we be able to click-through to the publication featured in the hero?

**Comment by alice-mcandrew-development-initatives** [comment]
@edwinmp OK, I'll look out for when this is ready to review
