### ISSUE TITLE
Issue with hero image on who we are page

### ISSUE THREAD

**Issue by riahasler-DI** [devinit/DIwebsite-redesign#266]
## I'm submitting a ...
question

**Describe the Issue**
I am trying to pull through an image for the hero on the "who we are page" - I believe Anna designed the image to fit the hero dimensions, however when added to the hero the image does not pull through properly 

**To Reproduce**
1. Go to http://159.65.56.142/admin/pages/603/edit/
2. on the preview setting the hero image is not aligned

**Expected Behaviour**
If the image has been designed to fit the dimensions - i would expect the image to pull through to the hero properly 

**Screenshots/GIF**
This is the image designed by Anna 
![image](https://user-images.githubusercontent.com/56585598/66821670-b5dfde80-ef3a-11e9-94c6-4dd6a2b03adc.png)

Here is how it pulls through 
![image](https://user-images.githubusercontent.com/56585598/66821779-e889d700-ef3a-11e9-8513-a9c4eef31aa7.png)

When I edit the focus area of the image nothing changes. Is there anything I can do to resolve this issue? Thanks

**Comment by edwinmp** [comment]
@riahasler-DI I've checked, and the two images (the one you added on the site, and the one above) are of different dimensions. The one above renders better cos it's bigger. It too is not of the ideal dimensions, but at least the majority of the image is not cropped out.

![image](https://user-images.githubusercontent.com/5672438/66823969-fe55c700-ef4f-11e9-96de-6b4b91a8627d.png)

**Comment by riahasler-DI** [comment]
Thank you Edwin :)

**Comment by k8hughes** [comment]
@riahasler-DI can this issue be closed now?

**Comment by alice-mcandrew-development-initatives** [comment]
@riahasler-DI @AnnaHope
