### ISSUE TITLE
Consultancy services 'Find our how we can help you' banner

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#272]
## I'm submitting a ...
Bug

**Describe the Issue**
1) Image shape and crop (being addressed elsewhere)
2) No option to add bold in banner block (possibly being addressed elsewhere?)
3) No option to add email address as link

**To Reproduce**
![Sheena banner live](https://user-images.githubusercontent.com/55877063/66920357-03337d00-f01b-11e9-98c6-559c39af45a5.JPG)
![Sheena banner](https://user-images.githubusercontent.com/55877063/66920368-09295e00-f01b-11e9-8225-c5ad503e5e57.JPG)

**Expected Behaviour**
http://development-initiatives.surge.sh/page-templates/09-consultancy-services
![Consultancy help](https://user-images.githubusercontent.com/55877063/66920406-1ba39780-f01b-11e9-8dee-152da0773e0e.JPG)

**Comment by akmiller01** [comment]
Fixed with https://github.com/devinit/DIwebsite-redesign/pull/306 by adding a `richtext` block in addition to just plain text.

@benjamincoleman can you take a look at the CSS so that hyperlinks inside of `banner__excerpt` match the font colour:

![image](https://user-images.githubusercontent.com/2836840/67366843-ec41dd00-f57c-11e9-890c-3c2965b69e6d.png)

**Comment by k8hughes** [comment]
@benjamincoleman can you check this one as well please? Alex left you a question.

**Comment by benjamincoleman** [comment]
This should already be fixed as we have the following CSS in place: 

```
.banner__excerpt a {
    color: #fff;
    text-decoration: underline;
}
```

![Screen Shot 2019-10-31 at 12 44 44](https://user-images.githubusercontent.com/64877/67947747-3dd11400-fbdc-11e9-95e7-889fd5071485.png)

**Comment by akmiller01** [comment]
Cool. I see the CSS there but we need to pull it through to Staging

**Comment by k8hughes** [comment]
@edwinmp can you pull the changes through from the pattern library please?
