### ISSUE TITLE
Test job / Apply for this... 

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#274]
## I'm submitting a ...
Bug or question
relating to http://159.65.56.142/work-for-us/vacancies/test-job/

**Describe the Issue**
Sometimes the download pulls through the fie name and sometimes it pulls through the title

**To Reproduce**
Two documents uploaded - one pdf and one docx - with different file name but same title...
![Doc list](https://user-images.githubusercontent.com/55877063/66922474-0cbee400-f01f-11e9-8f5b-ebb683e1cfc2.JPG)

...added to CMS in the same way...
![Test job apply cms](https://user-images.githubusercontent.com/55877063/66922492-13e5f200-f01f-11e9-855b-2bc02cfd281d.JPG)

...but appear different:
![Test job apply live](https://user-images.githubusercontent.com/55877063/66922555-30822a00-f01f-11e9-8ad6-92c708bf93a1.JPG)

Why does this happen?

**Comment by akmiller01** [comment]
Hi @alice-mcandrew-development-initatives when the website recognizes a file format, it displays it and appends a filesize (e.g. PDF). When it doesn't recognize the fileformat, it will default just to the file title. Would it be worthwhile to have it display file extensions regardless of recognizing the type or not?

**Comment by alice-mcandrew-development-initatives** [comment]
@akmiller01 Would this require us to put the file extension in the name of the file? In which case it could double up where it is recognised?

**Comment by akmiller01** [comment]
Improvements here: https://github.com/devinit/DIwebsite-redesign/pull/317
