### ISSUE TITLE
What we do

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#276]
## I'm submitting...
Bugs

**Describe the Issue**
1)  Missing red line next to Where we work (this was in the design)
![Missing red line for Where we work](https://user-images.githubusercontent.com/55877063/66927382-9b376380-f027-11e9-8a56-89e6c18d991e.JPG)

2) No option to add Consultancy services as white section
![No option to add Consultancy servives as white section](https://user-images.githubusercontent.com/55877063/66927409-aab6ac80-f027-11e9-8325-e9de4dc7b26b.JPG)

3) While this won't be needed if point 2 is addressed, there doesn't seem to be an option to change the colour of the button in the Consultancy services banner

**To Reproduce**
http://159.65.56.142/what-we-do/

**Expected Behaviour**
http://development-initiatives.surge.sh/page-templates/07-what-we-do

1) 
![Red line](https://user-images.githubusercontent.com/55877063/66927788-53650c00-f028-11e9-8156-4c3b49ace1f7.JPG)

2)
![White section](https://user-images.githubusercontent.com/55877063/66927797-57912980-f028-11e9-82c2-de36e292d2f7.JPG)

**Comment by alice-mcandrew-development-initatives** [comment]
Also, I need to add some links in the 'Our impact' banner but am currently unable to. This will be applicable elsewhere also.

![Links in banner](https://user-images.githubusercontent.com/55877063/67011831-3859d100-f0e8-11e9-8a2c-83cb55db67c4.JPG)

**Comment by akmiller01** [comment]
Checking on this one, the red line is a CSS issue for @benjamincoleman . It appears on my screen, so it must be tied to resolution:

![image](https://user-images.githubusercontent.com/2836840/67364053-6ff8cb00-f577-11e9-971d-28ddf4bee5ee.png)

**Comment by akmiller01** [comment]
A richtext field as added here will let you add links to a banner: https://github.com/devinit/DIwebsite-redesign/pull/306

**Comment by akmiller01** [comment]
And after a bit of work adding a completely new consultancy section, I've scrapped it all because I just realized that you need to add the consultancy section as a `duo` block @alice-mcandrew-development-initatives followed by a `testimonial` block. Once #306 is merged that should address all your issues.

**Comment by alice-mcandrew-development-initatives** [comment]
Thanks @akmiller01 
The red line appears at 100% so that's fine, Ben confirmed elsewhere
I will check that I can resolve the other issues once the merge has happened

**Comment by alice-mcandrew-development-initatives** [comment]
1) I added a duo block, but we don't have a video for the consultancy services section at the moment. Can we have the option to add an image instead? We also don't have a testimonial yet, but this doesn't impact the design (and I've tested it works if we did have one int he future and that looks fine). Also, as far as I can tell, there still doesn't seem to be the option to make this section white rather than grey.

2) I've been able to add the links to the our impact section. Can we make the hyperlinks something other than red? Sadly it's not legible at the moment.

![Who we are](https://user-images.githubusercontent.com/55877063/67582618-04168e00-f742-11e9-822b-1a4dbb213bb2.JPG)

**Comment by benjamincoleman** [comment]
@alice-mcandrew-development-initatives I think we'll need variants in the pattern library for (1). 

For (2) we need to update the CSS to accept links.

@BenDarby can you help ⏫

**Comment by BenDarby** [comment]
@benjamincoleman @alice-mcandrew-development-initatives I've updated the styles so links display correctly here. With regards to the first point, you can have an image instead of a video. You just need to replace the `<div class="media-wrapper">` containing the video with a normal `img` tag. 
Also you can give sections a white background by adding the modifier class `section--alt` to the section, examples of both of these are in the pattern library. http://development-initiatives.surge.sh/page-templates/07-what-we-do

**Comment by alice-mcandrew-development-initatives** [comment]
@akmiller01 @edwinmp I think I need your help before I can do anything in the cms? ^

**Comment by akmiller01** [comment]
Yep! Issues addressed here: https://github.com/devinit/DIwebsite-redesign/pull/331

**Comment by alice-mcandrew-development-initatives** [comment]
Also, hyperlinks are not displaying correctly still

**Comment by alice-mcandrew-development-initatives** [comment]
![our impact links](https://user-images.githubusercontent.com/55877063/67940567-d6ab6380-fbcb-11e9-8a4f-afa3953c7a77.JPG)

**Comment by benjamincoleman** [comment]
@akmiller01 looks like Ben D's code hasn't been pulled through / deployed for the hyperlink style

**Comment by k8hughes** [comment]
@edwinmp can you pull through the pattern library code?

**Comment by akmiller01** [comment]
Added the ability for image duos to have headers here: https://github.com/devinit/DIwebsite-redesign/pull/352
