### ISSUE TITLE
block quote source line

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#280]
## I'm submitting a ...
Bug or design query

**Describe the Issue**
There's nowhere to add the source for block quotes.

**To Reproduce**
http://159.65.56.142/what-we-do/our-focus-areas/improving-understanding-humanitarian-assistance/

**Screenshots/GIF**
At the moment I've had to add the source in a paragraph block...
![Block quote cms](https://user-images.githubusercontent.com/55877063/66992878-81972a00-f0c2-11e9-9a28-2386051bc660.JPG)

...which doesn't look great:
![Block quote](https://user-images.githubusercontent.com/55877063/66992811-62989800-f0c2-11e9-878f-3078349a9243.JPG)

**Comment by BenDarby** [comment]
@benjamincoleman @akmiller01 I've amended the styles a little so you just add a `cite` like so: 
```
<blockquote>
    <p>“A blockquote! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus magna. Cras in mi at felis aliquet congue. Ut a est eget ligula molestie gravida.”</p>
    <cite>Space for source text</cite>
</blockquote>
```

**Comment by k8hughes** [comment]
@edwinmp @davidebukali what do we need to do our side to pull through this change?

**Comment by edwinmp** [comment]
@k8hughes we'll pull it from the `pattern_library` branch then update the `blockquote` block.

**Comment by k8hughes** [comment]
Has this been deployed to preproduction?  I check the linked about but it is still looking the same.  I think with the issues the comms team are reporting it makes sense to deploy straight to their environment as the environment I have been testing on previously doesn't have enough correct content in to get at the nuances that they have been reporting.

@edwinmp

**Comment by k8hughes** [comment]
![Screenshot 2019-10-30 at 12 27 12](https://user-images.githubusercontent.com/36768381/67845598-cda98c00-fb10-11e9-8715-2ae1c78f8d5c.png)

@BenDarby is this font size correct?

**Comment by alice-mcandrew-development-initatives** [comment]
@k8hughes this font size does not look legible to me - can we check it meets accessibility standards?

**Comment by benjamincoleman** [comment]
@BenDarby can we bump up the `<cite>` font-size to 16px please?

**Comment by BenDarby** [comment]
@benjamincoleman @alice-mcandrew-development-initatives  I've increased the font size for `cite` to 16px
