### ISSUE TITLE
T11a News listing

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#29]
Sketch: https://marvelapp.com/3j51290/screen/57558637

Design: http://development-initiatives.surge.sh/page-templates/11a-news-listing

Functional Specification: 

Under the hero, we have a button to go to the newsletter sign up page. This is a page hosted on Mailchimp, so would be an external URL. This also applies to the footer button for the newsletter too. 

Below that the template lists the news posts. 

They should be ordered by date, so you see the latest posts first, and the ones further in the past last. 

There should be 9 posts shown on each page before the pagination controls. 

For each post, it should show: 

* Post title
* Post date
* Excerpt - this should be able to be set by the admin, and then fall back to the first 40 words in the content. Let's not use a character count to do this though - that could end up being a problem.

**Comment by benjamincoleman** [comment]
> Change sign up button to be ‘sign up to our newsletter’ as that’s what people would be signing up to

**Comment by edwinmp** [comment]
@Napho I'm not seeing much difference between this one and blog listing, so I'm banding them together.

**Comment by k8hughes** [comment]
http://178.128.102.213/news/ 

I am assuming the empty white box is because the pages that will fill the box haven't been built yet.  I think this is working as intended.

**Comment by edwinmp** [comment]
@k8hughes yes, that'll hold the "what we do" links.
