### ISSUE TITLE
Change to default image for pages without a manually assigned hero

### ISSUE THREAD

**Issue by jamesharle** [devinit/DIwebsite-redesign#290]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
We need to change the current image that is assigned automatically to pages that do not have an image manually assigned to them via the cms, as the current image is incomplete.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to the event listing page
2. See the default images, which contain an incomplete DI logo in the top centre of the image.

**Expected Behaviour**
We need a complete image.

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: dd/MMM/YYYY

**Comment by akmiller01** [comment]
Could you please provide us a placeholder image in roughly 713 px wide and 537 px tall @jamesharle ? This is the image that was provided to us in the pattern library as the placeholder http://159.65.56.142/assets/img/fallback-image.jpg

**Comment by jamesharle** [comment]
lol @ roughly 713 wide and 537 tall :D Please find below a corrected image approximately exactly that size.

Thanks for your help with this A :)

![fallback-image](https://user-images.githubusercontent.com/43270042/67375572-bb60a880-f57a-11e9-98a7-2bf89ed91991.jpg)

**Comment by akmiller01** [comment]
@benjamincoleman could you please incorporate the above placeholder image into the pattern library as `assets/img/fallback-image.jpg`? I'm worried if we add it at our end it may eventually be overwritten the next time we pull in pattern library changes.

**Comment by benjamincoleman** [comment]
@BenDarby can you do this please?

**Comment by BenDarby** [comment]
@akmiller01 @benjamincoleman  I can add a placeholder image for when there is no hero image assigned but there is already a system in place for this, when the user doesn't assign a hero image then you need to remove the `hero--image` modifier class on the hero element and it will display the red with a pattern which is created with css. We have a slightly darker red behind the text for accessibility reasons too.

**Comment by akmiller01** [comment]
Thanks Ben,

I think this issue is just about the index page placeholders. If you
replace the file in the pattern library with the one above it should pull
through.

**Comment by benjamincoleman** [comment]
@BenDarby so on the homepage pattern library template we have a placeholder image for a "featured work" item. It's that element that Alex is referring to (see screenshot). 

http://development-initiatives.surge.sh/page-templates/02-homepage

<img width="1251" alt="Screen Shot 2019-10-24 at 09 44 53" src="https://user-images.githubusercontent.com/64877/67468754-f9290400-f642-11e9-8c23-a241448058ab.png">

**Comment by BenDarby** [comment]
@akmiller01 Ah sorry, I misunderstood. I've updated the fallback image in the pattern library to the one provided above.
