### ISSUE TITLE
Image credit name limited characters

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#296]
## I'm submitting a ...
Bug

**Describe the Issue**
Please can we remove the character limit on the 'Image credit name' for the hero on each page

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/305

**Comment by k8hughes** [comment]
@akmiller01  I have tested this and there is still a charater limit for me, so it doesn't appear to have worked.
