### ISSUE TITLE
Hyphenated words on same line of title

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#297]
Can we have hyphenated words on the same line of the title?
E.g. here 'pro-poor' should be together as a compound:
![Capture2](https://user-images.githubusercontent.com/55877063/67198589-34cf8e00-f3f7-11e9-94c6-a0e883b82790.JPG)

(This was flagged on Slack a while back but I can't see anything on Github)

**Comment by akmiller01** [comment]
@benjamincoleman I think this is sorted out via CSS?

**Comment by benjamincoleman** [comment]
@BenDarby can we do something clever here to prevent breaking lines at hyphenated words with CSS?

**Comment by akmiller01** [comment]
If not, the only other solution seems to be replacing hyphens with a `non-breaking hyphen` character. Although I don't know how hard that would be to type into the CMS: https://stackoverflow.com/a/7691604

**Comment by BenDarby** [comment]
@akmiller01 @benjamincoleman I've researched if this was possible with css but I can't see way to achieve this, the hyphen is functioning as it should be in terms of css. Using non-breaking hyphens will solve the issue but I'm not sure how possible it is for devs.

**Comment by akmiller01** [comment]
Hi Alice. Just researched a few solutions and the only one that works is to use the following character in place of a standard hyphen:



‑
--


It's code is U+2011 and the best way to use it is just to copy and paste it from one source to another. This tells the HTML not to use the hyphen as a breaking opportunity: 

![image](https://user-images.githubusercontent.com/2836840/67462045-735b8780-f647-11e9-878d-59941e7a90f4.png)

I've also updated the publication so you can copy that special hyphen from that article in the future: http://159.65.56.142/publication/is-the-201920-uganda-budget-pro-poor/
