### ISSUE TITLE
T11 Blog Listing

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#3]
Design: http://development-initiatives.surge.sh/page-templates/11-blog-listing

Functional specification: 

The blog page has the standard hero, and then under there has a number of tags for the blog posts. When a user hits one, the list is filtered to show only blog posts which have that tag. This would also change the title 'Latest blog posts' to read 'Latest blog posts tagged {tagname}'

Each blog post shows: 

* post date
* post title
* Excerpt - this should be able to be set by the admin, and then fall back to the first 40 words in the content. Let's not use a character count to do this though - that could end up being a problem.
* Author - this should be a team member, or in the case where it's a guest author, just their name / job title. There's a variant design for this coming. 

The list of blog posts should be 9 posts long, and then paginate.

**Comment by k8hughes** [comment]
http://178.128.102.213/blog/ 

LGTM.

**Comment by edwinmp** [comment]
@akmiller01 for the excerpt (as per the description up there), we're not doing the first 40 words for it... problem?

**Comment by akmiller01** [comment]
I'd rather not truncate, if we can avoid it. It looks really weird to have partial sentences. Plus, if the hero_excerpt is more than 40 words I think we'll have problems on the blog article page as well.

**Comment by edwinmp** [comment]
I'm truncating for the news article... have no problem with it really. In fact, serves its purpose of motivating users to go to the main article if they want to read more. Also, I'm not getting it from the `hero`

**Comment by benjamincoleman** [comment]
@akmiller01 @edwinmp excerpt should be able to be edited by the admins as I mentioned in the functional spec. 

If you're truncating as a fallback that's ok.

**Comment by alice-mcandrew-development-initatives** [comment]
Something odd is going on with the blog listing again. I'm seeing no images and some older content being brought forward with the wrong date:
![image](https://user-images.githubusercontent.com/55877063/69958252-4b8bf900-14fc-11ea-90da-50ac02ce1445.png)

**Comment by alice-mcandrew-development-initatives** [comment]
Cleared cache and it's back to working again!
