### ISSUE TITLE
T11b Events listing

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#30]
Sketch: https://marvelapp.com/3j51290/screen/57560127

Design: http://development-initiatives.surge.sh/page-templates/11b-events-listing

Functional Specification: 

This template lists events. 

They should be ordered by date ascending, so you see the closest events first, and the ones further in the future last. 

There should be 9 events shown on each page before the pagination controls. 

For each event, it should show: 

* Event title
* Event start date - end date including the year e.g. `Dec 10 - Dec 12, 2019`. If the start year is different to the end year, it should show both e.g. `Dec 10, 2019 - Jan 12, 2020`
* Start time - end time
* Location

I would use date pickers for the dates, rather than free text. 
I would use free text for the start time - end time, and for the location.

**Comment by k8hughes** [comment]
http://178.128.102.213/events/ 
If an event doesn't have an image then you get a big white space.  Is that working as intended?

**Comment by k8hughes** [comment]
Lets add a default image so there isn't so much white space...

**Comment by benjamincoleman** [comment]
Hi folks, you can see the default image here - http://development-initiatives.surge.sh/page-templates/01d-media-center

It's the red squares.

**Comment by edwinmp** [comment]
Ah, nice... thanks @benjamincoleman ... we'd missed that.

**Comment by edwinmp** [comment]
@k8hughes this should be fixed now.

**Comment by k8hughes** [comment]
Yes it LGTM :)
