### ISSUE TITLE
Sign up link not available

### ISSUE THREAD

**Issue by riahasler-DI** [devinit/DIwebsite-redesign#300]
## I'm submitting a ...
Bug or design issue

**Describe the Issue**
On the News page, there should be a button allowing people to sign up to our newsletter via this link: https://us11.list-manage.com/subscribe?u=a829237ca0cf1470615c7f059&id=ce30e2af0f
On the page I cannot find the option to add this. 

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'http://159.65.56.142/admin/pages/277/edit/'

**Expected Behaviour**
This is the template design: 
![image](https://user-images.githubusercontent.com/56585598/67300339-b56cb800-f4e5-11e9-94a6-a5e70aecc51f.png)
This is the live page: 
![image](https://user-images.githubusercontent.com/56585598/67300395-ca494b80-f4e5-11e9-905e-5c6f7d771f3c.png)

And this is what the editing page looks like: 
![image](https://user-images.githubusercontent.com/56585598/67300469-e3ea9300-f4e5-11e9-9df6-f6c24a92b052.png)

I would expect to be able to add the Sign up button to the page but can't see how on the editing page.  
Thanks!

**Comment by davidebukali** [comment]
Newsletter items can be added through the snippets menu in the admin section.

**Comment by akmiller01** [comment]
http://159.65.56.142/admin/snippets/home/newsletter/
