### ISSUE TITLE
Tags on blog page are not in alphabetical order

### ISSUE THREAD

**Issue by riahasler-DI** [devinit/DIwebsite-redesign#301]
## I'm submitting a ...
Design issue or Bug

**Describe the Issue**
The tags on the Blogs page are not in alphabetical order.

**To Reproduce**
This is the design template: 
![image](https://user-images.githubusercontent.com/56585598/67301444-50b25d00-f4e7-11e9-9449-890395698dc9.png)
Here the tags are in alphabetical order

This is the live Blogs page: http://159.65.56.142/blog/?topic=aidoda
![image](https://user-images.githubusercontent.com/56585598/67301566-7e97a180-f4e7-11e9-8fc7-e292f4af1439.png)

Here the tags are not in order. 

How do we fix this issue?

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/307
