### ISSUE TITLE
Office location snippet line breaks

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#302]
## I'm submitting a ...
Bug

**Describe the Issue**
There does not seem to be a way to add line breaks in cms for office location snippets

**To Reproduce**
http://159.65.56.142/who-we-are/
![Office location live](https://user-images.githubusercontent.com/55877063/67305600-7fcbcd00-f4ed-11e9-99b1-241eb9f3508b.JPG)

**Expected Behaviour**
![Office location cms](https://user-images.githubusercontent.com/55877063/67305611-82c6bd80-f4ed-11e9-9d24-6519f24cd0c1.JPG)

**Comment by akmiller01** [comment]
@benjamincoleman would it be possible to allow linebreaks in class `location__copy`?

**Comment by benjamincoleman** [comment]
@BenDarby can you help with this? It's from this template: http://development-initiatives.surge.sh/page-templates/03-who-we-are

**Comment by BenDarby** [comment]
@benjamincoleman @akmiller01 if you update the markup for `location__copy` to this then it will work
```
<div class="location__copy">
                        <p>North Quay House Quay Side</p>
                        <p>Temple Back Bristol</p>
                        <p>BS1 6FL</p>
                        <p>UK</p>
                    </div>
```
You can see it in the pattern library as well

**Comment by akmiller01** [comment]
Cheers @BenDarby I cannot really update the mark-up as this is CMS user entered content, but I'll swap out the plain text field for a Rich text field with the div tags stripped, and that way Alice can enter each line as a separate paragraph.

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/313
