### ISSUE TITLE
More about

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#303]
## I'm submitting a ...
Question

**Describe the Issue**
How does the 'More about' on top right of each page work? Should this pull through automatically with relevant child pages? At the moment it doesn't seem to be doing this. What do we need to do?

**To Reproduce**
http://159.65.56.142/who-we-are/

**Expected Behaviour**
http://development-initiatives.surge.sh/page-templates/03-who-we-are

**Screenshots/GIF**
![Who we are 'more about'](https://user-images.githubusercontent.com/55877063/67307333-4183dd00-f4f0-11e9-9c36-792ad97a69ea.JPG)

**Comment by akmiller01** [comment]
`More about` sections are automatic, and either list children of a given page or siblings, depending on the page. In the above case, it will display all children of `Who we are` that are marked `show in menus` on the `Promote tab` of the respective pages.

We still need to sort out the main menu, so that all of the pages you mark "Show in menus" don't automatically appear in the top menu as well, but for the moment mark any pages you want to show in "More about" as "Show in menus"

**Comment by jamesharle** [comment]
Thanks @akmiller01! Regarding the How we work page specifically, I have followed your instructions above for its sole child page (Partnerships and collaboration) and the More about section appears to be auto-populating with Homepage content still (see image).
![image](https://user-images.githubusercontent.com/43270042/67385037-2f567d00-f58a-11e9-91ef-ce0e74f644c4.png)

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/312/files

**Comment by alice-mcandrew-development-initatives** [comment]
@akmiller01 You may already be checking for this (as I'm not sure if it's another example or separate issue), but I can see that the 'More about' for the Our team page is pulling through 'Our team'' when it should be 'Who we are'.

What it looks like:
![Team live](https://user-images.githubusercontent.com/55877063/67568641-a758aa80-f724-11e9-831b-6c2ac968a8db.JPG)

What it should look like:
![Team pattern](https://user-images.githubusercontent.com/55877063/67568651-acb5f500-f724-11e9-93bf-40073f7ed445.JPG)


In terms of process, do let me know whether it's helpful to raise related (potentially repeat) issues in the same place or to create a new ticket.

**Comment by edwinmp** [comment]
Hi @alice-mcandrew-development-initatives ... I'd raised this (raising related issues) on Slack before. We'd prefer it if you didn't raise new issues for recurring or related issues. If the existing issue is closed, reopen it.

As for the issue above, yes that's a bug. Will let you know when a fix is deployed.

**Comment by jamesharle** [comment]
@edwinmp to flag, the issue Alice raises above also applies to every team member profile.

**Comment by akmiller01** [comment]
Fixed for team member pages in code here https://github.com/devinit/DIwebsite-redesign/pull/329

**Comment by edwinmp** [comment]
> Fixed for team member pages in code here #329

@jamesharle this fix has been deployed.
