### ISSUE TITLE
Rescrape all content added since last WP scrape.

### ISSUE THREAD

**Issue by akmiller01** [devinit/DIwebsite-redesign#311]

**Comment by akmiller01** [comment]
@AnnaHope and @alice-mcandrew-development-initatives do we have a date by which we're going to stop adding new content to the old devinit.org for the migration?

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/405

**Comment by alice-mcandrew-development-initatives** [comment]
@akmiller01 I've confirmed with Anna and Simon that now is a good time to migrate the content. We have something to publish on 25th but nothing else planned in the near future except potentially a couple of blogs, and we could just create new pages for these when/if needed.

**Comment by k8hughes** [comment]
I am assuming this is fine now.
