### ISSUE TITLE
Project page links not working on Our Focus Areas page

### ISSUE THREAD

**Issue by riahasler-DI** [devinit/DIwebsite-redesign#316]
## I'm submitting a ...
Question or Bug: 
On the Our Focus Areas Page when I click on the key projects section I am not sent to the related project page. 

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'http://159.65.56.142/what-we-do/our-focus-areas/'
2. Click on 'any of the key projects'

**Expected Behaviour**
 I would expect to be sent to the project page as the ones I have linked to the parent page are live.

**Comment by k8hughes** [comment]
This is now working.
