### ISSUE TITLE
T1d Media Center

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#32]
Sketch: https://marvelapp.com/3j51290/screen/58622383

Design: http://development-initiatives.surge.sh/page-templates/01d-media-center

Functional specification: 

We have the standard hero here, with page title and hero content, plus the image with credit if required.

There's the sidebar menu on the right, which has had a recent update to the way the title is spelled out "More about:" being the thing that has changed. What should happen there is the "More about:" will be fixed and the "What we do" will be the top page of the section that has this menu. So, What we do, Who we are etc. etc.

Under the hero we have a streamfield block as detailed in #19 

Then we have a list of people. They would be selected from the people within the system - the same that are used for the team page #26. 

We then have a list of press releases, which are actually selected news posts. The news posts themselves would need a control to say "this post is a press release" and then allow it to be automatically shown in this template. I've added this requirements as a comment here: https://github.com/devinit/DIwebsite-redesign/issues/21#issuecomment-515410198

**Comment by benjamincoleman** [comment]
Remove spaces in phone numbers

**Comment by k8hughes** [comment]
http://178.128.102.213/media-center/ 

LGTM

**Comment by benjamincoleman** [comment]
@akmiller01 I've just updated #19 with details of the content streamfield in play there. I don't think it's 100% needed, but it might be an idea to have that same streamfield available here for consistency

**Comment by alice-mcandrew-development-initatives** [comment]
Can we make the Spokespeople images on this page a bit bigger? They seem a bit small at the moment. (They also don't look great because of variety in photo style, but I think increasing the size may help a bit).

How they are now:
![Spokespeople](https://user-images.githubusercontent.com/55877063/67001196-19037980-f0d1-11e9-9796-781d0482ccb4.JPG)

What the pattern library shows:
![Spokespeople pattern](https://user-images.githubusercontent.com/55877063/67001214-1f91f100-f0d1-11e9-8dcf-0d01092323e7.JPG)

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/281

**Comment by alice-mcandrew-development-initatives** [comment]
Bizarrely, the page displays correctly at 75% but not 80% zoom.

Red line next to 'Press releases' at 75%:
![75%](https://user-images.githubusercontent.com/55877063/67014881-7e656380-f0ed-11e9-8bf7-561b60917e5e.JPG)

No red line at 80%:
![80%](https://user-images.githubusercontent.com/55877063/67014893-832a1780-f0ed-11e9-8884-dbb5d7ac22c8.JPG)

**Comment by k8hughes** [comment]
@benjamincoleman I assume this is a pattern library thing?

**Comment by benjamincoleman** [comment]
@k8hughes this is an interesting one - we only ever design, and test, for 100% zoom. 

If we did look at zoom levels, then we'd normally only go to higher zoom levels, and would only look at whether things were fundamentally broken and unusable.
