### ISSUE TITLE
Random publications pulling through to team member pages

### ISSUE THREAD

**Issue by jamesharle** [devinit/DIwebsite-redesign#327]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
Some staff profile pages are pulling seemingly random publications. An example is Alice's profile, which suggests she's the author of CBLB and a paper on the P20.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Visit Alice's profile under Our team
2. See error

**Expected Behaviour**
Publications should only pull through to the profile pages of listed authors.

**Screenshots/GIF**
![image](https://user-images.githubusercontent.com/43270042/67579560-9e73d300-f73c-11e9-8396-a21ad9992204.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: dd/MMM/YYYY

**Comment by k8hughes** [comment]
@akmiller01  as this is a publications issue I think that you'll be the man to fix it.

**Comment by akmiller01** [comment]
Yep. Alice's ID was 9, Zach's was 93, so in some cases Zach's pubs were being assigned to Alice. Code here https://github.com/devinit/DIwebsite-redesign/pull/329

**Comment by k8hughes** [comment]
http://159.65.56.142/who-we-are/our-team/alice-mcandrew/ 

Now Alice has no publications which I believe is correct.
