### ISSUE TITLE
Sub-saharan Africa is showing twice in the country drop-down in publications

### ISSUE THREAD

**Issue by AnnaHope** [devinit/DIwebsite-redesign#333]
@edwinmp I'm trying to add countries so we can assign them to individual publications to appear in the dropdown menu in the publications page. I added Kenya, Uganda and Somalia all to sub-saharan africa but the dropdown is showing Kenya as separate to the others with the region name duplicated. We need them all to be in the same list under a single SSA region.

![image](https://user-images.githubusercontent.com/16958942/67692890-be073780-f998-11e9-9e16-c711c84e4c78.png)

Thanks!

Anna

**Comment by k8hughes** [comment]
@akmiller01 as this is a bug in publications I think it would be one for you?
I've checked the CMS content and it seems to be correct so I'm not sure what the cause is.

**Comment by akmiller01** [comment]
Ah, so when you asked me to alphabetize the tags I alphabetized all of them. Including the countries. How would you like the countries sorted? Alphabetical within regions?

**Comment by akmiller01** [comment]
I've recoded this as first alphabetically by region, and then alphabetically by country @AnnaHope https://github.com/devinit/DIwebsite-redesign/pull/346
