### ISSUE TITLE
Homepage navigation bar not displaying in the correct order

### ISSUE THREAD

**Issue by AnnaHope** [devinit/DIwebsite-redesign#337]
The top nav bar on the homepage is not displaying in the right order, and contact us + media centre shouldn't be there at all. Can't see how to amend this using the cms if it is editable?

![image](https://user-images.githubusercontent.com/16958942/67858267-bd91ac80-fb10-11e9-98f4-96b6f31938ef.png)

It should look exactly as the design template looks

![image](https://user-images.githubusercontent.com/16958942/67858324-d8642100-fb10-11e9-8f30-192d77c250ec.png)

Although we may need to hide 'data' until that section is built, or make that a page that says the data section is coming soon...

@k8hughes FYI

**Comment by edwinmp** [comment]
I've arranged them as you want them, though the downside of doing this with wagtail is that when you edit a page, it snaps to the top and will require you to drag it back in place.

**Comment by edwinmp** [comment]
Actually, I was wrong on the effect of editing on the order. The sorting remains even after editing. :)

**Comment by riahasler-DI** [comment]
Hi @edwinmp I'm reopening this issue as Anna has flagged that the nav bar has 'how we work' and 'what we do' the wrong way round. 

Here's the template: 
![image](https://user-images.githubusercontent.com/56585598/68031522-bce54b80-fcb3-11e9-8398-9d30ece1dd69.png)

Here's what appears on the live page:
![image](https://user-images.githubusercontent.com/56585598/68031567-d9818380-fcb3-11e9-9c2b-f0dafe499b7d.png)

Is there any way to fix this? 

Thanks
