### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#341]
http://159.65.56.142/admin/pages/709/edit/

1) I can't see an option to add a new row to tables in the cms manually. It only seems to work when you copy and paste the content from excel. I'm not sure if this is a bug or not:
![Table cms](https://user-images.githubusercontent.com/55877063/67866781-5f20fa00-fb21-11e9-8022-1edbe79159f2.JPG)

2) Can we have the content in each column start at the top of the cell rather than the bottom. This would be a nice to have if its straightforward:
![Table live](https://user-images.githubusercontent.com/55877063/67866921-8d9ed500-fb21-11e9-866f-f3867d1f58ef.JPG)

**Comment by akmiller01** [comment]
@alice-mcandrew-development-initatives easiest way to add rows/columns is to right click on the table.

**Comment by akmiller01** [comment]
On table formatting I think we need help from @benjamincoleman

**Comment by benjamincoleman** [comment]
@BenDarby can we make the content of the table cells vertically align to the top please
?

**Comment by BenDarby** [comment]
@benjamincoleman @akmiller01 table cells now align to the top of the cell.

**Comment by alice-mcandrew-development-initatives** [comment]
@k8hughes from my perspective, this looks like it's done: http://159.65.56.142/publication/global-humanitarian-assistance-report-2019/methodology-and-definitions/

**Comment by k8hughes** [comment]
👍  I'll close it then.
