### ISSUE TITLE
Chart example 2 - Line chart with animation

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#351]
This chart should be a simple line chart. 

Both lines should animate left to right to reveal the lines. 

Anna's comment on this: 

> Fig 11: stuff like this would be really nice to animate. If people see the orange line spiking up while the dark pin bumps along the bottom it really emphasises how the trend in use of loans has radically altered over time.

![Group](https://user-images.githubusercontent.com/64877/67935257-5e3fa500-fbc1-11e9-8137-8cac70dbb78f.png)

Data is here: 

https://docs.google.com/spreadsheets/d/1s8XNtEwWcMbSkHWffEUfUNDb1S-pVK3gW3Qx1AFl1Gg/edit#gid=822192478

**Comment by urlsangel** [comment]
@benjamincoleman 

This is now up on surge:

http://development-initiatives.surge.sh/page-templates/22-visualisations
