### ISSUE TITLE
Data formatting

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#356]
So we have different data formats possible, from the ones provided, and the one we use. 

The principle we have is that columns are fixed, and describe the thing, and then the rows underneath are the values. 

Question is, will this be the format we receive the data in or will there need to be some work to get it into this format? 

https://docs.google.com/spreadsheets/d/1s8XNtEwWcMbSkHWffEUfUNDb1S-pVK3gW3Qx1AFl1Gg/edit#gid=822192478

**Comment by AnnaHope** [comment]
@benjamincoleman so the plan was to have a standardised format for data used in visualisations in publications, and it would be a .csv machine readable file i.e. not what you have linked to.
