### ISSUE TITLE
T14.1 Publication long form - chapter

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#36]
Sketch: https://marvelapp.com/3j51290/screen/57853944

Design: http://development-initiatives.surge.sh/page-templates/14-1-publication-long-form

Functional Specification: 

The publications section can be copied across from the GNR website and the templates are broadly very similar in the content and functionality they have. 

This template is also very very similar to the one for a short form publication - #17. I think the only difference may be the nav menu in the bottom right of the screen and how that works. 

**Hero:** 

- `type of publication` e.g. FACTSHEET. This is not present in GNR. This also is shown in the #15 Publication template. 
- `title`
- `Publication downloads button` - this links you down to the "Publication downloads" section right at the bottom of this template. 

**Content:**

This uses a large streamfield which allows you to insert multiple types of content. We've deliberately kept the functionality here the same to hopefully make it importable from GNR with zero issues. I've mentioned footnote seperately, but this functionality is presnet here, and is less portable / more complicated. We've had a call about that, and if you need support do please reach out as we're more than happy to help. 

**Downloads:**

There may be specific downloads for this chapter. Again, this will also need to accept links to pages in the new Data Section when that is built. 

**Sharing**

This should just work I hope. It's common to #16 and #17 

**Publication Downloads**

This section is common to the Publication Summary template - #16 and it's likely that it's that page which will define this content. It should only have PDF downloads of the whole report in different languages, the space for other types of download is the Downloads section I mentioned previously.

**Footnotes**

We allow users to add footnotes and recently built some really innovative functionality to help with this. We've had a call about this, and if you need help do please say so and we'll be able to assist.

**Related content**

The ability to link to up to three other pages of content - could be publications, could be other types of content from within the website such as News, Blog etc. 

**Chapter navigation**

We have the chapter navigation in the bottom right of the screen: 

<img width="430" alt="Screen Shot 2019-08-27 at 11 45 29" src="https://user-images.githubusercontent.com/64877/63765115-3fbae600-c8c0-11e9-884d-e702cd4382df.png">

I am hoping this will be able to be copied across from GNR and work without needing any adjustment. The idea is that the arrows allow you to move between chapters, and the contents menu then shows the following menu which allows you to navigate to specific sections of other chapters in the publication: 

<img width="1440" alt="Screen Shot 2019-08-27 at 11 45 38" src="https://user-images.githubusercontent.com/64877/63765168-611bd200-c8c0-11e9-90a2-0ca3be6d5d9d.png">

You can see this working in the GNR website: https://globalnutritionreport.org/reports/global-nutrition-report-2018/burden-malnutrition/#section-2-2

**Comment by benjamincoleman** [comment]
@BenDarby the footnotes look a bit odd spaced out like this: 

![Screen Shot 2019-08-01 at 13 45 58](https://user-images.githubusercontent.com/64877/62294404-bea83480-b462-11e9-9dae-e52f052daacb.png)

Can we make the footnote number, and content line up?

**Comment by urlsangel** [comment]
@BenDarby @benjamincoleman 

Missed this before, but doesn't this template and the other 'flexible content' type templates have the old case study issue from GNR, where the nested infographic is not full width?

I think the style for the infographic in the case study blocks should match the full width ones as in GNR to mitigate this.

**Comment by benjamincoleman** [comment]
@urlsangel quite right - @BenDarby can you amend this please?

**Comment by BenDarby** [comment]
I can look but this could look strange as this design has a solid background colour for case studies. The graphs can have a white background colour but it might look like the design is broken. I'll implement and see what you think

**Comment by BenDarby** [comment]
@benjamincoleman @urlsangel updated but I'm not sure it works as well with this design.

**Comment by k8hughes** [comment]
http://178.128.102.213/publications/new-long-publication/chapter-one/ 

This looks ok with the content I have added.

**Comment by alice-mcandrew-development-initatives** [comment]
@k8hughes 

The labels in the download section at the bottom are not appearing as intended:
1) The font weight is heavier than the pattern library
2) We should have 'Publications downloads' and 'Data downloads' (and these are not editable)

This is what is looks like:
![Downloads](https://user-images.githubusercontent.com/55877063/67680909-2a2b7080-f984-11e9-912d-48edd492f027.JPG)

It should look like:
![Downloads pattern](https://user-images.githubusercontent.com/55877063/67680918-2f88bb00-f984-11e9-81f6-bece8d714966.JPG)

**Comment by k8hughes** [comment]
@edwinmp I think this might ahve been something you worked on?

**Comment by akmiller01** [comment]
Fixed here for the moment. Actual content of data downloads will need to change once we plugin the DDW: https://github.com/devinit/DIwebsite-redesign/pull/332

**Comment by alice-mcandrew-development-initatives** [comment]
@akmiller01 Not sure what you mean by 'Actual content of data downloads will need to change once we plugin the DDW' but the page looks good!

**Comment by akmiller01** [comment]
@alice-mcandrew-development-initatives Edwin has left the data downloads as they are, but while we're incorporating the `Data section` pages in, we're adding the ability to tag a publication to a live dataset as well.

**Comment by alice-mcandrew-development-initatives** [comment]
@akmiller01 Understood, thanks
@AnnaHope  FYI

**Comment by alice-mcandrew-development-initatives** [comment]
@edwinmp and @akmiller01 , thank you for changing the footnotes!

Are you able to change the in-body reference to be superscript and without square brackets. This is what it looks like at the moment:
![Capture](https://user-images.githubusercontent.com/55877063/68583687-bb671080-0475-11ea-8c4e-3d6f799e89b8.JPG)

Also, at the bottom, to my eyes, the length of the line above the '1' looks different to the line above '2' - can we make this consistent or is this dictated by the length of the number?
![Capture2](https://user-images.githubusercontent.com/55877063/68583864-20226b00-0476-11ea-9d59-2fa73ad68365.JPG)

Please let me know if/when you're going to make changes, as I'll be going through adding the footnote content (and want to make sure the upload saves).

In addition, @AnnaHope, do we actually want to have this heading (as in above screenshot ^) as 'Notes' rather than 'Footnotes'? (I'm aware this is different from the template but I think it would make more sense...)

**Comment by alice-mcandrew-development-initatives** [comment]
With regards to the above, Anna and Simon would like to change the heading 'Footnotes' to 'Notes' throughout

**Comment by edwinmp** [comment]
Hi @alice-mcandrew-development-initatives renamed Footnotes to Notes in #376 

As for the superscripts, @BenDarby could you look into repositioning those?

As for the other request (top bar on numbers), yes, those are determined by the numbers ...

**Comment by BenDarby** [comment]
@edwinmp the superscript has been updated

**Comment by alice-mcandrew-development-initatives** [comment]
@edwinmp do you need to pull this change through?

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives it's already in the pipeline ... will let you know when deployed.

**Comment by edwinmp** [comment]
> Are you able to change the in-body reference to be superscript and without square brackets.

@alice-mcandrew-development-initatives I'm soon to deploy the pattern-library update for the superscript, and I have to say, it looks strange without the square brackets.

![image](https://user-images.githubusercontent.com/5672438/68759263-6b787d00-0620-11ea-8d81-1b27fb029ade.png)


It's more natural with square brackets since this is the convention for this kind of citation:

![image](https://user-images.githubusercontent.com/5672438/68759317-81863d80-0620-11ea-9764-2cb38e41fada.png)

**Comment by alice-mcandrew-development-initatives** [comment]
@edwinmp Yes, I see what you mean... Square brackets looked clunky before but look OK when in superscript. Do follow convention as you suggest. Thank you.

**Comment by k8hughes** [comment]
We don't have detailed enough content on the dev server to test this so just push it straight through to pre-production.

**Comment by k8hughes** [comment]
@alice-mcandrew-development-initatives can you check this and close if you are happy with it.

**Comment by alice-mcandrew-development-initatives** [comment]
@k8hughes the footnotes are not superscript (as they should be): 
![image](https://user-images.githubusercontent.com/55877063/69553344-f5690400-0f97-11ea-9742-5bc47a275e36.png)

**Comment by k8hughes** [comment]
@edwinmp @akmiller01 could one of you heck what needs to be done here?

**Comment by akmiller01** [comment]
These are already <sup> tags. If you want them displayed any differently, we'll need CSS help from @benjamincoleman 

![image](https://user-images.githubusercontent.com/2836840/69556743-4e727100-0f73-11ea-8828-6555e83f6232.png)

**Comment by alice-mcandrew-development-initatives** [comment]
It should be the same as the GNR, which is superscript:
![image](https://user-images.githubusercontent.com/55877063/69557945-521bed00-0f9f-11ea-955d-5e631b6f08cf.png)
Is that a problem?

**Comment by akmiller01** [comment]
It is the same as the GNR website @alice-mcandrew-development-initatives , it is already a Superscript. There's just something in the styling that's preventing it from being displayed as such @benjamincoleman

**Comment by AnnaHope** [comment]
@benjamincoleman are you able to help??

**Comment by benjamincoleman** [comment]
@AnnaHope I can if I can see it, does anyone have a link to an example of this so I can check? @alice-mcandrew-development-initatives @akmiller01 ?

**Comment by alice-mcandrew-development-initatives** [comment]
@benjamincoleman 
1) http://159.65.56.142/publications/global-humanitarian-assistance-report-2019/chapter-1-people-crisis-and-assistance/
2) http://159.65.56.142/publications/preliminary-oda-data-2018-total-falls-for-second-consecutive-year/

**Comment by benjamincoleman** [comment]
@BenDarby can you have a look and work out why we've lost styling on the `<sup>` elements used for the footnotes please?

**Comment by BenDarby** [comment]
@akmiller01 @BenDarby I've added sup styling back into the `is-typeset` class, will need pulling from `pattern_library branch`

**Comment by benjamincoleman** [comment]
@alice-mcandrew-development-initatives @AnnaHope the supertext style has been added, it'll need the code integrating but there's a solution there for you.

**Comment by akmiller01** [comment]
Cheers guys. Can you make a other pattern library PR @edwinmp ?
