### ISSUE TITLE
Map on what we do page showing incorrect locations

### ISSUE THREAD

**Issue by AnnaHope** [devinit/DIwebsite-redesign#360]
At the mo, the map on the 'what we do page' is showing our offices but should ideally be completely separate for us to manually enter. Just to flag that some places we have done work don't appear anywhere on the website such as consultancy for someone else, so wouldn't be just where a publication is tagged as being in a particular country. http://159.65.56.142/what-we-do/

@edwinmp

**Comment by edwinmp** [comment]
@AnnaHope a fix for this has been deployed.

**Comment by AnnaHope** [comment]
@edwinmp the map has disappeared entirely? we can't figure it out from the cms...could you help? FYI @alice-mcandrew-development-initatives

**Comment by edwinmp** [comment]
Hi @AnnaHope ... please add locations for the map to appear.

![image](https://user-images.githubusercontent.com/5672438/68940167-84fdfe00-07b3-11ea-81d6-b0ba27a028b4.png)

**Comment by alice-mcandrew-development-initatives** [comment]
This was done :)
