### ISSUE TITLE
We need google analytics set up for the site

### ISSUE THREAD

**Issue by AnnaHope** [devinit/DIwebsite-redesign#361]
Hi guys,

We need google analytics set up before the site goes live to ensure we can keep an eye on website use when we make the switch and thereafter. 

Thanks!

Anna

**Comment by edwinmp** [comment]
@AnnaHope I created a new analytics account and added `devinitanalytics@gmail.com` as a super user.

**Comment by riahasler-DI** [comment]
Hi @edwinmp, what is the name of the new account? Will take a look at google analytics and close this issue then. Thanks!

**Comment by edwinmp** [comment]
You should have received an invitation on the `devinitanalytics@gmail.com`. The account is `DI Website` ...

**Comment by k8hughes** [comment]
@riahasler-DI @AnnaHope can you confirm that you had the invitation?

**Comment by AnnaHope** [comment]
@k8hughes yep we have it in that account. Thanks @edwinmp!
