### ISSUE TITLE
T23 Spotlight Location Comparison

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#366]
Design: http://development-initiatives.surge.sh/page-templates/23-spotlight-location-comparison

---

This page is to satisfy the user need where a user will want to compare two or more geographical areas in one indicator:

> As a user I would like to view `indicator` for `location` and `location`.

For example. I would like to view Poverty Headcount for Bungoma and Kisumu.

This may be extended to more than one indicator, and more than two locations if possible. 

It is a separate page as it doesn't fit the model of the country spotlight page. 

Sketch: https://marvelapp.com/d36178e/screen/63238266

Module by module: 

**Locations bar**

We have a link to 'add another location' - this then brings up the location menu from the Spotlights design. 

Once selected the location is added to a list of locations. Each of the location has a `X` button to remove it from the list. 

**Charts**

For each indicator added a chart appears. The chart has:

1. Indicator dropdown. Indicator dropdowns should use Select 2 to manage the hierarchy: https://select2.org/appearance#example. I will have a complete list of indicators for this available as JSON.

2. Chart - Simple D3 chart of indicator value over time or each of the selected locations.

**Add an indicator**

A button that puts a new Chart section in place for you to select an indicator to display on. This should default to a blank chart with a call to action in the select box to "Choose an indicator to display".

**Comment by benjamincoleman** [comment]
Initial sketch here: https://marvelapp.com/d36178e/screen/63238266

**Comment by benjamincoleman** [comment]
@BenDarby I've updated the spotlight location comparison sketch with a mobile version: https://marvelapp.com/d36178e/screen/64488651

**Comment by benjamincoleman** [comment]
Changes: 

* [  ]  Remove `indicator` from the title

* [  ] `add another section` should be `add another location` at the bottom

**Comment by benjamincoleman** [comment]
Sketch here: https://marvelapp.com/d36178e/screen/65882704

Videos will show you how this works:

Location comparison - https://www.dropbox.com/s/hhg710u7818kqcs/di-spotlights-location-comparison.mp4

Location comparison on mobile - https://www.dropbox.com/s/edeuheg3o7v27n1/di-spotlights-location-comparison-mobile.mp4

---

Checklist of changes:

- [ ] Add location button now shows the bar from the Spotlight for location selection (From the prototype I did)
- [ ] Indicator selection now has the two selects - `topics` and `indicators`

**Comment by BenDarby** [comment]
@benjamincoleman I've updated the titles and added the additional titles and form fields

**Comment by benjamincoleman** [comment]
@BenDarby can we get the right content into the topic and indicator dropdowns on this template please? 

![Screenshot 2020-02-05 at 10 41 57](https://user-images.githubusercontent.com/64877/73834786-3d13d380-4804-11ea-8497-98d48b8c4603.png)

Also the compare button has gone rogue!

![Screenshot 2020-02-05 at 10 42 57](https://user-images.githubusercontent.com/64877/73834828-5026a380-4804-11ea-8b80-c6114223975f.png)

**Comment by BenDarby** [comment]
@benjamincoleman fixed button placement and updated content in select fields

**Comment by urlsangel** [comment]
@BenDarby @benjamincoleman 

The buttons location buttons overlap with the compare button on iPad landscape orientation:

![Screenshot 2020-02-06 at 16 02 33](https://user-images.githubusercontent.com/560463/73955007-92321100-48fa-11ea-8f38-1a357d9fda81.png)

**Comment by urlsangel** [comment]
@BenDarby @benjamincoleman

IE11 / Win 10: Update button misaligned at medium width:

![Screenshot 2020-02-07 at 09 56 32](https://user-images.githubusercontent.com/560463/74019881-4df15000-4990-11ea-9374-bf8da2a4eb37.png)

**Comment by BenDarby** [comment]
Bugs above have been addressed

**Comment by benjamincoleman** [comment]
@BenDarby some design edits for you

the "add a location" interaction needs some changes, essentially to preserve the split on two lines as seen in the sketch. The design has this all in one row which causes issues: 

<img width="1213" alt="Screenshot 2020-03-09 at 14 02 28" src="https://user-images.githubusercontent.com/64877/76220104-d0c72e00-620e-11ea-99df-7670a58d1942.png">

On the Sketch I've updated it a little. 

We lead with this first design which is what you would see from first loading a screen when it might have no locations: https://marvelapp.com/d36178e/screen/67063698

Once a user hits the "add a location" button it is replaced with the select/search country module from the spotlights. Note this should all appear on it's own line - https://marvelapp.com/d36178e/screen/65882705

When a selection has been made you'll see locations appear on the line below: https://marvelapp.com/d36178e/screen/65882708

You can also see this on a mobile version: https://marvelapp.com/d36178e/screen/65883870

Updated sketches are all interactive so you can see what is happening. I've also done a quick video for you to see how this works: 

https://cloudup.com/cCJTjSKfr3R

**Comment by BenDarby** [comment]
@benjamincoleman I have updated this template on surge http://development-initiatives.surge.sh/page-templates/23-spotlight-location-comparison

The style of locations has changed to be less dominant, removing the background colour on the icon and changing the colour to grey has helped. I also added a lot more to fix any issues with wrapping. 

The add location functionality has been added with a little js to show how it works now too :)

**Comment by benjamincoleman** [comment]
@BenDarby can we avoid the jump in height when we swap between the "add location" button and the country selection modules please?

**Comment by BenDarby** [comment]
@benjamincoleman I added some padding to the add location button so the height matches the country lists, this as solved the height jumping issue
