### ISSUE TITLE
T22 Spotlight on Country

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#367]
Design: http://development-initiatives.surge.sh/page-templates/22-spotlight

---

**Development Notes:**

Some notes on some of the less obvious things we have going on here: 

1. the CSS for this template comes from `spotlights.min.css`, rather than the master `screen.min.css` used for the DI website. 

2. we're using the JavaScript file from `app.bundle.js` but we could take the functions we use out of there into another JavaScript file. The functions we use specifically for the Spotlight (and #366)  are: 

- `countryNav.js` - for the Country Nav element
- `countrySearch.js` - for the Country Search element
- `showHide.js` - used for the Show More button on the indicator comparison module

3. We have a section of the sidebar repeated in the DOM (HTML structure). This is so we can show it in different places depending on whether we are on a small screen, or large screen. You can see this in the screenshot below, where on mobile we have the key appearing below the map, but on large screens it appears in the sidebar. 

![Screenshot 2020-02-05 at 10 27 52](https://user-images.githubusercontent.com/64877/73833630-31bfa880-4802-11ea-9367-6efdb95e0e1c.png)

4. The Country Search works by filtering the elements shown in the Country Nav.

5. The Indicator comparison element has a load of `lorem ipsum` in there to give it some vertical height - this allowed us to implement a Show more / Show less button. The Show More button has two data attributes which control the text of that button as it changes state.

That's it - please do get in touch if you need anything -  @BenDarby and I are on Slack all the time and happy to help. 

---

Rethinking the spotlight view you can see on these two pages:

- Spotlight on Uganda: http://data.devinit.org/spotlight-on-uganda
- Spotlight on Kenya: http://data.devinit.org/spotlight-on-kenya

Sketches: 
- Desktop: https://marvelapp.com/d36178e/screen/63190028
- Mobile: https://marvelapp.com/d36178e/screen/64490724

Parts of this: 

**Map**

The map has different backgrounds / shades that are selectable using the 'Map type' button in the top right corner. This reveals a small menu (https://marvelapp.com/d36178e/screen/63783999). 

You able to select different indicators here and view shading to quickly see what is going on where. The map zones themselves are colour coded to show information about those zones according to the indicator selected. Indicator dropdowns should use Select 2 to manage the hierarchy: https://select2.org/appearance#example. I will have a complete list of indicators for this available as JSON.

You can zoom into one of the zones, and this then takes you to a new page view (could just AJAX load) about that zone, and the zones that make it up e.g. https://marvelapp.com/d36178e/screen/63786437

On the left we have a button on the title of the current view which opens a menu to also allow you to navigate through the constituent zones of the map. The menu system that I've found closest to it is this one: https://mmenujs.com/docs/. I have content for this menu and will try and produce a JSON file to populate it with. 

On the left side of the map area there are two buttons:

1. Sharing - opens a modal for sharing the current view. This actually is the same thing as is in place on the Spotlights at the moment

2. Compare this location to others - links to another page

For the design of this we'll want to have a `<div id="map"></div>` for the map to run in. @BenDarby you'll need to set that div up to be the right size etc. 

**Overview**

Summaries across:
- Overview
- Poverty
- Population
- Education
- Health
- Agriculture
- Climate change

This list will grow so make it able to expand - might want to think about a different configuration of tabs, so please don't feel beholden to what I've put here. It could also be something like this: https://codepen.io/madvic/pen/MOyqEg

The content here is from the original - I'm not sure whether it is useful or not, and have no information to steer me on this. You can find real content here: http://data.devinit.org/uganda/serere

**Indicator comparison**

This is new, and the big addition. It allows you to compare two indicators for the selected area. This works by comparing two indicators for the area you have selected, but also the sub-areas. 

You are able to check this over time as well with the timeline control for each indicator as the data is collected every few years. Moving the timeline would change which year of data the chart displays. 

The constituencies view also is able to be sorted - so this replaces the 'top 10 / bottom 10' lists on the current design. You can sort by A-Z, or by indicator high to low, so we might need up and down arrows to indicate order. 

~~I'd like feedback on the choice of charts here - if there's a better way of spotting trends / relationships I'd like to know. ~~

~~One issue with this at the country level, is that Kenya as 112 constituencies.~~

**Revenue**

Reworked the design to bring the timeline out of the chart, as I think users would not spot that the chart on the left controls time in the current design. Also as we have a timeline in other areas, it's important to keep controls consistent. 

As you change the timeline the light blue bar moves on the chart on the left to highlight current year. The treemap (chart with squares) works as it does at the moment. If it's possible to split data further we should.

**Expenditure**

As with revenue, I've reworked the design. 

The key thing here is we really want to split the data down further - this came from the research. 

**Data and sources**

We need to re-inforce that this is trustworthy data in the content here. 

I've included links to a page to talk about the methodologies used to expand on this, and also to downloads of the data. I'm not 100% sure where this data would be, but if it's the data section of the DI site we will want to include a 5th taxonomy to group this data together.

**Comment by benjamincoleman** [comment]
@BenDarby I've updated the spotlight sketches with a mobile version: https://marvelapp.com/d36178e/screen/64490724

**Comment by benjamincoleman** [comment]
Changes to do: 

* [ ] We want to re-introduce the tabs to the map, as you see in the current spotlights (http://data.devinit.org/spotlight-on-uganda) so that the list of indicators is broken up into a more easy to navigate way. 

* [ ] Change `Overview for {{ location }}` to `Key facts for {{ location }}`

* [ ] Change `Indicator comparison` to `Compare indicators`

* [ ] Seperate the `Revenue and Expenditure` section from the previous section - diff background colour

* [ ] Title for this section? ← try this out

* [ ] Introduce each as `xxx for {{ location }}`

**Comment by benjamincoleman** [comment]
@BenDarby I've updated the sketches: 

You can also view them on Marvel here: https://marvelapp.com/d36178e/screen/65846309

Here's some walkthrough videos you should watch so you're aware of how they work: 

Spotlights and how they work - https://www.dropbox.com/s/ok60ac1cwipy3zj/di-spotlights.mp4?dl=0

Spotlights on mobile - https://www.dropbox.com/s/7vrvk0mot641a47/di-spotlights-mobile.mp4?dl=0

Location comparison - https://www.dropbox.com/s/hhg710u7818kqcs/di-spotlights-location-comparison…

Location comparison on mobile - https://www.dropbox.com/s/edeuheg3o7v27n1/di-spotlights-location-comparison…

**Comment by BenDarby** [comment]
@benjamincoleman I have added the menu prototype you did to the pattern library and just updated the colors a little, so they are in line with the DI site, I also positioned the elements so they're matching the sketch. 
I updated the headings across the template and included the extra form fields where needed, the sketch didn't mention select2 so I commented it out for now and used a standard select field. 
The sketch has a few elements in a different order on the mobile, this will require us to move elements in the dom. Is this a good thing to do as it relies on JS or duplicating elements in the HTML and showing / hiding with css.

**Comment by benjamincoleman** [comment]
@BenDarby Ok, I have some feedback:

The top level location navigation should be distinct / seperate from the map - it controls the whole page - this is why I gave it a seperate background in the sketch. 

<img width="1263" alt="Screenshot 2020-02-03 at 14 57 32" src="https://user-images.githubusercontent.com/64877/73729349-c8ba3100-472c-11ea-9a98-5edc32e149ab.png">

The buttons should be below the key in the sidebar: 

<img width="390" alt="Screenshot 2020-02-03 at 14 58 05" src="https://user-images.githubusercontent.com/64877/73729376-d40d5c80-472c-11ea-9c31-c119c0514449.png">

Still seeing some orange highlighting in the dropdown menu - is this DI colours? You can find the colour definitions that need updating at the top of `_gnr-countries-block.scss`.

<img width="244" alt="Screenshot 2020-02-03 at 14 57 25" src="https://user-images.githubusercontent.com/64877/73729585-37978a00-472d-11ea-80e8-fd0a208c72a7.png">

Similarly, we have multiple different colours in user here, and could do with simplifying to a scale of similar colours with a stand out one for an active state.

<img width="349" alt="Screenshot 2020-02-03 at 14 57 18" src="https://user-images.githubusercontent.com/64877/73729658-59910c80-472d-11ea-83b9-3f46f7e3e388.png">

**Comment by BenDarby** [comment]
@benjamincoleman I've pushed some updates to surge. I duplicated the map element in the sidebar to show/hide it with CSS for mobile, the colors we're using DI, it was their orange color but I changed it to the red as it's their primary color. The country list is now using shades of the dark grey and the red is for the active class, but when you first open the menu the active class is being applied to all the first level items so that's why they're appearing red, JS thing? 
I also added a slightly different background color for alternating sections to help distinguish them.

**Comment by benjamincoleman** [comment]
@BenDarby Let's not duplicate the map - that's a really complex element. Best to duplicate either the dropdowns in the sidebar, or the content that comes below it.

**Comment by benjamincoleman** [comment]
@BenDarby ok, looking at the accordion on mobile, can we have an icon to indicate that it is in fact an accordion? 

Also, can we move from 3 cols in desktop, to 2 cols then 1 col. When we snap to 1 col at 849px wide it could really be 2 and we'd avoid the images / interactives being massive. Imagine if each col had an interactive - it would be really long.

<img width="808" alt="Screenshot 2020-02-04 at 11 16 54" src="https://user-images.githubusercontent.com/64877/73740430-19875500-4740-11ea-8c43-a9fe61799ecf.png">

**Comment by benjamincoleman** [comment]
Another issue: 

Show more button should be horizontally centred  - needs a negative left margin to pull it back onto the centre. 

<img width="808" alt="Screenshot 2020-02-04 at 11 19 44" src="https://user-images.githubusercontent.com/64877/73740642-73881a80-4740-11ea-9ca9-bba837f94c93.png">


On this piece as well, we could use a class on the interactive to limit its height. Then I can add some JS to the Show More button to get it working.

**Comment by benjamincoleman** [comment]
Can you also update the selects to use the right content? 

We should have in the first one the 'topics':

- Poverty and vulnerability
- Population
- Education
- Health
- Water and sanitation
- District public resources
- Agriculture
- Climate Change

You should be able to use the model `indicators` to do this by reading out the `group_name` for them. 

Then for the 'Indicator' dropdown you can have the first group's content: 

- Poverty headcount
- Decent standard of living score
- Life expectancy
- Population with a disability (%)
- Population with a hearing disability (%)
- Population with a remembering disability (%)
- Population with a seeing disability (%)
- Population with a walking disability (%)
- Children ever married as a % of total child population
- Male children ever married as a % of total child population
- Female children ever married as a % of total child population
- Households receiving remittances (%)
- Households using electricity for cooking (%)
- Households using charcoal for cooking (%)
- Households using firewood for cooking (%)
- Households using gas for cooking (%)
- Households using a paraffin stove for cooking (%)
- Households using electricity for lighting (%)
- Households using a paraffin lantern for lighting (%)
- Households using gas for lighting (%)
- Households using candles for lighting (%)
- Households using a paraffin tadooba for lighting (%)
- Households using firewood for lighting (%)

Again, you should be able to use the model `indicators` to do this

**Comment by BenDarby** [comment]
@benjamincoleman I've made the above amends. Tabs got to 2 then 3 columns, added an arrow icon when it's an accordion and fixed the button centering. I also updated the selects to use the correct content.

**Comment by urlsangel** [comment]
@BenDarby @benjamincoleman 

The search functionality could do with optimising/refactoring. The DOM tree that it's searching through is a lot bigger than the GNR CNP one, and it's making my fairly decent MacBook Air hang quite significantly.

**Comment by urlsangel** [comment]
@BenDarby @benjamincoleman 

Edge / Win 10: the topic/indicator sidebar displays with a scrollbar:

![Screenshot 2020-02-07 at 09 31 27](https://user-images.githubusercontent.com/560463/74018014-0f0dcb00-498d-11ea-9bc0-da2f667ca73f.png)

**Comment by urlsangel** [comment]
@BenDarby @benjamincoleman

Edge / Win 10: locations display with a scrollbar:

![Screenshot 2020-02-07 at 09 53 47](https://user-images.githubusercontent.com/560463/74019603-d6232580-498f-11ea-8b67-7f8cdeb81c8e.png)

**Comment by urlsangel** [comment]
@BenDarby @benjamincoleman

IE11 / Win 10: show more button cut off at narrow width:

![Screenshot 2020-02-07 at 10 02 46](https://user-images.githubusercontent.com/560463/74020244-120aba80-4991-11ea-90b1-310fb5a3b65f.png)

**Comment by urlsangel** [comment]
@BenDarby @benjamincoleman

Firefox / Win 10: nested menu displays with a scrollbar:

![Screenshot 2020-02-07 at 10 10 07](https://user-images.githubusercontent.com/560463/74020736-1aafc080-4992-11ea-86e4-74b028e532f3.png)

**Comment by BenDarby** [comment]
@urlsangel I can hide the scrollbar when the menu opens but as soon as you scroll it appears, we have an `overflow-y:` scroll; set on this element to control the height as the menu us really long.

**Comment by urlsangel** [comment]
> @urlsangel I can hide the scrollbar when the menu opens but as soon as you scroll it appears, we have an `overflow-y:` scroll; set on this element to control the height as the menu us really long.

@BenDarby I flagged this as it looked different from Mac browsers - if it's unavoidable then I guess that's just Windows :-)

**Comment by benjamincoleman** [comment]
@BenDarby how about `overflow: auto` - would that have it appear only when needed?

**Comment by BenDarby** [comment]
> @BenDarby how about `overflow: auto` - would that have it appear only when needed?

Nope but I've set to appear only when needed now with `-ms-overflow-style: -ms-autohiding-scrollbar;`

**Comment by BenDarby** [comment]
Bugs above have been addressed :)

**Comment by benjamincoleman** [comment]
@BenDarby can you update the tabs so that: 

1. Some of them dont have the currency select box

2. The currency select box is not 100% width

<img width="1304" alt="Screenshot 2020-02-26 at 16 17 47" src="https://user-images.githubusercontent.com/64877/75365077-97a8c880-58b4-11ea-9486-206f8083b2a1.png">

**Comment by BenDarby** [comment]
@benjamincoleman I've updated the tabs, the current `select` only appears where the money is referenced also I have kept the select 100% on small screens but not on medium and above. PL has been updated on surge as well

**Comment by benjamincoleman** [comment]
@BenDarby good man, that's perfect
