### ISSUE TITLE
T20 Contact

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#37]
https://marvelapp.com/3j51290/screen/57853952

Included a contact form, email address, locations, and specifics on registered addresses.

I've left some post-it notes on the sketches for specific questions. 

Design: http://development-initiatives.surge.sh/page-templates/20-contact

Functional specification: 

This template has a simplified hero, which uses the fallback hero design where there is no image. 

Under the hero we have standard page content

Above the form we have elements show the success / error messages for this template. 

Contact form, which has the following fields: 
- Name
- Organisation (optional)
- Email
- Telephone (optional)
- Message

**Comment by k8hughes** [comment]
http://178.128.102.213/contact-us/ 

LGTM

**Comment by k8hughes** [comment]
@benjamincoleman for the point about repeat addresses, as this is how the design appear in the pattern library I think this is one for you?

**Comment by benjamincoleman** [comment]
So it's entirely deliberate that they are repeated - as there are essentially two organisations with two official "registered addresses". I'd keep it in as it's been reviewed and approved prior to this.

**Comment by alice-mcandrew-development-initatives** [comment]
@benjamincoleman Pk, thanks,, let's leave for now and check-in with Anna when's back.
@k8hughes Are the other issues something Alex or Edwin can take care of?
