### ISSUE TITLE
Text not editable on 'our story' page that needs to be

### ISSUE THREAD

**Issue by AnnaHope** [devinit/DIwebsite-redesign#378]
Hi guys,

just spotted a subheading that says 'DI has achieved much over the last 20 years' that isn't editable in the cms. Obviously this is an issue because it is actually over 25 years and that will change every year so needs to be something we can update.

http://159.65.56.142/who-we-are/our-story/

![image](https://user-images.githubusercontent.com/16958942/68686031-e713f480-0562-11ea-8130-6f380f57c6de.png)

@edwinmp @Napho @akmiller01

**Comment by akmiller01** [comment]
Coded up @AnnaHope but this is a pretty extensive change to the structure of the Carousel. This will probably erase the Carousel content you've added so far, so if you have some way of writing it down outside of the CMS please do:

https://github.com/devinit/DIwebsite-redesign/pull/382

**Comment by k8hughes** [comment]
@akmiller01 this is in code review but there are no awaiting PR's, has this been completed.

**Comment by akmiller01** [comment]
The numbers in the text are PRs. You can see the tagged one above #382 which got merged. This should be in deploy to staging.

**Comment by k8hughes** [comment]
I can see the fields in the CMS now, so I think it is correct.
