### ISSUE TITLE
Footer quick links not showing in the order specified in the cms

### ISSUE THREAD

**Issue by AnnaHope** [devinit/DIwebsite-redesign#380]
Hey @akmiller01 !

Just went to add these in, and the CMS seems to suggest they should go in the order to appear as it allows you to reorder via arrows, yet they aren't appearing the way they have been made in the cms. So the hierarchy is currently wrong. It appears as this:

![image](https://user-images.githubusercontent.com/16958942/68688648-10cf1a80-0567-11ea-855a-e21677507ccb.png)

But I want it to be:

![image](https://user-images.githubusercontent.com/16958942/68688683-23495400-0567-11ea-8f04-9bacf1cbf563.png)

**Comment by akmiller01** [comment]
Quick fix here: https://github.com/devinit/DIwebsite-redesign/pull/381 Just needed to sort them by `sort_order`

**Comment by akmiller01** [comment]
Hey @riahasler-DI what's up with this issue? It looks like someone deleted all of the footer sections from staging? http://178.128.102.213/admin/snippets/home/footersection/

**Comment by riahasler-DI** [comment]
@akmiller01 I accidentally moved this to done by closing the issue, then moved it back to Comms Review as I wanted to check with Anna that the issue had been fixed.

**Comment by alice-mcandrew-development-initatives** [comment]
@riahasler-DI It looks done to me so I'm going to close
