### ISSUE TITLE
Geography drop down on datasets

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/DIwebsite-redesign#391]
Unsure what this is linked to and no results are being returned. Can edit one of the Google doc columns to align naming, if necessary.

**Comment by Duncan-Knox** [comment]
Have tidied content in columns 'Geography information' to state country name, global or region name.

**Comment by akmiller01** [comment]
So the XLSX spreadsheet drives the Geography metadata section on each page. But the actual dropdown is driven by the CMS only.
