### ISSUE TITLE
T9: Services

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#4]
Sketch: https://marvelapp.com/3j51290/screen/57566897

Design: http://development-initiatives.surge.sh/page-templates/09-consultancy-services

![image](https://gitlab.com/the-b-team/development-initiatives-website/uploads/8b9beff3f149bd6ac57839cb8d7dc2c0/image.png)

Functional Specification: 

**Hero**

Standard with: 

- Image
- Image credit (capable of having a link in it)
- Title
- Subtitle

**Content**

Standard content with a rich text editor follows the hero. 

**We specialise in**

A list of specialisms, for each we show: 

- Image
- Title
- Rich text content

**Our skills**

Uses the accordion pattern we use on template #8 What we do

For each accordion we have: 

- Title
- Rich text content

**News**

Here we are able to pull in three news items that are used to announce consultancy contracts. This could be controlled from this page by nominating 3, or could be done with some sort of taxonomy / option on the news items themselves.

**Examples of our work**

These are pages that sit underneath this page and use template T1. They would be listed here, and we want to be able to filter them by `service-type`. 

<img width="612" alt="Screen Shot 2019-08-27 at 14 07 28" src="https://user-images.githubusercontent.com/64877/63774068-5bc88280-c8d4-11e9-89df-ad54c145f59b.png">

For each example we would show the title linked to the page where this example is. 

**Our principles / How we work**

Sit side by side and would have 

- Title - in case the names change
- Rich text content

**Call to action module**

- Image
- Image credit (capable of having a link in it)
- Module title
- Module content - rich text so can include links

**Comment by benjamincoleman** [comment]
Remove focus areas and replace with offering.

What are the services you offer? ← Content - https://devinitorg.slack.com/archives/DDG7H1QMR/p1563889992000700

* Data science
* Data analysis

Will be the same as the taxonomy in examples of our work

**Comment by benjamincoleman** [comment]
New sketch for this template: https://marvelapp.com/3j51290/screen/57566897

**Comment by benjamincoleman** [comment]
@BenDarby Looks good but can you use a non-DI person image here please? Emily from the team page is the one.

**Comment by benjamincoleman** [comment]
@BenDarby 

Specialisms would not be linked anywhere. 

Related content -  should have the title "news", no intro, and the elements should just be news items, rather than a mix. Sorry, my sketch wasn't right here, I've updated it: https://marvelapp.com/3j51290/screen/57566897

**Comment by benjamincoleman** [comment]
@BenDarby 

> can this page be 'Consultancy services' as we offer other services and this only speaks to consultancy

We have this in the titles etc, but can you do it for the template too? 

> and then the icons in the examples of our work need to be removed because it indicates they link to documents and you confirmed with me last week that they go to pages

I think this is valid - the icon is a document icon, where in fact it will link to a page.

**Comment by benjamincoleman** [comment]
@BenDarby 

Looking at this piece: 

![Screen Shot 2019-08-01 at 13 34 54](https://user-images.githubusercontent.com/64877/62293760-31181500-b461-11e9-8df4-6928745cc729.png)

We wantt o eep the content, so for each we have image, title, text, but they are not clickable, so we'd like the design to be different to the clickable cards on blog listing for example. 

Very similar (but with paragraphs) to #8

**Comment by benjamincoleman** [comment]
> Again these feel clickable. Because we don’t have a separate section for the specialisms in the same way as focus areas, we do need more text here, so what could work well is to use the design from the focus areas page. Having the image small and top left allows the text to be more prominent and crucially to have a lot more text there, which we will need given that we need to say literally everything on this page about our specialisms. Having the much smaller image removes that feeling of clickability I think. 

<img width="552" alt="Screen Shot 2019-08-02 at 10 52 58" src="https://user-images.githubusercontent.com/64877/62361842-b65c0200-b513-11e9-92e5-5c41c9f6fb36.png">

**Comment by benjamincoleman** [comment]
@BenDarby missing the overflowing image - overflow is hidden on .project

![Screen Shot 2019-08-06 at 11 16 26](https://user-images.githubusercontent.com/64877/62532153-b1f95700-b83b-11e9-8b75-9c4e71de6273.png)

**Comment by akmiller01** [comment]
Direction from Anna, she wants the skills section here to be independent:

Hi guys, working on the website content and I've realised that having the 'our skills' section on the 'what we do' page also pulling through to the 'consultancy services' page doesn't work, because while our skills are the same, the way we describe them is very different for potential clients
I know it isn't in what Ben gave you, but is it possible to build that bit of the consultancy services page so it is separate and manually editable, rather than a copy of the what we do page?

**Comment by k8hughes** [comment]
I am blocked from buiulding this page till the parent page (07) has been built.

**Comment by k8hughes** [comment]
http://178.128.102.213/what-we-do/consultancy-services/ 
I currently get a value error and the page I have built doesn't show  

![Screenshot 2019-09-25 at 09 42 51](https://user-images.githubusercontent.com/36768381/65584498-e5717b80-df78-11e9-93b9-f26f12c5acb1.png)

**Comment by edwinmp** [comment]
@k8hughes this should now be fixed

**Comment by k8hughes** [comment]
LGTM.

**Comment by alice-mcandrew-development-initatives** [comment]
@k8hughes this seems fine (but I'll confirm when all content is uploaded)
