### ISSUE TITLE
Map default view in what we do, 'where we work' subsection needs to be more zoomed in

### ISSUE THREAD

**Issue by AnnaHope** [devinit/DIwebsite-redesign#400]
Hey @edwinmp! Sorry to be a pain, but now we are putting countries in, we've noticed that the level of zoom and the area covered as the default in the map in the what we do page under the where we work subsection doesn't look right. Can it be changed from what it is now to reflect the level of zoom and also positioning show in the second image below?:

What it is now:
![image](https://user-images.githubusercontent.com/16958942/68950524-3dc43d00-07b4-11ea-86f9-430c1032e798.png)

What we want it to be:

![image](https://user-images.githubusercontent.com/16958942/68950585-57fe1b00-07b4-11ea-9f42-a7d145448efb.png)

**Comment by akmiller01** [comment]
This may be something for cross-browser testing @benjamincoleman and @AnnaHope 

My default view looks like your desired one 
![image](https://user-images.githubusercontent.com/2836840/68951414-faee6f00-078b-11ea-9030-0d2eca0d0cef.png)

**Comment by edwinmp** [comment]
Mine too... the current configuration is set to automatically adjust the zoom level to show all the available markers without zooming in or out too much... if we hardcode a zoom level, it'll likely break this.

**Comment by edwinmp** [comment]
I've tested this page on Chrome, Safari and Firefox with identical results.

**Comment by akmiller01** [comment]
My bet would be that it's highly dependent on screen resolution at time of load @edwinmp

**Comment by akmiller01** [comment]
It's particularly bad when screen height is larger than screen width. Seen here testing in iPad resolution: 
![image](https://user-images.githubusercontent.com/2836840/68952017-22920700-078d-11ea-89fd-1bc6e52c1e95.png)

**Comment by edwinmp** [comment]
Ah, right ... still, I don't think that can be helped... the next zoom level would cut out one of the markers.

**Comment by k8hughes** [comment]
Does this mean we should close this image as soething we can't improve? @edwinmp @akmiller01

**Comment by akmiller01** [comment]
If it's improvable, it would be with @benjamincoleman

**Comment by AnnaHope** [comment]
@benjamincoleman can you help? It really doesn't look good with current zoom levels...feels like it must be an easy one to fix?

**Comment by k8hughes** [comment]
@benjamincoleman I don't know if this issue is on your radar.  Above is a question fro Anna.  It would be good to know if we should keep this open or close it.

**Comment by benjamincoleman** [comment]
@AnnaHope @k8hughes 

As @edwinmp pointed out, the code is set to zoom to be able to view all markers drawn on the map. This uses a built in function `fitBounds` which we cannot change. 

However, we can adjust the window I think to help by forcing a minimum height of around 350px to improve things a little perhaps. 

This really breaks down at mobile level, in which case I think we should only load the map, and content that talks about the map, on screens above a certain size, say 500px. 

We'll have a look at this and see what we can do to improve things.

**Comment by benjamincoleman** [comment]
Note to self in case we want to make it conditional: 

```if ($(window).width() < 960) {
   alert('Less than 960');
}
else {
   alert('More than 960');
}
```
