### ISSUE TITLE
Change mannequin icon to quote icon

### ISSUE THREAD

**Issue by jamesharle** [devinit/DIwebsite-redesign#401]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
On the data page, the quote we've selected appears next to an icon of a mannequin because we don't have an image of the person being quoted. In such instances, can we please have the below quotation icon appear instead of a mannequin? This way it will not look incomplete.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to '/data'
2. Scroll down
3. See error

**Expected Behaviour**
A clear and concise description of what you expected to happen

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: dd/MMM/YYYY

**Comment by jamesharle** [comment]
Sorry, should have added the suggested new icon. It's this: 
![quotes-01](https://user-images.githubusercontent.com/43270042/68954011-07d68700-07bb-11ea-8685-7ae044b79bfc.png)

**Comment by akmiller01** [comment]
@jamesharle you can upload that image of the quote under this field:

![image](https://user-images.githubusercontent.com/2836840/68956234-a64ff180-0795-11ea-8355-fb3cddfa881c.png)

If you want to hardcode the quote image as a default, we need to ask @benjamincoleman to include it in the pattern library.

**Comment by jamesharle** [comment]
@akmiller01 Yeah, imo this would be worth doing - it will always be more appropriate to have this pull through for quotes with no image than the mannequin.

**Comment by akmiller01** [comment]
@benjamincoleman would it be easy to include this in the pattern library? Otherwise we could try and store it in static elsewhere, but keeping the pattern library as the primary source of stock images would be nice.

**Comment by k8hughes** [comment]
@benjamincoleman  @BenDarby ^^ Can this be added to the pattern library?

**Comment by BenDarby** [comment]
@akmiller01 @k8hughes I've added this to the pattern library which can be seen here http://development-initiatives.surge.sh/page-templates/21-data-section Is this what you had in mind?

**Comment by akmiller01** [comment]
Sure, that works @BenDarby . We just need to code it into the relevant places. I was going to suggest replacing `profile-fallback.png` with it, but I guess in some cases we'll want the mannequin and in some cases we'll want the quote.

**Comment by akmiller01** [comment]
Incorporated here: https://github.com/devinit/DIwebsite-redesign/pull/656

**Comment by edwinmp** [comment]
![image](https://user-images.githubusercontent.com/5672438/81694248-c709b300-9469-11ea-81c1-28b6dfebd97b.png)
