### ISSUE TITLE
Column count for addresses on Who We Are page

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#410]
http://159.65.56.142/who-we-are/

We have 3 addresses at the moment, so the parent class `l-4up` should actually be `l-3up`.

Applies to this module: 

![Screen Shot 2019-11-18 at 11 47 19](https://user-images.githubusercontent.com/64877/69050094-3772d280-09f9-11ea-95e0-51cbe30cc445.png)

**Comment by akmiller01** [comment]
How high do the column counts go @benjamincoleman ? Is 4 the maximum? We could write template tag that outputs the class as l-1up through l-4up depending on the length of the number of offices...

**Comment by k8hughes** [comment]
LGTM.
