### ISSUE TITLE
Consultancy module uses wrong title style

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#418]
http://159.65.56.142/what-we-do/

![Screen Shot 2019-11-18 at 12 03 05](https://user-images.githubusercontent.com/64877/69051176-74d85f80-09fb-11ea-884e-69e861d2b7bd.png)

It should look like this: 

![Screen Shot 2019-11-18 at 12 04 52](https://user-images.githubusercontent.com/64877/69051234-a94c1b80-09fb-11ea-8130-398b5035542c.png)

as seen in the pattern library - http://development-initiatives.surge.sh/page-templates/07-what-we-do

**Comment by akmiller01** [comment]
@alice-mcandrew-development-initatives Could you use the heading box instead of creating a title in the RichText?

![image](https://user-images.githubusercontent.com/2836840/69078732-7d826300-0a06-11ea-8c2d-8e6cdb2862fe.png)

**Comment by alice-mcandrew-development-initatives** [comment]
Done :)
