### ISSUE TITLE
Pattern library testing

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#43]
## Issues 

Issue | Template | Browser | Proposed solution | Issue ref | Complete
----- | --------- | --------- | ------------------ | -------- |--------
~JS error `Cannot read property 'addEventListener' of null`~ | Multiple -  [Blog](http://development-initiatives.surge.sh/page-templates/11-blog-listing), [News](http://development-initiatives.surge.sh/page-templates/11a-news-listing), [Events](http://development-initiatives.surge.sh/page-templates/11b-events-listing) | Chrome/Mac | Fix the JS | | ✓
Horizontal scroll | Multiple -  [Blog](http://development-initiatives.surge.sh/page-templates/11-blog-listing), [News](http://development-initiatives.surge.sh/page-templates/11a-news-listing), [Events](http://development-initiatives.surge.sh/page-templates/11b-events-listing) | Safari/iPhone X/iOS 12.3.1 | Add `overflow-x:hidden` to `. pagecontent` element (looks like the fault of the `hero__flourish` elements) | 
~No focus ring on main navigation `<a>` tags~ | Global | Chrome/Mac |  |  | ✓
Keyboard focus lost in main navigation when mobile nav enabled | Global | Chrome/Mac |  | 
~Hero text overlaps or very close to side navigation at medium widths~ ![Screenshot 2019-06-18 at 10 16 45](https://user-images.githubusercontent.com/560463/59669679-90bca880-91b2-11e9-934c-839599f816a6.png) ![Screenshot 2019-06-18 at 10 17 08](https://user-images.githubusercontent.com/560463/59669704-a0d48800-91b2-11e9-9304-acf2549abb03.png) ![Screenshot 2019-06-18 at 10 30 23](https://user-images.githubusercontent.com/560463/59670620-21e04f00-91b4-11e9-8441-a982390cde0a.png) ![Screenshot 2019-06-18 at 10 43 37](https://user-images.githubusercontent.com/560463/59671702-07a77080-91b6-11e9-90d4-73aa94ee7c46.png) | [Events](http://development-initiatives.surge.sh/page-templates/11b-events-listing) / [News single](http://development-initiatives.surge.sh/page-templates/12a-news-single) / [Event single](http://development-initiatives.surge.sh/page-templates/12b-event-single) | Chrome/Mac / iPad |  |  | ✓
~Checkbox label wraps at narrow widths~ ![Screenshot 2019-06-18 at 10 49 44](https://user-images.githubusercontent.com/560463/59672482-789b5800-91b7-11e9-852d-04dbe4e57132.png) | [Vacancies](http://development-initiatives.surge.sh/page-templates/18-vacancy-listing) | Chrome/Mac / Chrome/Win 7 | | | ✓
~Misleading hand/link cursor on hover of download area, only 'PDF' and 'Doc' items are actually links~ ![Screenshot 2019-06-18 at 11 09 30](https://user-images.githubusercontent.com/560463/59673710-abdee680-91b9-11e9-9972-63b9875c5f76.png) | [Vacancy single](http://development-initiatives.surge.sh/page-templates/19-vacancy-single) | Chrome/Mac | | | ✓
~Navigation close to edge of container~ ![Screenshot 2019-06-18 at 12 03 16](https://user-images.githubusercontent.com/560463/59677269-5c9cb400-91c1-11e9-8292-32793dfbaead.png) | [News](http://development-initiatives.surge.sh/page-templates/11a-news-listing) | Firefox/Mac | | | ✓
Top checkboxes of non-first column not visible ![Screenshot 2019-06-18 at 12 17 26](https://user-images.githubusercontent.com/560463/59678012-32e48c80-91c3-11e9-800a-5aa88848a612.png) | [Vacancies](http://development-initiatives.surge.sh/page-templates/18-vacancy-listing) | Firefox/Mac / Firefox/Win 7 | | https://github.com/devinit/DIwebsite-redesign/issues/71 
Grid listing broken ![Screenshot 2019-06-18 at 14 08 52](https://user-images.githubusercontent.com/560463/59684833-bf4a7b80-91d2-11e9-9202-03eb50524d99.png) ![Screenshot 2019-06-18 at 14 14 37](https://user-images.githubusercontent.com/560463/59685195-8c54b780-91d3-11e9-850e-46ac1b706b06.png) ![Screenshot 2019-06-18 at 14 18 01](https://user-images.githubusercontent.com/560463/59685398-fb321080-91d3-11e9-903c-1031519a3378.png) ![Screenshot 2019-06-18 at 14 30 36](https://user-images.githubusercontent.com/560463/59688507-bc9d5580-91d5-11e9-9471-96091ec86fd1.png) | [Blog](http://development-initiatives.surge.sh/page-templates/11-blog-listing) / [News](http://development-initiatives.surge.sh/page-templates/11a-news-listing) / [Events](http://development-initiatives.surge.sh/page-templates/11b-events-listing) / [Vacancies](http://development-initiatives.surge.sh/page-templates/18-vacancy-listing) | Edge/Win 10 / IE11/Win 7 | | https://github.com/devinit/DIwebsite-redesign/issues/72 | 
Related content grid broken ![Screenshot 2019-06-18 at 14 22 00](https://user-images.githubusercontent.com/560463/59686758-90cda000-91d4-11e9-8e03-dd37f3b67556.png) | [Blog single](http://development-initiatives.surge.sh/page-templates/12-blog-single) / [News single](http://development-initiatives.surge.sh/page-templates/12a-news-single) / [Event single](http://development-initiatives.surge.sh/page-templates/12b-event-single) | Edge/Win 10 / IE11/Win 7 | | https://github.com/devinit/DIwebsite-redesign/issues/73 |
More about row not equal height ![Screenshot 2019-06-18 at 14 33 19](https://user-images.githubusercontent.com/560463/59688696-2584cd80-91d6-11e9-83ea-68384edd47e7.png) | [Vacancy single](http://development-initiatives.surge.sh/page-templates/19-vacancy-single) | Edge/Win 10 / IE11/Win 7 | | https://github.com/devinit/DIwebsite-redesign/issues/74 |

## Lighthouse audits
View with https://googlechrome.github.io/lighthouse/viewer/  
[DI lighthouse audits.zip](https://github.com/devinit/DIwebsite-redesign/files/3301136/DI.lighthouse.audits.zip)

**Comment by BenDarby** [comment]
Navigation menu has its focus ring back now
