### ISSUE TITLE
Favicon not configured correctly

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#432]
http://159.65.56.142/

Chrome/Mac

#### Favicon not configured correctly

Chrome displays default favicon.

![Screenshot 2019-11-18 at 14 19 17](https://user-images.githubusercontent.com/560463/69060008-82e3ab80-0a0e-11ea-862e-5fa9513727bd.png)

**Comment by k8hughes** [comment]
LGTM.
