### ISSUE TITLE
Metadata in <head> missing 

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#433]
http://159.65.56.142/

Chrome/Mac

#### Metadata in `<head>` missing 

Missing or incorrect metadata:

- Title/SEO title
- Meta description
- Social graph metadata and image, e.g. Facebook Opengraph/Twitter

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/468

**Comment by akmiller01** [comment]
Here now since Travis was refusing to clone the previous branch: https://github.com/devinit/DIwebsite-redesign/pull/469

**Comment by urlsangel** [comment]
@akmiller01 

It looks like this is issue is a work in progress? 

In case it's not, I'm still not seeing :

* `<meta name="description" content="...">`
* Facebook OG/Twitter metadata

**Comment by akmiller01** [comment]
Yep still in progress. responsiveimages caused a few CI errors so this branch wasn't passing

**Comment by urlsangel** [comment]
@akmiller01 

There's two `<title>` tags in the `<head>`, the second is likely the Wagtail Meta output.

Try adding `META_USE_TITLE_TAG = False` to `base.py`.

**Comment by akmiller01** [comment]
Just using wagtail-metadata without the django-meta, so I just had to overwrite their tags template: https://github.com/devinit/DIwebsite-redesign/pull/577
