### ISSUE TITLE
Missing robots.txt file

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#436]
http://159.65.56.142/robots.txt

Chrome/Mac

#### Missing robots.txt file

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/466

**Comment by urlsangel** [comment]
@akmiller01 @edwinmp 

Not sure if you'd be concerned or not, but I think your current implementation would leave non-www servers such as `dev` and `staging` indexable when serving the same `robots.txt` to all sites (although if password protected that shouldn't be an issue).

We serve different files on the GNR site to combat this:

https://github.com/devinit/gnr-website/blob/master/gnr/urls.py#L37

**Comment by akmiller01** [comment]
Good point! https://github.com/devinit/DIwebsite-redesign/pull/487

**Comment by k8hughes** [comment]
@akmiller01 I wouldn't know what is correct here.  Can you check and close if happy?

**Comment by akmiller01** [comment]
Yep, it's just this http://159.65.56.142/robots.txt
