### ISSUE TITLE
Adding more than one data download to legacy publication

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#437]
## I'm submitting a ...
[X] Bug report

**Describe the Issue**
We cannot add more than once data download to the bottom of this legacy publication page: http://159.65.56.142/admin/pages/986/edit/

**Screenshots/GIF**
![Data downloads](https://user-images.githubusercontent.com/55877063/69064213-b70e9a80-0a15-11ea-9845-c60fbacea0cd.png)

**Comment by akmiller01** [comment]
It's a weird holdover from the GNR website. Fixed here: https://github.com/devinit/DIwebsite-redesign/pull/439
