### ISSUE TITLE
Background hero image not responsive

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#438]
http://159.65.56.142/

Chrome/Mac

#### Background hero image not responsive

The background image served for the hero has no responsive implementation, meaning that the same image is served whether the user is viewing on a mobile, tablet, or desktop browser.

In the case of the homepage, the image being served is 1600 pixels wide `http://159.65.56.142//media/images/South_Sudan_2014.2e16d0ba.fill-1600x780-c100.jpg`, which has a file size of **538KB**. 

Whilst appropriate for a desktop visitor, it's likely that a file a fifth of the size or smaller could be served for a mobile device.

Also, the single background image implementation does not take into account differing pixel densities ("retina" screens) and serve appropriately targeted images.

For a working implementation of responsive and retina background images using scoped styles and unique ids, see: https://globalnutritionreport.org/reports/global-nutrition-report-2018/

**Comment by akmiller01** [comment]
Also fulfilled by https://github.com/devinit/DIwebsite-redesign/pull/465

**Comment by k8hughes** [comment]
LGTM.
