### ISSUE TITLE
Rogue <br> tag in hero title

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#440]
http://159.65.56.142/media-centre/

Chrome/Mac

#### Rogue `<br>` tag in hero title

Markup contains a `<br>` tag after the hero title, causing extra height of the hero element.

```
<div class="hero__content">
    <h1 class="hero__title">
    	<span>Media centre</span>
    </h1>
    <br>
</div>
```

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/464
