### ISSUE TITLE
Images not responsive

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#441]
http://159.65.56.142/media-centre/

Chrome/Mac

#### Images not responsive

Related to: #438 

Images served with the `img` tag do not utilise `scrset` for multiple image sizes targeted at different screen sizes/pixel densities.

As and example, the "Spokespeople" module serves an image that is 200 pixels wide, e.g. `/media/images/Harpinder-Collacott-e14507967.036e0088.fill-200x200-c100.jpg`.

This implementation does not take into account higher density displays ("retina) or differently sized screens.

Whilst this may not be too bad for this module, there will be other instances where the image served is not appropriate without using modern techniques such as `srcset` - either the image will be oversize for the screen (waste of user's bandwidth, slow downloading), or undersized (appearing blurry on the device).

For a working implementation of responsive `img` tags, see the hero image at https://globalnutritionreport.org/.

**Comment by akmiller01** [comment]
Generally replaced most instances of `{% image ...` with `{% responsiveimage ...` and a relevant global srcset. Is this what you had in mind @urlsangel ? https://github.com/devinit/DIwebsite-redesign/pull/465

**Comment by akmiller01** [comment]
Are responsive images a big server processing draw @urlsangel ? This page has maybe 70 images on it and it's timing out now that they've all been implemented as responsive... http://159.65.56.142/who-we-are/our-team/

**Comment by urlsangel** [comment]
> Generally replaced most instances of `{% image ...` with `{% responsiveimage ...` and a relevant global srcset. Is this what you had in mind @urlsangel ? #465

In general yes, although `srcset`s will usually work best if they the pattern library template is used to work out the various widths and viewport percentages required.

**Comment by urlsangel** [comment]
> Are responsive images a big server processing draw @urlsangel ? This page has maybe 70 images on it and it's timing out now that they've all been implemented as responsive... http://159.65.56.142/who-we-are/our-team/

It'll be the number of images x the number of `srcset` sources, so it may well time out on first run.

Once they're created that's it though, so it'll just be on new image additions which should be fine.

**Comment by urlsangel** [comment]
@akmiller01 

The Media Centre is a good example of where a generic `srcset` can cause problems - the images are cut off at desktop width:

![159 65 56 142_media-centre_ (1)](https://user-images.githubusercontent.com/560463/69136386-a9f3b900-0ab2-11ea-8684-9d16b769ab05.png)

**Comment by urlsangel** [comment]
Sorry @akmiller01 - more comments, I'll add them to this issue rather than creating new issues.

The following page templates have the `srcset` attribute on team member images, but no `srcset` content:

* [Our team](http://159.65.56.142/who-we-are/our-team/)
* [Team member](http://159.65.56.142/who-we-are/our-team/cecilia-caio/)

![Screenshot 2019-11-19 at 10 10 31](https://user-images.githubusercontent.com/560463/69137529-d90b2a00-0ab4-11ea-8fcd-9ff4cbe11de7.png)

**Comment by akmiller01** [comment]
Hm, I'm having trouble seeing any problem in our implementation. Any suggestions @urlsangel ?

```
{% load responsive %}
{% responsiveimage profile.image fill-400x400-c100 srcset=global.image_srcs as img %}
<img height="400px" width="400px" src="{{img.url}}" alt="{{img.alt}}" srcset="{{ image.srcset }}">
```

with `global.image_srcs` being:
```
'width-270 300w, width-370 400w, width-470 500w, width-750 780w, width-750 780w, width-800 800w'
```

**Comment by urlsangel** [comment]
@alex 

Yes, for `<img`> tags, just use the `responsiveimage` tag without capture as a variable:

```
{% load responsive %}
{% responsiveimage profile.image fill-400x400-c100 srcset=global.image_srcs alt=profile.image.title width='100%' height='auto' %}
```

**Comment by akmiller01** [comment]
Hopefully some better srcsets here: https://github.com/devinit/DIwebsite-redesign/pull/498

**Comment by k8hughes** [comment]
![Screenshot 2019-11-25 at 12 02 43](https://user-images.githubusercontent.com/36768381/69539005-84b3ee80-0f7b-11ea-8904-6cd4c41eadc8.png)

Now the images are responsive, but the names of people under the images are staying really wide.  
Where does this issue sit?  In the pattern library or in dev?

**Comment by edwinmp** [comment]
@k8hughes pattern lib

**Comment by k8hughes** [comment]
@benjamincoleman can you ask @BenDarby to check this for us please?

**Comment by BenDarby** [comment]
@k8hughes @edwinmp This looks like the dimensions of the images is too small, we have a max-width set to responsive images to they don't become oversized and pixelated. If you refer to the pattern library you can see the images spanning the same with as the names http://development-initiatives.surge.sh/page-templates/01d-media-center 

The dimensions I used for the PL are 600x600

I hope this is heplful
