### ISSUE TITLE
Pagination displayed even though there is only one page

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#442]
http://159.65.56.142/media-centre/

Chrome/Mac

#### Pagination displayed even though there is only one page

If there is only one page, displaying pagination is not required.

![Screenshot 2019-11-18 at 15 54 56](https://user-images.githubusercontent.com/560463/69068017-f93ada80-0a1b-11ea-984e-5d165bb8de26.png)

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/467

**Comment by k8hughes** [comment]
LGTM.
