### ISSUE TITLE
Different text output format for quotee in call out box

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#443]
http://159.65.56.142/who-we-are/

Chrome/Mac

#### Different text output format for quotee in call out box

The [pattern library](http://development-initiatives.surge.sh/page-templates/03-who-we-are) format for the quotee in the call out box is:

![Screenshot 2019-11-18 at 16 05 17](https://user-images.githubusercontent.com/560463/69068928-8894bd80-0a1d-11ea-873b-131611d541fe.png)

The [dev implementation](http://159.65.56.142/who-we-are/) is:

![Screenshot 2019-11-18 at 16 05 10](https://user-images.githubusercontent.com/560463/69068973-9b0ef700-0a1d-11ea-8b01-de456391559d.png)

**Comment by alice-mcandrew-development-initatives** [comment]
We prefer this without hyphens so are leaving it as it is :)
