### ISSUE TITLE
T5.1 Dynamic footer content

### ISSUE THREAD

**Issue by edwinmp** [devinit/DIwebsite-redesign#45]

**Comment by alice-mcandrew-development-initatives** [comment]
I created a snippet for the footer. Please can we change the colour of the hyperlink? I can't see an option for this at the moment.

At the moment it's red, which isn't legible:
![Footer hyperlink](https://user-images.githubusercontent.com/55877063/67576628-cfe9a000-f736-11e9-9886-8b3ba76a882c.JPG)

**Comment by akmiller01** [comment]
@BenDarby could you please change the colour of hyperlinks in the footer?

**Comment by akmiller01** [comment]
@benjamincoleman could you please look at the CSS for hyperlink colour?

**Comment by BenDarby** [comment]
@benjamincoleman @akmiller01 I pushed an update for this :)

**Comment by k8hughes** [comment]
This is for @edwinmp to pull through
