### ISSUE TITLE
Team filter default should be something like "All team members"

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#457]
http://159.65.56.142/who-we-are/our-team/?team-filter=

Chrome/Mac

#### Team filter default should be something like "All team members"

The default/unselected state of the filter is "Filter by department".

If a visitor lands on a filtered page such as `http://159.65.56.142/who-we-are/our-team/?team-filter=board-members` (or has filtered the page themselves), it is not obvious that the top "Filter by department" option will display all members (this is confusing select labelling with option values).

Would recommend changing this value to something like "All team members" so it is descriptive of its function as a default selection.

**Comment by k8hughes** [comment]
LGTM.
