### ISSUE TITLE
T5. Our Team Page

### ISSUE THREAD

**Issue by edwinmp** [devinit/DIwebsite-redesign#46]
Template: http://development-initiatives.surge.sh/page-templates/05-our-team

This will be split across multiple issues (mentioned below). This issue shall only be closed after all dependent issues are closed.

- [x] #45 
- [x] #47 
- [x] #48 
- [x] #49
- [x] #50
- [x] #51

**Comment by edwinmp** [comment]
@k8hughes is there anything else that needs fixing on this, besides the team list arrangement (shouldn't all be appearing below each other)

**Comment by k8hughes** [comment]
That is the only thing I have spotted so far.  I want to try the page with the correct images from the comms team as well before I confirm.  James has now shared the right images so I hope to do this later today.

**Comment by edwinmp** [comment]
@Napho could you look into why all the profiles are showing in a single row.
