### ISSUE TITLE
No search function when selecting a publication download

### ISSUE THREAD

**Issue by riahasler-DI** [devinit/DIwebsite-redesign#471]
## I'm submitting a ...
Bug or issue with the CMS. 
**Describe the Issue**
When adding a publication download to a publication page, there is no search filter. This means we have to manually search and click through all the publications we have added on the publication download snippets. This will get more difficult as we add more snippets to the CMS as we will have more to search through. 

**Expected Behaviour**
If possible can we add a search function to this so we can type what publication we want to add to the page? 

**Screenshots/GIF**
This is what we see when we go to add publication downloads to the page:
![image](https://user-images.githubusercontent.com/56585598/69133623-1fa95600-0aae-11ea-812b-4c5e890573a3.png)

Currently we have 2 pages to search through, and it would be easier if we had a search function so we could more easily find publications we want to add to the page. 

![image](https://user-images.githubusercontent.com/56585598/69133883-8595dd80-0aae-11ea-95fc-bde927103d6a.png)

**Comment by alice-mcandrew-development-initatives** [comment]
This search function doesn't appear to be working very well.

This snippet has been created:
![Capture_2](https://user-images.githubusercontent.com/55877063/69970616-6f5c3880-1516-11ea-87ee-ccc7429f5699.JPG)
But doesn't appear when you search:
![Capture_1](https://user-images.githubusercontent.com/55877063/69970622-72572900-1516-11ea-8a41-609d7c5e66a0.JPG)

**Comment by akmiller01** [comment]
Okay, solved this one @alice-mcandrew-development-initatives we just needed to reindex elastic-search http://159.65.56.142/admin/snippets/downloads/publicationdownload/?q=field

**Comment by alice-mcandrew-development-initatives** [comment]
Great!

**Comment by alice-mcandrew-development-initatives** [comment]
Hello @edwinmp and @akmiller01, we have the same issue for data downloads (i.e. there is no option to search when looking for a snippet to add a data download on publication pages): 
![No-search-function_Data-download-snippet](https://user-images.githubusercontent.com/55877063/78236441-e65c0a80-74d1-11ea-8f66-8b7e6231f140.JPG)

**Comment by SimonMurphyDI** [comment]
Hi there - can we raise the priority of this? We're having the same issue adding Related links at the bottom of pages, and when adding new featured pages to the home page - we end up clicking through 20 pages of content to find what we need. 
Thanks!

**Comment by akmiller01** [comment]
Hi @SimonMurphyDI I see a search box for related links. Looks like this when I click "Choose page" 
![image](https://user-images.githubusercontent.com/2836840/83049540-58a42380-a019-11ea-9a1a-ea29066fdd5c.png)

**Comment by davidebukali** [comment]
> Hello @edwinmp and @akmiller01, we have the same issue for data downloads (i.e. there is no option to search when looking for a snippet to add a data download on publication pages):
> ![No-search-function_Data-download-snippet](https://user-images.githubusercontent.com/55877063/78236441-e65c0a80-74d1-11ea-8f66-8b7e6231f140.JPG)

@alice-mcandrew-development-initatives we deployed a potential fix on staging, kindly take a look when you get time

**Comment by alice-mcandrew-development-initatives** [comment]
@davidebukali and @k8hughes Sorry, I'm not sure how to look at the cms as part of staging (http://staging.devinit.org/) - could you show me how to do this?

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives you’re probably still using the IP address to access it, but http://178.128.102.213/ is staging.

**Comment by alice-mcandrew-development-initatives** [comment]
@davidebukali The search function seems to work for some things but not others. 

For example:
![image](https://user-images.githubusercontent.com/55877063/85289065-bef05a80-b48e-11ea-9667-ffb34e6e0f02.png)
When I search "Benin" I don't get any results even though there are two relevant excel files that should appear: 
![image](https://user-images.githubusercontent.com/55877063/85289021-ada74e00-b48e-11ea-8176-3161208d30a1.png)

**Comment by akmiller01** [comment]
A bit baffled by this one. Manually rebuilt the index and got:
```
default: Rebuilding index wagtail__downloads_datadownload
default: downloads.DataDownload    .
default: indexed 42 objects
```

Which seems to indicate it's working well. And yet the behavior persists. Maybe a side-effect of our `restart` deployment instead of a full down and up @edwinmp ?

**Comment by edwinmp** [comment]
@akmiller01 @davidebukali This was coded to only index & search by title ... those snippets do not have explicit titles added on the snippets. What's shown is from the file. So I think we have to expand the search to include file titles, or only working with file titles.

![image](https://user-images.githubusercontent.com/5672438/85303309-fc66df00-b4b2-11ea-8a93-181de12610e9.png)

**Comment by akmiller01** [comment]
Are the titles ever manually written @alice-mcandrew-development-initatives ? If not, the easiest solution for us could be to automatically save the `title` field as the file title upon creation.

**Comment by alice-mcandrew-development-initatives** [comment]
@akmiller01 I think we'd always want the snippet title for data downloads to be the same as the file title. I can't think of an occasion where we'd want something different... So, that sounds like a good solution to me. I can let you know if we encounter any issues a result but would be surprised if there are any!

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/800

**Comment by AnnaHope** [comment]
ok this is good to go. Thanks
