### ISSUE TITLE
Adding publication date to blogs

### ISSUE THREAD

**Issue by riahasler-DI** [devinit/DIwebsite-redesign#472]
## I'm submitting a ...
Bug or issue with the CMS

**Describe the Issue**
On Publication pages you can edit the date that a report was published, however, on blogs pages you can't. The date does appear on blogs but there is no where on the CMS to edit the "published date".  I want to add a blog to the website from 2014 but if I can't edit the publication date I'm worried it would appear as the most recent blog. 

**Screenshots/GIF**
Here you can see the publication date of the blog in the banner at the top 
![image](https://user-images.githubusercontent.com/56585598/69135362-ed4d2800-0ab0-11ea-91c1-b098fb2ec954.png)

But in the CMS there is no where to edit that date, unlike for Publication pages. 
This is in the Publication page - can we add it to blog pages? 
![image](https://user-images.githubusercontent.com/56585598/69135547-2c7b7900-0ab1-11ea-842b-2dd21fb601cf.png)

**Comment by alice-mcandrew-development-initatives** [comment]
All of the blogs have now appeared with the date 20 November (as far back as I can tell):
![image](https://user-images.githubusercontent.com/55877063/69235397-3cff2280-0b89-11ea-9e27-fd8114bc7c9f.png)

**Comment by k8hughes** [comment]
@akmiller01 is there a way we can fix the dates via a script or will this need to be changed by a CMS user?

**Comment by akmiller01** [comment]
Sure, I'll fix it in shell.

**Comment by akmiller01** [comment]
Done.
