### ISSUE TITLE
Project card caption not contained inside <a>

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#478]
http://159.65.56.142/what-we-do/our-focus-areas/

Chrome/Mac

#### Project card caption not contained inside <a>

The `project-card__caption` element should be contained in its previous `<a>` sibling element, rendering outside means the captions aren't aligned with the project image:

![Screenshot 2019-11-19 at 10 50 46](https://user-images.githubusercontent.com/560463/69140550-9f3d2200-0aba-11ea-8a21-4cc8cd448989.png)

![Screenshot 2019-11-19 at 10 48 20](https://user-images.githubusercontent.com/560463/69140566-a3693f80-0aba-11ea-942b-90ad64b84693.png)

See http://development-initiatives.surge.sh/page-templates/08-focus-areas

**Comment by k8hughes** [comment]
![Screenshot 2019-11-25 at 12 23 55](https://user-images.githubusercontent.com/36768381/69540428-7adfba80-0f7e-11ea-91d4-ed357fad7fcf.png)
Why is the font weight different on the word 'Rachel'?
@davidebukali can you check why this is happening?

**Comment by akmiller01** [comment]
This is in the CMS @k8hughes , it's marked as bold and italics: 
![image](https://user-images.githubusercontent.com/2836840/69545525-026a0100-0f60-11ea-92b8-7ce78b5f1929.png)

**Comment by k8hughes** [comment]
@alice-mcandrew-development-initatives is this deliberate?
