### ISSUE TITLE
Project page breadcrumb current/last item has # instead of URL

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#479]
http://159.65.56.142/what-we-do/our-focus-areas/inspiring-action-malnutrition/

Chrome/Mac

#### Project page breadcrumb current/last item has `#` instead of page URL

```
<li class="breadcrumbs__item" aria-level="4">
    <a href="#">Inspiring action on malnutrition</a>
</li>
```

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/491

**Comment by k8hughes** [comment]
LGTM.
