### ISSUE TITLE
Not enough line height on multi-line button-style link

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#480]
http://159.65.56.142/what-we-do/where-we-work/our-work-kenya/

Chrome/Mac

#### Not enough line height on multi-line button-style link

![Screenshot 2019-11-19 at 11 20 12](https://user-images.githubusercontent.com/560463/69142519-e2998f80-0abe-11ea-9a13-1f51c6be44b1.png)

**Comment by k8hughes** [comment]
@BenDarby @benjamincoleman is this a pattern library thing?

**Comment by BenDarby** [comment]
@k8hughes @edwinmp I increased the line height, a pull from `pattern_library` needed to apply css style
