### ISSUE TITLE
No margin between buttons

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#481]
http://159.65.56.142/what-we-do/where-we-work/our-work-kenya/

Chrome/Mac

#### No margin between buttons

![Screenshot 2019-11-19 at 11 23 17](https://user-images.githubusercontent.com/560463/69142616-183e7880-0abf-11ea-9060-7c61f3db9655.png)

**Comment by k8hughes** [comment]
@BenDarby @benjamincoleman is this a pattern library thing?

**Comment by BenDarby** [comment]
@k8hughes @edwinmp I've fix this with css, pull needed to apply styles
