### ISSUE TITLE
Callout box has reverse layout to pattern library

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#482]
http://159.65.56.142/what-we-do/where-we-work/our-work-kenya/

Chrome/Mac

#### Callout box has reverse layout to pattern library

The call out box on the [pattern library template](http://development-initiatives.surge.sh/page-templates/08-1a-place) has the media item aligned right:

![Screenshot 2019-11-19 at 11 25 07](https://user-images.githubusercontent.com/560463/69142796-73706b00-0abf-11ea-88d0-aac625e28cc6.png)

The [dev implementation](http://159.65.56.142/what-we-do/where-we-work/our-work-kenya/) has the media aligned left:

![Screenshot 2019-11-19 at 11 25 00](https://user-images.githubusercontent.com/560463/69142818-84b97780-0abf-11ea-8034-bde1082b8bdf.png)

**Comment by alice-mcandrew-development-initatives** [comment]
We have the option to change this in the cms
