### ISSUE TITLE
Images missing on consultancy modules

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#483]
http://159.65.56.142/what-we-do/consultancy-services/

Chrome/Mac

#### Images missing on consultancy modules

"Development finance" and "Domestic resources" modules don't have images:

![Screenshot 2019-11-19 at 11 41 08](https://user-images.githubusercontent.com/560463/69143743-a287dc00-0ac1-11ea-8494-0711fc9e2105.png)

**Comment by alice-mcandrew-development-initatives** [comment]
I've added these missing images: http://159.65.56.142/what-we-do/consultancy-services/

@k8hughes Was there a conscious decision to not have credit captions for images below a certain size?
@AnnaHope ^ This would be a potential issue for licensing, right? Although, perhaps we add this information at the bottom of each box or bottom of the page?

**Comment by AnnaHope** [comment]
@alice-mcandrew-development-initatives if the license for the image used states we need to credit the image then we do need to find somewhere to put that credit. In this page I think it would need to go at the end of the description for each area.

**Comment by k8hughes** [comment]
If we need to add an image credit then does this require a pattern library change first @benjamincoleman or can the devs just do it direct in dev?

**Comment by alice-mcandrew-development-initatives** [comment]
@AnnaHope, I've done this:
![Capture](https://user-images.githubusercontent.com/55877063/69159645-2b157500-0ae0-11ea-932b-9466fe9eaf36.JPG)

If that's OK ^ then no action from devs

**Comment by alice-mcandrew-development-initatives** [comment]
@AnnaHope I'm closing this...
