### ISSUE TITLE
Contact details module doesn't use Firstname Lastname pattern

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#484]
http://159.65.56.142/what-we-do/consultancy-services/

Chrome/Mac

#### Contact details module doesn't use Firstname Lastname pattern

The [pattern library template](http://development-initiatives.surge.sh/page-templates/09-consultancy-services) shows the contact details module with a bold `Firstname Lastname` above the telephone number:

![Screenshot 2019-11-19 at 11 45 01](https://user-images.githubusercontent.com/560463/69143975-2e016d00-0ac2-11ea-9433-bc59baf593cd.png)

The [dev implementation](http://159.65.56.142/what-we-do/consultancy-services/) does not have this pattern in the same module:

![Screenshot 2019-11-19 at 11 43 58](https://user-images.githubusercontent.com/560463/69144010-42de0080-0ac2-11ea-921e-51ce7868dd6e.png)

**Comment by alice-mcandrew-development-initatives** [comment]
We are able to do this using the rich text editor:
![Capture](https://user-images.githubusercontent.com/55877063/69157197-86456880-0adc-11ea-8d59-104e2a3035b3.JPG)
