### ISSUE TITLE
News hero doesn't match pattern library

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#489]
http://159.65.56.142/what-we-do/news/development-initiatives-response-uk-voluntary-national-review/

Chrome/Mac

#### News hero doesn't match pattern library

The hero in the dev implementation is different to the pattern library in two respects:

- The metadata (category, date) is higher in the hero than the design
- It contains excerpt text below the title

(The dev implementation example hero is also challenging to read due to the choice of image).

[Pattern library template](http://development-initiatives.surge.sh/page-templates/12a-news-single):

![Screenshot 2019-11-19 at 14 20 40](https://user-images.githubusercontent.com/560463/69154686-5e540600-0ad8-11ea-9be3-95b73c3e4a67.png)

[Dev implementation](http://159.65.56.142/what-we-do/news/development-initiatives-response-uk-voluntary-national-review/):

![Screenshot 2019-11-19 at 14 20 29](https://user-images.githubusercontent.com/560463/69155984-a1af7400-0ada-11ea-942b-dd7540fc1a3c.png)

**Comment by k8hughes** [comment]
@edwinmp I can't see that anything has changed here.  What I see on staging still looks the same as the screenshot Russell shared.

**Comment by edwinmp** [comment]
Just a heads-up @alice-mcandrew-development-initatives ... I'm going to remove the hero text for this ... apparently it should be there as per the patterns library.

**Comment by edwinmp** [comment]
@urlsangel the page on surge doesn't have an excerpt, but the pattern library code appears to have a provision for it... so I'm not sure what to do here.
https://github.com/devinit/DIwebsite-redesign/blob/develop/patterns/includes/heroes/hero-news.html#L21

**Comment by urlsangel** [comment]
@edwinmp 

Ignore my comment about the `excerpt` then - I didn't see that in the pattern library!

**Comment by edwinmp** [comment]
@k8hughes this should be fixed then... only change is the position of the hero content

**Comment by k8hughes** [comment]
LGTM.
