### ISSUE TITLE
Empty paragraphs in rich text content

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#492]
http://159.65.56.142/what-we-do/news/development-initiatives-response-uk-voluntary-national-review/

Chrome/Mac

#### Empty paragraphs in rich text content

The main content has empty paragraphs, including one at the start:

![Screenshot 2019-11-19 at 14 54 22](https://user-images.githubusercontent.com/560463/69157273-a117dd00-0adc-11ea-8b65-903410d2a75c.png)

This means that the content does not get an increased-size first paragraph with a white box to the left, as per the pattern library template.

[Dev implementation](http://159.65.56.142/what-we-do/news/development-initiatives-response-uk-voluntary-national-review/):

![Screenshot 2019-11-19 at 14 55 40](https://user-images.githubusercontent.com/560463/69157462-d9b7b680-0adc-11ea-893b-c3c0548d14f9.png)

[Pattern library template](http://development-initiatives.surge.sh/page-templates/12a-news-single):

![Screenshot 2019-11-19 at 14 55 46](https://user-images.githubusercontent.com/560463/69157489-e9cf9600-0adc-11ea-8d80-a6a720cf87d2.png)

**Comment by edwinmp** [comment]
@akmiller01 I think this is happening for imported content only.

**Comment by urlsangel** [comment]
@k8hughes @AnnaHope @akmiller01 @edwinmp 

Just to clarify, this issue could be viewed as a content problem, but as empty paragraphs could always be entered by CMS editors in the future, and as they have a detrimental effect on the display (particularly the first paragraph style), you can also treat this as a development issue.

There are a couple of mitigations - either strip the empty paragraphs from the rich text content before saving to the database, or from the database content itself before rendering as HTML.

There are a couple of libraries that can help with a task like this:

- https://pypi.org/project/bleach/
- https://pypi.org/project/beautifulsoup4/

**Comment by urlsangel** [comment]
This issue also applies to blog article pages, which means that the initial paragraph is not getting the correct style applied, e.g.:

http://159.65.56.142/blog/priorities-uks-incoming-secretary-state-alok-sharma/

**Comment by alice-mcandrew-development-initatives** [comment]
I've amended in this instance: https://github.com/devinit/DIwebsite-redesign/issues/492
Now, it's just something to keep a note of and action wherever we notice?

**Comment by urlsangel** [comment]
Hi @alice-mcandrew-development-initatives 

You can mitigate this from being an issue at all by using an HTML sanitiser as suggested here: https://github.com/devinit/DIwebsite-redesign/issues/492#issuecomment-555933573

**Comment by urlsangel** [comment]
Also applies to this page: http://159.65.56.142/work-for-us/

**Comment by urlsangel** [comment]
@edwinmp 

You might want to add `.replace('<p></p>', '')` (without the empty string) to strip completely empty `p` tags as well:

https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/common/templatetags/string_utils.py#L81

This blog article for instance still has empty `p` tags at the start:
http://159.65.56.142/blog/priorities-uks-incoming-secretary-state-alok-sharma/

A regular expression would probably be the best thing here :-)

**Comment by edwinmp** [comment]
Ah, true ... though the current one seems to be doing the trick http://178.128.102.213/blog/priorities-uks-incoming-secretary-state-alok-sharma/

**Comment by urlsangel** [comment]
@edwinmp 

Yep, looks good! :-)

**Comment by alice-mcandrew-development-initatives** [comment]
@edwinmp I am still seeing empty lines on this: http://178.128.102.213/blog/priorities-uks-incoming-secretary-state-alok-sharma/

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives this is now fixed. You can verify on the link above ... we'll push to staging soon.

**Comment by alice-mcandrew-development-initatives** [comment]
Great :) thanks
