### ISSUE TITLE
Event single hero missing class

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#494]
http://159.65.56.142/what-we-do/events/financing-crisis-webinar/

Chrome/Mac

#### Event single hero missing class

[Pattern library template](http://development-initiatives.surge.sh/page-templates/12b-event-single):

`<section class="hero hero--minor">`

[Dev implementation](http://159.65.56.142/what-we-do/events/financing-crisis-webinar/):

`<section class="hero ">`

**Comment by k8hughes** [comment]
Unsure what visually to be looking for here, but it seems ok.
