### ISSUE TITLE
Event time format doesn't match pattern library

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#495]
http://159.65.56.142/what-we-do/events/bristol-sdgs-bridging-local-global/ 

**Note: this was previewed data, so as not to amend existing data**

Chrome/Mac

#### Event time format doesn't match pattern library

Previewed dev implementation:

![Screenshot 2019-11-19 at 15 26 30](https://user-images.githubusercontent.com/560463/69160298-42a12d80-0ae1-11ea-96bb-e83918817c12.png)

[Pattern library template](http://development-initiatives.surge.sh/page-templates/12b-event-single):

![Screenshot 2019-11-19 at 15 26 41](https://user-images.githubusercontent.com/560463/69160375-5fd5fc00-0ae1-11ea-9e2d-635ae5ce3654.png)

**Comment by alice-mcandrew-development-initatives** [comment]
@edwinmp I've added the correct time (18:00 to 19:45) for this event.
@k8hughes While I think we need to get the style right for this going forward (for which this is a good test case), I don't think it will be necessary for us to add the time for all historic events (i.e. it's fine if this is blank).

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/551

**Comment by k8hughes** [comment]
LGTM.

**Comment by alice-mcandrew-development-initatives** [comment]
This has not been fixed everywhere:
![image](https://user-images.githubusercontent.com/55877063/69536994-09503e00-0f77-11ea-8aff-52dcd73222d5.png)
^ It appears in 'Related content' section incorrectly

**Comment by k8hughes** [comment]
Events are now fine 👍
