### ISSUE TITLE
Hero text is too high

### ISSUE THREAD

**Issue by AnnaHope** [devinit/DIwebsite-redesign#496]
The hero text - title and subtitle are too high. The original design makes the image gradiated so it is darker at the bottom and allows white text overlay that is still legible and accessible. This is now not the case. Can we drop it down quite a bit?

Current:
![image](https://user-images.githubusercontent.com/16958942/69160957-4c776080-0ae2-11ea-9bd0-424716ca42db.png)

**Comment by akmiller01** [comment]
Maybe this is a screen-size issue again @benjamincoleman ? The text height is matching the pattern library on my screen:

![image](https://user-images.githubusercontent.com/2836840/69161417-212c4b80-0ab9-11ea-8f25-b9a0848ba380.png)

**Comment by akmiller01** [comment]
I think this is sorted out now @AnnaHope , moved to comms review, can you confirm?

**Comment by AnnaHope** [comment]
@akmiller01 looks like it has moved down, so yep thanks! Will close.
