### ISSUE TITLE
Publications filters: resetting and query results 

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#497]
http://159.65.56.142/publications/

Chrome/Mac

##### Resetting filters
The default values of the publications filter selects are labels rather than values, so it's not clear how you would unset a filtered query.

E.g. if the page was filtered as:

http://159.65.56.142/publications/?topic=about-development-initiatives&country=&q=

It would be more intuitive if the top-most value of the first select was "All topics" (and similarly "All countries" for the second select).

##### Query results
If two filters are selected - one for topic and one for country - in all cases tested no results were returned.

This is likely because the query is using AND (so only results that match both filters are returned). 

If the query filter was amended to OR, then results would always be returned (assuming that valid filters are only ever displayed in the selects).

**Comment by davidebukali** [comment]
@akmiller01 for "Query Results" above you mentioned that `AND` returns only results from both selects which is expected behavior; does it make sense to only update the select titles and leave the search as it is now ?

**Comment by akmiller01** [comment]
Yep! We're all good.

**Comment by k8hughes** [comment]
LGTM.
