### ISSUE TITLE
Malformed HTML in publication page template

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#499]
http://159.65.56.142/publications/global-humanitarian-assistance-report-2019/executive-summary/

Chrome/Mac

#### Malformed HTML in publication page template

It looks like there are some missing closing tags in the template, causing `<section>`s to render outside the `<main>` element, and also wrapping the `<footer>`:

![Screenshot 2019-11-19 at 16 13 46](https://user-images.githubusercontent.com/560463/69164341-bd6d4700-0ae7-11ea-913e-42f1ee78d19c.png)

The problem lines appear to be these ones:

* https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/templates/publications/publication_chapter_page.html#L32
* https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/templates/publications/publication_chapter_page.html#L50

This line has an error - should be `row--narrow` instead of `row-narrow`:

* https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/templates/publications/publication_chapter_page.html#L54

The `orderReport` div should be a child of the div immediately above:

* https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/templates/publications/publication_chapter_page.html#L60

**Comment by akmiller01** [comment]
Sorry if you were working on this one @davidebukali but it made sense to subsume it into #522
