### ISSUE TITLE
T3 Who we are

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#5]
Sketch: https://marvelapp.com/3j51290/screen/57215550

Design: http://development-initiatives.surge.sh/page-templates/03-who-we-are

Functional Specification: 

**Hero** 
This page has a standard hero with: 
- `title`
- `sub-title`
- `image`
- `image-credit` with link 

**Out vision / mission**

Rich text content for each, and then the mission has a button after it where we'd like to content manage the `button label` and the `button link location`.

**Message from Pin**

We have a quote section which has the following content: 

- Image
- Image credit (capable of having a link in it)
- Quote
- Citation
- Button - link location for the button
- Button label - the text label of the button

**Values**
- Intro paragraph
- List of values each with the following: 
    - Value title
    - Value content

**Our offices**

For each location the mark up should be as follows: 

```
<div class="media-map__location__point" data-latlng="51.453227, -2.585808" data-title="UK" data-desc="North Quay House Quay Side, Temple Back Bristol, BS1 6FL, UK" data-tel="" data-email="" data-web=""></div>
```

Then the JS will fire and create the map. 

**List of offices**

Underneath the map we have the office list. Now, there may be three offices, or there may be four. Depending on this you'll need to adjust one class on the parent div: 

`<div class="l-4up space-section-top">` for 4 locations

`<div class="l-3up space-section-top">` for 3 locations

---

# 🎯 Template Purpose

The purpose of the ‘Who we are’ section is to establish credibility and clearly explain DI’s purpose / reason for being. 

**The ‘Who we are’ section answers the following user questions:**

* What type of organisation is DI?
* What is the goal of DI?
* Where are DI based?
* Is DI trustworthy?
* How are DI funded?
* Who works for DI?
* How do I find contact details for {name}?

**The ‘Who we are’ page is the top level page of this section and has the following sub pages:**

* Our Story
* Meet the team
* Our Strategy
* Finances

# 🗂Template details

**Template Number and variation**

Adaptation of [T1 General] (https://git.fffunction.co/fffunction/development-initiatives/issues/3) with additional fields for:
* Our Values (this module also appears on the ‘Work with us’ page)
* Where offices are based

**Sketch:**

https://marvelapp.com/1b2f486g/screen/51358448

https://www.dropbox.com/s/e6qix56gb9vt4rp/DI%20website%20sketches%20-%20Who%20we%20are.pdf?dl=0

**Placeholder copy:**

https://docs.google.com/document/d/1AT2zLsO9Y5cnI533wHBOpjZMR8dXl7rFJNjsQLj-SlU/edit

# 📋 Template spec

**Modules (as per spec for this template in IA):**

**Side menu**
* Our Story
* Meet the team
* Our Strategy
* Finances

**Page title**

Succinct one line overview of who DI are

**Vision and Mission**

WYSIWYG: level 2 + 3 headings; copy and primary CTA to link to the Strategy sub-page

**Values**

*  module shared on the 'Work with us' page
*  6 icons for the values. The idea with the icons was to break up the heavy copy. DI currently don't have icons for values. 

**Message from Executive Director Harpinder Collacott**

* WYSIWYG: Testimonial module
 
* Headshot  
* Testimonial
* Name
* Title

and optional CTAs
for this instance, the CTAs are 'Meet the team' and 'Team Stories'

**Where offices are based**

*  A flat map rather with 4 locations rather a than Google map/interactive map
*  Exclude map on mobile
*  4 locations to include addresses and telephone numbers where available

**Comment by benjamincoleman** [comment]
Where our offices are based ← Our offices
Other pages in this secton ← More about

**Comment by edwinmp** [comment]
Hi @benjamincoleman is this done on your end. We'd love to have it cos a lot of pages are flowing from it.

**Comment by k8hughes** [comment]
http://178.128.102.213/who-we-are/ 

The map doesn't seem to be generating properly for me,  can you see t @edwinmp ?

**Comment by benjamincoleman** [comment]
@k8hughes it might be because the Google Maps API is not set to work with the server IP you have set. It should work with the domain though, so would be worth getting that set up along with SSL etc.

**Comment by benjamincoleman** [comment]
@k8hughes @edwinmp I've updated the spec to include some specific guidance around formatting HTML for the map.

**Comment by k8hughes** [comment]
OK, moving back to To Do till the map chages have been done

**Comment by edwinmp** [comment]
@k8hughes @benjamincoleman  I don't think there's anything wrong here. The locations just didn't have coordinates configured. I've added some coordinates, so it should be rendering properly now.

**Comment by k8hughes** [comment]
Excellent, thank you Edwin.  LGTM than.
