### ISSUE TITLE
Section ids not present

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#501]
http://159.65.56.142/50abe0#section-3-1

Chrome/Mac

#### Section ids not present

Deep linking to sections via ids doesn't work when sharing content or using the chapter navigation - it appears that section ids are not present in the markup.

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/522

**Comment by k8hughes** [comment]
LGTM.
