### ISSUE TITLE
Publication hero format doesn't match pattern library

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#502]
http://159.65.56.142/publications/global-humanitarian-assistance-report-2019/chapter-1-people-crisis-and-assistance/

Chrome/Mac

#### Publication hero format doesn't match pattern library

The [pattern library template](http://development-initiatives.surge.sh/page-templates/14-1c-publication-long-form-yellow) hero has this format:

![Screenshot 2019-11-19 at 16 39 18](https://user-images.githubusercontent.com/560463/69166616-6c5f5200-0aeb-11ea-9ef2-40821eeff845.png)

The [dev implementation](http://159.65.56.142/publications/global-humanitarian-assistance-report-2019/chapter-1-people-crisis-and-assistance/) is different:

![Screenshot 2019-11-19 at 16 39 11](https://user-images.githubusercontent.com/560463/69166626-72553300-0aeb-11ea-8e67-8b89845e8742.png)

**Comment by akmiller01** [comment]
Hmm, just looking at this @edwinmp , I know that Publication downloads button was explicitly requested, so we shouldn't remove that.

**Comment by akmiller01** [comment]
#522

**Comment by k8hughes** [comment]
LGTM.
