### ISSUE TITLE
Publication footnotes: highlighting, sharing and return to source

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#503]
http://159.65.56.142/publications/global-humanitarian-assistance-report-2019/chapter-1-people-crisis-and-assistance/#note-m_6PHa2f2

Chrome/Mac

##### Highlighting

There is no highlight class on the footnotes, which helps to focus the user - a working implementation is here: https://globalnutritionreport.org/reports/global-nutrition-report-2018/burden-malnutrition/#note-b2a67844-1

##### Sharing opens all

Sharing a single footnote opens the dialog for all footnotes: 

![Screenshot 2019-11-19 at 16 45 44](https://user-images.githubusercontent.com/560463/69167126-5736f300-0aec-11ea-8b43-20a5400fe99a.png)

##### Return to footnote source

The ability to return to the source text exists, but hasn't been implemented (sharing has instead). 

A working return implementation is here: https://globalnutritionreport.org/reports/global-nutrition-report-2018/burden-malnutrition/#note-b2a67844-1

**Comment by akmiller01** [comment]
Hey @urlsangel are we sure we actually want a SHARE FOOTNOTE feature? I always found this a bit odd to have sharing instead of returning to source. I don't know if any users would actually use sharing.

Also, if we have both together, how is it supposed to look? I coded in a return to source feature, but commented it out because it had no place in the pattern library.

**Comment by akmiller01** [comment]
Maybe like so? Two anchors with a <br/> inbetween?

![image](https://user-images.githubusercontent.com/2836840/69242209-5cd51d00-0b6e-11ea-8bdd-507ecaebf9b3.png)

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/522

**Comment by akmiller01** [comment]
@benjamincoleman how does the snapshot above look design-wise?

**Comment by urlsangel** [comment]
@akmiller01 @benjamincoleman 

"Share footnote" was used in the first iteration of footnotes when linking back to source text wasn't possible.

Once the inline footnotes were developed, the template was amended to remove the share functionality and replace with the return to source link.

My recommendation would be to do the same for this site.

**Comment by akmiller01** [comment]
Done, removed the sharing link.

**Comment by k8hughes** [comment]
LGTM.
