### ISSUE TITLE
Issues with short form legacy publication

### ISSUE THREAD

**Issue by riahasler-DI** [devinit/DIwebsite-redesign#509]
There's a few issues with the GHA 2018 legacy publication page where content is either not pulling through or pulling through weirdly. (http://159.65.56.142/publications/global-humanitarian-assistance-report-2018/) 
(FYI @alice-mcandrew-development-initatives)

What the page looks like: 

![image](https://user-images.githubusercontent.com/56585598/69230145-a4fc3b80-0b7e-11ea-8982-9e1688f22386.png)

Here you can see the Chapter 1 download is separated from the others by a line and there is no image where the "download the full report" button is. 

What the CMS looks like: 
![image](https://user-images.githubusercontent.com/56585598/69230288-dffe6f00-0b7e-11ea-8e40-1dec11429d09.png)

![image](https://user-images.githubusercontent.com/56585598/69230312-eb519a80-0b7e-11ea-80ad-b165a034cf61.png)

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/522 fixes the report cover. Don't see the line, though!

**Comment by riahasler-DI** [comment]
@akmiller01 thanks Alex! I managed to resolve the line issue - the publication that was below the others wasn't marked as English.
