### ISSUE TITLE
Empty id attribute on <a> tags

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#511]
http://159.65.56.142/publications/global-humanitarian-assistance-report-2019/

Chrome/Mac

#### Empty id attribute on <a> tags

Chapter-type links have an empty `id` attribute on the `<a>` tags, e.g.:

```
<a href="/publications/global-humanitarian-assistance-report-2019/executive-summary/" id="" class="button button--a11y " title="Read the executive summary"><span>Read the executive summary</span></a>
```

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/522
