### ISSUE TITLE
Incorrect HTML on long form report summary

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#512]
http://159.65.56.142/publications/global-humanitarian-assistance-report-2019/

Chrome/Mac

##### Additional class on hero

The class `hero--minor` is present on the hero, this should be removed:
https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/templates/includes/heroes/hero-pubs.html#L3

##### Downloads and share block incorrect class and tag

The container should be a `<section>`, it is currently a `<div>`:
https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/templates/publications/publication_page.html#L58

The immediate child `<div>` has a mis-named class, currently `row-narrow`, should be `row--narrow`:
https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/templates/publications/publication_page.html#L59

**Comment by urlsangel** [comment]
The problem noted above "Downloads and share block incorrect class and tag" also applies to the short form publications template, e.g.:

http://159.65.56.142/publications/innovative-financing-refugee-situations/

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/522

**Comment by k8hughes** [comment]
I'm not sure how to test this one, @akmiller01 can you check staging and close if it is now correct?

**Comment by akmiller01** [comment]
Yep. Looks good.
