### ISSUE TITLE
No "All topics" button on blog listing

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#516]
http://159.65.56.142/blog/?topic=development-finance

Chrome/Mac

#### No "All topics" button on blog listing

If a user is on the topic-filtered listing, there is no obvious way to get back to an unfiltered list. 

Would suggest adding a link labelled "All topics" at the start of the topic list that clears the filters.

![Screenshot 2019-11-20 at 11 13 43](https://user-images.githubusercontent.com/560463/69234478-2657cc00-0b87-11ea-8251-321343b6393c.png)

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/580

**Comment by edwinmp** [comment]
@akmiller01 I think the `All topics` tag should be selected by default, and remain selected when clicked, even after page reload... like it is with the other tags.

**Comment by akmiller01** [comment]
> @akmiller01 I think the `All topics` tag should be selected by default, and remain selected when clicked, even after page reload... like it is with the other tags.

https://github.com/devinit/DIwebsite-redesign/pull/587

**Comment by k8hughes** [comment]
LGTM.
