### ISSUE TITLE
Blog author thumbnail cropped on listing item

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#517]
http://159.65.56.142/blog/

Chrome/Mac

#### Blog author thumbnail cropped on listing item

[Pattern library template](http://development-initiatives.surge.sh/page-templates/11-blog-listing):

![Screenshot 2019-11-20 at 11 18 15](https://user-images.githubusercontent.com/560463/69234658-96fee880-0b87-11ea-99df-19c4f81aa82f.png)

[Dev implementation](http://159.65.56.142/blog/):

![Screenshot 2019-11-20 at 11 17 05](https://user-images.githubusercontent.com/560463/69234643-8e0e1700-0b87-11ea-9990-1e67731010ef.png)

**Comment by urlsangel** [comment]
Also applies to "Related content" module in blog page footer:

http://159.65.56.142/blog/review-delivery-global-goals-immediate-priorities-uk-government/

**Comment by akmiller01** [comment]
I just haven't been able to get the responsive images to work on smaller images, so for the moment thumbnail sized things have been reverted: https://github.com/devinit/DIwebsite-redesign/pull/521

**Comment by k8hughes** [comment]
LGTM.
