### ISSUE TITLE
Incorrect HTML on blog page

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#518]
http://159.65.56.142/blog/priorities-uks-incoming-secretary-state-alok-sharma/

Chrome/Mac

##### Additional class on hero

The class `hero--minor` is present on the hero, this should be removed:
https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/templates/includes/heroes/hero-post.html#L4

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/523

**Comment by k8hughes** [comment]
LGTM
