### ISSUE TITLE
Apply for job description field

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#520]
http://159.65.56.142/work-for-us/vacancies/test-job/
http://159.65.56.142/admin/pages/636/edit/

Chrome/Mac

### Apply for job description field

The content contains an email address that is an empty `#` link:

![Screenshot 2019-11-20 at 11 58 17](https://user-images.githubusercontent.com/560463/69237524-cd3f6680-0b8d-11ea-80c4-91ae1cb14663.png)

Trying to edit this link to ensure email links work results in a Draftail rich text editor fatal error:

![Screenshot 2019-11-20 at 12 05 35](https://user-images.githubusercontent.com/560463/69237677-1a233d00-0b8e-11ea-9ac7-6e78c3efb0dd.png)

**Comment by akmiller01** [comment]
Probably a matter of clearing your cache @urlsangel We just updated to Wagtail 2.7 and they changed a lot in the backend. Worked fine for me:

![image](https://user-images.githubusercontent.com/2836840/69246818-6d3dc580-0b77-11ea-856c-82141562936e.png)
