### ISSUE TITLE
Vacancies list could do with an empty list message

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#525]
http://159.65.56.142/work-for-us/vacancies/

Chrome/Mac

#### Vacancies list could do with an empty list message

(Unpublish the current test vacancy to replicate)

If there are no current vacancies in the list, then an alternative message would be helpful - currently the page has an empty space where the list would be:

![Screenshot 2019-11-20 at 14 43 01](https://user-images.githubusercontent.com/560463/69248629-7d1fce80-0ba4-11ea-905b-920cadc4a6dd.png)

**Comment by k8hughes** [comment]
LGTM
