### ISSUE TITLE
Vacancy subscribe form

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#527]
http://159.65.56.142/work-for-us/vacancies/

Chrome/Mac

#### Vacancy subscribe form

Entering an email but not checking the consent box means the form doesn't submit, but there is no indication why. Suggest adding `required` attribute to the consent checkbox.

After successful completion, the success message is posted above the form - the form should be removed from the page:

![Screenshot 2019-11-20 at 14 48 35](https://user-images.githubusercontent.com/560463/69249297-907f6980-0ba5-11ea-9ba3-d4fa3570db4c.png)

When trying to subscribe again, an error message is presented above the form which is beyond the top of the screen. This error message should be next to the button so it is visible when errors occur.

![Screenshot 2019-11-20 at 14 55 14](https://user-images.githubusercontent.com/560463/69249458-cc1a3380-0ba5-11ea-8d79-eee31475f65f.png)

It looks like the marketing permissions value might not be transferring correctly, all others were pre-populated correctly when testing with JavaScript disabled:

![Screenshot 2019-11-20 at 14 58 17](https://user-images.githubusercontent.com/560463/69249773-59f61e80-0ba6-11ea-95c2-4de1fad9281b.png)

![Screenshot 2019-11-20 at 14 58 24](https://user-images.githubusercontent.com/560463/69249779-5cf10f00-0ba6-11ea-8de7-905b5c7e187c.png)

**Comment by edwinmp** [comment]
@davidebukali there seems to be a lot going on in this template since the mail chimp integration. Could you have a look?

**Comment by akmiller01** [comment]
#552

**Comment by k8hughes** [comment]
LGTM.
