### ISSUE TITLE
No images in benefits modules

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#528]
http://159.65.56.142/work-for-us/

Chrome/Mac

#### No images in benefits modules

Possibly because they are optional?

[Pattern library template](http://development-initiatives.surge.sh/page-templates/16-work-for-us):

![Screenshot 2019-11-20 at 15 15 58](https://user-images.githubusercontent.com/560463/69251254-0f29d600-0ba9-11ea-9521-11ef35691432.png)

[Dev implementation](http://159.65.56.142/work-for-us/):

![Screenshot 2019-11-20 at 15 08 50](https://user-images.githubusercontent.com/560463/69251277-13ee8a00-0ba9-11ea-9f40-8af19058e190.png)

**Comment by edwinmp** [comment]
Hi @alice-mcandrew-development-initatives ... this one's for you. There's a provision for images on the benefits block.
