### ISSUE TITLE
T18 Vacancies listing

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#53]
Sketch: https://marvelapp.com/3j51290/screen/57215564

Design: http://development-initiatives.surge.sh/page-templates/18-vacancy-listing

Functional spec: 

**The vacancies section is almost identical to the one we've recently released for GNR, so it's best to copy it from there**

Shows a list of vacancies - this is all the available vacancies by page order (the order they appear in Wagtail). 

Following that there is a form for people to submit to a mailchimp list. Above the form are success and error messages for display when the user submits the form. The success message lists the form options the user selected for the role types. 

Required fields are the email input, and the 'By checking this box...' checkbox.

**Comment by k8hughes** [comment]
LGTM.
