### ISSUE TITLE
Contact us form

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#530]
http://159.65.56.142/contact-us/

Chrome/Mac

#### Contact us form

When submitting the form without a required field, the page refreshes to the top, but no overall error message is visible, just the field errors which are visible when scrolling down through the form:

![Screenshot 2019-11-20 at 15 31 01](https://user-images.githubusercontent.com/560463/69252502-fde1c900-0baa-11ea-92be-492ec8b7881a.png)

A non-field error message pattern is available in the pattern library template: http://development-initiatives.surge.sh/page-templates/20-contact

A successful submission refreshes the page, but again the message isn't immediately visible - would suggest replacing the body test with the success message instead of placing it underneath as currently:

![Screenshot 2019-11-20 at 15 34 06](https://user-images.githubusercontent.com/560463/69252725-5dd86f80-0bab-11ea-8813-2d082d5f91b9.png)

**Comment by edwinmp** [comment]
@urlsangel just to clarify, you'd like the field errors to be instead shown in the alert above the form?

**Comment by urlsangel** [comment]
@edwinmp 

It doesn't need to be the errors themselves (although it can be), but an indication that the form has errors should be displayed as near the top of the page as possible so that the user understands there is a problem - that's currently not obvious unless they scroll down.

An alternative would be to force the browser to scroll to the first field with errors using anchor links or JS, but that's a whole other rabbit hole to go down.

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/558

**Comment by k8hughes** [comment]
LGTM
