### ISSUE TITLE
Data contact email link not a valid email link

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#531]
http://159.65.56.142/data/datasets/oda-loan-repayments-from-developing-countries-to-top-8-dac-donor-recipients-2016/

Chrome/Mac

#### Data contact email link not a valid email link

![Screenshot 2019-11-20 at 15 47 04](https://user-images.githubusercontent.com/560463/69253822-28348600-0bad-11ea-8209-37251ffc1a77.png)

**Comment by alice-mcandrew-development-initatives** [comment]
@k8hughes I think this is a devs issue because this isn't editable in the cms as far as I can tell

**Comment by k8hughes** [comment]
As thi is hard coded we need to fix it in dev, please can someone change this to have info@devinit.org

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/535

**Comment by k8hughes** [comment]
LGTM.
