### ISSUE TITLE
Dataset listing 

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#533]
http://159.65.56.142/data/datasets/?report=&source=&topic=

Chrome/Mac

#### Dataset listing 

The metadata on the listing could do with more line height for when the data is multiple lines:

![Screenshot 2019-11-20 at 16 18 11](https://user-images.githubusercontent.com/560463/69256679-c1fe3200-0bb1-11ea-98ec-87e5f5a1fb22.png)

Also, the dev implementation doesn't match the pattern library date format (short versus full month name) - pattern library template:

![Screenshot 2019-11-20 at 16 20 54](https://user-images.githubusercontent.com/560463/69256799-eeb24980-0bb1-11ea-94ce-400324fd3c6b.png)

**Comment by BenDarby** [comment]
@urlsangel increased line height
