### ISSUE TITLE
Large screen logo background

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#539]
Background disappears from behind the logo at large screen sizes

![Screen Shot 2019-11-21 at 10 13 39](https://user-images.githubusercontent.com/64877/69328792-cd03a180-0c47-11ea-9edb-b705b51be987.png)

**Comment by BenDarby** [comment]
@edwinmp pushed a fix for this, it will need a pull from the `pattern_library` branch for styles to update.

**Comment by k8hughes** [comment]
Tested on my ma with crome and firefox and was working as intended.
