### ISSUE TITLE
Single line date not vertically centred on story timeline buttons

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#541]
http://159.65.56.142/who-we-are/our-story/

Chrome/Mac

#### Single line date not vertically centred on story timeline buttons

![Screenshot 2019-11-21 at 11 00 15](https://user-images.githubusercontent.com/560463/69332329-59b15e00-0c4e-11ea-8a75-4c7b183e2e9c.png)

**Comment by BenDarby** [comment]
@urlsangel updated css for this

**Comment by edwinmp** [comment]
@BenDarby still doesn't look centred ... was aligned to the top before, now it's to the bottom.

![image](https://user-images.githubusercontent.com/5672438/69525622-93010b00-0f79-11ea-92ef-b130510d0843.png)

**Comment by BenDarby** [comment]
@edwinmp the pattern library is displaying like this http://development-initiatives.surge.sh/page-templates/04-our-story is there some difference between to the two?
