### ISSUE TITLE
Timeline content shows border of previous or next item 

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#542]
http://159.65.56.142/who-we-are/our-story/

Galaxy (emulated) screen width 360px

#### `April 2015` shows border of previous item to left

![Screenshot 2019-11-21 at 11 04 27](https://user-images.githubusercontent.com/560463/69332844-70a48000-0c4f-11ea-9c4a-28b231f2210f.png)

#### `May 2015` shows border of next item to right

![Screenshot 2019-11-21 at 11 04 42](https://user-images.githubusercontent.com/560463/69332856-769a6100-0c4f-11ea-8a99-eaecbbff781c.png)

#### `June 2016` whose download box border is displayed on previous items to left

![Screenshot 2019-11-21 at 11 04 53](https://user-images.githubusercontent.com/560463/69332867-7b5f1500-0c4f-11ea-9af0-1f5bd21a7185.png)

**Comment by BenDarby** [comment]
@urlsangel  I'm not seeing this with the emulated Galaxy (360px) in the inspector, it's using a JS library with the slider though. But I did notice the arrows don't appear in desktop for the staging site
