### ISSUE TITLE
Hero subheading is appearing above the title

### ISSUE THREAD

**Issue by AnnaHope** [devinit/DIwebsite-redesign#543]
Just going through historic publications and spotted all of them are showing the 'hero text' above rather than below the title. The image below shows this, but I'm seeing it on all of the ones I click on.

![image](https://user-images.githubusercontent.com/16958942/69332952-a5b0d280-0c4f-11ea-863e-3e2a3f8028db.png)

**Comment by akmiller01** [comment]
This is covered by #522 right @edwinmp ?

**Comment by edwinmp** [comment]
@akmiller01 @AnnaHope supposedly this is how it's supposed to be ... it's how it is on the pattern library and was raised in issue #502

**Comment by AnnaHope** [comment]
@edwinmp hmmm so this is just saying the chapter name/title. But if we are putting a subheading then it should be the same as any other hero with a subheading e.g. 

![image](https://user-images.githubusercontent.com/16958942/69336979-acdbde80-0c57-11ea-9ddc-3dd5c26e97bb.png)

If it was designed differently in the pattern library, then that was a flaw in the design because it looks absolutely terrible when populated! Can we revert?

**Comment by AnnaHope** [comment]
@edwinmp just looking at what russell sent, that publication was the long form one where the text is denoting chapters, in which case the text does need to be above. So is it that we are misusing the intended purpose of 'hero text' in the cms? @benjamincoleman can you confirm how this is supposed to work and whether we now need to manually delete all the hero text for publications?

**Comment by benjamincoleman** [comment]
This has the wrong hero. 

http://159.65.56.142/publications/measuring-civil-registration-legal-identity/

This post is a **Short form publication** because it consists of only one page, and so should be using the template for that - http://development-initiatives.surge.sh/page-templates/14-1a-publication-short-form

**Comment by edwinmp** [comment]
@benjamincoleman I'll have to go back to the original issues and make adjustments based on the instructions there ... though @alice-mcandrew-development-initatives that means for short publications, they'll lose the `hero text` ...

**Comment by AnnaHope** [comment]
@benjamincoleman so should the subtitle be below? The pattern library doesn't display it so I can't see how it is supposed to be? Which comes back to my original quesiton of whether I need to go through all our publications removing the hero text or whether it should be below? I think the reason that publication is not in the right template is that Alex created a new template for legacy publications due to them all being pdf and not working properly if we had a content nav on the page

**Comment by AnnaHope** [comment]
@akmiller01 @edwinmp have chatted to Ben and what we've concluded is we just need to hide the 'hero text' in the legacy and short publications so all we see displayed is the title. So it is only the long publication format where this text should be possible.

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/561

Just to reiterate what was on Slack @AnnaHope was this understanding correct?

- No text on short publications
- No text on legacy publications
- Parent title: Chapter number above chapter title on chapter pages
- Hero text below publication title on publication pages
- Hero text below appendix title on appendix pages
- Hero text below summary title on summary pages

**Comment by k8hughes** [comment]
@AnnaHope would it be possible for you to confirm the above is corret and then to check if the implementation was what we wanted.  If it looks ok then please close the issue.

**Comment by AnnaHope** [comment]
@akmiller01 that all sounds good to me except for the appendix. On this we want text that appears below the title on the boxes that sit in a summary of a publication, but the hero once you are on an appendix page proper will just have a title and no text displaying. We don't have this in any publications at the mo for me to check against, but below I have put screenshots of the GNR as this is how it should be I think. @k8hughes FYI

Text below title shows here:
![image](https://user-images.githubusercontent.com/16958942/69541641-87194700-0f81-11ea-80d5-108d231f43c0.png)

Just title with no text once you click through:
![image](https://user-images.githubusercontent.com/16958942/69541662-94363600-0f81-11ea-84d6-367fb42f40b7.png)

**Comment by akmiller01** [comment]
Okay @AnnaHope the chapter pages now have:

"{{ parent_page.title }}: Chapter {{ chapter.number }}" above their titles as per the pattern library.

Do we likewise want:

"{{ parent_page.title }}: Appendix {{ appendix.number }}" above the titles for the appendix pages?

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/576

**Comment by AnnaHope** [comment]
@akmiller01 yes actually that would be great, thank you

**Comment by k8hughes** [comment]
@AnnaHope I think this is now working correctly, but as there are quite a few variations I leave this issue for you to close when you've had a chance to check.

**Comment by AnnaHope** [comment]
@k8hughes it is! Thanks - will close
