### ISSUE TITLE
Download button link needs more line height when wrapping to multiple lines

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#544]
http://159.65.56.142/who-we-are/our-story/

iPhone 6 (emulated)

#### Download button link needs more line height when wrapping to multiple lines

Link text needs more line height: "Progress report 2018 PDF 3.6 MB"

![Screenshot 2019-11-21 at 11 14 27](https://user-images.githubusercontent.com/560463/69333339-5e771180-0c50-11ea-9322-032ddfede6fc.png)

**Comment by BenDarby** [comment]
Increased line height
