### ISSUE TITLE
Bold text bold in Firefox but not Chrome

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#545]
http://159.65.56.142/who-we-are/our-team/amy-cox/

Firefox/Mac & Chrome/Mac

#### Bold text bold in Firefox but not Chrome

Also, these are using `<b>` instead of `<strong>`, not sure if that's correct.

##### Firefox rendered HTML:

![Screenshot 2019-11-21 at 11 23 39](https://user-images.githubusercontent.com/560463/69334093-e27dc900-0c51-11ea-92ae-0ec9a8a8869d.png)

##### Chrome rendered HTML:

![Screenshot 2019-11-21 at 11 23 33](https://user-images.githubusercontent.com/560463/69334123-f3c6d580-0c51-11ea-954f-06267c92030e.png)

**Comment by BenDarby** [comment]
@urlsangel that content is wysiwyg but I've updated the `is-typeset` class to include `b` and `strong` so it will display correctly still
