### ISSUE TITLE
Share section link causes 500 error

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#554]
http://159.65.56.142/publications/global-humanitarian-assistance-report-2019/chapter-1-people-crisis-and-assistance/

Chrome/Mac

#### Share section link causes 500 error

Using this generated link from the top most section of the page causes a 500 error: http://159.65.56.142/505ad6/#section-1-1

![Screenshot 2019-11-21 at 15 33 41](https://user-images.githubusercontent.com/560463/69352160-53ce7380-0c74-11ea-9f17-0133798963ff.png)

**Comment by akmiller01** [comment]
I'm rather confused @urlsangel I was able to recreate this once. And then I restarted the server without changes and now it's no longer causing problems... This leads me to believe it's some sort of race condition, but I'm not sure... Any thoughts?

**Comment by urlsangel** [comment]
Hey @akmiller01 

I've just tested that link again, and I received another 500 error.

Disregarding the cause for a second, there's a few things that should be sorted out anyway (and then you'll be able to work out what's going on).

I've seen a couple of the vanilla Django 404 templates while testing - this means it was in `DEBUG=TRUE` mode. Django's pretty good at masking pass keys etc, but it's unsafe to be in debug mode on a public server.

How to differentiate between `dev`, `staging`, and `www` then? That's where at fffunction we would set a `STAGING` variable on `dev` and `staging`, so that these apps can act differently (different `robots.txt` for instance).

I'm not sure if the dev app is still in debug mode, but I would look to switch that off asap if so, then, with regard to errors, make sure that your 404 and 500 templates are working correctly.

Finally, you should make sure that ADMINS is set correctly in settings (it looks like it is so), and ensure that the SMTP server is working, so that you can be emailed with the details of 500 errors - this will help you track down the cause of the error. You could also employ file logging or logging to a third party service to capture errors externally.

Hope that helps, give me a shout if you have any questions.

**Comment by akmiller01** [comment]
Ah yeah, I temporarily flipped our staging server into debug mode to try and troubleshoot this error. I must have forgotten to flip it back, but it will do so itself on the next deploy.

**Comment by urlsangel** [comment]
Hey @akmiller01 

It looks like it's not on DEBUG anymore, as it should be giving out the Django 500 error template, but your custom 500 template doesn't seem to be being served (it looks like the default Apache one randomly).

**Comment by akmiller01** [comment]
Figured it out. Someone coded NGINX to catch every page that begins with 5 as 500: http://159.65.56.142/5/

**Comment by akmiller01** [comment]
Well, with regards to the 500 error producing an error, this fixes that one: https://github.com/devinit/DIwebsite-redesign/pull/565

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/566 Should hopefully sort redirects out.

**Comment by k8hughes** [comment]
LGTM.
