### ISSUE TITLE
Full chapter nav not viewable on small screen

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#555]
http://159.65.56.142/publications/global-humanitarian-assistance-report-2019/chapter-1-people-crisis-and-assistance/#note-source-5UzRNMYWF

Galaxy (emulated) 360px wide

#### Full chapter nav not viewable on small screen

![Screenshot 2019-11-21 at 15 37 41](https://user-images.githubusercontent.com/560463/69352540-ff77c380-0c74-11ea-80b6-cde436e4dfee.png)

**Comment by urlsangel** [comment]
I think this might be due to URLs in footnotes breaking the container:

![Screenshot 2019-11-21 at 15 41 49](https://user-images.githubusercontent.com/560463/69352826-7745ee00-0c75-11ea-976e-446e0a53b438.png)

**Comment by BenDarby** [comment]
@urlsangel I've added `word-break: break-word;` for links in a wysiwyg so that should fix this

**Comment by k8hughes** [comment]
@edwinmp can you pull this change through?

**Comment by edwinmp** [comment]
@BenDarby as far as I can tell, this isn't fixed for the screen size above... below is how it appears on iPadPro simulation

![image](https://user-images.githubusercontent.com/5672438/69603788-a7eaa680-102c-11ea-8b62-c1fc2985aa14.png)

**Comment by BenDarby** [comment]
<img width="1440" alt="Screenshot 2019-11-29 at 11 26 43" src="https://user-images.githubusercontent.com/944594/69866131-2b113400-129b-11ea-99a3-01b659e467f3.png">
@edwinmp it seems to be displaying correctly on the iPad Pro simulation for me. I tested on the devices I have available to me and it's okay.
