### ISSUE TITLE
Datasets URL causes 500 error

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#556]
http://159.65.56.142/data/datasets/

Chrome/Mac

#### Datasets URL causes 500 error

![Screenshot 2019-11-21 at 16 10 08](https://user-images.githubusercontent.com/560463/69355362-8f1f7100-0c79-11ea-8ac3-462e94a914a7.png)

**Comment by k8hughes** [comment]
LGTM
