### ISSUE TITLE
Page scrolls beyond end of footer

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#557]
http://159.65.56.142/

(All pages affected)

Safari/iPhone X

#### Page scrolls beyond end of footer

![IMG_A945DAFE8148-1](https://user-images.githubusercontent.com/560463/69357101-71074000-0c7c-11ea-8337-d5ab77347d1b.jpeg)

**Comment by k8hughes** [comment]
@benjamincoleman does the fit for this sit on your side?

**Comment by BenDarby** [comment]
@k8hughes I don't have access to an iPhoneX to test this and in my IphoneX emulation it seems to be okay now

**Comment by edwinmp** [comment]
@urlsangel is this fixed for you as well?

**Comment by urlsangel** [comment]
@edwinmp 

Looks good on my iPhone X 👍
