### ISSUE TITLE
Office modules grid not working

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#559]
http://159.65.56.142/who-we-are/

IE11/Win 10

#### Office modules grid not working

![Screenshot 2019-11-21 at 16 56 27](https://user-images.githubusercontent.com/560463/69359166-022be600-0c80-11ea-951d-462bf0acdfdb.png)

**Comment by BenDarby** [comment]
@urlsangel @akmiller01  a 4th location was added so I changed the grid to 4 columns. You just need to change the container class from `l-3up` to `l-4up` and it will work. I also updated the css so 3 columns will still display in a grid.

**Comment by akmiller01** [comment]
Oh @BenDarby we made this programmatic so it varies from `l-2up` to `l-5up` depending on the number of offices. We have had offices come and go (e.g. Brazil, Nepal) so I think if we could be flexible here that's our best bet. Are you saying that `l-4up` will work for every scenario now?

**Comment by k8hughes** [comment]
@BenDarby @benjamincoleman ^^^

**Comment by BenDarby** [comment]
@akmiller01 yeah `l-4up` will work for any scenario, so if there is more than 4 items they will wrap to a new row etc if that works for you? CSS will need to pulled from the `pattern_library` branch though.

**Comment by akmiller01** [comment]
@davidebukali I'm afraid we'll need to remove that templatetag you wrote to count the number of offices, and replace it with a static `.l-4up` instead. Can you make a PR for that?

**Comment by edwinmp** [comment]
> @davidebukali I'm afraid we'll need to remove that templatetag you wrote to count the number of offices, and replace it with a static `.l-4up` instead. Can you make a PR for that?

@davidebukali ^^

**Comment by davidebukali** [comment]
@edwinmp @akmiller01 here's the updated PR [#585](https://github.com/devinit/DIwebsite-redesign/pull/585)
