### ISSUE TITLE
T12d Blog single guest author

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#56]
Sketch: 

Design: http://development-initiatives.surge.sh/page-templates/12a-blog-single-guest

Functional spec: 

This is the same as #12 but with a guest author so there's no link there.

**Comment by k8hughes** [comment]
http://178.128.102.213/blog/and-another-blog/ 

I have filled in having a guest author but their details so not display on this page.  Can someone see if it is user error or a bug?

**Comment by edwinmp** [comment]
@k8hughes this required that the external author's image be added before it shows the whole thing. I've changed that to requiring only the author's name. Image will be a placeholder if none is provided.

**Comment by akmiller01** [comment]
Question for @benjamincoleman on blogs. I noticed there are topics to filter the blogs on the T11 index page, but then the topics don't appear anywhere on the T12 article pages. Are the topics meant to appear anywhere on the single article pages? And do we have a limit to the number of topics per page?

**Comment by benjamincoleman** [comment]
@akmiller01 the topics are used as a filter only, so they don't appear on the single page. 

I've also clarified the issue around the small labels here - #107

**Comment by benjamincoleman** [comment]
@edwinmp This is the same placeholder we use when there is no Team Member image. 

As @akmiller01 mentioned, we're going to provide a gender neutral one, so it will be the same fallback image used here.

**Comment by k8hughes** [comment]
LGTM
