### ISSUE TITLE
Hero text title too high

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#560]
http://159.65.56.142/what-we-do/events/

Edge/Win 10

#### Hero text title too high

![Screenshot 2019-11-21 at 17 17 18](https://user-images.githubusercontent.com/560463/69360633-ce05f480-0c82-11ea-8f43-acf2a03ace30.png)

**Comment by BenDarby** [comment]
Amending media query seems to fix this oddly

**Comment by k8hughes** [comment]
@edwinmp is there a change for you to pul through here?

**Comment by BenDarby** [comment]
@edwinmp I updated the css so you will need to pull from the `pattern_library` branch
