### ISSUE TITLE
Data link not in footer nav

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#562]
http://159.65.56.142/ (any page)

Chrome/Mac

#### Data link not in footer nav

The "Get around" footer nav appears to mirror the top nav, but it's missing the "Data" page link:

![Screenshot 2019-11-21 at 17 23 40](https://user-images.githubusercontent.com/560463/69361157-cdba2900-0c83-11ea-95d4-5beacb05071b.png)

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives @riahasler-DI not sure who created this one. I'm replacing the manual links with a simple check of "Show navigation links"
There seems to be a sorting problem for the sections following the update. I'm fixing that...

![image](https://user-images.githubusercontent.com/5672438/69615326-b7c2b480-1045-11ea-8a26-67db7bf7952e.png)

**Comment by edwinmp** [comment]
@akmiller01 you set these to be ordered by 'sort_order', but that changes a snippet's position every time a change is made... is that the desired behaviour?

**Comment by akmiller01** [comment]
Sort order should just be however the user ordered the orderable.

**Comment by alice-mcandrew-development-initatives** [comment]
@akmiller01 Yes, I think we agreed that. There shouldn't ever be too may to start from scratch to create  a new order so should be fine.
