### ISSUE TITLE
No padding on blog notes module

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#563]
http://159.65.56.142/blog/accelerating-crvs-and-legal-identity-in-africa-from-problems-and-principles-to-practice/

Chrome/Mac

### No padding on blog notes module

![Screenshot 2019-11-21 at 17 34 23](https://user-images.githubusercontent.com/560463/69361904-52f20d80-0c85-11ea-8ccc-1352e3acb2bb.png)

**Comment by BenDarby** [comment]
@urlsangel I've added a notes module which can be seen here http://development-initiatives.surge.sh/page-templates/12-blog-single

**Comment by urlsangel** [comment]
> @urlsangel I've added a notes module which can be seen here http://development-initiatives.surge.sh/page-templates/12-blog-single

Cheers @BenDarby 

@akmiller01 @edwinmp - one for you to implement into your dev template?

**Comment by akmiller01** [comment]
Implemented proper footnotes in the style above into blogs: https://github.com/devinit/DIwebsite-redesign/pull/567

But I do just want to flag, the element you were styling there was scraped from Wordpress. I think there are likely to be many different scraped elements, and we're not going to be able to style them all. As was the issue with publications, this foreign markup shimmed into the Drafttail editor displays at first, but will disappear on first save. So unless @alice-mcandrew-development-initatives and @AnnaHope want me to import Blogs in a similar fashion to Publications (i.e. importing content into a `raw_content` field that can later be deleted), please keep in mind that editing these imported blog pages will result in the loss of embeds.
