### ISSUE TITLE
Blog author

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#579]
Firstly, some of the blog pages do not match the pattern library in terms of display of author:

E.g. http://159.65.56.142/blog/blog-blended-finance-impact/ (Should be on right not left)
E.g. http://159.65.56.142/blog/accelerating-crvs-and-legal-identity-in-africa-from-problems-and-principles-to-practice/ (Shown in middle instead of left, without image)

This is what it should look like: http://development-initiatives.surge.sh/page-templates/12-blog-single

Secondly, can I confirm that we have something in place to ensure that the hyperlink on the author's name is removed if there is no individual profile to link to (in the event that someone leaves)?

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives for the first link, the author is on the right on my laptop, which makes me believe it's one of those pesky screen size things.
As for the second one, this is the design for when a blog has multiple authors.

Since we're only going to unpublish the pages of past staff, we can check if an author's page is live before we create the hyperlink.

**Comment by alice-mcandrew-development-initatives** [comment]
@edwinmp 
For the first, I think you might be right, as I'm just using laptop screen today (as I'm WFH) and it looks OK now!
For the second, did @AnnaHope sign off on this? I wasn't aware of discussions and there's no template to reference as far as I can tell.

So, if we unpublish a staff profile should the link styling automatically disappear then? (We wouldn't want it to look like a link and then go nowhere)

**Comment by edwinmp** [comment]
Ah, @alice-mcandrew-development-initatives  I've figured out the difference... the author image appears on the left for blogs without a hero image
![image](https://user-images.githubusercontent.com/5672438/69619045-ffe4d580-104b-11ea-8a55-bcfcae464569.png)

**Comment by alice-mcandrew-development-initatives** [comment]
@edwinmp That's good to know! We'll get heros for those pages!

**Comment by edwinmp** [comment]
> For the second, did @AnnaHope sign off on this? I wasn't aware of discussions and there's no template to reference as far as I can tell.

@akmiller01 ^^

**Comment by edwinmp** [comment]
> So, if we unpublish a staff profile should the link styling automatically disappear then? (We wouldn't want it to look like a link and then go nowhere)

@alice-mcandrew-development-initatives I'm currently implementing this ... will let you know when it's deployed.

**Comment by akmiller01** [comment]
> > For the second, did @AnnaHope sign off on this? I wasn't aware of discussions and there's no template to reference as far as I can tell.
> 
> @akmiller01 ^^

Yep. This was thoroughly discussed because the designs never contemplated having multiple authors on a blog. So the multiple authors link was taken from the publication design. Remember all the conversations we had regarding the commas between the author names?

**Comment by AnnaHope** [comment]
@akmiller01 cool so you've copied the design we use for publications to have in blogs where there are multiple authors, and then if it is a single author we have the box with image and name as per the original design? If that's the case then that's fine and we can close this issue

**Comment by akmiller01** [comment]
> @akmiller01 cool so you've copied the design we use for publications to have in blogs where there are multiple authors, and then if it is a single author we have the box with image and name as per the original design? If that's the case then that's fine and we can close this issue

Yep. That's precisely it!

**Comment by AnnaHope** [comment]
Great. Issue closed.

**Comment by edwinmp** [comment]
Uhm, @AnnaHope we still have a pending fix on this issue that's not related to the multiple authors ... will reopen.
