### ISSUE TITLE
T8.1: Project

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#6]
Sketch: https://marvelapp.com/3j51290/screen/57215554

Design: http://development-initiatives.surge.sh/page-templates/08-1-project

Functional specification: 

This template shows a single project. The user would arrive here from #7 template. 

We have the standard hero here, with page title and hero content, plus the image with credit if required.

There's the sidebar menu on the right, which has had a recent update to the way the title is spelled out "More about:" being the thing that has changed. What should happen there is the "More about:" will be fixed and the "What we do" will be the top page of the section that has this menu. So, What we do, Who we are etc. etc.

Under the hero we have a breadcrumb to aid wayfinding.

Under the breadcrumb we have standard editor content - text & images etc. 

Lastly, there is a "Related content" section. For this one that title should be editable, as we may want to have some fine grained control over that content. Then three items are selectable by the admin. These can pretty much be any type of content on the website.

**Comment by k8hughes** [comment]
@davidebukali is working on this

**Comment by k8hughes** [comment]
@benjamincoleman for all the issues that are marked with the device testing label and assigned to Russel when is this likely to happen?

**Comment by urlsangel** [comment]
@k8hughes @benjamincoleman 

I'm on these testing issues now.

**Comment by k8hughes** [comment]
http://178.128.102.213/what-we-do/focus-areas/investments-end-poverty-itep/ 

LGTM
