### ISSUE TITLE
Summary child missing from reports

### ISSUE THREAD

**Issue by jamesharle** [devinit/DIwebsite-redesign#600]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
Adding a summary page as a child page of a report page is no longer possible. Instead, child pages can only be created in the categories appendix or chapter (see screengrab below)

![image](https://user-images.githubusercontent.com/43270042/69814421-0a3dd580-11ec-11ea-90b3-d8e20f613a10.png)

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to CMS
2. Navigate to GHA page
3. Click 'add child page'

**Expected Behaviour**
Summary page should be an option

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: dd/MMM/YYYY

**Comment by jamesharle** [comment]
Simon discovered this bug, and provides a slightly expanded description in email screengrabbed below:

![image](https://user-images.githubusercontent.com/43270042/69814672-9d770b00-11ec-11ea-9736-146d07616d9d.png)

**Comment by davidebukali** [comment]
@akmiller01 I just tested this on localhost adding same number of chapter and summary publications as `staging` and indeed adding summary page link disappears from the publication page; Still debugging to get the link back;

**Comment by akmiller01** [comment]
@jamesharle the GHA 2019 publication already has a summary page http://159.65.56.142/publications/global-humanitarian-assistance-report-2019/executive-summary/ you're allowed one summary per publication.

**Comment by jamesharle** [comment]
Thanks @akmiller01 that makes sense, and resolves that part of the issue - but this also applies to a new report Simon is setting up (http://159.65.56.142/publications/multi-year-humanitarian-funding-and-planning-jordan-and-lebanon/)

**Comment by akmiller01** [comment]
Huh, you're right @jamesharle . Just looked at the UniquePageMixin and it's checking whether a page exists globally, not just as a child of that particular page.

Funny thing is this is code borrowed directly from the GNR website, which means that they also must have lost the ability to create summary pages after they created the very first one. Might want to fix it on your end too @urlsangel !

I'll push a hotfix on Monday, @jamesharle

**Comment by urlsangel** [comment]
@jamesharle @akmiller01 

Good spot!

I've updated GNR with a new mixin, `UniqueForParentPageMixin`:

https://github.com/devinit/gnr-website/commit/5febda7e2927da0fca17b0b5ca24c9c59501c07c

**Comment by riahasler-DI** [comment]
@alice-mcandrew-development-initatives and @jamesharle Publication summary has been added to the report child page. Can close this issue now :) 

![image](https://user-images.githubusercontent.com/56585598/70050271-75115700-15c6-11ea-94dd-906e6d846c98.png)
