### ISSUE TITLE
Query on Datasets -> related figures

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/DIwebsite-redesign#601]
The related figures section (which brings in related figures and datasets) seems to have become related datasets only in-certain instances. This can sometimes have the effect of bringing in datasets which are not relevant as opposed to figures which could be relevant.

In this example: http://159.65.56.142/data/datasets/change-in-oda-loans-to-protracted-crisis-response-countries-and-other-developing-countries-20122017/

A dataset called  'Domestic and International Resources in Developing countries, 2016' is brought in, however this is not used at all in the report the figure is from, it may be a preference to only link a related dataset when it is shown on a figures metadata line and otherwise link related figures.

**Comment by akmiller01** [comment]
I think this could mostly be mitigated by adding related pages via the CMS, right @Duncan-Knox ?

![image](https://user-images.githubusercontent.com/2836840/70465321-b30eef00-1a8e-11ea-95b2-471b030bca26.png)

**Comment by Duncan-Knox** [comment]
Yes looks so @akmiller01.
