### ISSUE TITLE
Data section author/contact query

### ISSUE THREAD

**Issue by Duncan-Knox** [devinit/DIwebsite-redesign#602]
The author profile for Cecilia Ciao does not appear in datasets, for example: http://159.65.56.142/data/datasets/jobs-created-with-gender-breakdown/

Unclear why this may be the case?

**Comment by edwinmp** [comment]
@Duncan-Knox Cecilia was added as an external author without linking to her DI profile ... probably happened during import, not sure why ... @akmiller01 any clue? @Duncan-Knox this could be fixed manually by editing the page.

![image](https://user-images.githubusercontent.com/5672438/69848664-bd114080-128b-11ea-9c27-f9e9d412f213.png)

**Comment by Duncan-Knox** [comment]
@edwinmp @akmiller01 it's a typo my end. I think it might be best if I change these manually on the wagtail pages.

**Comment by akmiller01** [comment]
A manual fix would involve deleting the "external author" with the incorrect name, and selecting the "internal author" page of the right analyst @Duncan-Knox

**Comment by Duncan-Knox** [comment]
Thanks @akmiller01, is there a preference for publish or submit for moderation?

**Comment by akmiller01** [comment]
Yeah publish should be fine. Are you sure you want to fix all of them manually? Are you able to sort through the spreadsheet and find which ones are misspelled? Because otherwise it would be a big task to click through all the datasets and figures.

**Comment by Duncan-Knox** [comment]
I've found the ones which are wrong (every single one) though it should be fine to fix through manually as I can match the Google doc with the pages on the website.

**Comment by Duncan-Knox** [comment]
I have fixed this across the data set pages in Wagtail.

**Comment by akmiller01** [comment]
Cheers Duncan. I think it also applies to the figure pages. Did you work on both figures and datasets?

**Comment by Duncan-Knox** [comment]
Edits have been made to 1 Data Set Page and 42 Figure Pages.
