### ISSUE TITLE
Author names on publications not displaying correctly

### ISSUE THREAD

**Issue by jamesharle** [devinit/DIwebsite-redesign#604]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
The way the author name is displayed in publications is not as expected. Two screenshots below show the current application, and the template:

![image](https://user-images.githubusercontent.com/43270042/69916398-7e79b280-1452-11ea-8cb6-9dacdb9606ae.png)

![image](https://user-images.githubusercontent.com/43270042/69916432-cef11000-1452-11ea-98fe-a5bd7c4f4d87.png)

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'http://159.65.56.142/publications/multi-year-humanitarian-funding-and-planning-jordan-and-lebanon/'
2. See error

**Expected Behaviour**
The application seen in the pattern library

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: dd/MMM/YYYY

**Comment by akmiller01** [comment]
Should be fixed by https://github.com/devinit/DIwebsite-redesign/pull/612 if the above link was a LegacyPublicationPage @jamesharle It's 404ing now.

**Comment by jamesharle** [comment]
Hi @akmiller01 and @edwinmp! Just reopening this one as @SimonMurphyDI has flagged that the behaviour still isn't as expected - see screengrab below, with the pattern template on the left and the live page on the right. As you can see, a white box has been added in the live version that was not present in the template, and the gap between the author credit and the text is greater than expected.

![image](https://user-images.githubusercontent.com/43270042/71096617-8c476b80-21a6-11ea-990a-1e567df0110d.png)

**Comment by AnnaHope** [comment]
@edwinmp was this fix made? The publications authors still aren't displaying correctly and I see no movement seems to have happened since 21 days ago? @k8hughes FYI

**Comment by edwinmp** [comment]
@AnnaHope I thought this had been fixed, but it appears some pages, specifically those with chapters still have the problem. This is a pattern library disparity.

@BenDarby chapter publication pages with multi-authors are still displaying in the old style. There's css tied to the `chapter-block_content` class that's responsible for this.

**Comment by akmiller01** [comment]
The main issue that Anna is referring to is the fact that there's too much space between the author block and the content @edwinmp . In our templates we have the author block off in its own `section--large` and that adds way too much padding. My PR nests the author block in the same section as the first bit of content, eliminating the gap.

I think the styling issue you mention exists, but it is separate.

**Comment by edwinmp** [comment]
@AnnaHope this has been fixed and deployed to staging http://staging.devinit.org/resources/coronavirus-and-aid-data-what-latest-dac-data-tells-us/

**Comment by SimonMurphyDI** [comment]
@edwinmp  looks good to me. One to keep in mind for multi-author blogs, it looks like we might want to amend these so they match the  style you've shared here. This is related to another ticket I raised, number 647
Thanks for fixing
Simon
