### ISSUE TITLE
Country filter on the Datasets page

### ISSUE THREAD

**Issue by riahasler-DI** [devinit/DIwebsite-redesign#606]
## I'm submitting a ...
Bug

**Describe the Issue**
On the Datasets page the country filter is pulling though weirdly. I think we had this issue with the publications page so hopefully it can be fixed quickly. We want to match the Dataset filter to the Publication page one.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to http://159.65.56.142/data/datasets/
2. Click on the Country filter

This is the Publications country filter 

![image](https://user-images.githubusercontent.com/56585598/69957471-ab81a000-14fa-11ea-9c16-49f5783970ee.png)

This is the Datasets country filter 

![image](https://user-images.githubusercontent.com/56585598/69957522-c2c08d80-14fa-11ea-8800-1fe75d49c79a.png)

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/608
