### ISSUE TITLE
Embolden 'Share' on publication pages

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#609]
Non-essential and very low priority but it would be great if we could have the word 'Share' in the share section at the bottom of publication pages emboldened:
![image](https://user-images.githubusercontent.com/55877063/69971076-44beaf80-1517-11ea-9d9c-9665dc8ccc47.png)

See this page for example: http://devinit.org/publications/multi-year-humanitarian-funding-planning-jordan-and-lebanon/

**Comment by SimonMurphyDI** [comment]
Looks good to me, thanks!
