### ISSUE TITLE
Orange publication appendix hero

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#613]
The page title (in the hero) of the orange publication appendix page has a dark orange box around it - can this be removed (so it's just white text on orange background)? We don't want to need to add hero images for appendixes.

Example: 
![image](https://user-images.githubusercontent.com/55877063/69979408-2a400280-1526-11ea-88e7-b1688f3bc751.png)

http://devinit.org/publications/multi-year-humanitarian-funding-planning-jordan-and-lebanon/acknowledgements/

**Comment by SimonMurphyDI** [comment]
Just to flag this is an issue for all secondary colour heroes 
![image](https://user-images.githubusercontent.com/22001094/70321718-f7e11e80-181f-11ea-8c52-b113ddd068bc.png)

**Comment by benjamincoleman** [comment]
@alice-mcandrew-development-initatives @SimonMurphyDI can you post a URL we can see this at please? 

@BenDarby can you have a look at this to see wha't going on? 

B

**Comment by alice-mcandrew-development-initatives** [comment]
@benjamincoleman  @BenDarby  
I provided this above for orange: https://159.65.56.142/publications/multi-year-humanitarian-funding-planning-jordan-and-lebanon/acknowledgements/
And this is for green (but there is a pattern there now): https://159.65.56.142/publications/donors-triple-nexus-lessons-united-kingdom/acknowledgements/

**Comment by BenDarby** [comment]
@benjamincoleman @alice-mcandrew-development-initatives I've updated the css so the right colour appears on the green variation when there is no image. A pull from the `pattern_library` feature branch would be required to see update.
