### ISSUE TITLE
Internal links search function

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#614]
It is difficult to search for and find some internal pages when creating hyperlinks.

Example - Trying to link to this publication appendix page (http://159.65.56.142/publications/multi-year-humanitarian-funding-planning-jordan-and-lebanon/interviewees/) from this appendix page (http://159.65.56.142/publications/multi-year-humanitarian-funding-planning-jordan-and-lebanon/acknowledgements/):
![image (1)](https://user-images.githubusercontent.com/55877063/69980119-7d668500-1527-11ea-9123-d26a4b9e0e35.png)

You can create the link manually by clicking back through several pages of publications, but this will become increasingly lengthy process as we add more publications.

**Comment by akmiller01** [comment]
This one should also be fixed by the crontab updating the search index once per hour @alice-mcandrew-development-initatives if you try searching for it again it should appear now since I just updated the index.

**Comment by alice-mcandrew-development-initatives** [comment]
Wonderful!
