### ISSUE TITLE
Arrows missing on Our Story page

### ISSUE THREAD

**Issue by riahasler-DI** [devinit/DIwebsite-redesign#616]
## I'm submitting a ...
Bug

**Describe the Issue**
Arrows are missing on the Our Story page timeline. 

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'the Our Story template page http://development-initiatives.surge.sh/page-templates/04-our-story' and go to the live page http://159.65.56.142/who-we-are/our-story/
2. Scroll down to 'the timeline'
3. See error

**Screenshots/GIF**
Template design: 

![image](https://user-images.githubusercontent.com/56585598/70049121-e3a0e580-15c3-11ea-91ce-bf76453276a0.png)

Live page: 

![image](https://user-images.githubusercontent.com/56585598/70049144-f2879800-15c3-11ea-9c1a-5de9c4a99e59.png)

**Comment by akmiller01** [comment]
Hi @riahasler-DI and @edwinmp I think the arrows only appear once the timeline overflows and there are too many circles to display at once.

**Comment by edwinmp** [comment]
I'm closing this issue as this is expected behaviour for the current context.
