### ISSUE TITLE
Option to include infographics in blog post

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#618]
If possible, it would be great to have the option to add infographics to blog posts (as we can for publications). 

Example: https://devinit.org/blog/how-well-aid-targeting-disability/
At the moment, we can add the charts as images but don't have the option for the title/caption styles.

**Comment by edwinmp** [comment]
Hi @alice-mcandrew-development-initatives ... this is done. Please test on staging.

**Comment by SimonMurphyDI** [comment]
Thanks @edwinmp this looks good to me
