### ISSUE TITLE
Chronological ordering for news and events listings screwy

### ISSUE THREAD

**Issue by jamesharle** [devinit/DIwebsite-redesign#621]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
On news and event listings, listings appear in chronological order but sometimes loop back to 2019 at the end. The final page of listings in both cases ends with some recent posts.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to News or Events listings
2. Navigate to final page of listings
3. See error

**Expected Behaviour**
New posts should appear on the first page, and progress from newest to oldest.

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.

![image](https://user-images.githubusercontent.com/43270042/70064463-7dc35680-15e1-11ea-99a2-2011e44c3cbb.png)

![image](https://user-images.githubusercontent.com/43270042/70064588-b2cfa900-15e1-11ea-8acb-78924404a5cf.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: dd/MMM/YYYY

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/633
