### ISSUE TITLE
Chapter navigation popup not appearing on exec summary

### ISSUE THREAD

**Issue by jamesharle** [devinit/DIwebsite-redesign#627]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
The chapter navigation pop-up is not displaying on exec summary pages. Also applies on GNR site.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'https://159.65.56.142/publications/global-humanitarian-assistance-report-2019/executive-summary/'
2. See error

**Expected Behaviour**
the popup should appear on these pages

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.
![X](https://user-images.githubusercontent.com/43270042/70136756-8325ad00-1684-11ea-88d9-ea4934af7a35.jpg)
![xx](https://user-images.githubusercontent.com/43270042/70136771-8f116f00-1684-11ea-93b8-b387c5af2521.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: dd/MMM/YYYY

**Comment by edwinmp** [comment]
I don't think this feature is available for summary pages ... it's not showing on the patterns library as well... hmm ... http://development-initiatives.surge.sh/page-templates/14-publication-summary ... @BenDarby, is this a regression?

**Comment by akmiller01** [comment]
Mostly working, but new JS seems to not be functional. More info: https://github.com/devinit/DIwebsite-redesign/issues/610#issuecomment-563346397

**Comment by edwinmp** [comment]
Closing as the [comment](https://github.com/devinit/DIwebsite-redesign/issues/610#issuecomment-564035699) in #610 indicates that it's fixed.
