### ISSUE TITLE
Dataset copy needs amending

### ISSUE THREAD

**Issue by jamesharle** [devinit/DIwebsite-redesign#634]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
Currently the text that automatically appears alongside the download button for datasets is incorrect. It reads 
'XLS files contain the figure, metadata and charts / images
CSV files contain the raw figure'

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to datasets
2. Click on any dataset
3. Scroll down to download button

**Expected Behaviour**
The text should read:
'XLS files contain the data, metadata and charts / images
CSV files contain the raw data'

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.
![image](https://user-images.githubusercontent.com/43270042/70249422-4802a700-1774-11ea-8a3d-11f05f019c10.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

**Requested Delivery Date: 09/12/2019**

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/640
