### ISSUE TITLE
Search results text doesn't make sense

### ISSUE THREAD

**Issue by jamesharle** [devinit/DIwebsite-redesign#635]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
The text that displays at the top of search results pages (both data and publications searches) doesn't make sense. For 22 search results across three pages, it reads 'Showing page 1 of 22 results'.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to publications
2. Filter by country:Kenya
3. See error

**Expected Behaviour**
The text should instead read 'Showing 22 results' in the example given, or in general 'Showing X results' where X is the total number of results.

**Screenshots/GIF**
![image](https://user-images.githubusercontent.com/43270042/70250731-43d78900-1776-11ea-9575-cb16a2580ad6.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: 09/12/2019

**Comment by benjamincoleman** [comment]
Hi @jamesharle just to add my 2p to this. 

I would expect the text to read something like: 

"Showing 1-9 of 22 results" so the user both knows where they are in the range, and the size of the range.

My fault - this came through via the sketching / designs and should have been picked up before development

**Comment by jamesharle** [comment]
Sounds good, happy with this formulation!

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/640
