### ISSUE TITLE
Amending order of 'featured work' on homepage broken

### ISSUE THREAD

**Issue by jamesharle** [devinit/DIwebsite-redesign#636]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
When adding ‘featured work’ to the homepage, it’s only possible to alter the order by deleting all featured content and re-adding it in the order you require - the arrows that shift content up/down do so, but after saving and publishing the page, the original order stays on the live page, and the ‘featured content’ reverts to the original order (not saving the changes) in the CMS

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to homepage in CMS
2. Amend order of featured work using arrows and publish
3. Go to live page
5. Return to CMS page
6. See error

**Expected Behaviour**
The arrows should allow us to rearrange the items under featured work.

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: 09/12/2019

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/640
