### ISSUE TITLE
multi-author blogs only pull through one authors face on the listings page

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#647]
**Is your feature request related to a problem? Please describe.**
When two (or more) individuals have written a blog, only one photo pulls through on the blog listing page

**Describe the solution you'd like**
Can all authors' photos pull through? 

**Requested Delivery Date:** 

Could we have this working in Jan next year please - there are some blogs coming up with external stakeholders an it would be great to link our team and theirs

**Comment by edwinmp** [comment]
Hi @SimonMurphyDI ... this was changed for multi-author blogs. We're not showing a list of names
![image](https://user-images.githubusercontent.com/5672438/80697635-ead00f00-8ae1-11ea-9f7d-4a9f4edcd2e5.png)
https://devinit.org/blog/people-want-building-resilience-stability-conflict-crises/

**Comment by SimonMurphyDI** [comment]
Comms review - on the listing page there's still only one author name and photo, even when more than one author is selected
![image](https://user-images.githubusercontent.com/22001094/83018505-5643c880-a01d-11ea-8e8e-d1970b0b42da.png)

**Comment by benjamincoleman** [comment]
Might need a design update for this on the listing view - easy to do, if you're happy for us to do that.

**Comment by edwinmp** [comment]
@benjamincoleman, that'd be great ... though I worry about having too many authors here ... well, not likely.

**Comment by benjamincoleman** [comment]
@BenDarby some publications have multiple authors, can you design a variant of the listing module which caters for that ?

**Comment by BenDarby** [comment]
@benjamincoleman We have a module for showing multiple authors on a single post template, so I created a version that works on a listing page too, most of it is controlled by CSS but this is the markup for multiple authors on a listing page. 
```
<div class="m-authors">
    <h3 class="m-authors__title">Written by</h3>
    <p class="m-authors__copy">Emily Underhill, Joe Bloggs, Amanda Hughes Reilley</p>
</div>
```

You can see an example of it working here: http://development-initiatives.surge.sh/page-templates/11-blog-listing

**Comment by benjamincoleman** [comment]
@edwinmp Ben's outlined the markup needed for multiple authors, and given you an example in the pattern library to help.

**Comment by edwinmp** [comment]
@davidebukali could you have a look at this one as well.

**Comment by k8hughes** [comment]
This page has an internal and an external author but the pictures are not showing:  http://178.128.102.213/blog/build-back-better-risk-informed-development-cooperation/ 

This page I chose to have two internal authors but the pictures do not show:  http://178.128.102.213/blog/people-want-building-resilience-stability-conflict-crises/

**Comment by edwinmp** [comment]
@k8hughes photos do not show for blogs or publications with more than one authors ... 
The authors are shown above the content
![image](https://user-images.githubusercontent.com/5672438/85691542-4501e080-b6dd-11ea-8c75-bd0c97e0b643.png)

**Comment by k8hughes** [comment]
Ah in which case this is doing what it is meant to them 🤦 
I'll pop it in the comms review collumn

**Comment by AnnaHope** [comment]
yeh multiple authors always reverts to just names being listed, not images. @SimonMurphyDI  FYI

**Comment by SimonMurphyDI** [comment]
@AnnaHope @edwinmp @k8hughes 

At the moment if there are multiple authors of a blog, only one picture shows on the listing page. For example, Pin and Charlotte wrote this blog, but only Pin's face appears on the listing page. Do we want blogs with multiple authors to revert to names on the on the listing page? That sounds like a good solution to me
Best
S
![image](https://user-images.githubusercontent.com/22001094/86015975-258af080-ba1a-11ea-9370-de995f6af923.png)

**Comment by edwinmp** [comment]
@SimonMurphyDI @AnnaHope Ben already made a design update to that effect ... you can test it here http://staging.devinit.org/blog/?page=2&nav=header
![image](https://user-images.githubusercontent.com/5672438/86017762-1b262200-ba2d-11ea-8f90-367d57f1c40a.png)

**Comment by SimonMurphyDI** [comment]
Thanks - is it possible to keep the name in bold and to pull through the individual's role too - important to keep consistency with others and to flag the author's credentials
Best
Simon

![image](https://user-images.githubusercontent.com/22001094/86116691-c4205b80-bac5-11ea-8557-7189f45a4b5e.png)

**Comment by benjamincoleman** [comment]
@edwinmp @SimonMurphyDI we'll get a design tweak done for you

**Comment by edwinmp** [comment]
@SimonMurphyDI I think this is kinda consistent as it is ... we don't show roles for multiple authors on the blog pages either ... it'd get really crowded if we do (some of these roles are wordy), and this space is a lot less than we have on the blog pages.

![image](https://user-images.githubusercontent.com/5672438/86119124-92fe5600-bada-11ea-9e0f-e2635ea588f0.png)


What do you think @benjamincoleman?

**Comment by benjamincoleman** [comment]
@edwinmp is quite right to point this out - it could get silly:

<img width="1516" alt="Screenshot 2020-06-30 at 16 58 27" src="https://user-images.githubusercontent.com/64877/86148789-fa280480-baf2-11ea-8841-7421be45b689.png">

**Comment by k8hughes** [comment]
It would be good to get a final decision on this so we know that the instruction for the developer team is.  @SimonMurphyDI are you happy with it as it is or do you want a change even with the risks as flagged by @benjamincoleman ?

**Comment by SimonMurphyDI** [comment]
Thanks for testing this out - the example above is the only one that's like this but I take the point 
Happy to go with this design shown above:  https://user-images.githubusercontent.com/5672438/86017762-1b262200-ba2d-11ea-8f90-367d57f1c40a.png
But is it possible to make the names bold on the listings paper also, so they match the single-author blogs?
Thanks
Simon

**Comment by k8hughes** [comment]
@edwinmp this sounds simple enough fix to do. Could you asign it to one of the team please?

**Comment by benjamincoleman** [comment]
To clarify, I think we should go with the design which just shows author names for posts with multiple authors. This would apply to the listing, and to the article itself. 

Then, if it's going to cause issues with authors not having their job descriptions shown, we could create a new block to put at the end of multi-author articles to list them with their full titles.

**Comment by AnnaHope** [comment]
@benjamincoleman  Or we just make it part of the content. Most websites don't stick everything in boxes so I don't think it is an issue if we just add their profiles at the bottom in normal text, maybe italicised.

**Comment by edwinmp** [comment]
@SimonMurphyDI added the bold author names
![image](https://user-images.githubusercontent.com/5672438/86227718-1e88ed00-bb96-11ea-8493-cba90be5c223.png)

@benjamincoleman I'm reusing the `m-authors__title` class for this - seems harmless at the moment, though susceptible to future changes.

**Comment by SimonMurphyDI** [comment]
spot on - thanks so much
