### ISSUE TITLE
DI website analytics event tracking 

### ISSUE THREAD

**Issue by AnnaHope** [devinit/DIwebsite-redesign#648]
@edwinmp @akmiller01 further to slack conversations, here is the google doc to use for the event tracking in analytics on the site

https://docs.google.com/document/d/1K7LPjbyPgxYiNLsq1E0X3DhqRMy8nWfxOYDYjVnuM1c/edit

this is fairly urgent as we are currently losing important data on a range of elements that can tell us how well our site and key publications are performing.

Thank you!

**Comment by akmiller01** [comment]
Partially done here with everything I can do via just templates: https://github.com/devinit/DIwebsite-redesign/pull/649 Will need pattern library additions to support the custom GA events.
