### ISSUE TITLE
Add Mouseflow code to the website

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#668]
We want to add Mouseflow tracking to the website. 

> To install Mouseflow, you need to copy the following script to the end of the <body>-section of each web page you want to record.

```
<script type="text/javascript">
    window._mfq = window._mfq || [];
    (function() {
        var mf = document.createElement("script");
        mf.type = "text/javascript"; mf.defer = true;
        mf.src = "//cdn.mouseflow.com/projects/0abe85f5-2641-44d4-bbae-690751b5f50d.js";
        document.getElementsByTagName("head")[0].appendChild(mf);
    })();
</script>
```

**Comment by akmiller01** [comment]
Cheers @benjamincoleman I was just reading about precisely where to place mouseflow, and I came across this guide for use with GTM. Would this be an easier implementation? https://support.mouseflow.com/support/solutions/articles/44001806517-installing-using-google-tag-manager

**Comment by benjamincoleman** [comment]
@akmiller01 Ah, if we have GTM there then that's great - I've set IATI up using that method. Is GTM already working with the DI website?

**Comment by akmiller01** [comment]
Yes, GTM is set up and deployed live.

**Comment by benjamincoleman** [comment]
Ok great - leave this to me and  I'll get Mouseflow working today :)

**Comment by benjamincoleman** [comment]
@akmiller01 can you give me access to the DI GTM account please  - ben@bteam.co

Thanks

**Comment by akmiller01** [comment]
@edwinmp set it up. Do you have the credentials to share with Ben? Maybe over Slack?

**Comment by edwinmp** [comment]
@benjamincoleman I've sent u an invitation to our GTM account.
