### ISSUE TITLE
Searching on Publications does not sort the results by most recent date

### ISSUE THREAD

**Issue by edwinmp** [devinit/DIwebsite-redesign#669]
## I'm submitting a ...
<pre><code>
[x] Bug report 
</code></pre>

**To Reproduce**
https://devinit.org/publications/?topic=&country=&q=somalia

**Expected Behaviour**
Results with the most recent dates should appear first

Requested Delivery Date: ASAP

**Comment by edwinmp** [comment]
@akmiller01 this doesn't happen locally, but it does on the deployed versions ... could be some elastic search issue ... any ideas?

**Comment by akmiller01** [comment]
Definitely possible. The behavior does change very slightly when elasticsearch is active. Here's the relevant section: https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/publications/models.py#L213-L221

But it's only meant to sort by elasticsearch `_score` when there is a search query given (the `q` parameter). Maybe worth changing this line: https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/publications/models.py#L218
from
```
if search_filter and elasticsearch_is_active:
```
to
```
if search_filter and search_filter != "" and elasticsearch_is_active:
```

Just in case a blank q parameter is being parsed as `""` instead of `None`?

**Comment by davidebukali** [comment]
@edwinmp sure thing

**Comment by SimonMurphyDI** [comment]
Comms review - able to test this for 'Type' (pubs format) and it works. 

The other search functions on the staging site return this:

![image](https://user-images.githubusercontent.com/22001094/83017719-0c0e1780-a01c-11ea-9cd0-e401838d3b9f.png)

**Comment by edwinmp** [comment]
@SimonMurphyDI this was a space issue on the server and has been since fixed ... could you please test again.

**Comment by SimonMurphyDI** [comment]
hi @edwinmp - tried again but still getting an error 

![image](https://user-images.githubusercontent.com/22001094/83513092-238c4b00-a4c9-11ea-8b4d-0004f6041b80.png)

**Comment by akmiller01** [comment]
@edwinmp this looks like Elasticsearch is improperly configured on the staging website. Might be related to this issue: https://github.com/elastic/elasticsearch-docker/issues/92 for which the solution is:
```
sudo sysctl -w vm.max_map_count=262144
```

But I would also check
```
docker-compose logs elasticsearch
```
For any further error messages.

**Comment by edwinmp** [comment]
@akmiller01 we keep running out of space on the staging server, which means the space hog is still there ... tracked it down to the elastic search container (cos I don't think it should be using 14GB) ... can't make sense of the logs or any of the online info ... reminds me why I gave up on Java... could you please give it a go.

**Comment by akmiller01** [comment]
I think this is the solution. https://stackoverflow.com/a/50371108

If you check `docker-compose logs elasticsearch` you should see it complaining about vm max map count.

**Comment by akmiller01** [comment]
Oh hmm space, not memory. Hmm okay I'll take a look in a bit.

**Comment by akmiller01** [comment]
Fix here for posterity:
```
docker-compose exec elasticsearch bash
curl -XPUT -H "Content-Type: application/json" http://localhost:9200/_cluster/settings -d '{ "transient": { "cluster.routing.allocation.disk.threshold_enabled": false } }'
curl -XPUT -H "Content-Type: application/json" http://localhost:9200/_all/_settings -d '{"index.blocks.read_only_allow_delete": null}'
```

**Comment by SimonMurphyDI** [comment]
hi @edwinmp 

When I search, the newest content doesn't always appear first:

![image](https://user-images.githubusercontent.com/22001094/84507040-243a9380-acb8-11ea-969c-23619fa556fa.png)

Cheers
Simon

**Comment by akmiller01** [comment]
@SimonMurphyDI when a search term is active, it's sorted by relevance.

@edwinmp if you want to change this, this like needs to be `published_date` https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/publications/models.py#L259

**Comment by SimonMurphyDI** [comment]
@edwinmp @akmiller01 
If it's OK with you, I'll run the two options past the Comms team (most recent and most relevant) and get back to you.  
cheers

**Comment by akmiller01** [comment]
> @edwinmp @akmiller01
> If it's OK with you, I'll run the two options past the Comms team (most recent and most relevant) and get back to you.
> cheers

Oops, meant to reply instead of edit. 
If we've got space in the template, we could also give users the ability to toggle whether it's sorted by relevance or date.

**Comment by AnnaHope** [comment]
@akmiller01 I really like the idea of letting people choose to get results by date OR relevance. Can I check how this would interact with the manual search work you did in promoted results. Would that still function as it currently does? If that's all good it would be great if you could show how we can do implementation of toggling date and relevance in the test site so we can see how it looks?

**Comment by akmiller01** [comment]
Sure. Regardless of sorting by relevance or by date, the promoted search results will always come first.

**Comment by akmiller01** [comment]
It does bump the filter button down a row. How does this look @AnnaHope ? 
![image](https://user-images.githubusercontent.com/2836840/84660817-6b5a9b80-aee7-11ea-9949-734b0e5e7edd.png)

**Comment by akmiller01** [comment]
Just changed the language to `Order by newest` `Order by oldest` and `Order by relevance` how does that sound?

**Comment by akmiller01** [comment]
Sorry for the feature creep @edwinmp I just thought this would be nice to have :) https://github.com/devinit/DIwebsite-redesign/pull/782

**Comment by AnnaHope** [comment]
perfect thanks @akmiller01 @edwinmp

**Comment by AnnaHope** [comment]
oh sorry didn't see the screengrab @akmiller01 is it possible for the ordering drop down to sit below the rest as it is technically a second filter once you get results from filtering the other stuff?

**Comment by AnnaHope** [comment]
As in, I filter say by a topic or do a manual search, then I get results. I then want to order those results by date or relevance. That's the user behaviour we would want to enable @akmiller01

**Comment by akmiller01** [comment]
How does this look?
![image](https://user-images.githubusercontent.com/2836840/84664757-0013c800-aeed-11ea-949b-10b68628327e.png)

It's not technically feasible to do sorting after clicking "Filter." The server does the date and relevance score lookups, so the sorting is done upon submit.

**Comment by akmiller01** [comment]
Given the mobile view, I think we need to keep the order before the filter button. 
![image](https://user-images.githubusercontent.com/2836840/84666033-93013200-aeee-11ea-99d8-015291963542.png)

**Comment by akmiller01** [comment]
Up on staging for you to test @AnnaHope you might need to clear your cache to get the new CSS file for the filters to display correctly: http://staging.devinit.org/resources/

**Comment by AnnaHope** [comment]
@akmiller01 this doesn't look great visually as it is so dominant on the page. Could we have all the main filters as they currently stands, all on one line as drop downs plus the filter button. 

THEN

Underneath all that quite a subtle option replicating the visual design of the blog breadcrumbs. That says ' Order results by [date] [relevance] where latest and relevance are in the dark red button to denote they are clickable. 

Like this:
![image](https://user-images.githubusercontent.com/16958942/84762062-3a9b6480-afc2-11ea-9041-e9cd86650dc0.png)

Then you click on 'date' for that to change the results to be from the most recent onwards or 'relevance' for that? By making it not a drop down menu it stops it looking like it is a filter in the same way as the other things.

**Comment by akmiller01** [comment]
How does this look @AnnaHope ?

Desktop:
![image](https://user-images.githubusercontent.com/2836840/84771881-1d599c80-afa8-11ea-892d-526a2046712b.png)

Mobile:
![image](https://user-images.githubusercontent.com/2836840/84771924-2d717c00-afa8-11ea-985a-6c6203904950.png)

**Comment by benjamincoleman** [comment]
@akmiller01 just to chime in - you'll need an active state for the current option. I like this implementation though.

**Comment by AnnaHope** [comment]
weirdly I can't see it on the page on the staging site, and I cleared my cache? @akmiller01

**Comment by akmiller01** [comment]
> weirdly I can't see it on the page on the staging site, and I cleared my cache? @akmiller01

It's local right now. I just wanted to check with you before pushing to staging.

**Comment by akmiller01** [comment]
Basic underline for active state?
![image](https://user-images.githubusercontent.com/2836840/84774497-e8e7df80-afab-11ea-922b-0e2d7b0928a7.png)

**Comment by AnnaHope** [comment]
@akmiller01 yeh I think this looks good. I'm happy with it :)
