### ISSUE TITLE
Key facts section - what to do when we don't have content

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#678]
**Question**

> Currently the key facts section only shows once you select a location - but how would a user know that there is extra information they can see once a location is selected?  How can we make it clear to the user that they should take this action to see everything the spotlights has available?

**Comment by benjamincoleman** [comment]
I think we probably need to show the tab system anyway, but with a message about where data is available in each tab. Something like this: 

![Screenshot 2020-03-04 at 12 51 05](https://user-images.githubusercontent.com/64877/75881389-d8ee2a80-5e16-11ea-8dd8-3f628d0e1cf9.png)

The message here reads: 

`Unfortunately, we do not have data for this location`.

We might adapt that to say `we do not have data for counties, but we do for parishes withing this county` so we give the user some more useful information, if we know this to be the case. 

Some questions from me: 

1. Can we not show key facts for country level?
2. Are there any other levels we cannot show data for?

**Comment by k8hughes** [comment]
I still don't think this solves the problem that:
1. As a user I don't even know the section exisits till I have a location selected.
There needs to be a default display that actually informs the user that they need to select a location then they have the chance to see key facts.
2.  What year do the facts come from?  I assue we have this data annually, so what year is being shown?

I've added @akmiller01 to this issue as he might have a better idea about the data - I can't answer the questions about whether we have this at country level.

In terms of what levels we don't have data for I think this is the wrong question - I think it is that this section only pertains to one level.

**Comment by akmiller01** [comment]
I imagine it will generally be easier to display key facts at the national level, either by aggregation or by national data source...

But there's no hard-and-fast rule for where we have data and where we don't. It will be safe to assume we'll have data gaps of varying sizes at every level, and design around that.

I would generally agree that we shouldn't design anything around the assumption that the user knows what they're looking for, but I would say that currently our analytics data shows that our users do less "browsing and discovery" and more "hunting for specifics" or "bookmarking things that apply to them and revisiting over and over." But maybe we want to encourage more of the discovery process?

**Comment by edwinmp** [comment]
@k8hughes I'd forgotten about this, but couldn't we show country level facts from the data that feeds the country profiles? 
http://data.devinit.org/country/uganda

**Comment by edwinmp** [comment]
@k8hughes @benjamincoleman  Actually, I really think showing country profile data solves this problem (at least for the national level)... knock me on the head for forgetting about it.

**Comment by k8hughes** [comment]
We need to solve the problem at the data level also though - ie where did we get that data on the country profile from and what year does it show?
Can you check with Chris what data we have currently in the spotlights dataset?
We'd need to make sure we keep this updated if we are going to show it.  None of this is a blocking issue but it is important to consider

**Comment by edwinmp** [comment]
The years vary per indicator, but the last update on spotlight data was last year, but that was to load 2018 data (for the indicators we had data for).

**Comment by benjamincoleman** [comment]
Just catching up on the discussion above...

> Kate: As a user I don't even know the section exisits till I have a location selected.
and
> Kate: In terms of what levels we don't have data for I think this is the wrong question - I think it is that this section only pertains to one level.

The tabs should show facts for any level. (Tell me if that's not possible). 

The tabs should always be shown at all levels. As a general rule, I believe we need to keep the interface the same, regardless of the availability of data - something I originally mentioned in #679 

> Alex: I imagine it will generally be easier to display key facts at the national level, either by aggregation or by national data source...

If we can aggregate to show data at the national level that would be great. 

**Q.** Do we need to inform the user that data is an aggregate when we've done that so they know? 

> Alex: But there's no hard-and-fast rule for where we have data and where we don't. It will be safe to assume we'll have data gaps of varying sizes at every level, and design around that.

So we need a design for this - I'll ask @BenDarby to create a design variant to cope with missing data for this and #679.

**Comment by k8hughes** [comment]
Hi @benjamincoleman varient to cope with missing data sounds like a good idea.
@wakibi to update about national elevl data after speaking to Moses.

**Comment by benjamincoleman** [comment]
@k8hughes ok I'll get sketches completed and brief @BenDarby to get designs available

**Comment by wakibi** [comment]
> Hi @benjamincoleman varient to cope with missing data sounds like a good idea.
> @wakibi to update about national elevl data after speaking to Moses.

Hi @k8hughes from my conversation with Moses, we shall always have data gaps. So we need to go with a generic solution that will work both when we have the data and when we do not. Remember some of this data is periodical - a case in point is the data we get from the census data which can only be updated after 10 years for Uganda.

**Comment by benjamincoleman** [comment]
@wakibi @k8hughes we've covered this in this issue: https://github.com/devinit/DIwebsite-redesign/issues/679#issuecomment-598700062
