### ISSUE TITLE
Compare indicators section - what do we do when we don't have sub-county data available?

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#679]
**Question**

> in the compare indicators section - what do we do when we don't have sub-county data available?  The layout is for two graphs, the county selected and then the sub-county layer, but this means that if we don't have sub-county data then we are showing just the selected county very large - is this what you expected? Should we just show all counties if sub-county data is not available?

**Comments:** 

> Edwin: We don't have sub-county level data ... @Ben, that view shows when you haven't selected any location ... just select your comparison options and click compare. It'll show a comparison of all the districts

> Kate: I think my question was shold we show that chart always for the whole country then the selected location data to the side?

**Another Question**

> Edwin: hmm ... and for the reverse, where we have data for the right side but not for the left? Aggregations aren't often accurate here...

**Comment by benjamincoleman** [comment]
So we currently have gaps in our data, that may well be filled in the future.

I also think consistency is important when we've got a sophisticated interface like this. 

So, I'd say we keep the layout the same, so the user is familiar with what can be displayed there. 

Where we do not have data, have a message to explain this, something like this: 

![Indicator comparison v3 no data v1](https://user-images.githubusercontent.com/64877/75882764-b7427280-5e19-11ea-9df0-dc234faf330d.png)

or like this: 

![Indicator comparison v3 No data v2](https://user-images.githubusercontent.com/64877/75882776-bb6e9000-5e19-11ea-9356-57bad8a53825.png)

**Some questions on this from me:** 

1. You mentioned "Aggregations aren't often accurate here..." - I'm not sure I follow, if data is accurate and then combined, how does this not work? 

2. Is there value in showing inaccurate aggregate data but explaining why it is not accurate? 

3. When looking at the country level when we first load a spotlight, are we able to show Uganda on the left and the 4 Regions on the right? If possible I would like to as it shows how the chart works.

**Comment by edwinmp** [comment]
1. Some districts may be missing data, so aggregating it doesn't necessarily reflect the truth at a country level. What we can do is to acquire country level data as a whole despite having gaps in the district/county data. Will pose this question to one of the analysts.
3. The disparities between data across countries makes this tricky ... e.g. Kenya doesn't appear to care about regions ...

**Comment by k8hughes** [comment]
@edwinmp do we still have outstanding design questions, or does this issue have the answers that we needed?

**Comment by benjamincoleman** [comment]
> 1. Some districts may be missing data, so aggregating it doesn't necessarily reflect the truth at a country level. What we can do is to acquire country level data as a whole despite having gaps in the district/county data. Will pose this question to one of the analysts.

I think it might be best we have some sort of notification content to flag this - not doing so means we are not presenting 100% reliable data. Better to highlight the issues than not I think.

> 2. The disparities between data across countries makes this tricky ... e.g. Kenya doesn't appear to care about regions ...

Should we show them then? If there is no user need for looking at regional level data then why have them?

**Comment by edwinmp** [comment]
> Should we show them then? If there is no user need for looking at regional level data then why have them?

We have they were they're relevant. At the moment, we're showing regions for Uganda but not for Kenya. The goal has been to build this to handle these kinds of disparities between countries.

> Where we do not have data, have a message to explain this, something like this:

I'm fine with messages in sections that have no data. This should motivate us to fill in these blanks.

**Comment by benjamincoleman** [comment]
@BenDarby can you produce a variant template for the Country Spotlights to use when we have no data please. 

You can find sketches for each of the modules with data here: 

https://marvelapp.com/d36178e/screen/67187241

**Comment by BenDarby** [comment]
@benjamincoleman I added a no data variation template http://development-initiatives.surge.sh/page-templates/22a-spotlight-nodata 

I've used our alert module for this and added to the sections from the sketch.

**Comment by benjamincoleman** [comment]
@edwinmp you can see the designs set up for the "no data" notifications here: http://development-initiatives.surge.sh/page-templates/22a-spotlight-nodata
