### ISSUE TITLE
Compare indicators module - Graph is really really long

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#680]
**Question**

> We have used scroll on this graph as due to the data it is actually really long, so working with "show more" seemed problematic as then the graph would extend down the page too much.

**Comment by benjamincoleman** [comment]
This needs some thought...

We have the design here: http://development-initiatives.surge.sh/page-templates/22-spotlight

In the design, we wanted to have a `Show more / Show less` button to expand / contract that right-hand chart. 

In the spotlight though, we think this is not going to work, as the user will hit `Show more` and that will expose a long chart. The problem is that if they do not want to see that chart, then they cannot use the `Show less` button as it is at the bottom of the chart. 

So, I think this is not a problem of the chart being too long - we anticipated that, but of the user's lack of ability to collapse the chart having hit `Show more`.

**Comment by benjamincoleman** [comment]
Ok, I have an idea for this which will allow us to use full height charts, but give the user the ability to collapse the chart back to where it was. 

Given we're up against the clock, I think the restricted height is fine, although I would increase it depending on the screen width using media queries. 

Something like:

```
.jsx-676191243 {
    min-height: 500px;
}
@media only screen and (min-width: 600px) {
    .jsx-676191243 {
        min-height: 600px;
    }
}

@media only screen and (min-width: 1000px) {
    .jsx-676191243 {
        min-height: 700px;
    }
}

```

**Comment by benjamincoleman** [comment]
@k8hughes @edwinmp Ok, I've worked up a prototype which will allow the button to always be in view - this means the user can always collapse the large chart area once it's been expanded. 

You can see it here: https://spotlight-prototype.surge.sh/

It might take a few refreshes to work properly, but you should be able to do this: 

https://cloudup.com/cU5DU6EnP0r

**Comment by edwinmp** [comment]
@benjamincoleman good idea ... though I'm wondering which is more disruptive to UX ... in both options, the one constant is that the user will have to scroll. I think the option above has quite the huge side-effect in that once the user has scrolled far enough and then collapses it, all the content below shall move to fill the vacated space. The user will have to scroll back up.

**Comment by benjamincoleman** [comment]
> I think the option above has quite the huge side-effect in that once the user has scrolled far enough and then collapses it, all the content below shall move to fill the vacated space. The user will have to scroll back up.

@edwinmp we could scroll to the top on close easily enough.

**Comment by k8hughes** [comment]
Are we happy with the resolution of this issue?

**Comment by benjamincoleman** [comment]
@k8hughes I'll see about updating my prototype JS so it has the 'scroll to top' behaviour.

**Comment by benjamincoleman** [comment]
I've updated the prototype to have a scroll to top feature - this fires when you expand and contract the element, although it could just be implemented on the closing action.

**Comment by edwinmp** [comment]
Since the design for this is done, I'm closing it here in favour of its copy on the spotlights.
