### ISSUE TITLE
Current item class for Location Selection

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#682]
http://development-initiatives.surge.sh/page-templates/22-spotlight

@BenDarby can you check we have a class for the list items to show the currently selected item please, and provide some guidance on how / where it should go.

Also, can you make the Country sentence case rather than Uppercare please?

**Comment by BenDarby** [comment]
@benjamincoleman I've changed the country to be sentence case, the location selection has an active class already in place working. They need to add an `active` class to `countries-menu-list__item` for the selected item. Here is a video of it working if it's helpful https://drive.google.com/file/d/1cUAZW3KndvHW5WfBEVVc4wxCDyg1cbwn/view

**Comment by benjamincoleman** [comment]
@k8hughes @edwinmp @davidebukali here's some guidance around highlighting the country select menu's current location, so we're showing what location we're currently showing.
