### ISSUE TITLE
Sharing design

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#685]
We need a sharing modal designed @BenDarby. 

This is based on the original sharing functionality you can see in the spotlights: http://data.devinit.org/spotlight-on-uganda

![Screenshot 2020-03-13 at 12 54 58](https://user-images.githubusercontent.com/64877/76622715-ed72a700-6529-11ea-8c1d-45b91e8e4139.png)

I've produced a sketch here: https://marvelapp.com/d36178e/screen/65882709

![Screenshot 2020-03-13 at 12 58 25](https://user-images.githubusercontent.com/64877/76622906-5823e280-652a-11ea-970b-ddf0097baeb3.png)

**Comment by BenDarby** [comment]
@benjamincoleman I've updated the template to include the share modal. We had modal element already from the dataset templates so I created a variation for this.

**Comment by benjamincoleman** [comment]
@mariamiah you can find the modal design here: http://development-initiatives.surge.sh/page-templates/23-spotlight-location-comparison

If you click on the "share visualisation" button at the bottom of the page.

**Comment by k8hughes** [comment]
I think we have a corresponding issue for this now so closing.
