### ISSUE TITLE
Move events to second in the hierarchy of the sub-menu on the 'what we do' page

### ISSUE THREAD

**Issue by AnnaHope** [devinit/DIwebsite-redesign#686]
At the moment events is at the bottom of the hierachy, we want it to become second.

![image](https://user-images.githubusercontent.com/16958942/76778364-9e36ab80-67a1-11ea-8bd2-c7cbe1416cc2.png)

Thanks!

Anna

**Comment by edwinmp** [comment]
@AnnaHope you can rearrange any of these on the CMS using the `sort` option. You click it and then drag and drop to rearrange, then click it again to confirm. Don't mind that the pages appear to return to their old order - the sorting remains.

<img width="505" alt="Screenshot 2020-04-30 at 11 55 37" src="https://user-images.githubusercontent.com/5672438/80692426-37afe780-8ada-11ea-855d-b76fcfa9c4c8.png">

I've moved Events to second.

**Comment by SimonMurphyDI** [comment]
Thanks @edwinmp this looks good to me
