### ISSUE TITLE
Navigating around spotlights

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#688]
From Kate's slack comment: https://devinitorg.slack.com/archives/CCJDWJ669/p1585042716001100

```
@Ben we have implemented the location comparison section now :celebrate:

But I am not sure that the way of navigating there is going to be obvious enough for 
users that dont know there is this second page of the spotlights to explore.

http://157.245.39.153/spotlight/spotlight-kenya

 [ Compare this location to others ] is the button but it isn't super clear.
```

**Comment by benjamincoleman** [comment]
So one idea is to move the [ Compare this location to others ] button to be in the map element. This would make it a little more obvious by moving away from the sidebar content. 

Additionally, we'd want to move between the two. Given the Spotlights are now comprised of two pages - the spotlight, and the location comparison page, something simple in the hero might be best. Perhaps something like this: 

![Screenshot 2020-03-24 at 15 48 41](https://user-images.githubusercontent.com/64877/77446927-f5aeca00-6de6-11ea-9fa6-b4498b7b7f66.png)

Looking at the general idea of navigation something we've not done yet is update the Data Section page template to show how we get here in the first place.

**Comment by benjamincoleman** [comment]
I've added a separate issue to update the Data page #692

**Comment by benjamincoleman** [comment]
@k8hughes @edwinmp I've added this issue to cover the navigation from a Spotlight to a Location comparison page. 

Also worth mentioning here that we'd ideally take the selected location and indicator across to the location page to use there. I've mentioned more about this in issue #689

**Comment by edwinmp** [comment]
> Also worth mentioning here that we'd ideally take the selected location and indicator across to the location page to use there. I've mentioned more about this in issue #689

Do we have two captions then; one for when a specific location is selected i.e. `Compare this location to others`, and another when still showing the entire country e.g. `Compare locations in {{Country}}`?

**Comment by k8hughes** [comment]
I'm definately in favour of moving the Location comparision up above the map element so it is clearer to the user - I'm also assuming this would be on the page for the comparision so you could click back to the main spotlight page.

It would be good to action this one before launch. @edwinmp shall I write up a ticket for the Spotlights repo?

**Comment by benjamincoleman** [comment]
Just to clarify - I mean over the map, as in it appears on top of the map. I'll ask @BenDarby to update the spotlight design so this is in place.

**Comment by benjamincoleman** [comment]
@BenDarby can you move the "compare" button to be absolutely positioned above the map please? 

![Screenshot 2020-04-02 at 09 37 02](https://user-images.githubusercontent.com/64877/78227806-c1fa3100-74c5-11ea-951b-3646ecefdc25.png)

**Comment by BenDarby** [comment]
@benjamincoleman @k8hughes I've updated the pattern library and moved the location comparison button to within the map element. I went with a the DI grey as the button color so it stands out enough against the white and red tones of the interactive map. You can see the updates on surge http://development-initiatives.surge.sh/page-templates/22-spotlight

**Comment by k8hughes** [comment]
@edwinmp shall I create an issue for this in the spotlights repo?

**Comment by edwinmp** [comment]
Sure @k8hughes  ... for any resolutions that don't have issues there yet :)
