### ISSUE TITLE
Initial view of location comparison

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#689]
From Kate's Slack comment: https://devinitorg.slack.com/archives/CCJDWJ669/p1585042716001100

```
Then when you land on the page there is nothing initially until you select things, 
do you think this is ok or do we need to land with something pre loaded that 
shows the functionality?
```

**Comment by benjamincoleman** [comment]
So there's two potential landing states: 

1. You have one area pre-selected having hit the [compare this location to others] button on a spotlight. 2. Empty, when you navigate directly into this page either from the DI data page (still todo) or a google search result for example

---

In scenario 1 you would see this a view containing one location, and we could take the current indicator from the spotlight as the first indicator shown. This would be the most useful for someone coming from a spotlight as it takes the current state (location and indicator) and loads that into the new page. This would appear like this in a sketch: https://marvelapp.com/d36178e/screen/67531402

You can see you have Bungoma loaded, showing Poverty Headcount on the chart. 

For scenario 2 we need to allow the user to work out how to add locations. I suggest we have the same default indicator showing as we do in the Spotlights, so there is a chart there already. You can see this in the sketch here: https://marvelapp.com/d36178e/screen/67531603

@k8hughes @edwinmp let me know what you think, and if you'd like template variants made to cover these scenarios just let me know.

**Comment by k8hughes** [comment]
@edwinmp this makes sense to me do you agree?
 I imagine you can do this without templates right?

**Comment by edwinmp** [comment]
Yup, will implement behaviour for both scenarios.
