### ISSUE TITLE
Footer social icons

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#69]
http://development-initiatives.surge.sh/page-templates/05-our-team

IE11/Win 7

#### Social icons displaying incorrectly

![Screenshot 2019-07-02 at 12 16 30](https://user-images.githubusercontent.com/560463/60508780-516a7d80-9cc3-11e9-831d-b14a0c6449cb.png)

**Comment by BenDarby** [comment]
@urlsangel could this be a vm issue? It displays fine on IE11 on the windows laptop I have here.

**Comment by urlsangel** [comment]
@BenDarby

Could be, but I've no way of knowing :-)

 @benjamincoleman - do you have a VM or real IE to verify with?

**Comment by benjamincoleman** [comment]
I could do later, but maybe you can try an online trial of browserstack or something? That'll be faster as I wont be home till later
