### ISSUE TITLE
Location comparison incomplete data

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#690]
From Kate's Slack comment: https://devinitorg.slack.com/archives/CCJDWJ669/p1585044489003400

```
@Ben one other question for you, in this example I have manage to select a location 
that we don't have data for, but there is nothing that notifies a user of this, 
instead there is just one line on the graph, what would be the best way to notify 
the user of the lack of data?
```

![Screenshot 2020-03-24 at 10 04 29](https://user-images.githubusercontent.com/64877/77437376-7fa56580-6ddc-11ea-9362-0ebd248530b4.png)

**Comment by benjamincoleman** [comment]
So looking at this I examined locations KOLE, OMORO, BUSIA, BUTEBO. Two have data and two do not. I’m not sure what data we have though…

For Omoro and Butebo, which we don't appear to have data for, we have the following possible scenarios: 

**A. Partial data, as in for some indicators we have data, but others we do not?** 

If this is the case then I think we need to indicate that no data is available for this indicator for the following locations: (name of location). This should be near the indicators as they are the things to change to show data. Perhaps something like this: 

![Screenshot 2020-03-24 at 15 59 42](https://user-images.githubusercontent.com/64877/77448281-7f12cc00-6de8-11ea-856c-2c1a0cf737d8.png)

**B. No data at all for this area**

If this is the case, then we should disable the view button in the menu so it is not selected. Maybe make it a non-link elements and show “no data” label.

**Comment by benjamincoleman** [comment]
@k8hughes @edwinmp I've added some thoughts on how to deal with incomplete / no data for locations, and it will need your feedback as to which of those we're dealing with. We can use this issues for a discussion thread :)

**Comment by k8hughes** [comment]
I like the label that says " We don't have data for this topic in Nabru" that seems like a good suggestion.
Agree with B as well.
I think we'd need to have both, what do you think @edwinmp @wakibi ?

**Comment by edwinmp** [comment]
A is fine... cannot implement B since we only know there's no data after none is returned on fetching.
