### ISSUE TITLE
Update Data Page to showcase Spotlights

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#692]
We need to update the data page on the website to showcase the spotlights. 

https://devinit.org/data/?nav=header

Current IA shows this, under the Data page. 

![Screenshot 2020-03-25 at 10 30 18](https://user-images.githubusercontent.com/64877/77527525-301a7480-6e84-11ea-9a56-ecba4e12936b.png)

Had discussions around this here: https://basecamp.com/1931476/projects/15759410/messages/88843111#comment_737002272

**Comment by k8hughes** [comment]
@edwinmp we will need to do this but I think it makes sense to keep this issue in this repo - what do you think?

**Comment by edwinmp** [comment]
Oh yeah, this stays here ...
