### ISSUE TITLE
Compare locations - do we need a "compare" button?

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#693]
Looking at the compare locations, do we even need a "compare" button. 

When we add a location, we can start the chart, even if we only have one location. 

When we add more, we want to compare them so could reload the page with the added location.

When one is taken away, we should reload the page too. This all makes it feel like the "compare" button is not needed.

**Comment by k8hughes** [comment]
What would we have in its place if we didn't have compare?

Agree we should start the chart with only one location.

Still a bit of puzzling out on the nav front so a user can go backwards and forwards between these two pages.

**Comment by benjamincoleman** [comment]
> What would we have in its place if we didn't have compare?

Nothing. As I understand it we're not looking at a no-js solution for these so there's no button needed. When a location is added, or removed, the charts should reload. 

For the back forwards question I suggested a header navigation update here: https://github.com/devinit/DIwebsite-redesign/issues/688#issuecomment-603320869

**Comment by edwinmp** [comment]
While it made sense to remove the `Update` button on selecting an indicator, I think the compare button is still useful. As a user, I'd find it more than distracting if the chart keeps updating while I'm still selecting locations.
The current behaviour has the `Compare` button (and the chart) completely hidden until a user selects  at least two locations, but now that we've opted for full disclosure, keeping it disabled seems fine to me.

On a separate note, I find the usability of the location selector to be a few clicks too many. Any chance we could keep the menu & search widgets visible full time?

**Comment by benjamincoleman** [comment]
> On a separate note, I find the usability of the location selector to be a few clicks too many. Any chance we could keep the menu & search widgets visible full time?

That's an interesting idea - I'll try and update the sketch this afternoon to see what it would look like.

**Comment by benjamincoleman** [comment]
@edwinmp I've updated the sketch with an idea around the locations selection elements being visible all the time. Let me know what you think.

https://www.dropbox.com/s/pnqzxmnjt6a3zyf/add-location-element.mp4?dl=0

**Comment by edwinmp** [comment]
Could we do without the `Add Location` button, or will that make the widget a bit vague? I'm thinking instead of having Uganda or Kenya as the menu title, it reads `Select a location`, to match the `Search for a location` ... instead of `View` buttons, they read `Add` ... the act of selecting automatically adds it to the list.

![image](https://user-images.githubusercontent.com/5672438/78257443-816cd880-7502-11ea-8a61-b4e9f726cbcb.png)

**Comment by k8hughes** [comment]
I have just watched the dropbox video and this makes sense, I don't think you need the compare button if it refreshes on 'add location'

**Comment by edwinmp** [comment]
@k8hughes @benjamincoleman  having to click `Add Location` every time is what I want to get rid of. It's no different from how it is now. The `Compare` button has to stay cos that's just a single click ... `Add Location` is a click per location.

**Comment by benjamincoleman** [comment]
I see what you mean, we could adjust this to have a label: "Add location" and then keep it there all the time: https://marvelapp.com/d36178e/screen/67899660

And to agree the flow, I've recorded a video - https://www.dropbox.com/s/lghbo0oihn8us4g/2020-04-06%20spotlight%20location%20comparison.mp4?dl=0

Let me know what you think

**Comment by k8hughes** [comment]
@edwinmp that makes sense to me, are you happy with it?

**Comment by edwinmp** [comment]
Yes, that works @k8hughes @benjamincoleman

**Comment by benjamincoleman** [comment]
@BenDarby can you update the comparison template to match the sketch and video from my [comment above](https://github.com/devinit/DIwebsite-redesign/issues/693#issuecomment-609662554) please?

**Comment by BenDarby** [comment]
@benjamincoleman I updated the location comparison template so the country list and search are present when you first land on the page instead of hidden behind the add location button. http://development-initiatives.surge.sh/page-templates/23-spotlight-location-comparison

**Comment by benjamincoleman** [comment]
@edwinmp the design has been updated for you
