### ISSUE TITLE
Change to show 'Resources' (rather than just 'Publications')

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#705]
**Instructions provided in PDF as well as below: [Brief for website development - 200420.pdf](https://github.com/devinit/DIwebsite-redesign/files/4503884/Brief.for.website.development.-.200420.pdf)**
**Please let me know if anything is unclear.**

**Overview** 

Changes requested to be made to the following parent pages: homepage (https://devinit.org/) and ‘Publications’ pages (https://devinit.org/publications/?nav=header)

Deadline: Asap, before 4 May if possible

**Changes to the homepage**

On the homepage (https://devinit.org/), please change the word ‘Publications’ in the main menu at the top of the page to ‘Resources’:

![image](https://user-images.githubusercontent.com/55877063/79760400-e81e2e80-8317-11ea-8935-9ab5f989c596.png)

The order of the menu should stay the same.

**Changes to the ‘Publications’ page (now re-named ‘Resources’)**

On the ‘Publications’ page (https://devinit.org/publications/?nav=header) (which should be re-named ‘Resources as outlined above), please add a new drop-down menu called ‘All types’. The new drop-down menu should be placed before (to the left of) the existing ones, so that they appear in the following order (from left to right):

![image](https://user-images.githubusercontent.com/55877063/79760483-0d12a180-8318-11ea-8784-8c827570e600.png)

1.	All types
2.	All topics
3.	All countries
4.	Search…

The drop-down for ‘All types’ will use the following taxonomy:
•	Audio and Visual
o	Podcast
o	Presentation
o	Webinar
•	Publication
o	Background paper
o	Briefing
o	Discussion paper
o	Factsheet
o	Report

This taxonomy should be able to be added through the creation of snippets in the CMS. Please create a new snippet called ‘Resource category’. Please also create a snippet called ‘Resources type’, which should replace ‘Publication types’:

![image](https://user-images.githubusercontent.com/55877063/79760511-1a2f9080-8318-11ea-82cc-5239ca0b7a50.png)

‘Resource category’ and ‘Resource type’ should be linked in the same way that ‘Regions’ and ‘Countries’ are linked: when you create a ‘Resource type’ (comparable to ‘Countries’) you should be forced to select a ‘Resource category’ (comparable to ‘Regions’):

![image](https://user-images.githubusercontent.com/55877063/79760539-23206200-8318-11ea-81d2-82509195232a.png)

**Changes to existing child pages for ‘Publications’ parent page (now re-named ‘Resources’)**

For the ‘Legacy Publication’, ‘Publication Page’ and ‘Short Publication’ templates, please change the word ‘Publication type’ to ‘Resource type’ to allow this snippet to be applied or changed as necessary:

![image](https://user-images.githubusercontent.com/55877063/79760591-34696e80-8318-11ea-9fa3-1468e82aa1b3.png)

It should be imperative (not optional) for the ‘Legacy Publication’, ‘Publication Page’ and ‘Short Publication’ to be marked with a ‘Resource type’ snippet. Once marked, the ‘Resource type’ should then appear as a label whenever the page is shown as a thumbnail (such as on the ‘Publications’ parent page, now re-named ‘Resources’)…:

![image](https://user-images.githubusercontent.com/55877063/79761003-c83b3a80-8318-11ea-8d1d-9d5100630bea.png)

… as well as at the top of each child page:

![image](https://user-images.githubusercontent.com/55877063/79761014-cd988500-8318-11ea-91d4-dc455b1e9740.png)

**Creating a new child page (‘Audio and Visual Media Page’) for the ‘Publications’ parent page (now re-named ‘Resources’)**

Please created a new template for the child pages of the ‘Publications’ parent page (which is now re-named ‘Resources’). This should be called: ‘Audio and Visual Media Page’. It should be based on the ‘General Page’ template with adaptions outlined below.

It should be imperative for the ‘Audio and Visual Media Page’ to be marked with the ‘Resource type’ snippet. Once marked, the ‘Resource type’ should appear as a label whenever the page is shown as a thumbnail, as well as at the top of each page, as outlined above.

Please allow for videos from Vimeo to be embedded on these pages, with the content appearing full-width on the page:

![image](https://user-images.githubusercontent.com/55877063/79760905-a641b800-8318-11ea-82de-325b60994a8d.png)

Please ensure that you can add pages created using the ‘Legacy Publication’, ‘Publication Page’ and ‘Short Publication’ templates as ‘Related Links’ at the bottom of the page on any pages created using the ‘Audio and Visual Media Page’ template – and vice versa:

![image](https://user-images.githubusercontent.com/55877063/79761096-ea34bd00-8318-11ea-980b-351824f7bcad.png)

**Scoping for further development of new ‘Audio and Visual Media Page’ template**

Please indicate the feasibility and cost (in developer time) of having audio content hosted directly on our website (that is, without embedding). Please use Brookings’ website as an example: 

![image](https://user-images.githubusercontent.com/55877063/79761753-c756d880-8319-11ea-8ffa-e592f12f5aae.png)

Like Brookings, we will need a display for audio that allows you to:
a.	View the length of the content in ‘XX:XX’ format
b.	Play and pause the content
c.	See where you are within the content from the change in time, in terms of ‘XX:XX/XX:XX’, as well as from a circle which moves along a full-page width bar
d.	Move backwards and forwards in time using the scrollable bar
e.	Adjust the volume
f.	Download the content from the menu bar on the right, as well as from the download button below.

Please explain the reasons behind the feasibility and cost for this, as well as any other factors or potential issues that we should consider. 

Should having audio content hosted directly on our website not be possible for any reason, we will look into our options for which sites to embed audio content from, as we understand this should be a more straight-forward process.

**Comment by edwinmp** [comment]
That's a misleading title ... there's so much going on with this issue.

**Comment by k8hughes** [comment]
@alice-mcandrew-development-initatives an issues needs to be one discreate piece of work instead of all the changes on one item.  Issues are then assigned to developers to work on and lead to how the code it split into branches etc.

Can you email the PDF document to the team for our discussion?  Then we can break it down into issues and estimate how long it would take to do.

**Comment by alice-mcandrew-development-initatives** [comment]
@k8hughes Sure. Sorry I had thought it was helpful for you to have all information here but appreciate that's not the case if that's your work process.

**Comment by k8hughes** [comment]
Hi Alice, I am going to close this issue as we will need to break the work into specifc issues per feature request or per change, so we can't use this to work from.  Thank you for the breif - it will be discussed with the team once the spotlights are completed.
