### ISSUE TITLE
Ensure drop-down option for countries only appear if dataset is tagged

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#708]
There are currently options in the drop-down menu for datasets that yield no results when searched.

For example:
https://devinit.org/data/datasets/?report=&source=&topic=&country=lebanon

![image](https://user-images.githubusercontent.com/55877063/80002190-3d447680-84b7-11ea-8a09-d7abcff3ca7f.png)

This seems to be because the drop-down is linking to the full list of countries in snippets unfiltered.

**Comment by SimonMurphyDI** [comment]
Comms review: The only country that appears now is Kenya (despite Uganda-specific charts showing up in the sub-Saharan results). Is this an issue with how the Uganda data sets are tagged, or how the filter is working? Thanks!

**Comment by edwinmp** [comment]
@SimonMurphyDI do you have an example I can use to troubleshoot?

**Comment by SimonMurphyDI** [comment]
@edwinmp  Just checked back and this is working well now, thanks!
