### ISSUE TITLE
Changing the publications section to a resources section

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#709]
**Is your feature request related to a problem? Please describe.**
We want to start offering different content now because of the COVID lockdown.  We will now want to have videos and podcasts available not just publications.

**Describe the solution you'd like**

Changes to the ‘Publications’ page (now re-named ‘Resources’)
On the ‘Publications’ page (https://devinit.org/publications/?nav=header) (which should be re-named ‘Resources as outlined above - URL redirects will be required), please add a new drop-down filter called ‘All types’. 

The new drop-down menu should be placed before (to the left of) the existing ones, so that they appear in the following order (from left to right):
![Screenshot 2020-04-22 at 16 45 22](https://user-images.githubusercontent.com/36768381/80003281-b1cbe500-84b8-11ea-8c22-565b402b7e91.png)

1. All types
2. All topics
3. All countries 4. Search...

The drop-down for ‘All types’ will use the following taxonomy:
• Audio and Visual o Podcast
o Presentation
o Webinar • Publication
o Background paper o Briefing
o Discussion paper o Factsheet
o Report
This taxonomy should be able to be added through the creation of snippets in the CMS. Please create a new snippet called ‘Resource category’. Please also create a snippet called ‘Resources type’, which should replace ‘Publication types’:
![Screenshot 2020-04-22 at 16 47 01](https://user-images.githubusercontent.com/36768381/80003413-e9d32800-84b8-11ea-8564-3cdf9677bdb4.png)

‘Resource category’ and ‘Resource type’ should be linked in the same way that ‘Regions’ and ‘Countries’ are linked: when you create a ‘Resource type’ (comparable to ‘Countries’) you should be forced to select a ‘Resource category’ (comparable to ‘Regions’):

![Screenshot 2020-04-22 at 16 47 42](https://user-images.githubusercontent.com/36768381/80003475-02434280-84b9-11ea-921f-7d25d1ecc83f.png)

**Describe alternatives you've considered**

**Additional context**
There will be other changes need listed on other issues that are linked to this change.

**Requested Delivery Date:** 
ASAP - there is already content of this type waiting for upload.

**Comment by k8hughes** [comment]
@davidebukali I went into the CMS to create a page - the new child page existing to be selected by a user.

The resource type drop down menu does not ahve the changes in that are listed above.  We need to be able to choose from:
* Audio and Visual 
o Podcast
o Presentation
o Webinar 
• Publication
o Background paper 
o Briefing
o Discussion paper
 o Factsheet
o Report

Screen shot attached that shows the options I could see:

![Screenshot 2020-05-06 at 14 48 47](https://user-images.githubusercontent.com/36768381/81184904-dc359c00-8fa8-11ea-8025-70382a5c0868.png)

**Comment by davidebukali** [comment]
@k8hughes Sorry should filled those in before hand; they are now updated to include audio and visual types

**Comment by k8hughes** [comment]
http://178.128.102.213/admin/pages/add/publications/audiovisualmedia/352/preview/ 

That is my test page.

But if I search podcast is doesn't show up:  http://178.128.102.213/resources/?types=podcast&topic=&country=&q= 

Do you know what that is?

**Comment by k8hughes** [comment]
I also noticed this in the drop down menu:
![Screenshot 2020-05-06 at 15 45 16](https://user-images.githubusercontent.com/36768381/81191201-aac0ce80-8fb0-11ea-848e-607f86e8196b.png)

I don't think we should ahve the heading "none" or the option "full text".

**Comment by davidebukali** [comment]
@k8hughes both these issues are now sorted.

**Comment by SimonMurphyDI** [comment]
Thanks: three questions on this 

- looks like all hyperlinks to publications (within the DI site) have been fixed - does this include pages and PDFs? Is that true for PDF and HTML links?

- Is this done with redirects, and if so, are there any implications of this we should be aware of?

- Can we amend this so the 't' of types is lower case?

![image](https://user-images.githubusercontent.com/22001094/83008507-2ab8e200-a00d-11ea-8a2b-41c0f909325b.png)

**Comment by davidebukali** [comment]
@akmiller01 is there a chance you did some work on the publications hyperlinks and can answer the first two of Simon's queries above; @SimonMurphyDI yes we can amend the `t` to lowercase

**Comment by akmiller01** [comment]
Yes, this was done with redirects:

https://github.com/devinit/DIwebsite-redesign/blob/develop/config/nginx/django.conf#L84

The only implication @SimonMurphyDI is that we can no longer use the slug `publications` as a child of the home page. It's set up as a permanent redirect so that won't clear from a lot of browsers and they'd get redirected to `resources.`

**Comment by SimonMurphyDI** [comment]
OK thanks @akmiller01 
Can we have a day's notice of the change so we can sort out tag manager for the changeover?
Also, possibly a daft question, but if we ever wanted to undo this process, would we run into issues because some of our outputs have the word 'resources' in the title?

**Comment by akmiller01** [comment]
Hey @SimonMurphyDI , I can technically remove the redirect but it is 301 permanent. Many computers will not recognize the removal and will continue to redirect anyway. And new people who have bookmarked /publications links or are clicking on them from Tweets will hit 404 not found pages.

I tagged `@commsteam` on Slack to discuss this change when it occurred on May 6: https://devinitorg.slack.com/archives/CCG8Y0YJG/p1588780810322900

There should be no issues with "resources" or "publications" in the titles, as long as the URL is not `devinit.org/publications*`

**Comment by SimonMurphyDI** [comment]
Thanks @akmiller01 - I checked back to the message on the 6th. I don't follow it all (it would be easier for me to process if it was concrete examples of risks, but these may not be known) and anyway, I trust you guys! As I said, please can we have some warning of the deployment of this to adjust the tags? 
Thanks

**Comment by AnnaHope** [comment]
@akmiller01 this all looks good to me. Can I check whether the snippets will need to be created from scratch when this is deployed? If so we just need to know exactly when it will be live so we can jump on it :)

**Comment by akmiller01** [comment]
Hi @AnnaHope yes. I know for certain that "Resource Categories" needs to be created from scratch: http://staging.devinit.org/admin/snippets/publications/resourcecategory/

Resource Types might carry over some of the previous Publication Types, but new types will need to be added and after Categories are made they'll all need to be assigned categories: http://staging.devinit.org/admin/snippets/publications/publicationtype/

**Comment by AnnaHope** [comment]
Ok no problem. If you can let us know when you plan to do this, we can block time out to get them up and running as soon as it is live. Thanks!

**Comment by k8hughes** [comment]
If everything gets approved our plan was to do the deployment to live today.
@edwinmp  is that looking possible still?
