### ISSUE TITLE
Vacancies checkboxes

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#71]
http://development-initiatives.surge.sh/page-templates/18-vacancy-listing

Firefox/Win 7

#### Top checkboxes of non-first column not visible 

![Screenshot 2019-07-02 at 13 58 36](https://user-images.githubusercontent.com/560463/60515191-048ea300-9cd3-11e9-94d2-24edbfe519e1.png)

**Comment by BenDarby** [comment]
I'm at a loss on this one, it only happens on Firefox and when the page is initially loaded, if you resize the window even by 1px then the checkbox appears. I can't find anything online but I'll keep searching.

**Comment by benjamincoleman** [comment]
@BenDarby 

The float:left is the problem here - comment that out and it shows. 

Absolutely positioning the labels fixes this. Need to make the checkbox group position:relative.

**Comment by BenDarby** [comment]
@benjamincoleman did you add this to the PL or does it need adding still?

**Comment by benjamincoleman** [comment]
I just wrote the notes after playing in the inspector - it'll need implementing and re-testing.

B

**Comment by urlsangel** [comment]
@BenDarby 

This is also an issue on IE11/Win 10:

![Screenshot 2019-11-21 at 17 08 39](https://user-images.githubusercontent.com/560463/69360044-be39e080-0c81-11ea-86a1-eae6d38ffe95.png)
