### ISSUE TITLE
Changes to the homepage

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#710]
**Is your feature request related to a problem? Please describe.**
Linked to the changes in #709

**Describe the solution you'd like**
On the homepage (https://devinit.org/), please change the word ‘Publications’ in the main menu at the top of the page to ‘Resources’
The order can stay the same.

(This might not need its own issue, please just close if this change would be automatic with #709)

**Describe alternatives you've considered**

**Additional context**

**Requested Delivery Date:** ASAP
This gives us a better sense of the urgency of the issue compared to labels 
If possible, We'll respond with the actual delivery date
-->

**Comment by edwinmp** [comment]
@davidebukali I think this is pretty much just renaming the title and slug ... you'll need to setup a redirect from `/publications` to `/resources` ... all this should be done after merging the other Resources changes.
