### ISSUE TITLE
Changes to existing child pages for ‘Publications’ parent page (now re-named ‘Resources’)

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#711]
**Is your feature request related to a problem? Please describe.**
Linked to the changes requested in #709 

**Describe the solution you'd like**
For the ‘Legacy Publication’, ‘Publication Page’ and ‘Short Publication’ templates, please change the word ‘Publication type’ to ‘Resource type’ to allow this snippet to applied or changed as necessary:
![Screenshot 2020-04-22 at 16 55 18](https://user-images.githubusercontent.com/36768381/80004309-1176c000-84ba-11ea-8e43-b582e7f81642.png)

It should be imperative (not optional) for the ‘Legacy Publication’, ‘Publication Page’ and ‘Short Publication’ to be marked with a ‘Resource type’ snippet. Once marked, the ‘Resource type’ should then appear as a label whenever the page is shown as a thumbnail (such as on the ‘Publications’ parent page, now re-named ‘Resources’)...:››

![Screenshot 2020-04-22 at 16 55 52](https://user-images.githubusercontent.com/36768381/80004377-26ebea00-84ba-11ea-825d-d58aafa0c4a5.png)

... as well as at the top of each child page:$›
![Screenshot 2020-04-22 at 16 56 22](https://user-images.githubusercontent.com/36768381/80004444-39662380-84ba-11ea-9a7f-0bc68d18ef7e.png)

**Describe alternatives you've considered**

**Additional context**

**Requested Delivery Date:** ASAP

**Comment by k8hughes** [comment]
I think this has been done correctly and just needs a member of the comms team to confirm it is working as they expected it to work.

**Comment by SimonMurphyDI** [comment]
Comms review - looks the same as it previously was on the front end. Resource type (rather than Publication type) is appearing in the CMS - which is I think the aim
