### ISSUE TITLE
Scoping for further development of new ‘Audio and Visual Media Page’ template

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#713]
**Is your feature request related to a problem? Please describe.**
Linked to the changes requested in #709 

**Describe the solution you'd like**
We need the ability to host audio content directly on our website.  Use this website as an example:  https://www.brookings.edu/events/webinar-protecting-elections-during-the-coronavirus-pandemic/ 

Like Brookings, we will need a display for audio that allows you to:
a. View the length of the content in ‘XX:XX’ format
b. Play and pause the content
c. See where you are within the content from the change in time, in terms of
‘XX:XX/XX:XX’, as well as from a circle which moves along a full-page width bar
d. Move backwards and forwards in time using the scrollable bar
e. Adjust the volume
f. Download the content from the menu bar on the right, as well as from the download
button below.

How do we deliver this?  Is it just a case of uploading a file into the CMS?  Can we explore the ways of delivering it and discuss before it is implemented?

**Describe alternatives you've considered**

**Additional context**

**Requested Delivery Date:** ASAP

**Comment by SimonMurphyDI** [comment]
Thanks @edwinmp 
Can we add the share and social media buttons to this, a bit like the one you get at the bottom of this publication page?
https://devinit.org/publications/why-do-coronavirus-related-poverty-projections-vary-so-widely/

Also, it would be good to have the option to tag people involved in making a podcast, so the output appears on their profile screen (so the resource could appear on the list at the bottom of this page) https://devinit.org/who-we-are/our-team/zach-christensen/

lastly, can the 'a' of audio here be lower case?
![image](https://user-images.githubusercontent.com/22001094/83430254-39e4c900-a42d-11ea-88f1-ff0fdc2d8587.png)

**Comment by edwinmp** [comment]
@davidebukali ^^

**Comment by edwinmp** [comment]
Hi @SimonMurphyDI ... about tagging authors, would you also like the authors to appear on the page, as they do with publications? Probably titled differently ... does one author a podcast?
![image](https://user-images.githubusercontent.com/5672438/84135818-1a642680-aa53-11ea-87d5-4671a0024582.png)

**Comment by edwinmp** [comment]
> Thanks @edwinmp
> Can we add the share and social media buttons to this, a bit like the one you get at the bottom of this publication page?
> https://devinit.org/publications/why-do-coronavirus-related-poverty-projections-vary-so-widely/
> 
> Also, it would be good to have the option to tag people involved in making a podcast, so the output appears on their profile screen (so the resource could appear on the list at the bottom of this page) https://devinit.org/who-we-are/our-team/zach-christensen/
> 
> lastly, can the 'a' of audio here be lower case?
> ![image](https://user-images.githubusercontent.com/22001094/83430254-39e4c900-a42d-11ea-88f1-ff0fdc2d8587.png)

@SimonMurphyDI these have been implemented.

**Comment by SimonMurphyDI** [comment]
@edwinmp 
Thanks, I can see the added share button. I think the 'A' is still uppercase (see above) and I'm struggling to see  how we'd link an individual's profile to a podcast
Best
S

**Comment by edwinmp** [comment]
Strange ... those changes were made in PR #770  and deployed, but they're not showing ... let me investigate.

**Comment by edwinmp** [comment]
@SimonMurphyDI had to manually refresh the deployment for the changes to register ... please test again. For the link to profiles:
![image](https://user-images.githubusercontent.com/5672438/84512816-3543ce80-acd1-11ea-8526-5bc97ffcb597.png)
Not quite sure about the wording :)

**Comment by AnnaHope** [comment]
@edwinmp happy with all this so that change can be implemented!

**Comment by AnnaHope** [comment]
Ooops spoke too soon! The bottom says 'more about' but needs to be 'related content' as per other publications! @edwinmp

**Comment by edwinmp** [comment]
@AnnaHope I recall a discussion a while back on whether this page should have a `More about` section or `Related content` ... currently, it seems we went with the `More about` version ... do you wish me to keep that design and simply rename it to `Related content`, or change the design as well?

![image](https://user-images.githubusercontent.com/5672438/84664791-b5fc0800-af27-11ea-8158-75b3ae5e02b5.png)


![image](https://user-images.githubusercontent.com/5672438/84664836-c4e2ba80-af27-11ea-93a4-781c13b6716b.png)

**Comment by AnnaHope** [comment]
@edwinmp the audio and video template should be the same as we have for publications as they are all in the same section so we would want the bottom part of the page to act consistently. The 'more about' is used on parent pages like who we are and what we do so I don't think it works. A child publication page and therefore resources page should signpost people to related content in the exact same way. So can we copy what we have on the short publication format for this bit?

Apologies if you were told otherwise at some point as you shouldn't have been!

**Comment by edwinmp** [comment]
@AnnaHope made the changes as requested. Deployed to staging.

**Comment by AnnaHope** [comment]
Great all good to go in that case @edwinmp
