### ISSUE TITLE
Embedded video content no longer displaying on 'How we work' page

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#717]
**The page** 
https://devinit.org/how-we-work/?nav=header

**The issue**
This embedded video is not displaying as it should in the duo block (despite no changes being made in the CMS and it appearing previously without any issues): https://www.youtube.com/watch?v=PbwIUQwL_Jc&feature=youtu.be
I'm not sure why this has now happened

**What it looks like on the page**
![image (1)](https://user-images.githubusercontent.com/55877063/80189951-62e29480-860b-11ea-9018-c5f38387ad0a.png)

**What it looks like in the CMS**
![image](https://user-images.githubusercontent.com/55877063/80190133-a9d08a00-860b-11ea-8266-bd794d27284e.png)

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives this should be fixed now.

**Comment by alice-mcandrew-development-initatives** [comment]
Looks good! Thanks for fixing it!
