### ISSUE TITLE
The maps are no longer showing 

### ISSUE THREAD

**Issue by edwinmp** [devinit/DIwebsite-redesign#724]
## I'm submitting a ...
<pre><code>
[ ] Bug report 
[X] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
The map under the 'Where we work title' is no longer showing. I'm assuming this is the same for other areas with maps (haven't checked) 
https://devinit.org/what-we-do/?nav=header
![image](https://user-images.githubusercontent.com/5672438/80390931-c5f75400-88b5-11ea-9adc-985c38dac530.png)

I can confirm that this issue is also appearing on surge
https://development-initiatives.surge.sh/page-templates/07-what-we-do
![image](https://user-images.githubusercontent.com/5672438/80390883-b7a93800-88b5-11ea-8921-4873ef833312.png)

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Follow the links above

**Expected Behaviour**
A map with all the specified locations should be showing

**Environment/Server:**
<pre><code>
- [x] Production
- [x] Staging
- [x] Development
</code></pre>

**Additional Context**
There's a worry about why these regressions occur and how we can avoid it.

Requested Delivery Date: As soon as possible

**Comment by benjamincoleman** [comment]
@edwinmp I've updated the pattern library branch with a fix for this

**Comment by edwinmp** [comment]
@SimonMurphyDI this should be fixed now.
