### ISSUE TITLE
On banners, the big "download" buttons appear entirely white and illegible on hover

### ISSUE THREAD

**Issue by edwinmp** [devinit/DIwebsite-redesign#725]
## I'm submitting a ...
<pre><code>
[ ] Bug report 
[x] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**To Reproduce**
1. Go to 'https://devinit.org/what-we-do/?nav=header'
2. Scroll down to the `Our impact` banner (refer to screenshot below)
3. Hover over the download button

Happens on surge as well: https://development-initiatives.surge.sh/page-templates/04-our-story

**Expected Behaviour**
Shouldn't vanish in white

**Screenshots/GIF**
![image](https://user-images.githubusercontent.com/5672438/80391244-25edfa80-88b6-11ea-87f6-c5f22e638f3a.png)

**Environment/Server:**
<pre><code>
- [x] Production
- [x] Staging
- [x] Development
</code></pre>

Requested Delivery Date: As soon as possible

**Comment by benjamincoleman** [comment]
@BenDarby there's an issue on this template where we're using the button class to give style to the download box: https://development-initiatives.surge.sh/page-templates/04-our-story

Can you have a look and push a fix please as this is affecting the live site

**Comment by BenDarby** [comment]
@benjamincoleman pushed a fix so the background colour doesn't change on hover, you can see it here too http://development-initiatives.surge.sh/page-templates/04-our-story

**Comment by SimonMurphyDI** [comment]
Comms review: Looks to be fixed on the staging site - thanks
