### ISSUE TITLE
Fix spacing on author information box for blog articles

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#733]
If the author has a long title (more than two lines) we encounter problems in how the author information box displays:
https://devinit.org/blog/transforming-aid-gpi-could-help-achieve-social-justice/
![image](https://user-images.githubusercontent.com/55877063/80686517-b8fa8080-8ac0-11ea-8e3b-e540dd177dc2.png)

The above was a shortened version of the full title, which looks even worse, so we couldn't use it:
![Bug](https://user-images.githubusercontent.com/55877063/80686407-92d4e080-8ac0-11ea-89ea-975eafeda30a.png)

Ideally, to avoid this box looking crowded, the empty space after the author's title should be the same size as the space above 'Written by'. (I don't think it's essential that the image is the same height as the text if the title is more than two lines).

This isn't a huge priority right now, although it may be a problem we encounter more often in the future because we are likely to host more blogs by external authors, potentially with longer titles than DI staff have, and it would be good to fix before we end up in the same situation again.

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives we encountered this earlier on, and thought it'd been handed ...but I guess there's always going to be a longer title :)

Our options include:
1. We truncate the text if longer than a specific number of characters, appending ellipses at the end e.g. `Honorary Professor of Global Hea...`
2. We could reduce the font size if text is longer than a specific number of characters ... this one is limited and the text will spill over again for longer job titles

**Comment by alice-mcandrew-development-initatives** [comment]
Thanks for looking into this @edwinmp. Do you know what the max. characters is to display OK? (That could be useful to know). I don't think truncating would work for job titles (as some people are a bit precious about these!) and I'd be concerned about legibility if we reduce font size. Hopefully Ben has some suggestions.
@SimonMurphyDI FYI - and any ideas welcome!

**Comment by benjamincoleman** [comment]
@alice-mcandrew-development-initatives @edwinmp We could adjust the dimensions of the box, and allow its height to adjust depending on the content. A fairly quick fix I think.

**Comment by alice-mcandrew-development-initatives** [comment]
Sounds perfect ^

**Comment by BenDarby** [comment]
@benjamincoleman @edwinmp I have updated the pattern library to fix the issue of no space at the bottom of the module when the titles are long. This has required a small markup change as I have not changed the profile image to be a `background-image` rather than using the `img` tag. The new markup is this: 
```
<div class="m-author">
    <div class="m-author__image" style="background-image: url({{ global.assets_root }}/img/profile-fallback.jpg);"></div>
    <div class="m-author__body">
        <h3 class="m-author__title">Written by Emily Underhill</h3>
        <p class="m-author__job">Senior Strategic Partnership & Engagement Manager</p>
    </div>
</div> 
```

You can see this working in pattern library as well http://development-initiatives.surge.sh/page-templates/12-blog-single

**Comment by edwinmp** [comment]
> @benjamincoleman @edwinmp I have updated the pattern library to fix the issue of no space at the bottom of the module when the titles are long. This has required a small markup change as I have not changed the profile image to be a `background-image` rather than using the `img` tag. The new markup is this:
> 
> ```
> <div class="m-author">
>     <div class="m-author__image" style="background-image: url({{ global.assets_root }}/img/profile-fallback.jpg);"></div>
>     <div class="m-author__body">
>         <h3 class="m-author__title">Written by Emily Underhill</h3>
>         <p class="m-author__job">Senior Strategic Partnership & Engagement Manager</p>
>     </div>
> </div> 
> ```
> 
> You can see this working in pattern library as well http://development-initiatives.surge.sh/page-templates/12-blog-single

@davidebukali update `feature/patterns`, and since there's a code freeze on `develop`, you'll have to branch off `feature/patterns` to implement this.

**Comment by edwinmp** [comment]
@davidebukali `feature/patterns` has been merged into `develop` ... anyway, I'm free now, so I'll take this on :)

**Comment by edwinmp** [comment]
@benjamincoleman @BenDarby this is still displaying strangely ... but perhaps there's something we can do our end, like set the image height to 100%
https://devinit.org/blog/build-back-better-risk-informed-development-cooperation/

**Comment by benjamincoleman** [comment]
Looks like the markup is not right. The image is now used as a CSS background applied inline: 

so the code in the link you mention:

```
<div class="m-author__image">
    <img src="/media/images/Navid_Hanif.2e16d0ba.fill-80x80-c100.jpg" alt="Navid Hanif.jpeg">
</div>
```
Should be replaced with: 

```
<div class="m-author__image" style="background-image: url({{ global.assets_root }}/img/profile-fallback.jpg);"></div>
```

**Comment by edwinmp** [comment]
Ahh, right ... I was wondering what was different ... thought it was in the CSS ... thanks for clarifying.

**Comment by edwinmp** [comment]
@benjamincoleman just one problem ... it sort of folds in on itself when the content is short 
![image](https://user-images.githubusercontent.com/5672438/85310029-2670cf00-b4bc-11ea-9ef7-bab64135684f.png)

**Comment by benjamincoleman** [comment]
@BenDarby looks like we need to look at this when there's less content to force the width.

**Comment by BenDarby** [comment]
@benjamincoleman @edwinmp I have added `min-width: 300px;` to the author block to stop this from happening.

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives this is ready for testing on staging.

**Comment by AnnaHope** [comment]
sorry I can't see the difference with the current website and staging on this so can't work out if it is done although it looks fine.  @alice-mcandrew-development-initatives are you able to confirm? Here is an example on staging https://www.devinit.org/blog/build-back-better-risk-informed-development-cooperation/

**Comment by SimonMurphyDI** [comment]
Looks good to me, thanks

**Comment by SimonMurphyDI** [comment]
Thanks - is it possible to keep the name in bold and to pull through the individual's role too - important to keep consistency with others and to flag the author's credentials 
Best
Simon

**Comment by edwinmp** [comment]
@SimonMurphyDI the name is in bold and the role is showing as well ... 
![image](https://user-images.githubusercontent.com/5672438/86115278-68110380-bad4-11ea-91ee-35b38514b48f.png)

**Comment by SimonMurphyDI** [comment]
Sorry, wrong thread, this is fine :)
