### ISSUE TITLE
More about row not equal height

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#74]
http://development-initiatives.surge.sh/page-templates/19-vacancy-single

Edge/Win 10 / IE11/Win 7

#### More about row not equal height 

![Screenshot 2019-06-18 at 14 33 19](https://user-images.githubusercontent.com/560463/59688696-2584cd80-91d6-11e9-83ea-68384edd47e7.png)

**Comment by BenDarby** [comment]
This is working in Edge now, IE11 doesn't support equal height with css grid. I don't think that's a problem though.
