### ISSUE TITLE
T21 - Data section template update

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#751]
The current design here: http://development-initiatives.surge.sh/page-templates/21-data-section needs to be updated. This will replace this page on the website: https://devinit.org/data/

I've created a sketch for this here: https://marvelapp.com/3j51290/screen/67766242

Changes are: 

1. The content of the sub menu has changed
2. There's a tools module - check the note about the button and the title 'featured tools' being optional - the design needs to work with them removed too. 
3. Datasets module has been changed - there's now an intro, please use real content from the sketch file for this. 
4. The data support section is unchanged, but will be optional.

**Comment by BenDarby** [comment]
@benjamincoleman I have updated the data section template to include the changes mentioned above, the button and title in the tools section is optional, just removing these items will enough the design will adapt, and the data support section at the button can be optional by omitting the whole `<section>`
You can see the design here: http://development-initiatives.surge.sh/page-templates/21-data-section

**Comment by benjamincoleman** [comment]
Looks great @BenDarby

**Comment by benjamincoleman** [comment]
@BenDarby some updates on this design - http://development-initiatives.surge.sh/page-templates/21-data-section

Can we update the menu to have the following items: 

- Country Spotlights
- COVID tracker tool
- Another tool
- Datasets

**Comment by BenDarby** [comment]
@benjamincoleman I have updated the menu and deployed to surge as well

**Comment by k8hughes** [comment]
@edwinmp  I feel like the dev part of this work was in another ticket - do we need this?

**Comment by edwinmp** [comment]
True ... the template has been updated.
