### ISSUE TITLE
Historic publications (present page 30) display error

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#754]
This page doesn't seem to be displaying correctly: https://devinit.org/publications/?page=30

**1) Missing/jumbled content in one thumbnail**
![image](https://user-images.githubusercontent.com/55877063/82328403-ba400e80-99d7-11ea-84f3-514ae19ebe54.png)

**2) Thumbnails not completing 3x3 structure at bottom, despite there being another page to follow**
![image](https://user-images.githubusercontent.com/55877063/82328558-f8d5c900-99d7-11ea-9e75-710dca1df4b9.png)

**Comment by edwinmp** [comment]
Having content with links was messing up the markup ... removing the link from the excerpt (on the `Formation of African Union` card in the image above) was the quickest fix.

**Comment by SimonMurphyDI** [comment]
@edwinmp  looks like it's fixed and no need to deploy, 
Thanks!
S
