### ISSUE TITLE
Spotlight images are blurry

### ISSUE THREAD

**Issue by edwinmp** [devinit/DIwebsite-redesign#755]
## I'm submitting a ...
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**To Reproduce**
1. Go to 'https://devinit.org/data/spotlights-on-kenya-and-uganda/?nav=header'

**Expected Behaviour**
Not blurry

**Screenshots/GIF**
![image](https://user-images.githubusercontent.com/5672438/82351258-081f3b80-9a05-11ea-8d39-414e42f134dc.png)

Requested Delivery Date: ASAP

**Comment by edwinmp** [comment]
Hi @SimonMurphyDI ... this is fixed on staging. Please have a look and let me know if it's satisfactory ... http://staging.devinit.org/data/spotlights-on-kenya-and-uganda/?nav=header

**Comment by SimonMurphyDI** [comment]
@edwinmp  looks much sharper, thank you!
