### ISSUE TITLE
Full report report button is missing in publication menus

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#757]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
In long-form publications the 'view full report' button on menus is missing 

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'https://devinit.org/publications/donors-triple-nexus-lessons-sweden/executive-summary/
2. Click on the bottom right menu button
3. note there is no way to return to the full report 

**Expected Behaviour**
http://development-initiatives.surge.sh/page-templates/14-1-publication-long-form
See the designed menu here

Requested Delivery Date: dd/MMM/YYYY
This is a high priority for us - if you could fix it as soon as possible, that would be much appreciated

**Comment by edwinmp** [comment]
Hi @akmiller01, there's logic [here](https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/templates/publications/chapter-nav/nav.html#L22) that excludes this `View full report` button for `Publication Page` types. Any drawbacks in removing it?

**Comment by akmiller01** [comment]
Hey @edwinmp the logic was that the "View full report" button is for bringing you from a chapter subpage back to the main publication page. So that's why it wouldn't make sense to have "View full report" on the main PublicationPage or Short pub page.

But if that purpose has changed, we can remove the boolean.

**Comment by benjamincoleman** [comment]
@akmiller01 @edwinmp Just to chime in here...

I would recommend keeping the "View full report" button in view when we are in a long form publication, including the 'main publication page' or 'summary page' so the navigation is consistent. This is what we did on the GNR site - https://globalnutritionreport.org/reports/2020-global-nutrition-report/

I would not show it on short pub pages, as there is no 'summary page' to go to as they are single page publications.

**Comment by edwinmp** [comment]
That'd shorten the solution to simply removing `Publication Page` from the conditional ... let me do that and update the PR.

**Comment by edwinmp** [comment]
@SimonMurphyDI the fix for this is deployed on staging ... please have a look.
http://staging.devinit.org/resources/donors-triple-nexus-lessons-sweden/executive-summary/

**Comment by SimonMurphyDI** [comment]
Thanks @edwinmp 
Looking at this I realise the button will show for all publications (not just reports). Is it possible to amend the word 'report' to 'publication'. Sorry for that oversight on my part

![image](https://user-images.githubusercontent.com/22001094/84507643-120d2500-acb9-11ea-9fb5-cb871d9dc1a8.png)

**Comment by edwinmp** [comment]
@SimonMurphyDI the button has been updated

**Comment by SimonMurphyDI** [comment]
Thanks @edwinmp  this looks good to me!
