### ISSUE TITLE
Typo in 'Other pages' 'Learn more about Development Initiatives' text.

### ISSUE THREAD

**Issue by GeorgeCarver** [devinit/DIwebsite-redesign#759]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
When adding a vacancy child page, I noticed that there is a section called 'Other pages' at the bottom which is auto populated with 'Learn more about Developement Initiatives'. This has a typo in 'Developement', i.e. the extra 'e'. You can correct it on the page, and this doesn't appear on the live page anyway once published. However, I would like this to be corrected so we're reassured this isn't appearing anywhere else on the site.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.

**Expected Behaviour**
Typo is corrected.

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.
![image](https://user-images.githubusercontent.com/62111796/83869631-c7256780-a724-11ea-9838-e0bd1edaf911.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: dd/MMM/YYYY

**Comment by edwinmp** [comment]
Hi @GeorgeCarver ... this should be fixed on staging for all new vacancy pages (http://staging.devinit.org/admin/pages/635/add_subpage/)

**Comment by k8hughes** [comment]
@SimonMurphyDI  as we need to get this approved today so we can do a deployment - could you check this for us and give it a thumbs up?

**Comment by SimonMurphyDI** [comment]
@k8hughes  looks good!
