### ISSUE TITLE
Team profile grid display

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#77]
http://development-initiatives.surge.sh/page-templates/06-team-member#

IE11/Win 7

#### Grid display broken (equal and unequal height)

![Screenshot 2019-07-02 at 17 23 14](https://user-images.githubusercontent.com/560463/60529330-48db6c80-9cee-11e9-8a5b-0a6eecc1a506.png)

**Comment by BenDarby** [comment]
fallback math was incorrect, this is fixed now
