### ISSUE TITLE
Data section design update

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#772]
We have some changes to the data section to simplify the structure and design.  

Structurally, we won't have a Tools page, or a Country Spotlights page anymore. So the IA for this section updates to: 

![DI website IA v3 2](https://user-images.githubusercontent.com/64877/84657625-75db5c00-af0c-11ea-99e4-659e52b54e82.png)

**T21 Data page**

The design has been updated - http://development-initiatives.surge.sh/page-templates/21-data-section 

This will update this page - https://devinit.org/data/

We have the following on this page:

**Hero** - remove the dataset button
**Intro text** - as is there currently
**Tools** - for each tool we have a box with the following properties: 
- Title
- Description - richtext
- Image or video
- Button with custom label and link
**Datasets** - this currently exists on the page

---

Historical design notes:

Sketch: https://marvelapp.com/3j51290/screen/70158215

**T24 Country Spotlights**

Remove this template.

**Comment by BenDarby** [comment]
@benjamincoleman I have updated the T21 data section template to match the marvel screen. http://development-initiatives.surge.sh/page-templates/21-data-section

**Comment by benjamincoleman** [comment]
@BenDarby what do you think of the datasets / more about pieces being the same background colour? They blend in together too much for me.

**Comment by BenDarby** [comment]
@benjamincoleman Country spotlights template has been reinstated

**Comment by benjamincoleman** [comment]
@BenDarby some more changes on the Data template - 

Duplicate the "Country Spotlights" box, and set the two boxes to speak about each spotlight. So, we'll have Spotlight on Kenya, then Spotlight on Uganda. I've updated the sketch to reflect this: https://marvelapp.com/3j51290/screen/69215526

Also, delete T24 - http://development-initiatives.surge.sh/page-templates/24-country-spotlights we no longer need it.

**Comment by BenDarby** [comment]
@benjamincoleman I have updated the data section template and removed T24 as well. Let me know if that's all good now :) http://development-initiatives.surge.sh/page-templates/21-data-section

**Comment by benjamincoleman** [comment]
@k8hughes this issue is ready to go - it will update the data page. We could do with a quick browser test when this has been done on the `dev` site.

**Comment by k8hughes** [comment]
@edwinmp @davidebukali the design has been approved and this is ready to be done in dev now.  I am not sure who is best placed to do this?

**Comment by edwinmp** [comment]
> I am not sure who is best placed to do this?

I'll just leave it under `ToDo` ... either of us shall get it to when available.

**Comment by edwinmp** [comment]
@benjamincoleman @AnnaHope  removing the Country Spotlights page has major side-effects on the Spotlight page links - do we now want the spotlight links to be `/data/spotlight-uganda` or we keeping them in the format `data/spotlight-on-kenya-and-uganda/spotlight-uganda`

**Comment by benjamincoleman** [comment]
I recommend `/data/spotlight-uganda` with the following 301 redirects put in place: 

`data/spotlight-on-kenya-and-uganda/spotlight-uganda` > `data/spotlight-uganda`
`data/spotlight-on-kenya-and-uganda/spotlight-kenya` > `data/spotlight-kenya`
`data/spotlight-on-kenya-and-uganda/` > `data`

**Comment by edwinmp** [comment]
Great, will do @benjamincoleman

**Comment by edwinmp** [comment]
@k8hughes this is ready for review ... http://staging.devinit.org/data
The tools are added via a Banner Block
![image](https://user-images.githubusercontent.com/5672438/86141257-81c54180-bafa-11ea-9643-6c287961322f.png)

**Comment by k8hughes** [comment]
I just created two banners with dummy content - it seems to be working, now it just needs a comms review with correct content.

**Comment by AnnaHope** [comment]
@k8hughes  @edwinmp this doesn't look like the design http://development-initiatives.surge.sh/page-templates/21-data-section so I can't approve it.

**Comment by edwinmp** [comment]
@AnnaHope you added the banners in the wrong section ... they should be added under `tools`, not `sections`... also their appearance is managed under the banner configs i.e image orientation, background colour.

Sections is for any extra content ...

**Comment by edwinmp** [comment]
Ah, I've just noticed some differences here:
![image](https://user-images.githubusercontent.com/5672438/86225303-b84e9b00-bb92-11ea-9bc2-7a79da57a1da.png)

Will work on those ... thanks.

**Comment by AnnaHope** [comment]
> @AnnaHope you added the banners in the wrong section ... they should be added under `tools`, not `sections`... also their appearance is managed under the banner configs i.e image orientation, background colour.
> 
> Sections is for any extra content ...

I have no idea what you're referring to? @k8hughes was this you?

**Comment by edwinmp** [comment]
@AnnaHope this should be fixed now http://staging.devinit.org/data/

**Comment by AnnaHope** [comment]
@edwinmp great. I'm happy with this. When it goes live, I presume we 'lose' the current page' So how do I ensure the content that needs to be moved across is retained? Shall I put the content as it should be on staging so the content and new structure/functionality/design all goes across?

**Comment by edwinmp** [comment]
Actually we won't lose any of the current content on the `data` page ... we'll just need to add what's missing. It'll need to be added to the live CMS once we deploy (doesn't automatically get copied off staging) ... But you can add it on staging and I'll copy it once I deploy ...

**Comment by AnnaHope** [comment]
@edwinmp thank you! So I have done the content as I would like now. The only issue is the button on the spotlight on Uganda is off to the left rather than contained within the module it should sit in http://staging.devinit.org/data/

**Comment by AnnaHope** [comment]
once this is sorted it can be considered approved and ready for live

**Comment by edwinmp** [comment]
@benjamincoleman did we ever have a banner with left-oriented media & a button? Can't find one for reference on the PL 
![image](https://user-images.githubusercontent.com/5672438/86270916-b5749a00-bbd4-11ea-830f-cbaa7c052888.png)

Would be nice to have a page with these widgets in all their different variations - some have usages so rare it takes a while to find them on surge :)

**Comment by benjamincoleman** [comment]
> did we ever have a banner with left-oriented media & a button? 

@BenDarby can you remember building something like this, or do we have modifier classes that can be used? 

> Would be nice to have a page with these widgets in all their different variations

We have sometimes done that in pattern library builds, but it takes time to curate. I don't think there's budget available for this, unfortunately.

**Comment by edwinmp** [comment]
> > did we ever have a banner with left-oriented media & a button?
> 
> @BenDarby can you remember building something like this, or do we have modifier classes that can be used?

@benjamincoleman @BenDarby we got a response on this ... there's a dedicated issue for it here #857
