### ISSUE TITLE
Interactive visualisation module in publication

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#781]
Sketch here: https://marvelapp.com/3j51290/screen/57853947

**Want to do this work in the branch `visualistions_june_2020` and deploy to `di-vis.surge.sh`**

Adding a new type of chart module, which holds an interactive chart in it. 

We have the standard share function, title, source, data link for a chart module, but it will be interactive.

Russell has been adding charts to the [T25 template](https://di-vis.surge.sh/page-templates/25-visualisations) as a prototype, but we want to update [T14.1a Short form publications template](https://di-vis.surge.sh/page-templates/14-1a-publication-short-form) instead.

Will also have an accordion from the [what we do template](https://di-vis.surge.sh/page-templates/07-what-we-do) underneath each visualisation with instructions on how to use it as seen in the sketch. I'd like this to be unobtrusive though, so can we swap out for a light grey?

**Accessibility**

We want to have a fallback image of a chart here, can you include that as a `no-js` element?

**Comment by BenDarby** [comment]
@benjamincoleman I added one of the interactive charts to the publications template https://di-vis.surge.sh/page-templates/14-1-publication-long-form
Is this what you had in mind? Also when JS is disabled you get the standard responsive graph we use elsewhere.

**Comment by benjamincoleman** [comment]
@BenDarby thanks, some change requests for you: 

The accordion loses it's icon when it opens. See page here for it changing from a + to a x - https://devinit.org/what-we-do/?nav=header

Need to add the figure caption and source link as you see for the Fig 4.4 element: https://di-vis.surge.sh/page-templates/14-1-publication-long-form#2.1

**Comment by BenDarby** [comment]
@benjamincoleman I have updated this by adding the source link to the interactive chart and amending the colour of the accordion so the icon is always visible.

**Comment by benjamincoleman** [comment]
@BenDarby can you make the colour of the icons match the colour of the text label please?

**Comment by BenDarby** [comment]
@benjamincoleman I've implemented a workaround so we can change colour of the icon for the active state, grunticon doesn't allow us to do this so I have two icons in the markup and we show/hide depending on the sate.

**Comment by benjamincoleman** [comment]
@BenDarby we want to iterate the design of this. 

`.plotly-notifier` can be moved closer to the chart - interact with the chart by clicking and dragging a rectangle on the chart to see it appear in the top left. 

Add icons to the chart instructions as seen in the sketch - https://marvelapp.com/3j51290/screen/57853947

and below:

![Screenshot 2020-06-19 at 14 29 10](https://user-images.githubusercontent.com/64877/85137546-4b094480-b239-11ea-9e78-452a52fcc8eb.png)

**Comment by benjamincoleman** [comment]
@BenDarby quick update on this as well - can you give that module a unique ID so we can link to it please, currently it has a duplicate: 

https://di-vis.surge.sh/page-templates/14-1-publication-long-form**#2.1**

**Comment by BenDarby** [comment]
@urlsangel with moving the `.plotly-notifier` element closer to a chart, at the moment it gets added to the bottom of the <body> so I can only position relative to the viewport. Do you know if it's possible to append this element to a class? The `charts-container` for example, then I can position relative to the chart instead :)

**Comment by BenDarby** [comment]
@benjamincoleman will the icons be added via the CMS? Or is it something we'll add as a hardcoded icon when we know them?

**Comment by urlsangel** [comment]
> @urlsangel with moving the `.plotly-notifier` element closer to a chart, at the moment it gets added to the bottom of the so I can only position relative to the viewport. Do you know if it's possible to append this element to a class? The `charts-container` for example, then I can position relative to the chart instead :)

@benjamincoleman @BenDarby 

From the look of the DOM, there is only a single `.plotly-notifier` element created even if there is more than one chart is on the page, hence the position of this item being relative to the body/viewport rather than a chart.

We could probably add some JS that moves the element around on chart interactions, but it'd be good to check if this is what you want, as it's adding more complexity/points of failure etc.

**Comment by BenDarby** [comment]
@benjamincoleman @urlsangel I updated the accordion to display an icon list and changed the ID to something unique https://di-vis.surge.sh/page-templates/14-1-publication-long-form#visualisation 
With the `.plotly-notifier` I have amended the CSS so it's vertically positioned centrally in the viewport so it will generally appear closer to the charts in most use cases. If we wanted it to appear next to the chart at all times then we'll need to what Russell suggested but as it pointed out it could add more complexity and points of failure, wanted to check if @benjamincoleman was happy with how it currently is before we go down the more complex route.

**Comment by benjamincoleman** [comment]
> @benjamincoleman will the icons be added via the CMS? Or is it something we'll add as a hardcoded icon when we know them?

Uploaded via CMS. 

Do include the options for there not to be an icon too please

**Comment by benjamincoleman** [comment]
@BenDarby @urlsangel let's park the notifier work until later - may not need it.

**Comment by edwinmp** [comment]
@urlsangel there's a slight styling bug when rendering the caption at the bottom of the chart ... the top margin doesn't seem to appear as expected.
![image](https://user-images.githubusercontent.com/5672438/86006609-e612d300-ba1e-11ea-87b4-cd3146d84010.png)

**Comment by urlsangel** [comment]
@BenDarby @benjamincoleman 

Not sure if you're actioning a fix for @edwinmp's comment above?

https://github.com/devinit/DIwebsite-redesign/issues/781#issuecomment-651093580

This is because the accordion isn't present in the current Wagtail template - it's be good if the design can cope with this?

**Comment by benjamincoleman** [comment]
Ok, will update in the issue @BenDarby is working on other design edits.

**Comment by BenDarby** [comment]
@edwinmp this has been fixed now :)

**Comment by k8hughes** [comment]
Do we still need this issue @edwinmp ? or can we close it?

**Comment by SimonMurphyDI** [comment]
@k8hughes not sure I need to review this one?
