### ISSUE TITLE
Add field to Dataset and Figure Page to allow manually linking DataSource snippets

### ISSUE THREAD

**Issue by akmiller01** [devinit/DIwebsite-redesign#791]
Add field to Dataset and Figure Page to allow manually linking DataSource snippets

**Comment by k8hughes** [comment]
@davidebukali can you look at this issue next please?

**Comment by akmiller01** [comment]
Here's how it was done automatically: https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/common/management/commands/datasectionexcel.py#L292-L302

We need an field for users to select the Orderable `DataSetSource` on the DataSetPage CMS.
