### ISSUE TITLE
Resource (publication) pages displaying with a narrow width - and other visual issues

### ISSUE THREAD

**Issue by edwinmp** [devinit/DIwebsite-redesign#795]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[ ] Bug report 
[x] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**To Reproduce**
https://devinit.org/resources/status-disability-kenya-statistics-2019-census/

Testing will have to be on all publication page types to ensure they're displaying as expected.

**Expected Behaviour**
Review pattern library pages for publications http://development-initiatives.surge.sh/page-templates/

**Screenshots/GIF**

![image](https://user-images.githubusercontent.com/5672438/85021890-2babe200-b17b-11ea-8c64-2726a26281d1.png)

Requested Delivery Date: ASAP

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives staging has been updated for testing ... I've made changes to templates for the following pages: `Publication Chapter` , `Publication Summary`, `Short Publication`, and `Publication Appendix`

**Comment by alice-mcandrew-development-initatives** [comment]
Thanks @edwinmp. I will review these one by one (so they can potentially be picked up by someone else in comms if needed, @SimonMurphyDI, if I can't get to all of them today): 1) Publication Chapter , 2) Publication Summary, 3)Short Publication, and 4)Publication Appendix

So, firstly...
**1) Publication Chapter**

I've checked against this page: http://staging.devinit.org/resources/digital-civil-registration-and-legal-identity-systems/survey-data-birth-registration-coverage/

The width looks fine now. Thank you!

However, we appear to have lost the bold on first paragraph:
![image](https://user-images.githubusercontent.com/55877063/85023426-9f92be00-b16c-11ea-8a47-c9d2791a69db.png)

We also appear to have lost the block of colour to the left of section headings (which isn't in the pattern library but was an amended made and appears on the present site):
![image](https://user-images.githubusercontent.com/55877063/85023379-8ee24800-b16c-11ea-966d-7a3188367bef.png)

**Comment by edwinmp** [comment]
Looking at the same page, and the block of colour is still there, only it's following the appearance of the pattern library
Staging:
![image](https://user-images.githubusercontent.com/5672438/85026743-b8599e80-b181-11ea-8e4c-b708a3259adb.png)

PL (https://development-initiatives.surge.sh/page-templates/14-1f-publication-long-form-blue):
![image](https://user-images.githubusercontent.com/5672438/85026828-d921f400-b181-11ea-83f1-c7e7e8942c0b.png)

Let me fix the first paragraph boldness, thanks.

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives the bold first paragraph issue is fixed.

**Comment by AnnaHope** [comment]
@edwinmp sorry is this able to be pushed now? We are doing a lot of promotion to a publication right now so would be really great to have this sorted. @akmiller01 in case he has stopped working as I know it is late in Uganda.

**Comment by k8hughes** [comment]
I'm going to move this to the "deploy to live" colum as I'm understanding this is approved for deployment.

**Comment by k8hughes** [comment]
@edwinmp I think you moved this issue back to the comms review column, what review do we still require?  I thought this had been deployed already?

**Comment by edwinmp** [comment]
It was deployed in a rush before @alice-mcandrew-development-initatives finished all her testing ... we went on faith. A confirmation that everything is fine would be nice ... with publications, you can't be too careful.

**Comment by alice-mcandrew-development-initatives** [comment]
@k8hughes and @edwinmp I don't have time at the moment to do a methodical review all of the remaining page types (2) Publication Summary, 3) Short Publication, and 4) Publication Appendix) but I will flag to the team to see if anyone can fit this in or we can divide it between us

**Comment by edwinmp** [comment]
That's fine @alice-mcandrew-development-initatives ... we'll move this to done then. Any problems found can be logged as new issues.
