### ISSUE TITLE
T7: What we do

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#8]
Sketch: https://marvelapp.com/3j51290/screen/57215552

Design: http://development-initiatives.surge.sh/page-templates/07-what-we-do

Functional Specification:

**Hero**

Standard hero with `title` and `introduction`.

**Content**

Following the hero we have space for some rich text editor content

**Our focus areas**

Would be a list of items on this page alone. 

The button then links through to the page "Our Focus Areas" 

**Where we work**

This section shows a map of the world with a number of locations on it. For each location you need to provide a line of markup as follows: 

```
<div class="media-map__location__point" data-latlng="33.93911,67.709953" data-title="Afghanistan" data-desc="" data-tel="" data-email="" data-web=""></div>
```

The`data-latlng` can be got from a list of country latitudes and longitudes like this: https://developers.google.com/public-data/docs/canonical/countries_csv

On load, the JavaScript fires and produces a list from that markup. 

Underneath a map there is a button to link through to the "Where we work" page. 

**Our expertise**

An array of accordions each with 

- `title`
- `content` - this can be Rich Text Editor content, so would have links etc. 

**Call out module**

There is then an optional module that can be used as a call to action to view another section, in this case we think Data Services. For the module we have: 

- Image
- Image credit (capable of having a link in it)
- Module title
- Module content - rich text so can include links
- Module button - link location for the button
- Module button label - the text label of the button

**Our consultancy**

Here we introduce DI's consultancy services. 

We have the following: 

- Video (fallback to image)
- Content - rich text so can include links
- Button to link through to "Consultancy Services" page
- Quote with:
    - Quote
    - Citation (Name, Job Role, Organisation)
    - Image of person - optional

The idea is that we would have more than one quote in the system, and then show one at random when the page loads. 

**Impact**

A module to showcase the impact of the work that DI do. Includes the same as the **Call out module** I wrote about above. 

- Image
- Image credit (capable of having a link in it)
- Module title
- Module content - rich text so can include links
- Module button - link location for the button
- Module button label - the text label of the button

**Comment by benjamincoleman** [comment]
> This needs to have a section on ‘places we work in’ right? So it navigates to that page. This should come under our focus areas. So we need to showcase a preview of the ‘places we work’ content there to navigate.

> Also just want to make sure it is all editable - it’s not ideal having what we do as the page and then a subheading of our work - we should remove the subheading ideally as the page already has this. The button on find out more should just say ‘find out more’ rather than the whole sentence, but again, is that text editable? If not please edit down.

**Comment by benjamincoleman** [comment]
There are 6 focus areas:

Items in brackets are the projects I think

1.    **Measuring progress of the poorest people** (P20 and inclusion, GNR)
2.    **Revolutionizing Data to Leave No-one Behind** (country level work to improve data systems, focus on disaggregated data esp disability data, UNICEF work on data mapping, CRVS, World Data Forum, Partnership with UBOS & GPSDD – Data Charter, Data for Development Nepal)
3.    **Increasing transparency and effectiveness of humanitarian financing** (cash transfers, GHA report, multi-year funding work etc, Syria tracking, Grand Bargain)
4.    **Increasing transparency and effectiveness of development finance** (IATI, sector analysis, ITEP, blended finance, GNR)
5.    **Increasing transparency and effectiveness of domestic financing** (country level budget analysis, tracking nutrition financing, GNR, DRM)
6.    **Building Data Savvy Partners** – (Data Support Service, trainings and capacity building of CSOs and officials, building tools to increase data use (Cloudera pilot in Uganda which improves Spotlights for use))

Places we work - show the Map - shallower though.

**Comment by BenDarby** [comment]
@benjamincoleman updated this and left in the lorem descriptions for each focus area, I can remove this though if it's not needed

**Comment by benjamincoleman** [comment]
@BenDarby looking at the section below: 

![Screen Shot 2019-08-01 at 13 32 40](https://user-images.githubusercontent.com/64877/62293593-dd0d3080-b460-11e9-91de-30d94ff8c0ab.png)

Please remove the paragraph so we just have the image and title. 

As these are not interactive we think it would be good to change the design to make sure they are visually different to the other cards you see in blog for example.  

This is similar to the edit to #4

**Comment by benjamincoleman** [comment]
> These still feel clickable by use of the big image. What would work better we think, is to use the approach you have done with our values on the who we are page and we will source and send an icon that denotes ‘focus’ to be used identically across each.

**Comment by BenDarby** [comment]
I'll source an svg version of this icon instead of png

**Comment by benjamincoleman** [comment]
@BenDarby sorry, can we have a different icon rather than a crosshair? 

![share](https://user-images.githubusercontent.com/64877/62542038-ecbab980-b852-11e9-9f4e-9b350a33d0c1.png)

**Comment by benjamincoleman** [comment]
@BenDarby sorry dude, another change to this - rather than the icon can we have some random little squares from the brand? 

> What if we just go for some little DI squares or something? Do we need an actual icon?

**Comment by k8hughes** [comment]
http://178.128.102.213/what-we-do/ 

I tried to add the location map, as per design, but it isn't showing. @edwinmp is this user error or a bug?

**Comment by edwinmp** [comment]
@k8hughes it's not an error ... you need to have Office Locations added in the `Snippets` first, with coordinates. Without coordinates, the map won't show.

![image](https://user-images.githubusercontent.com/5672438/63832959-8cfb8e00-c97a-11e9-8268-6c5c646c9acb.png)

But yes, there is a bug ... even with coordinates, it's showing the map but not showing the locations. Let me move this and fix.

**Comment by urlsangel** [comment]
Hi @edwinmp 

Not sure if it's useful, but there's a package for Wagtail that lets you use a Google Map as a location picker in the CMS edit screen - it'll then populate and format a lat/lng field for you (which is much easier for CMS editors): 

https://pypi.org/project/wagtailgmaps/

**Comment by k8hughes** [comment]
In the CMS it should be possible to write the button text on the map, but there is no input field for this.

![Screenshot 2019-09-25 at 10 43 24](https://user-images.githubusercontent.com/36768381/65589663-5321a580-df81-11e9-87c7-25405507b310.png)

**Comment by edwinmp** [comment]
Hi @k8hughes ... that's not a bug. It's weird though & can be confusing ... this wasn't the case when I initially built this, but it seems there was an update to Wagtail. Anyway, the fields below `button`, i.e Caption, Url, and Page, all belong to the button field and are where the info is added.

**Comment by edwinmp** [comment]
![image](https://user-images.githubusercontent.com/5672438/65683102-1d55ed00-e065-11e9-9d33-0c7d3bc5b2dd.png)
Better?

**Comment by k8hughes** [comment]
I still can't work out how to get the text button that I have tried to create to match the pattern library version of the design.  Here is a screen shot of staging vs pattern library.  
![Screenshot 2019-10-10 at 14 17 02](https://user-images.githubusercontent.com/36768381/66572417-d25dce80-eb68-11e9-9838-efbee2e55225.png)

I have tried a couple of places adding button captions but none of these are showing on the page.  this might be user error and maybe I am doing something wrong. @edwinmp can you explain why what I do in the CMS doesnt create the button?

**Comment by edwinmp** [comment]
![image](https://user-images.githubusercontent.com/5672438/66637719-3beae500-ec1c-11e9-8838-4f1dead4b524.png)

It seems the majority of button occurrences are confusing now ... will need to fix that. In the meantime, just specify a caption and a URL or Page.

**Comment by k8hughes** [comment]
I already have that text in that box but it doesn't result in a button, do you get a button from doing that?

**Comment by k8hughes** [comment]
Ooo maybe I have worked it out, is the issue that a URL needs to be specified?  
What is weird here as a user is that elsewhere in the CMS when adding an internal link you do it by selecting it within the CMS rather than free text.
It might also be worth having something that tells the user they need to add a URL...
@edwinmp

**Comment by edwinmp** [comment]
It has support for both ... You have to specify either a URL or a Page ... You can see both options in the screenshot. But yeah, this whole bit has become confusing since the UI changed. Will fix it. I remember you raised a similar issue elsewhere.

**Comment by edwinmp** [comment]
@k8hughes I settled on the view below... there's a noticeable indentation that groups the fields. Also added some info to describe their purpose.

**Comment by k8hughes** [comment]
This is perfect 👍
