### ISSUE TITLE
CMS Editable Call to Action

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#801]
This is a new request from the comms team.

They want a pop up form, that would be editable in the CMS that allows for sign up to our mailing list.
The use case is this:  when the GHA report launches the PDF of the report will not be online, this will come a week or so later so we want users to see this pop up when they view the HTML version of the report giving them a chance to sign up to get an email when the PDF is ready.

I'm not sure how we are collecting email addresses on the website is it via a mail chimp pop up or via the CRM?

It would be good to have a quick chat about the implementation of this before someone starts to work on the issue to make sure that we get it right.

**Comment by k8hughes** [comment]
@alice-mcandrew-development-initatives hopefully this sounds about right to you.  I am not sure if we can have a form from mail chimp be editiable so it might have to be a two step process ie:
Step one: CMS editable pop up appears, it has a link to the form you fill in to sign up to get the report
Step two: user see the form to fill in for mailchimp or the CRM

Note for the devs - we'd want these email addresses to go to a special list obviously...

**Comment by alice-mcandrew-development-initatives** [comment]
@k8hughes Explanation looks spot on and definitely sounds sensible to talk through before starting
@AnnaHope or @jamesharle Can you advise from your perspective on how best to have this integrated with mailchimp or crm?

**Comment by edwinmp** [comment]
@k8hughes @benjamincoleman  I think this may require a design

**Comment by k8hughes** [comment]
@benjamincoleman it would be good to speak about a design for this, but it would take a second place after the data vis work obviously!

**Comment by benjamincoleman** [comment]
@k8hughes

The question is really around how disruptive to the user viewing the report you want this to be. 

I can see two options for this: 

1. Pop up which takes over the screen, which is disruptive - the user would need to close the pop up to read the report. 
2. Call to action models designed in the page - less disruptive, but potentially less uptake. 

I would have the following content for each option: 

- Title
- Richtext
- Button

And the button I would link out to the native Mailchimp form page in a new tab, which is how the DI newsletter works currently. 

Let me know what you think.

**Comment by k8hughes** [comment]
@alice-mcandrew-development-initatives @AnnaHope @jamesharle if you can confirm with Ben how you want this to function then we can get a design to work from, there are two options to choose from above.

**Comment by alice-mcandrew-development-initatives** [comment]
@SimonMurphyDI ^

**Comment by jamesharle** [comment]
@k8hughes @benjamincoleman Can we have option 2 please? And this can direct to the DI Newsletter mailchimp sign-up (we actually have a GHA-specific list, but I think it makes most sense to direct users to the overall newsletter)

**Comment by benjamincoleman** [comment]
@jamesharle sure. 

As a specification, I'm assuming the following: 

1. The pop up can be applied to a specific publication, rather than being a site-wide thing. 
2. If set on a publication which has sections, it will appear on all pages in that publication. 
3. The pop up will link to any external URL, so this can be linked to any Mailchimp form or other links to surveys for example. 
4. Users should be able to dismiss it, in which case it will set a cookie with an expiry of 2 weeks. 

I'll get something sketched up and ready for review.

**Comment by jamesharle** [comment]
@benjamincoleman  sorry I'm confused - by option two I meant where you said 'Call to action module designed in the page - less disruptive, but potentially less uptake.', and I had understood from this that this option wasn't a pop-up? Perhaps that's just my reading of this, but want to make sure we're on the same page.

That notwithstanding, I agree with all four of those clarifications (though as per above I struggle to visualise how a module of the page would be dismissed?)

**Comment by benjamincoleman** [comment]
Sorry - my fault, it's not a pop-up! I'll amend the message above :)

**Comment by jamesharle** [comment]
No worries! Perfect, thanks Ben :)

**Comment by benjamincoleman** [comment]
Hi @jamesharle 

I've created a sketch for this which you can see here: https://marvelapp.com/prototype/3j51290/screen/57853947

Two things to review: 

1. The in page call to action - no visual design as yet, but I'm assuming you would like this to stand out. 

2. Global alert - something we've added to IATI that would be easy to port over. Seemed this could be useful, and the dev team could lift the code from IATI for this - http://iati.surge.sh/page-templates/0-home

**Comment by BenDarby** [comment]
@benjamincoleman I have added the CTA module to the short form and long form templates so we can see how they look with the different colours as well, the standard one is here http://development-initiatives.surge.sh/page-templates/14-1-publication-long-form this will fit anywhere in the site, the variations on the colour specific long form templates match the body class of that page. The notification message from IATI has also been added

**Comment by benjamincoleman** [comment]
@BenDarby that's great, can you check it working on the following templates too: 

* http://development-initiatives.surge.sh/page-templates/14-publication-summary
* http://development-initiatives.surge.sh/page-templates/14-1a-publication-short-form
* http://development-initiatives.surge.sh/page-templates/12-blog-single

**Comment by BenDarby** [comment]
@benjamincoleman added the CTA module to these templates too 😄

**Comment by benjamincoleman** [comment]
@BenDarby can you ensure authors appear above the CTA

e.g. http://development-initiatives.surge.sh/page-templates/14-1a-publication-short-form

**Comment by BenDarby** [comment]
@benjamincoleman updated the template show CTA module appearing after authors

**Comment by benjamincoleman** [comment]
@k8hughes 

We have the new CTA block ready for development. 

We've designed this to work in publications (renamed resources?) and blog posts (for flexibility). I think the immediate requirement is for this to work in publications though, we added it to the blog posts for flexibility. 

You can see the designs here: 

- http://development-initiatives.surge.sh/page-templates/14-publication-summary
- http://development-initiatives.surge.sh/page-templates/14-1-publication-long-form
- http://development-initiatives.surge.sh/page-templates/14-1a-publication-short-form
- http://development-initiatives.surge.sh/page-templates/12-blog-single

In terms of content management I would expect to see the following fields:

- Title (text field)
- Description (richtext editor)
- Button label (text field)
- Button URL (text field or URL)

On long form publications I would expect the CTA block to be managed from the summary (main) page, and appear on all child pages.

**Comment by k8hughes** [comment]
@davidebukali or @edwinmp who ever is available first, if you could look at this that would be great.
I'm assuming this will be @davidebukali but tagging you both just in case.

**Comment by edwinmp** [comment]
@k8hughes this has been deployed to staging.

**Comment by k8hughes** [comment]
I'll move it to the comms review space so the comms team can confirm they are happy with it.

**Comment by SimonMurphyDI** [comment]
This works, for James, but I was getting real issue with slow load, before I got kicked out of the Staging site. @k8hughes can you test this and OK it? I can't 
S

**Comment by k8hughes** [comment]
@edwinmp was this deployed?

**Comment by edwinmp** [comment]
Yes it was @k8hughes
