### ISSUE TITLE
Setup a zero downtime deployment

### ISSUE THREAD

**Issue by mariamiah** [devinit/DIwebsite-redesign#802]
**Is your feature request related to a problem? Please describe.**
Currently there is downtime whenever a fresh deployment is made which makes the application inaccessible for a few minutes.. 

**Describe the solution you'd like**
There is need to set up a zero downtime deployment

**Describe alternatives you've considered**
Blue green deployment  where there is gradual transfer of user traffic from a previous version of an app  to another version—both of which are running in production. 

The old version may be the blue environment while the new version may be the green environment. Once production traffic is fully transferred from blue to green, blue can be stopped

**Additional context**

**Requested Delivery Date:** dd/MMM/YYYY

**Comment by edwinmp** [comment]
@mariamiah anything pending on this? If not, move to `Deploy to live`
