### ISSUE TITLE
Related content should not include current page

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#809]
The current page should not be able to appear in the related content section. E.g. https://devinit.org/resources/kenyas-201920-budget-and-the-big-four-agenda-a-pro-poor-analysis/

**Comment by k8hughes** [comment]
This looks good to me now: http://staging.devinit.org/resources/kenyas-201920-budget-and-the-big-four-agenda-a-pro-poor-analysis/

**Comment by SimonMurphyDI** [comment]
I still seem able to do this? Saved a published page here. 
http://staging.devinit.org/resources/kenyas-201920-budget-and-the-big-four-agenda-a-pro-poor-analysis/
