### ISSUE TITLE
Update chart configuration options

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#810]
Updating the config options.

**Downloading**

https://plotly.com/javascript/configuration-options/#customize-download-plot-options

**Size**

Russ, I would like to try a couple of settings to see how this behaves. Does it expand the chart to fit the width and height and therefore stretch it? 

So, let's try: 

- [x] 1200px square
- [x] 1200 x 900px
- [x] 1200 x 675px

**Format** to be PNG

**Scale** maybe play with this and see what you think

---

**Modebar**

https://plotly.com/javascript/configuration-options/#force-the-modebar-to-always-be-visible

Always show the modebar

---

**Remove modebar buttons**

https://plotly.com/javascript/configuration-options/#remove-modebar-buttons

Remove:
- pan2d
- select2d
- lasso2d
- hoverClosestCartesian
- hoverCompareCartesian
- toggleSpikelines

That works out as `modeBarButtonsToRemove:['pan2d','select2d','lasso2d','hoverClosestCartesian','hoverCompareCartesian','toggleSpikelines']` as worked out here: https://codepen.io/bencoleman/pen/NWxaaQa

---

**Make responsive**

Already done but adding here for completeness.

https://plotly.com/javascript/configuration-options/#making-a-responsive-chart

---

**Edit chart link**

Does this link to the Plotly chart in Chartstudio? If so might be handy

Add a link to edit the chart: https://plotly.com/javascript/configuration-options/#display-the-%60edit-chart%60-link

**Notes**

`Plotly.restyle` is of interest, as shown in this example, in case we need this for future work: https://plotly.com/javascript/configuration-options/#add-buttons-to-modebar

**Comment by urlsangel** [comment]
@benjamincoleman 

Here's the chart downloads as png and at your specified dimensions above:

#### 1200x1200
![newplot (5)](https://user-images.githubusercontent.com/560463/86020517-ea8bbb80-ba1f-11ea-92d4-7952d659339c.png)

#### 1200x900
![newplot (1)](https://user-images.githubusercontent.com/560463/86020480-e19aea00-ba1f-11ea-8ebb-903b0241a2d9.png)

#### 1200x675
![newplot (2)](https://user-images.githubusercontent.com/560463/86020510-e95a8e80-ba1f-11ea-8d75-936d2e493e1f.png)

I outputted the same files with scale `1` and `2` and it had zero effect as far as I can tell.

**Comment by urlsangel** [comment]
@benjamincoleman 

These options have been updated on the PL and pushed to surge:

https://di-vis.surge.sh/page-templates/26-interactive-visualisation

Could you let me know what options you want carried over to production once you've reviewed?
