### ISSUE TITLE
Chart colourways

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#811]
Been working on this with Anna. 

Have updated the pattern lib with the secondary colour palette from the brand doc (attached). 

[DI Brand Book - update July 2018.pdf](https://github.com/devinit/DIwebsite-redesign/files/4845886/DI.Brand.Book.-.update.July.2018.pdf)

Also added a rainbow colourway.

https://di-vis.surge.sh/style-guide/colour

**Comment by benjamincoleman** [comment]
Need to update to include 12 colours for the rainbow to make things more distinct.

**Comment by benjamincoleman** [comment]
12 colours: 

`["#e84439","#eb642b","#f49b21","#109e68","#0089cc","#893f90","#c2135b","#f8c1b2","#fccc8e","#f6bb9d","#92cba9","#88bae5","#c189bb","#e4819b"]`

**Comment by benjamincoleman** [comment]
@urlsangel here's the updated 12 colours

**Comment by benjamincoleman** [comment]
From Anna regarding rules of using colourways: 

1. Lower or equal than 8 items, use the colourway from the publication. 

2. Above 8 items use the rainbow colourway

3. Use light grey #D9D4DA for no data (I can't see where this is used - if we have no data there won't be anything to colour)

Colours are in the pattern library: https://di-vis.surge.sh/style-guide/colour

**Comment by urlsangel** [comment]
@benjamincoleman 

Couple of questions:

> Lower or equal than 8 items, use the colourway from the publication.

`Redscale extended` has no body class reference, is that because this is the default?

> Above 8 items use the rainbow colourway

Is that specifically the `Rainbowscale 12a` colourway?

**Comment by urlsangel** [comment]
@benjamincoleman 

Also, what's our default if we don't have a legend to use as an item list (Treemaps for instance)?

**Comment by benjamincoleman** [comment]
1. The default has no body class. 

2. Yep, 12a is the one, just updated and pushed now as there was a mistake in the order

`["#e84439","#eb642b","#f49b21","#109e68","#0089cc","#893f90","#c2135b","#f8c1b2","#f6bb9d","#fccc8e","#92cba9","#88bae5","#c189bb","#e4819b"]`

3. Default colour? The DI red.

**Comment by urlsangel** [comment]
@benjamincoleman 

Is the order correct for the "themes"? The lighter elements are going to come first, which seems counter-intuitive to me - see the screenshot for example:

<img width="1087" alt="Screenshot 2020-07-08 at 10 46 37" src="https://user-images.githubusercontent.com/560463/86904286-61a00e80-c108-11ea-82a2-b786616278fc.png">

**Comment by benjamincoleman** [comment]
Er yes, that should start with the darkest I would say

**Comment by urlsangel** [comment]
@benjamincoleman 

Cool, I'll reverse them in the code 👍

**Comment by urlsangel** [comment]
@benjamincoleman 

Just spotted in my test `factsheet` locally - `body--poppy`:

<img width="421" alt="Screenshot 2020-07-08 at 11 48 54" src="https://user-images.githubusercontent.com/560463/86910114-16d6c480-c111-11ea-94a3-a82fc3d3afae.png">
