### ISSUE TITLE
Update chart style to match brand

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#817]
Need to update the style of this to match the DI brand book - 
[DI Brand Book - update July 2018.pdf](https://github.com/devinit/DIwebsite-redesign/files/4856869/DI.Brand.Book.-.update.July.2018.pdf)

Page 48 - 58 covers charts. 

We'll need to look at all charts on this template: https://di-vis.surge.sh/page-templates/25-visualisations

To include: 

- [x] fonts - colours / weight
- [x] line colours - axis, grid lines etc

Where we cannot match the brand, can you make a note so we can state the things we can't do, or look at doing them in plotly?

**Comment by BenDarby** [comment]
@benjamincoleman I've updated the charts to match the DI brand, there's no mention of font size on labels etc so I have left them how they are. The rule lines are set to the right colour grey but they look quite dark compared to the brand book PDF, I double-checked the values in the PL and they match the brand book.
