### ISSUE TITLE
Blog profile images look odd

### ISSUE THREAD

**Issue by jamesharle** [devinit/DIwebsite-redesign#826]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
As per Slack thread here [https://devinitorg.slack.com/archives/CCG8Y0YJG/p1593787921104000] the blog profile images are not looking as we'd want them. Ideally height of the picture would increase to accommodate larger titles, but the height would not reduce below a 1:1 aspect ratio (as it does for this blog for example: https://devinit.org/blog/what-do-trends-uks-aid-spending-nutrition-tell-us/). It would also be good if the overall blog listing page reverted to the original design.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.

**Expected Behaviour**
A clear and concise description of what you expected to happen

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: dd/MMM/YYYY

**Comment by edwinmp** [comment]
@jamesharle this is ready to test on staging http://staging.devinit.org/blog/?nav=header

**Comment by jamesharle** [comment]
Thanks @edwinmp ! Is it possible to:
1) Set a 1:1 ratio as the minimum for the profile pictures as they appear on the individual blog pages? Ie. The pictures are never shorter than they are wide?
2) On the listings page, ensure that the image is aligned to the centre of the title text? Currently, for Gorik Ooms blog for example, his picture is appearing above his name and title. Ideally the vertical centre of the image would align with the vertical centre of the text box.

**Comment by jamesharle** [comment]
To show what I mean:

![Capture](https://user-images.githubusercontent.com/43270042/86930468-f9185800-c12e-11ea-97fd-9a812e7c8970.JPG)

![Capture](https://user-images.githubusercontent.com/43270042/86930976-7cd24480-c12f-11ea-8142-d90d16f5469b.JPG)

**Comment by edwinmp** [comment]
@jamesharle thanks for the visual aid ... I think those changes will need @benjamincoleman's input ...

**Comment by benjamincoleman** [comment]
@BenDarby we want to force a min-height to produce the effect @jamesharle has described above.

**Comment by benjamincoleman** [comment]
@BenDarby 

Let's use this template to sort out the listings:  http://development-initiatives.surge.sh/page-templates/11-blog-listing

- [ ] Add `min-height: 81px` to the `.m-author__image` to make sure the images is square or portrait but never landscape
- [ ] Add real content to the different listings to include
   - images for guest authors
   - ridiculously long job titles
 
And for the single page template: http://development-initiatives.surge.sh/page-templates/12a-blog-single-guest

- [ ] Add `min-height: 81px` to the `.m-author__image` to make sure the images is square or portrait but never landscape

**Comment by BenDarby** [comment]
@benjamincoleman Added min-height to author image, added images for guest authors and updated listing template to include long multi-line Job titles

**Comment by benjamincoleman** [comment]
@edwinmp @davidebukali I think you've spotted this, but @BenDarby has applied some fixes to the author profiles images for you

**Comment by edwinmp** [comment]
@benjamincoleman @BenDarby is it possible to have the images on the blog listing centered relative to the text without stretching them, as in @jamesharle's first image above. Currently, the result is as below:
![image](https://user-images.githubusercontent.com/5672438/87510187-c5cc5080-c67b-11ea-8c53-f04696053263.png)

**Comment by BenDarby** [comment]
@edwinmp I'm not sure aligning the image centrally to the text is the right way as the balance will appear off visually when there is a lot of text, I can add a max-height to the image element though so the image doesn't stretch to fill the space.

**Comment by jamesharle** [comment]
Cool, that sounds fine to me @BenDarby :)

**Comment by BenDarby** [comment]
@jamesharle @edwinmp @k8hughes I have added a max height to the image element now and pushed to the `pattern_library` feature branch

**Comment by k8hughes** [comment]
@jamesharle can you confirm this looks as you expected it to?

**Comment by jamesharle** [comment]
@k8hughes sure - so where am I checking it? On the pattern library at these links?

http://development-initiatives.surge.sh/page-templates/11-blog-listing

http://development-initiatives.surge.sh/page-templates/12a-blog-single-guest

**Comment by k8hughes** [comment]
If you can check on staging that it has come over correctly?  http://staging.devinit.org/blog/?nav=header

**Comment by jamesharle** [comment]
Thanks @k8hughes! Yep, looks good by us :)
