### ISSUE TITLE
T6 Team Profile

### ISSUE THREAD

**Issue by Napho** [devinit/DIwebsite-redesign#83]

**Comment by k8hughes** [comment]
I tested this by creating profiles for Alex and for myself.  As soon as I added an image for my profile it appear for Alex as well.

![Screenshot 2019-07-18 at 14 32 40](https://user-images.githubusercontent.com/36768381/61462069-f21a9780-a969-11e9-8580-ba911ea9211d.png)

Particularly with this part of the website we don't want iages looping a some members of staff don't wan to have pictures.

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/102 Should fix profile image bleed.

**Comment by akmiller01** [comment]
Just merged #102 @k8hughes so it should be deployed within a few minutes. I've tested it locally, so hopefully no more need to test in staging since it involves erasing images directly from the server!

**Comment by k8hughes** [comment]
This now is working, my picture doesn't carry over to your name, but  think we need to change the default position of where the text appear in the case where there is no image so that it aligns at the bottom.
![Screenshot 2019-07-19 at 14 16 00](https://user-images.githubusercontent.com/36768381/61537778-dda0d280-aa2f-11e9-8462-115babbd8fb7.png)

**Comment by edwinmp** [comment]
@akmiller01 @k8hughes is there anything still pending on this?

**Comment by k8hughes** [comment]
I think we are waiting for fffunction to align the text at the bottom in the case where there is no image, so they were going to make a channge in the pattern library.

**Comment by edwinmp** [comment]
Yup, that'd be great... let me check on their branch and see if they've pushed the change.

**Comment by benjamincoleman** [comment]
@edwinmp we're going to create a fallback image for people with no image, rather than changing the markup / CSS for when that happens. @BenDarby can you do this ASAP please - I think this is the last thing blocking completion of the template

**Comment by k8hughes** [comment]
@BenDarby do you know when you'll be able to look at this for us?

**Comment by BenDarby** [comment]
@k8hughes fallback image added and can be seen on these two templates: 
http://development-initiatives.surge.sh/page-templates/12a-blog-single-guest
http://development-initiatives.surge.sh/page-templates/05-our-team

**Comment by akmiller01** [comment]
@BenDarby would it be possible to get a gender neutral placeholder? Just implementing it now and I realized it may be a little confusing for users:

![image](https://user-images.githubusercontent.com/2836840/61810096-8b372b80-ae0c-11e9-8fb6-66e3daa4db05.png)

**Comment by benjamincoleman** [comment]
@akmiller01 we'll get this for you, it should also be used for the Blog Guest author #12 if no image is available.

**Comment by BenDarby** [comment]
@akmiller01 @benjamincoleman this has been updated now
