### ISSUE TITLE
Exclude items from the select drop-down or/and the aggregated chart

### ISSUE THREAD

**Issue by edwinmp** [devinit/DIwebsite-redesign#833]
**Is your feature request related to a problem? Please describe.**
Currently, we cannot exclude items from the drop-down or the aggregated stacked bar chart

**Describe the solution you'd like**
To use the example of the `Total IHA from public donors by donor, 2010-2019` chart [here](http://178.62.8.61/resources/test-charts/):

I'd like to have EU Institutions appear in the select drop-down, but excluded from the aggregated stacked chart that's shown on selecting `All data`.

**Comment by edwinmp** [comment]
Deployed to Viz testing:
http://178.62.8.61/visualisations/total-official-ha-oda-recipient-country-2009-2018/
http://178.62.8.61/visualisations/total-iha-public-donors-donor-2000-2019/

**Comment by k8hughes** [comment]
This needs to be checked by someone with understanding of the data, probably Danielle.
