### ISSUE TITLE
The drop-down on one chart is broken

### ISSUE THREAD

**Issue by edwinmp** [devinit/DIwebsite-redesign#837]
On the `20 largest recipients of IHA, 2009-2018` chart [here](http://178.62.8.61/resources/test-charts/), selecting countries from the drop-down doesn't change the chart.

Dev Note: Not sure how, but the `groupby` transformation generated for this chart has incorrect values in its `styles` property. A solution would be to check the `groups` array for the currently selected item, and if found, update the `styles` array, adding missing groups as you go.

**Comment by k8hughes** [comment]
This looks like it is working now.

**Comment by SimonMurphyDI** [comment]
the drop down seems to work for me too
