### ISSUE TITLE
Add a Wagtail configurable prefix and suffix to charts

### ISSUE THREAD

**Issue by edwinmp** [devinit/DIwebsite-redesign#838]

**Comment by edwinmp** [comment]
![image](https://user-images.githubusercontent.com/5672438/87658706-3bf8b200-c765-11ea-9156-2b959b991a79.png)

**Comment by k8hughes** [comment]
Moving this to comms review so @SimonMurphyDI can check this off as he adds content.

**Comment by SimonMurphyDI** [comment]
@k8hughes do far the charts are working well for me. Not sure what I need to review here
Best
S

**Comment by k8hughes** [comment]
@edwinmp  - my understanding is that this issues is so that the Y axis and X axis can be edited in wagtail. If it is working then you can just approve I think.
