### ISSUE TITLE
Add URL to PNG download in charts

### ISSUE THREAD

**Issue by edwinmp** [devinit/DIwebsite-redesign#839]

**Comment by k8hughes** [comment]
When I open the downloaded PNG the URL is now at the top.

**Comment by edwinmp** [comment]
I think it'd be better to use the more specific URL that's generated by the `SHARE CHART` button ... I'll make the change.
![image](https://user-images.githubusercontent.com/5672438/87453413-23748480-c60b-11ea-8a7a-9aed0c05b57b.png)

**Comment by edwinmp** [comment]
Have updated this to use the share URL.

**Comment by SimonMurphyDI** [comment]
I think this is just for the interactive charts?
The link I'm getting isn't the page title, which is what the users will want toi see

**Comment by edwinmp** [comment]
@SimonMurphyDI this is the share link ... if you don't wish for me to shorten it, I'll change it to add the whole link ... they'll both lead to the same place
![image](https://user-images.githubusercontent.com/5672438/87923781-a4f26980-ca86-11ea-9834-794a1afee9cf.png)

**Comment by edwinmp** [comment]
I suggest you keep the short link though ... some of the publications have very long titles.

**Comment by SimonMurphyDI** [comment]
Yes, I agree, but I think better to have the whole link, thanks!
