### ISSUE TITLE
Adding data modules - issue with left-aligning content 

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#857]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**

When adding a module to the data page, selecting 'media orientation', 'left' means the button overhangs the edge of the box

![image](https://user-images.githubusercontent.com/22001094/88038437-1e00c800-cb3e-11ea-8883-25c33ea90f36.png)

**Expected Behaviour**
The button appears with appropriate spacing, as on the right hand side

Requested Delivery Date: Not urgent

**Comment by BenDarby** [comment]
@edwinmp I have pushed a fix so the button doesn't overlap, I added the variation to the pattern library so you can see how it works now http://development-initiatives.surge.sh/page-templates/21-data-section

**Comment by edwinmp** [comment]
@SimonMurphyDI a fix for this has been deployed to staging http://staging.devinit.org/data/

**Comment by alice-mcandrew-development-initatives** [comment]
@edwinmp Looks good to me!
