### ISSUE TITLE
Topics appearing on dataset page that were not added via tags on cms

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#858]
See Dataset Page for Global Humanitarian Assistance Report 2020: https://devinit.org/admin/pages/2110/edit/preview/

These topics are appearing: 
![image](https://user-images.githubusercontent.com/55877063/88040606-0aa32c00-cb41-11ea-954a-49bdee97aa87.png)

Only some were added via tags on cms:
![image](https://user-images.githubusercontent.com/55877063/88040660-20b0ec80-cb41-11ea-8a02-5c7683752717.png)

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives a fix for this was deployed to staging ... sorry, forgot to alert you.

**Comment by alice-mcandrew-development-initatives** [comment]
@edwinmp This looks good on staging 👍
