### ISSUE TITLE
White object on mobile device chapter menu

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#862]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**

When viewing the pop-up menu for the multi-page GHA report there's a white object over some of the text
![Screenshot_20200721-222320](https://user-images.githubusercontent.com/22001094/88108649-158da900-cba1-11ea-816b-83e4bcbd9add.png)

**To Reproduce**

Visit the GHA report using a mobile device and select the menu from the bottom right: the chapter titles on the menu are part obscured by a white object

**Expected Behaviour**

No white object over the chapter titles 

**Smartphone (please complete the following information):**
 - Device: iPhoneX - Chrome simulator

**Environment/Server:**
<pre><code>
- [x] Production
- [x] Staging
- [x] Development
</code></pre>

Requested Delivery Date:

It would be good to fix this as soon as possible.

**Comment by edwinmp** [comment]
@benjamincoleman this happens on the PL as well for small devices
![image](https://user-images.githubusercontent.com/5672438/88126133-8c469880-cbd9-11ea-8eaa-fcd650b858a1.png)

**Comment by benjamincoleman** [comment]
@BenDarby can you have a look at this small screen bug please? 

You can see it in the pattern library here: http://development-initiatives.surge.sh/page-templates/14-1b-publication-long-form-pink

and on the live site here: https://devinit.org/resources/global-humanitarian-assistance-report-2020/

**Comment by BenDarby** [comment]
@edwinmp There was a small issue with the CSS so I have pushed a CSS fix for this on the `pattern_library` feature branch

**Comment by edwinmp** [comment]
@SimonMurphyDI a fix for this is deployed on staging
http://staging.devinit.org/resources/global-humanitarian-assistance-report-2019/executive-summary/

**Comment by alice-mcandrew-development-initatives** [comment]
@edwinmp This looks good to me on staging (but, again, worth noting that I'm on a an Android not iPhone)
