### ISSUE TITLE
Text in tables resizes in mobile view

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#864]
## I'm submitting a ...
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**

When reading the report on a mobile device the text in tables appears in different sizes (it's fine on desktop)

**To Reproduce**

Visit this page on a mobile: https://devinit.org/76125c#section-5-1

**Expected Behaviour**

text to be be consistent size

**Screenshots/GIF**

![Screenshot_20200721-234028](https://user-images.githubusercontent.com/22001094/88149661-4baa4780-cbf8-11ea-94b3-cb403411d05f.png)

**Smartphone (please complete the following information):**
 - Device: iPhone X - chrome simulator

**Environment/Server:**
<pre><code>
- [x] Production
- [x] Staging
- [x] Development
</code></pre>

Requested Delivery Date: 

Low priority

**Comment by edwinmp** [comment]
This is related to issue #863 ... the fix there applies here as well.
