### ISSUE TITLE
'Audio and visual media pages' can't display in featured content on homepage

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#866]
## I'm submitting a ...
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**

Not quite a bug, but the new 'Audio and visual media pages' format doesn't seem to be one we can choose as featured content on the homepage - it would be great if this was an option. 

**To Reproduce**

Go to the homepage in the CMS, and try to add our new GHA animation as featured content, it doesn't appear in the menu

**Expected Behaviour**

Would be good if audio/visual content could be chosen as featured content

Requested Delivery Date: 

Ideally asap, but we can use the legacy format if needed to share the GHA event :)

**Comment by edwinmp** [comment]
@SimonMurphyDI what exactly would you like to appear on the home page for this type of page?
@k8hughes I don't think the AudioVisualMedia page went through FF for its design... makes such enhancements tricky.

**Comment by k8hughes** [comment]
Yeah - we just adapted a general page.  Ideally we don't want to have to go to Ben's team for every design tweek, it is helpful to be able to do simple stuff with our own inhouse team.

**Comment by edwinmp** [comment]
@SimonMurphyDI this is now possible on staging 
![image](https://user-images.githubusercontent.com/5672438/88694481-46be2a00-d109-11ea-9389-8636c82e377b.png)

**Comment by alice-mcandrew-development-initatives** [comment]
@edwinmp  Weirdly, this didn't seem to work when I tried it: 
![image](https://user-images.githubusercontent.com/55877063/88819847-7415e100-d1b8-11ea-9ace-ca7bd8b1edee.png)

**Comment by edwinmp** [comment]
Tried it just now on staging and it's working as expected ... @k8hughes could you please give it a go
Edit Home Page -> Hero Section -> Featured page -> Choose another page
`Audio and Visual Media Page` should be listed in the alert at the top of the popup

**Comment by k8hughes** [comment]
@edwinmp it doesn't show in the alert list for me either, I see the same thing as Alice posted.

**Comment by edwinmp** [comment]
hmm ... tested on two other browsers and incognito, I see it's fine ... so, probably a cache issue.

**Comment by alice-mcandrew-development-initatives** [comment]
I cleared my cache and got the same behaviour @edwinmp 
Any luck @k8hughes?

**Comment by edwinmp** [comment]
I have no added an Audio & Visual Media page as the feature page ... do you see it on the home page? http://staging.devinit.org/ @alice-mcandrew-development-initatives

**Comment by alice-mcandrew-development-initatives** [comment]
Yes!
