### ISSUE TITLE
Set SSL certificate up for longer on the Spotlight API - we also need the documentation for how to renew this saved in the repo

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#867]
Can we check all DI products SSL certficates?

**Comment by akmiller01** [comment]
Making a list of all servers I know of that have SSL certificates. Can you think of any more @devinit/di-website-internal ?

- [ ] (www.)devinit.org
- [ ] api.devinit.org
- [ ] ddw.devinit.org

**Comment by k8hughes** [comment]
@edwinmp @davidebukali does this sound like everything?

**Comment by edwinmp** [comment]
Yup, that's all ...

**Comment by akmiller01** [comment]
api and ddw are sorted with their respective certbot.sh files.

devinit.org is still awaiting this PR to merge, and then we're sorted for automatic SSL refreshes. https://github.com/devinit/DIwebsite-redesign/pull/874

We probably should program in an SSL monitor that emails one of us when an expected refresh fails.
