### ISSUE TITLE
Set up a droplet with HTTPS

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#869]

**Comment by k8hughes** [comment]
@mariamiah is this now done?

**Comment by mariamiah** [comment]
yes it's done

**Comment by k8hughes** [comment]
could you just confirm the address so we have a record on the issue?  Will all testing be done on this version of staging from now on?  If so we need to also update all the comms team in slack

**Comment by edwinmp** [comment]
@k8hughes that definitely would be ideal ... I'd not considered since I thought the certificates where purchased ... @mariamiah you may as well pull this one down and update our usual staging to be https.
