### ISSUE TITLE
Improving the data for download section  - part three

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#880]
Metadata collection

Simon emailed the template the comms team currently use - I tried to attach it here but I wasn't able to, hopefully you have it in your inbox.
Here is the link for the googlesheet where we collected info from the R&A team to launch the section:  https://docs.google.com/spreadsheets/d/1pDbdncnm1TF41kJJX2WjZ2Wq9juOvUqU/edit#gid=1029209261 

We need to have a google form that is the only way a user can populate the google sheet that will reduce the margin for error.  Once we have a form we can share it with the comms team for review and then discuss the system with the R&A team.

**Comment by akmiller01** [comment]
Hi @SimonMurphyDI , tried making your template the cover sheet of the Spotlight XLSXs and I realized it's not a very good meta-data fit for whole datasets. It seems like it's more for individual figures. Could we do some work to make those fields more dataset specific?

E.g. 
[Spotlight_on_Kenya.xlsx](https://github.com/devinit/DIwebsite-redesign/files/5036270/Spotlight_on_Kenya.xlsx)

**Comment by k8hughes** [comment]
@SimonMurphyDI following our last discussion I think we've agreed that you'll produce a metadata colection sheet that fit what your team will be filling in on wagtail, and Alex and I will do the update wth the R&A team to support their buy in.  Does that sound ok to you?

**Comment by SimonMurphyDI** [comment]
@k8hughes we've shared this with you, and you have shared this with Bill. Not a priority but keen we reach a resolution that works for all 
S
