### ISSUE TITLE
Hero Text not displaying on Legacy pages

### ISSUE THREAD

**Issue by sarahharries66** [devinit/DIwebsite-redesign#882]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
Hero Text not displaying on Legacy pages.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to  https://devinit.org/resources/how-aid-being-impacted-covid-19-and-why-it-so-hard-find-out/
2. observe lack of hero text on live page
3. compare with hero text box in CMS page, which is populated

**Expected Behaviour**
We expect the hero text to display.

**Desktop (please complete the following information):**

Requested Delivery Date: dd/MMM/YYYY

**Comment by mariamiah** [comment]
@sarahharries66  please review the changes made for this issue here https://dev.devinit.org/. You should now be able to view hero text for legacy pages.

**Comment by sarahharries66** [comment]
Hello, seems to be working well, thankyou

**Comment by edwinmp** [comment]
Hi @sarahharries66 this has been deployed live.
