### ISSUE TITLE
Website not linking audio and visual media pages as related links and featured content

### ISSUE THREAD

**Issue by sarahharries66** [devinit/DIwebsite-redesign#885]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x ] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
We tried to add 'Audio and visual media pages' (which are a child of the 'Resources' page) as Related links on a blog page, and as featured content on the homepage, we weren't able to

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Navigate to blog pages and home page 
2. observe lack of audio and visual media content as related content on blogs, and featured content on homepages
3. See error

**Expected Behaviour**
We'd like to be able to add audio and visual media pages as related content across all pages (that are designed to show related content), and on the homepage as featured content

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: dd/MMM/YYYY

**Comment by mariamiah** [comment]
@sarahharries66  this has been fixed, please review `https://dev.devinit.org`

**Comment by sarahharries66** [comment]
Hello, also seems to be working well, thankyou

**Comment by edwinmp** [comment]
Hi @sarahharries66 this has been deployed live.
