### ISSUE TITLE
display of 3 digit notes

### ISSUE THREAD

**Issue by CeliaWarin** [devinit/DIwebsite-redesign#886]
## I'm submitting a ...

[X ] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
We need to add additional space between note and text for 3 digit notes so consistent with 1 and 2 digit notes and legible  

![image](https://user-images.githubusercontent.com/70264269/91550306-44c1d380-e920-11ea-8825-46dfc05cc2a5.png)

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'https://devinit.org/resources/socioeconomic-impact-of-covid-19-in-uganda/'
2. Scroll down to Notes

**Expected Behaviour**
Text is aligned and there is a space between note and text

**Desktop (please complete the following information):**
n/a 

**Smartphone (please complete the following information):**
n/a

**Comment by edwinmp** [comment]
@CeliaWarin please test a fix for this [here](https://dev.devinit.org/resources/socioeconomic-impact-of-covid-19-in-uganda/)

**Comment by CeliaWarin** [comment]
Hi Edwin,

I’ve tested and works fine thanks.

Best
Celia

**Comment by CeliaWarin** [comment]
Hi Edwin,

I’ve tested and published the page and seems to be working fine – thanks.

Best
Celia
