### ISSUE TITLE
Block quote functionality missing from Short publication and Publication page templates in Resources

### ISSUE THREAD

**Issue by CeliaWarin** [devinit/DIwebsite-redesign#887]
## I'm submitting a ...

<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
In resources, the Short Publication template and Publication Page (including child pages Publication Summary, Publication Appendix and Publication Chapter and Publication Foreword) are missing the Block quote:

![image](https://user-images.githubusercontent.com/70264269/91853907-cdab7880-ec5a-11ea-920f-911051ec5bbf.png)

This is available on other pages such as blogs:

![image](https://user-images.githubusercontent.com/70264269/91854043-051a2500-ec5b-11ea-9f2a-727d02d79517.png)

According to the pattern library, this should also be available on these pages: 
http://development-initiatives.surge.sh/page-templates/14-1a-publication-short-form
http://development-initiatives.surge.sh/page-templates/14-1-publication-long-form
http://development-initiatives.surge.sh/page-templates/14-2-publication-appendix

This means we're currently having to format quotes using bold and italics in the Wysiwyg editor which leads to a lack of consistency across the website. 

For example, a quote on the pubs pages styled in the Wysiwyg editor:
![image](https://user-images.githubusercontent.com/70264269/91854097-20853000-ec5b-11ea-9215-8f2a8d647698.png)

A correctly styled quote on another page using the Block quote:
![image](https://user-images.githubusercontent.com/70264269/91854222-50343800-ec5b-11ea-84ea-c70682e11582.png)

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to 'https://devinit.org/admin/pages/352/ - Pages > Homepage > Resources'
2. Click on 'Add child page'
3. Click on '+Short Publication' 
4. Scroll down to 'Content'
5. You will see on the content menu that there is no option for Block quote

**Expected Behaviour**
When adding content blocks to a Short publication page or Publication page (including child pages Publication Summary, Publication Appendix and Publication Chapter and Publication Foreword), the option to create a Block quote should be available, i.e. 

![image](https://user-images.githubusercontent.com/70264269/91854043-051a2500-ec5b-11ea-9f2a-727d02d79517.png)

**Comment by mariamiah** [comment]
@CeliaWarin please review the changes made for this issue here `https://dev.devinit.org/`. I added the missing Block quote functionality for  the Short Publication template, Publication Page and the child pages
![blockquote](https://user-images.githubusercontent.com/39744587/92234172-39d7e780-eeba-11ea-9c89-327a1125a81e.png)

**Comment by CeliaWarin** [comment]
Thanks Maria, I’ve now checked this and moved to ready to deploy to live.

Best
Celia

**Comment by edwinmp** [comment]
Hi @CeliaWarin this has been deployed live.
