### ISSUE TITLE
Examples of our work for the Consultancy page: bugs  

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#896]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**

Our consultancy services page (https://devinit.org/what-we-do/consultancy-services) has the option to add examples of our work (see the template here: http://development-initiatives.surge.sh/page-templates/09-consultancy-services

We've created the content for these example pages, and uploaded them as child pages of the consultancy page. 

When we moderate them in draft form there are two issues. 

1) the menu (see scree grab) is empty - I'd expect it to show content in the same way the Our work in Nepal page does (https://devinit.org/what-we-do/where-we-work/our-work-nepal/) - both with a full menu, and the breadcrumb trail 
![image](https://user-images.githubusercontent.com/22001094/92225748-9546ad00-ee9b-11ea-92c5-5ea8896260e0.png)

2) We added related links at the bottom of the pages we've created, but these don't pull through when the page is moderated 

@AnnaHope looping you in to make sure I've correctly interpreted how we want the menu element to appear on these pages (as there isn't a design for the consultancy example page) also sharing with @CeliaWarin who's been working on this 

Best
S

Requested Delivery Date: 01/10/2020

**Comment by edwinmp** [comment]
@SimonMurphyDI draft pages won't show up in related links.

**Comment by SimonMurphyDI** [comment]
@edwinmp of course, thank you

**Comment by SimonMurphyDI** [comment]
Hi @edwinmp @k8hughes - just to flag this is now a priority from our point of view - is it possible to have an estimated delivery date?
Thank you!
Simon

**Comment by edwinmp** [comment]
Hi @SimonMurphyDI this can be done today & deployed latest tomorrow morning ... would be great if everything in comms review is tested before then.

**Comment by SimonMurphyDI** [comment]
Thanks Edwin, we’ll look into this asap – have mentioned to Sarah and Celia 😊

**Comment by CeliaWarin** [comment]
Hi Edwin,

Just to let you know I’ve checked the relevant ticket on github and have moved to ready to deploy to live.

Best
Celia

**Comment by edwinmp** [comment]
@SimonMurphyDI this is now fixed ... though I had to replace the `General Page` with a `Standard Page` ... `General Pages` aren't configured to appear as u required that deep, and only Standard pages have breadcrumbs

**Comment by SimonMurphyDI** [comment]
Thanks @edwinmp 

Just tested this on dev and I can see the child page option is now a standard page rather than a general page - good to know. 

Three questions it would be great to have your thoughts on

1) we've prepared four pages of content as 'general pages' - is it possible to amend these to standard pages without re-adding all the content again?

2) while populating a 'standard page' to test the menu, I tried adding content into a paragraph block, but it wasn't possible to type into the block. The draft I made is online here: https://dev.devinit.org/admin/pages/add/home/standardpage/622/

![image](https://user-images.githubusercontent.com/22001094/92714353-0252ba80-f354-11ea-90e5-c1bab76acbf9.png)

3) Lastly there any difference (apart from the breadcrumbs/menu) between general and standard? Just so I know for future reference?

Thanks so much - sorry for the additional questions 
Simon

**Comment by edwinmp** [comment]
The main difference besides breadcrumbs is what's shown on the secondary menu ... as you realised when you tried with a `General Page`, they can only show parent menus. In this case, u wanted to show the menu of a grandparent ... `StandardPages` can manage that... Let me think of a better way to handle this kind of situation, cos you may want to go even deeper & neither page can handle that.

As for the strange paragraph error, thats happening for me too ... looking into it.

**Comment by SimonMurphyDI** [comment]
Thanks so much - let me know how you get on (and good luck :) )

**Comment by edwinmp** [comment]
Oh, another difference is that the `Standard Page` shows related links while the `General Page` shows "more about" links as shown below ... I'm including both of them, you decide which one works for you.
![image](https://user-images.githubusercontent.com/5672438/92729222-b23b1e80-f37a-11ea-9025-8e158570198f.png)

**Comment by edwinmp** [comment]
@SimonMurphyDI all issues fixed ... also added a checkbox to the general page that toggles breadcrumbs
![image](https://user-images.githubusercontent.com/5672438/92751733-ed484c80-f390-11ea-9e57-9f79d351d540.png)

**Comment by SimonMurphyDI** [comment]
@edwinmp thanks - the checkbox works well and it will save us needing to recreate this content in a different page style. 

I'm wondering if it's potentially confusing to have two very similar pages as options for child pages? Do you know why there are two kinds? If there's a reason to have them both, we can be sure to follow the rule. 

The paragraph block still isn't working for me!

**Comment by edwinmp** [comment]
Actually the decision for these was mainly because of the `More about` & `Related content` sections ... any page can be added to a `More about` section, but only a select few can appear in the `Related content` format ... I could add a setting that determines which version is used on any particular General Page, then remove the Standard Page entirely ... no worries, it won't affect any existing pages.

**Comment by SimonMurphyDI** [comment]
@jamesharle I'm in the office and can't get onto the staging to check this. (Although it's not working on my phone either....)
Could you or @sarahharries66 check to see if this is fixed and ready for deployment?
Thanks :)
S

**Comment by SimonMurphyDI** [comment]
@edwinmp 

The paragraph blocks are working (thanks @sarahharries66) so it sounds like this update is fixed.

We have the general pages ready in draft on the CMS - if you push it live - two questions 
1) will it automatically appear in the draft pages that we've made?
2) will it change anything about any live general pages already published on the website? 

After we know that, we might want to consider updating the information architecture, so we know what page types to use for which kind of content. After that would be the best time to confirm deleting the standard page works for everyone!

**Comment by edwinmp** [comment]
Hi @SimonMurphyDI 

1. Yes (the fields will appear - you'll need to update the pages to show breadcrumbs since the default is to hide them)
2. No (this was very important)

**Comment by edwinmp** [comment]
Hi @SimonMurphyDI this has been deployed live.

**Comment by SimonMurphyDI** [comment]
Thanks so much for this - it looks great. Two requests based on how it's deployed, which has pulled through this dropdown

![image](https://user-images.githubusercontent.com/22001094/94404858-9223a180-0167-11eb-8c54-fd7e9fe7d4b8.png)

1) Is there a way to set it so the drop-down appears only when there are a certain number of examples of out work? (I guess nine would make sense visually). At the moment there's no need to filter as the total number of examples (4) can all be seen at once 

2) When we have 9+ examples, will you let us know how we can tag the examples so the dropdown functions well (can't see that tagging option in the example pages)? At the moment (selecting 'poverty' the only option, refreshes the page and removes the examples of our work from the page. 

Thanks so much for helping to get this live. Really appreciate it. 
Cheers
Simon

**Comment by edwinmp** [comment]
@SimonMurphyDI a fix for the section in the comment above has been deployed on staging ... please verify https://dev.devinit.org/admin/pages/622/edit/

Changed the behaviour of the filter to not refresh the page or require clicking the filter button

**Comment by SimonMurphyDI** [comment]
@edwinmp afraid I can't load a preview on Dev.Devinit at the moment but if you send a screengrab I can check that?
S

**Comment by edwinmp** [comment]
Takes a while, but it loads ... anyway, this is deployed live (couldn't be avoided since some p20 viz change needed to go live), so you can test there since staging is giving u trouble ... the change above can't be tested in preview though.

**Comment by SimonMurphyDI** [comment]
@edwinmp you are such a star - thank you. I wish we worked in the same office so I could get you a nice coffee or some cake.
