### ISSUE TITLE
T4: Our Story

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#9]
Sketch: https://marvelapp.com/3j51290/screen/57215551

Design: http://development-initiatives.surge.sh/page-templates/04-our-story

Functional Specification:

**Hero:** 

In this hero we have the variant which shows what it looks like with no image. However, it should be capable of taking an image. That means it would be the same as #5 for example and would have the following content: 

- Image
- Image credit (capable of having a link in it)
- Title
- Subtitle

**Content**

Under the hero we have some rich text content

**Timeline**

So here we have a complicated timeline to do. What we want to produce is the following mark up structure in the pattern library. It iterates over a data array so would be similar to what you'll need in building the CMS: 

```
<div class="carousel">
    <div class="slider timeline" id="timeline-control">
        {% for item in timeline.timeline_list %}
        <div class="timeline__item"><span><span class="timeline__item__month">{{ item.month }}</span><span class="timeline__item__year">{{ item.year }}</span></span></div>
        {% endfor %}
    </div>
    <div class="slider highlight" id="timeline-slide">
        {% for item in timeline.timeline_list %}
            <div class="l-highlight" id="{{ item.month }}{{ item.year }}">
                <div class="l-highlight__main">
                    <span class="highlight__flag">{{ item.month }} {{ item.year }}</span>
                    <h3 class="highlight__heading">{{ item.title }}</h3>
                    <div class="is-typeset">
                        <p>{{ item.content }}</p>
                    </div>
                    <div class="button button--faux button--icon">
                        <i role="presentation" aria-hidden="true" class="ico ico--24 ico-download-poppy"></i>
                        <span class="button--faux__meta">Download</span>
                        {% for download in item.downloads %}
                            <h3 class="button--faux__heading">{{ download_title }}</h3>
                            <ul class="button--faux__list">
                                {% for file in download_files %}
                                    <li><a href="#">{{ file.file_label }}</a></li>
                                {% endfor %}
                            </ul>
                        {% endfor %}
                    </div>
                </div>
                <div class="l-highlight__aside">
                    <div class="highlight__media">
                        <img src="{{ image }}" alt="alt tag">
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
```

What we're producing from the same data is two lists - one for the **control list** with the month/year used as a control, and the second for the **content list** which animates. 

**Control list**

For each timeline point we want to show: 

- month
- year

**Content list**

For each content 'slide' we want to show: 

- Month & Year
- Title
- Content - rich text please so it can take formatting (bold / italic) and links
- Downloads (optional) - this uses a standard download pattern we use elsewhere, where admins can upload multiple formats of the same file
- Image

**Impact call to action module**

- Image
- Image credit (capable of having a link in it)
- Module title
- Module content - rich text so can include links

Then we have either, downloads, or a button:

- Downloads - multiple formats of the same file - as use elsewhere. 

or

- Module button - link location for the button
- Module button label - the text label of the button

---

Older content ⏬ 

# 🎯 Template Purpose

The purpose of the ‘Our Story’ section is to establish credibility and trust by sharing key milestones in DI's history and the impact of their work. 

**The ‘Our Story’ section answers the following user questions:**

* What type of organisation is DI?
* What is the goal of DI?
* How did DI begin?
* What has DI achieved since it began?
* Is DI trustworthy?

# 🗂 Template details

**Template Number and variation**

Adaptation of [T1 General] (https://git.fffunction.co/fffunction/development-initiatives/issues/3) with additional fields for:
* DI interactive timeline

**Sketch:**

https://marvelapp.com/1b2f486g/screen/51358457

**Placeholder copy:**

https://docs.google.com/document/d/189yGB2-x6CfU4GSOmTDtUrvISY46W5r0FwYXSLEgHyQ/edit

# 📋 Template spec

**Modules (as per spec for this template in IA):**

**Side menu**
* Who we are
* **Our Story - active**
* Meet the team
* Our Strategy
* Finances

**Page title**

Succinct one line overview

**Timeline**

*  Allow 10 milestones on each timeline at any one time - allow DI to choose which milestones they want to display
*  Each milestone to include:
- year and milestone title
- copy 
- image (optional)or video (optional)
- primary CTA (optional)
- button download full timeline (optional)

**Download full report**
- button to download full report (optional)

**Impact Report**

*  Image
*  Title
*  Copy
*  Download 2017 Impact Report

**Comment by benjamincoleman** [comment]
Slider complete, needs testing.

**Comment by BenDarby** [comment]
Tested in Chome, Firefox, Safari, Edge, IE11, iPad and Google Pixel 3 and it all looked good

**Comment by benjamincoleman** [comment]
Timeline - change to have the month and year in the buttons.
Impact section - Download, or Button “View the impact report”.

**Comment by BenDarby** [comment]
That's what I was thinking about too, it looks good to me

**Comment by benjamincoleman** [comment]
@BenDarby Cool - can you add the download button in the impact report module: http://development-initiatives.surge.sh/page-templates/04-our-story

**Comment by BenDarby** [comment]
@benjamincoleman there's a download button already, unless you just want a standard button instead?

**Comment by benjamincoleman** [comment]
@BenDarby Sorry, yes - a standard button, then it's an option of downloads, or the button.

**Comment by k8hughes** [comment]
http://178.128.102.213/who-we-are/our-story/ 

Quick question from me about how the timeline builds.  I think it is the last thing a user enters that appears at the start of the timeline, am I correct?

As a user, if after 1 year I want to add a new event to the end of the timeline, how do I do this?  Can I reorder within the CMS?  Or do we need to change the logic here?

**Comment by benjamincoleman** [comment]
@k8hughes I would recommend a datetime here - then you can order by changing the day in the month. 

We agreed in design that if there are two events in a month (unlikely) it's ok to just show them adjacently in the same month. 

Datetime would allow that, and any ordering required.

**Comment by k8hughes** [comment]
@akmiller01 if they can be reordered then that is good, can we add a sentance of instruction to the CMS to tell a user which end of the timeline they should enter first so it is clear for them what to do to get it to appear in date order on live?  It would be quite fiddly to add everything and have to reorder it all afterwards.

**Comment by k8hughes** [comment]
OK LGTM than :)
