### ISSUE TITLE
Date format to be uniform

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#90]
Date style to be 16 Month Year (cut the th, or ly, or rd); I note this is different in the blog listing. We should have the one date style only.

**Comment by alice-mcandrew-development-initatives** [comment]
@benjamincoleman (You are probably already aware of this but) this is also the case for vacancies.

At the moment:
![Format of dates live](https://user-images.githubusercontent.com/55877063/67222054-7165ae80-f424-11e9-809a-4958521cacd1.JPG)

What it should look like:
![Format of dates pattern](https://user-images.githubusercontent.com/55877063/67222058-775b8f80-f424-11e9-9aed-edca1c0fe97a.JPG)

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/343
