### ISSUE TITLE
Play tracking tag to track future podcast plays 

### ISSUE THREAD

**Issue by sarahharries66** [devinit/DIwebsite-redesign#902]
Hi this is a new request, so that we can start to upload our own audio instead of embedding soundcloud links.

We get analytics on media plays via soundcloud, so in order to switch our audio hosting we need a custom tag set up in Google Tag Manager to track media plays as Analytics Events.

Hopefully this should be simple, but it does require custom code, so would be great if we could get some dev support!

**Requested Delivery Date:** 18/09/2020

**Comment by sarahharries66** [comment]
Hi guys, are there any updates on this?

**Comment by edwinmp** [comment]
Hi @sarahharries66 ... not yet. We've been pulled away by other priorities. Don't hesitate to stick a `Priority` label on it. Usually gets things moving faster :)

**Comment by sarahharries66** [comment]
no worries! was mentioned to me that this would be good to have by the end of the month, but currently not priority :)

**Comment by edwinmp** [comment]
@sarahharries66 have added analytics for this ... tracks play, percentage played & pause.

**Comment by sarahharries66** [comment]
Thankyou!
