### ISSUE TITLE
Minify app.bundle.js, if expedient, compress JS and CSS

### ISSUE THREAD

**Issue by akmiller01** [devinit/DIwebsite-redesign#903]
app.bundle.js is not minified, and it represents a significant page-load time for people on slow networks:

![image](https://user-images.githubusercontent.com/2836840/93762698-190fd180-fbde-11ea-9cd0-79645466b76b.png)

Would help a lot if we could minify it. And I don't know if we've ever gotten around to compressing JS and CSS, but that could also help with page load.

**Comment by edwinmp** [comment]
@akmiller01 this is minified ...  you had pretty-print on.
