### ISSUE TITLE
P20 line charts to Chart Studio format

### ISSUE THREAD

**Issue by akmiller01** [devinit/DIwebsite-redesign#904]
Made test line chart here: https://dev.devinit.org/data/line-chart-test/

Already I can see the JSON only contains X and Y, which would make it unable to apply post-process filtering. I'm trying to find ways to stuff more metadata into the Chart Studio so all of my additional variables end up in the JSON, but I'm struggling with the interface.

So far, splitting the trace by country name is a good start, but it looks like I'm only allowed one split per trace:

![image](https://user-images.githubusercontent.com/2836840/93791893-cd235380-fc02-11ea-89ea-c146fab9647b.png)

Which means I cannot split by: P20/Extreme poverty, Pre/Post Covid, Estimate/Non-estimate... I don't know if any additional functionality on our side would enable this functionality.

**Comment by akmiller01** [comment]
Able to make more complicated line charts in R, but so far the JSON output embedded in the R output is dissimilar to the JSON output from Chart Studio: 

![image](https://user-images.githubusercontent.com/2836840/93792253-491d9b80-fc03-11ea-8d48-2d2fd8de3d2c.png)

Tried pasting the JSON from this chart into the DI website and it fails to load: https://dev.devinit.org/visualisations/test-line-chart-2/

**Comment by k8hughes** [comment]
@edwinmp would you be able to take a look at these two charts and have a think about our options before Alex gets online today?
I'll put in some time for us all to talk later.

**Comment by edwinmp** [comment]
I've come to a single conclusion on this ...not sure you'll like it, but ... I'll pitch it anyway :)

**Comment by edwinmp** [comment]
Hi @SimonMurphyDI we've added a few test charts to staging. Could you take a look and give any feedback

To avoid any confusion, I renamed the old visualisation pages to `Plotly Studio Chart Page` and the new ones `Advanced Chart Page` ... the can both be added to the content section of any resource page

![image](https://user-images.githubusercontent.com/5672438/94899618-4e4cd700-049c-11eb-96b3-9f0f8ccf8694.png)

With the Advanced Charts, we can create charts using 3 highly flexible libraries, d3, Plotly & ECharts ... the links below show a sample d3 and ECharts visualisations of the same data. 

D3: https://dev.devinit.org/visualisations/advanced-chart-d3/

ECharts: https://dev.devinit.org/visualisations/advanced-chart-echart/

**Comment by k8hughes** [comment]
@edwinmp   I get error messages at those links, are you sure they are working?

**Comment by edwinmp** [comment]
You need to be logged in to view the charts on their original pages.

**Comment by SimonMurphyDI** [comment]
Thanks @edwinmp - I guess we should prioritise feedback in the style that's going to be used in the P20 visualisation - that's D3 right?

**Comment by alice-mcandrew-development-initatives** [comment]
I was asked to take a look at this and have added to the feedback document, under the heading 'ROUND THREE - Feedback from Alice': https://docs.google.com/document/d/1GVNdIJwyMz0A8_LHn3qLZAar_roYU5ujj7WwAFwqois/edit# 

I've divided my feedback into: general questions; feedback on D3 based on Alex's designs; suggestions for Alex's design; proofreading comments for Simon; and copy for the instructions. I hope this is helpful. Let me know if anything is unclear.

**Comment by alice-mcandrew-development-initatives** [comment]
(I should have tagged you @akmiller01 and @edwinmp)

**Comment by akmiller01** [comment]
Hi @alice-mcandrew-development-initatives , thanks for your feedback.

All copy around the charts (title, notes at the bottom, instructions at the bottom) will be added in the CMS and freely editable. I'll try and incorporate all of your notes about what to write in those sections when I make the draft charts, but I imagine someone from comms will be writing the final versions.

All text will be in Geomanist font automatically (as it is on dev); Github pages is incapable of pulling the font files from a different domain.

I'm a little hesitant to reduce the spacing between the Y axis title and the Y axis labels. In the screenshot you captured the maximum % goes up to 9, but it can go to 100%, at which point there are two more characters worth of width added to the labels. Reducing the Y axis title spacing risks overlapping the title with the labels.

On the missing data front, the line does interpolate between gaps where they exist within a single series, but the mouseover does highlight to users exactly where the data points are.

On the zoom function, do you mean the "Click to open in new window" when JS is disabled? This would need to be removed in code @edwinmp 

The point on changing “Poorest 20%” to “People in poverty” is probably a messaging one. I think the latter is probably too vague for a factsheet about the P20, but we should ask Claudia/Zach.

It's not easily possible to add bold sections to the dropdown. The code @edwinmp wrote abstracts the population of the dropdowns, and I don't think we could quickly add categories.

Otherwise, here's my todo from your notes:

- [ ] Align Y axis titles to the top of the grid
- [ ] Add more padding underneath the dropdowns
- [ ] Increase tooltip fontsize with CSS
- [ ] Increase padding between legend lines and legend text
- [ ] Align legend rectangles with beginning of lines
- [ ] Change example lines to shades of grey
- [ ] Reduce the hue of the tooltip highlight dot when it's over a post-Covid line
- [ ] Change legend copy to read like "Before Covid-19: Estimated poverty %"
- [ ] Change tooltip copy to read like "Estimate: Before Covid-19"
- [ ] In the data, change "Other High Income" to "High-income countries"

**Comment by SimonMurphyDI** [comment]
@akmiller01 
Are there any cases in figure 1 where there's no data? (wondering what the visual would show if there was a country chosen that didn't have data against one that did)

**Comment by akmiller01** [comment]
There are no countries/regions with absolutely no data. The country with the least amount of data is Kosovo (which had estimates in the 2019 WEO but no estimates in the 2020 WEO).

**Comment by alice-mcandrew-development-initatives** [comment]
Thanks, @akmiller01. That all makes sense :) 

Yes, I meant disable the "Click to open in new window" function for interactive charts. So, yes, I think it would be great if @edwinmp could do this.

**Comment by edwinmp** [comment]
@akmiller01 the document is new to me & there's lots in there ... could you tag me on feedback that'll need my input ... 
On the dropdowns, I'll update them to accept options that specify value & caption... Should give u more flexibility with the visible naming. Not touching any of the d3 stuff :)

Probably too late to give it a go, but if you do find time to check it out [Plottable](https://github.com/palantir/plottable#plottable--) reduces the headache of d3 ... let me know if you want me to add it to our list of supported libraries. It is what built the charts of the data hub.
