### ISSUE TITLE
Hide figure pages from Datasets Index page, Resource Pages, and Dataset pages

### ISSUE THREAD

**Issue by akmiller01** [devinit/DIwebsite-redesign#907]
Remove all references to figure pages, as we're not using them anymore.

**Comment by akmiller01** [comment]
Completed here, also adding the topic amends to the same PR so draft for now: https://github.com/devinit/DIwebsite-redesign/pull/914

This will absolutely erase every figure page from the website, so we need to make sure we've got everything from them we need before erasing them.

Also worth considering running something to make redirects for every existing Figure page before we erase all of them?

Alternative @edwinmp ... We just remove all links to Figure pages, but keep them around? Or is that too untidy?

**Comment by akmiller01** [comment]
Hi @k8hughes I had started on this issue but it raised an interesting question before I could continue. Do we delete the figure pages and create redirects? Or just remove links to them and keep them around?

**Comment by k8hughes** [comment]
I think we can delete them tbh as I can't think of why we'd still need them.

**Comment by akmiller01** [comment]
Okay, in that case I think we should set up a redirect for all of the URLs. So if someone has a Figure Page bookmarked, or Google cached the link, they get brought back to the Dataset Listing page instead of a 404.

**Comment by k8hughes** [comment]
Perfect!

**Comment by akmiller01** [comment]
Done. Current figure pages have been deleted and their previous URLs redirected. https://github.com/devinit/DIwebsite-redesign/pull/914 Will erase the model from the backend.
