### ISSUE TITLE
Entirely code-based chart prototype

### ISSUE THREAD

**Issue by edwinmp** [devinit/DIwebsite-redesign#908]
**Resources**

Code Pen: https://codepen.io/edwinmp/pen/WNwLGbN
Ace Editor: https://ace.c9.io/

Further Inspiration:
- Echarts: https://echarts.apache.org/examples/en/index.html

**Implementation**

- Create a new page type under Visualisations
- Fields of the new chart page type include:
    - Library: a drop down that allows selection of the charting library used to render this chart e.g. Plotly, D3, ECharts e.t.c
    - CodePen Link: a link to a functional codepen (if available) where edits can be made and tested in realtime
    - HTML: an ace-editor field that takes in HTML
    - CSS: an ace-editor field that takes in CSS
    - JS: an ace-editor field that takes in JS
    - A few fields from the existing `Chart Page` e.g fallback image options, instructions, caption

**Comment by k8hughes** [comment]
@edwinmp for the review side of this what do we want to do?  Is it a case of a CMS user being happy they can make a factsheet with the code for a chart having been input by a developer first?

**Comment by edwinmp** [comment]
@k8hughes the Advanced Charts can be pulled through in any resource-type page, so this shouldn't stall the creation of factsheets ... feedback is being given in issue #904 so I'll close this.
