### ISSUE TITLE
Link Duplication on Spotlight Pages

### ISSUE THREAD

**Issue by sarahharries66** [devinit/DIwebsite-redesign#910]
## I'm submitting a ...
<pre><code>
[x ] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
On spotlight pages, links within the footer appear to be duplicating from the 'Get Around' section, into the 'Policies and Statements' and 'Get In Touch' sections. 

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to https://devinit.org/data/spotlight-uganda?t=uganda_poverty_and_vulnerability&i=spotlight_on_uganda_2017.uganda_poverty_headcount&y=2014
OR
https://devinit.org/data/spotlight-kenya?t=kenya_population&i=spotlight_on_kenya_2017.kenya_total_pop&y=2025

2. Scroll down to footer sections
4. See 'Who we are, What we do, How we work, Resources, Data, Blog and Work for us links permeating across all three headings 

**Expected Behaviour**
links to be categorised under their correct heading as with other pages on the site, eg: 
![DesiredBehaviour_LI](https://user-images.githubusercontent.com/69594823/94679626-52e88280-0318-11eb-90d3-83ba7ac6ab49.jpg)

**Screenshots/GIF**
Current problem:
![Unusual Behaviour_LI](https://user-images.githubusercontent.com/69594823/94679907-ca1e1680-0318-11eb-8c77-66620d828560.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: dd/MMM/YYYY

**Comment by edwinmp** [comment]
This is fixed https://devinit.org/data/spotlight-uganda
