### ISSUE TITLE
Removing links to authors who no longer have staff profiles

### ISSUE THREAD

**Issue by sarahharries66** [devinit/DIwebsite-redesign#911]
**Is your feature request related to a problem? Please describe.**
When staff who are accredited on publications leave DI, their name still links to their staff page which is removed when they leave. 

![Spotlight on Uganda - Google Chrome 30_09_2020 12_59_01_LI](https://user-images.githubusercontent.com/69594823/94682718-46b2f400-031d-11eb-906b-de76be581120.jpg)
![Spotlight on Uganda - Google Chrome 30_09_2020 12_59_14](https://user-images.githubusercontent.com/69594823/94682727-4adf1180-031d-11eb-9e6d-3547a9597631.png)

**Describe the solution you'd like**
When staff leave DI we'd like their author hyperlink on their published work to be removed automatically, rather than linking to their removed staff page. Therefore leaving the author credit on a publication with just their name as text, rather than being a link to their page which is not longer active. 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Requested Delivery Date:** dd/MMM/YYYY

**Comment by sarahharries66** [comment]
@akmiller01 I believe this has been mentioned to you

**Comment by akmiller01** [comment]
Included a couple images here. https://github.com/devinit/DIwebsite-redesign/pull/912

Please note, this only functions if author pages get unpublished instead of deleted. If they're deleted, it can create a blank author block when they're the only author.

**Comment by edwinmp** [comment]
@sarahharries66 this is ready for review on staging https://dev.devinit.org/resources/blended-finance-poorest-people/

**Comment by sarahharries66** [comment]
Hi, this appears to be working well, thankyou for sorting this out!
