### ISSUE TITLE
Change to how pages show as related content 

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#913]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[ ] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
A clear and concise description of what the issue is.

Hiya! When we select a page as related content, it shows the date that page was published. So this looks different from resources (and so it doesn't look out of date) please can we change it so pages don't pull dates through?
![image](https://user-images.githubusercontent.com/22001094/94781049-36eceb80-03c1-11eb-8fc4-3fc6f942dee7.png)
Thanks
Simon

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.

**Expected Behaviour**
A clear and concise description of what you expected to happen

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: dd/MMM/YYYY

**Comment by davidebukali** [comment]
@SimonMurphyDI is this the preferred behavior only on [publication pages](https://devinit.org/resources/uganda-disability-data-landscape-economic-inclusion-persons-with-disabilities/)  or across all resources (AudioVisualPages, LegacyPublications etc)

**Comment by SimonMurphyDI** [comment]
@davidebukali - all pages please! :)

**Comment by davidebukali** [comment]
@SimonMurphyDI alright, thanks :)

**Comment by davidebukali** [comment]
@SimonMurphyDI when you get time, this is ready to test on [staging](https://dev.devinit.org/)

**Comment by SimonMurphyDI** [comment]
Hi @davidebukali - the date has been removed for all pages, resources, blogs etc. It's important we keep it for resources and blogs, etc ... the only place we don't want a date to pull through is on pages, as this is content that should be up to date (and so it doesn't matter when it was published). It does matter to the user when a report was published.

**Comment by edwinmp** [comment]
@SimonMurphyDI that's confusing as they're all pages ... could you please share links of pages u want it to show and those u don't want it showing.

**Comment by edwinmp** [comment]
My understanding is that you only want it to show for resources, blogs, news, events (am I missing any ... no e.t.c) ...

**Comment by SimonMurphyDI** [comment]
Sorry for not being clear.

We'd like all pages under 'resources', 'data' and 'blog' to SHOW dates when they appear as related or featured content

We'd like all pages under 'who we are', 'what we do'. ' how we work' and 'work for us' NOT to show a date when they pull through as related or featured content

Let me know if there's anything I've missed there
S

**Comment by SimonMurphyDI** [comment]
@edwinmp - confirmed, no need to show the date an event page was created when it pulls through as related content. 
Thanks so much
Simon

**Comment by davidebukali** [comment]
@SimonMurphyDI this is ready for testing, it only shows the date for resources, blogs and news https://dev.devinit.org/resources/?nav=header

**Comment by alice-mcandrew-development-initatives** [comment]
@davidebukali This looks good to me - thank you for making the change!

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives @SimonMurphyDI this has been deployed live.
