### ISSUE TITLE
Reducing the size of notes section on reports

### ISSUE THREAD

**Issue by sarahharries66** [devinit/DIwebsite-redesign#917]
**Is your feature request related to a problem? Please describe.**
When on report pages such as https://devinit.org/resources/socioeconomic-impact-of-covid-19-in-uganda/#downloads , the notes section at the bottom is unnecessarily lengthy. 

**Describe the solution you'd like**
To mitigate this, we would like to take the GNR website as an example, and implement a 'show more' button so the long list can be optionally extended, see at the bottom of this page: https://globalnutritionreport.org/reports/2020-global-nutrition-report/introduction-towards-global-nutrition-equity/
Ideally the 'show more' button would be placed after 5 notes. 

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/69594823/95586721-f896a280-0a38-11eb-8827-41fddcf8eb76.png)
![image](https://user-images.githubusercontent.com/69594823/95586785-0fd59000-0a39-11eb-9319-ba1452538ec2.png)

**Requested Delivery Date:** dd/MMM/YYYY

**Comment by sarahharries66** [comment]
@k8hughes I've been told to copy you in on this :)

**Comment by edwinmp** [comment]
We'll copy it right off GNR then ... thanks so much for providing links @sarahharries66... those are always a great help

**Comment by sarahharries66** [comment]
No problem! helps get my head around the request too!

**Comment by edwinmp** [comment]
@sarahharries66 this is ready for testing https://dev.devinit.org/resources/socioeconomic-impact-of-covid-19-in-uganda/#downloads

**Comment by alice-mcandrew-development-initatives** [comment]
@edwinmp this look goods but can we have the 'SHOW MORE' button after 5 notes rather than 10 please?

**Comment by k8hughes** [comment]
@davidebukali  seeing as Edwin is on leave would you be able to make this change?  Only do it if it would be simple and easy for you to do, if it makes more sense to wait for Edwin to do in Jan then just comment on the ticket so we know it is being left for his return.

**Comment by davidebukali** [comment]
@sarahharries66 this was updated to show 5 footnotes, you can test here https://dev.devinit.org/resources/socioeconomic-impact-of-covid-19-in-uganda/#downloads

**Comment by alice-mcandrew-development-initatives** [comment]
Perfect @davidebukali ! Thanks very much

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives this update has been deployed live.
