### ISSUE TITLE
Featured content open to all page types

### ISSUE THREAD

**Issue by sarahharries66** [devinit/DIwebsite-redesign#918]
**Is your feature request related to a problem? Please describe.**
Currently, featured content can only be chosen from a specific set of page types thus limiting what we can show: 
![Wagtail - Editing Home Page_ Homepage - Google Chrome 09_10_2020 14_19_05_LI](https://user-images.githubusercontent.com/69594823/95587808-7f984a80-0a3a-11eb-9fad-554b61acfeb5.jpg)

**Describe the solution you'd like**
As we add more page types, rather than requesting them individually, we'd like to be able to choose from all existing page types for featured content on the homepage through some form of drop down/selection etc. 

**Describe alternatives you've considered**

**Additional context**

**Requested Delivery Date:** dd/MMM/YYYY

**Comment by edwinmp** [comment]
@sarahharries66 this is ready for testing on staging.

**Comment by sarahharries66** [comment]
Hi this is looking good! Thankyou for the change!
