### ISSUE TITLE
Add social sharing for website events

### ISSUE THREAD

**Issue by davidebukali** [devinit/DIwebsite-redesign#928]
**Describe the solution you'd like**
Share website events to social media sites the same way publications work. See attached image

**Describe alternatives you've considered**

**Additional context**

**Requested Delivery Date:** dd/MMM/YYYY

![social](https://user-images.githubusercontent.com/1607276/96595504-67ef7a80-12f4-11eb-8222-c638133218a2.png)

**Comment by alice-mcandrew-development-initatives** [comment]
Looks perfect thank you @davidebukali

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives this update has been deployed live.
