### ISSUE TITLE
T8a - Where we work

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#93]
Developed from T8 late in the process. 

Design: http://development-initiatives.surge.sh/page-templates/08a-where-we-work

Functional specification:

This template shows a single place. 

We have the standard hero here, with page title and hero content, plus the image with credit if required.

There's the sidebar menu on the right, which has had a recent update to the way the title is spelled out "More about:" being the thing that has changed. What should happen there is the "More about:" will be fixed and the "What we do" will be the top page of the section that has this menu. So, What we do, Who we are etc. etc.

Under the breadcrumb we have standard editor content - text & images etc.

Then we have a list of places we work. There are two types of this you can see in the template. We have Countries, and Regions. For both there are common elements and then just the one variation. Common elements are: 

- title
- subtitle
- content

Then we have the ability to link to "places" pages. These sit underneath this in the site heirarchy: 

![Screen Shot 2019-07-26 at 11 32 56](https://user-images.githubusercontent.com/64877/61945972-47256180-af99-11e9-84e2-5c26edc512a9.png)

As you can see from the design, the variation is the number of 'place pages' each 'place' links to. When it is a country, e.g. Nepal, it would have a button to link to a place page called Nepal. When it is a region, e.g. E Africa, it will have multiple buttons to cover a selection of places e.g. Uganda, Kenya. At the time of writing it is uncertain exactly how this content will be structured, so this will need to be flexible. I could be entirely possible that we could have a E Africa box, and only link to a page called E Africa. I'm happy to jump on a call to go through this, or preview things you're creating if that helps. 

~~Lastly, there is a "Related content" section. For this one that title should be editable, as we may want to have some fine grained control over that content. Then three items are selectable by the admin. These can pretty much be any type of content on the website.~~  - Removes from updated design

**Comment by benjamincoleman** [comment]
Map - remove but use a screenshot as the hero image.

Places we have worked  ← Places we work

**Comment by benjamincoleman** [comment]
Can we focus the screenshot on the equator please? 
Size for hero images = 1600px by 780px. Here's a PSD to help: https://www.dropbox.com/sh/hiy731zp3iyzt8a/AAC-Apn19-A1xEsTrYi80TnOa?dl=0

**Comment by BenDarby** [comment]
Yeah sure, I don't have Photoshop so I'll do it in sketch

**Comment by benjamincoleman** [comment]
I suggest purchasing Adobe Elements - it’s about £70 and gives you all photoshop stuff you’d need.

B

**Comment by Napho** [comment]
![hero-image-equator](https://user-images.githubusercontent.com/1554385/61890523-856e4280-aeff-11e9-8e6c-1c92738cb292.png)

Would that help?

**Comment by Napho** [comment]
![hero-image-equator2](https://user-images.githubusercontent.com/1554385/61890926-78058800-af00-11e9-9440-2f5de07dc035.png)

Or with just the equator adjustment to center and no scaling

**Comment by edwinmp** [comment]
@benjamincoleman the surge link for this is broken...

**Comment by benjamincoleman** [comment]
@edwinmp fixed - one of the last reviews updated the name from 'places we work' to 'where we work'. Sorry :)

**Comment by edwinmp** [comment]
Hi @benjamincoleman ... the description above describes the "Related content" section in a way that conflicts with what's on surge ... could you please clarify

**Comment by benjamincoleman** [comment]
@edwinmp looks like we removed it in the end - I've updated the spec. Thanks :)

**Comment by k8hughes** [comment]
I have made a where we work page:  http://178.128.102.213/where-we-work/ 

I could work out how to get the buttons on the side as per pattern library reference, I actually got really confused because when I made a place page there was an option for a button with text, but this then apears in the hero of the place page:  http://178.128.102.213/where-we-work/our-work-uganda/

As a user it was not clear to me how to fill out the content to get it to reflect the designs.

**Comment by k8hughes** [comment]
We are missing the links through to the child pages.
The image below shows the pattern library version of the page next to staging.  For staging I have made the Uganda child page but there was no way to link it back to the East Africa section...
![Screenshot 2019-08-15 at 11 54 51](https://user-images.githubusercontent.com/36768381/63090543-8b31d380-bf53-11e9-9900-1eb674ec3fcd.png)

**Comment by edwinmp** [comment]
![image](https://user-images.githubusercontent.com/5672438/63160196-e207dd80-c025-11e9-918e-f68222c2964e.png)

@k8hughes those last two options (side section title & links) in the stream field are how you populate the links...

**Comment by edwinmp** [comment]
![image](https://user-images.githubusercontent.com/5672438/63160481-8ab63d00-c026-11e9-8afc-d102274d0541.png)


![image](https://user-images.githubusercontent.com/5672438/63160460-7e31e480-c026-11e9-9a66-a86db468ce8e.png)

**Comment by k8hughes** [comment]
Ah ok, this is now clear. LGTM
