### ISSUE TITLE
Participant names not showing on AV pages 

### ISSUE THREAD

**Issue by sarahharries66** [devinit/DIwebsite-redesign#930]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x ] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
Participant boxes are currently not appearing on AV pages:
![Wagtail - Editing Audio and Visual Media Page_ How can innovative partnerships make data stronger and more inclusive_ - Google Chrome 22_10_2020 10_00_01_LI](https://user-images.githubusercontent.com/69594823/96851355-d7c64800-144f-11eb-8ad8-d79f19dab643.jpg)

**To Reproduce**
1. Go to https://devinit.org/resources/innovative-partnerships-data-stronger-inclusive/
2.  See lack of participant/author/credit box
3. See error

**Expected Behaviour**
Currently, this is being managed by the inclusion of participant names and links in paragraph text, although it would be great to have the participant box visible. As it's not currently working, we can't determine what it's supposed to look like, but are guessing it's like a [report](https://devinit.org/resources/uganda-disability-data-landscape-economic-inclusion-persons-with-disabilities/) or [blog](https://devinit.org/blog/beyond-vested-interests-reforming-international-cooperation-post-covid-19/) author/credit box.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: dd/MMM/YYYY

**Comment by davidebukali** [comment]
@sarahharries66 this was covered in issue #937

**Comment by edwinmp** [comment]
@davidebukali this is probably already deployed, so I'm closing it.
