### ISSUE TITLE
CMS search function for related content

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#931]
The search function for related content on the cms is not pulling up desired results. For example, I've typed a publication name word for word but it does not appear among the search results.

I am on this page: https://devinit.org/resources/global-humanitarian-assistance-report-2020/
and trying to select this page as related content on the cms: https://devinit.org/resources/financing-humanitarian-needs-amid-the-covid-19-pandemic/

![image](https://user-images.githubusercontent.com/55877063/97169431-f98e3a80-1781-11eb-8bc1-95571b5dcfbd.png)

Is this something that can be resolved by indexing more frequently? I think we've done a similar thing elsewhere on the cms previously.

**Comment by alice-mcandrew-development-initatives** [comment]
You encounter the same problem when trying to link to this factsheet (https://devinit.org/resources/financing-humanitarian-needs-amid-the-covid-19-pandemic/) from the homepage

**Comment by davidebukali** [comment]
@alice-mcandrew-development-initatives manually updating the index includes both missing factsheet and page in [search results](https://devinit.org/admin/pages/2098/edit/) We are working on improving this process so that it updates as resources are added.

**Comment by alice-mcandrew-development-initatives** [comment]
Thanks for the update @davidebukali 
Let me know when you need me to review anything

**Comment by davidebukali** [comment]
@alice-mcandrew-development-initatives yes, kindly review to see if the issue persists.

**Comment by alice-mcandrew-development-initatives** [comment]
Thanks @davidebukali. I think the best way to test this will be to see how the cms search function works just after we've published a new resource - and we should be able to do this at the end of the week.

**Comment by alice-mcandrew-development-initatives** [comment]
I've realised I won't be able to check this today/tomorrow because the resource coming out this week is an update of an existing page. I can check the cms search function in the first week of January after we publish our next report.

**Comment by alice-mcandrew-development-initatives** [comment]
I created this short publication page a couple of hours ago: https://devinit.org/admin/pages/2283/edit/
It's currently a draft and doesn't appear on the cms search function yet.

I tested this on the homepage: https://devinit.org/admin/pages/3/edit/
![Screenshot (200)](https://user-images.githubusercontent.com/55877063/104621866-7ac1e300-5688-11eb-9f69-1a30cc952794.png)

I also tested it on another short publication page: https://devinit.org/admin/pages/2242/edit/
![Screenshot (201)](https://user-images.githubusercontent.com/55877063/104621879-7e556a00-5688-11eb-8700-6fd235108f28.png)

How quickly should we be expecting to appear? I will let provide an update on if anything changes when the page is published.

**Comment by alice-mcandrew-development-initatives** [comment]
The cms search function for selecting snippets also doesn't pull up the factsheet. I needed to scroll to page 5 to find this: 
![Screenshot (203)](https://user-images.githubusercontent.com/55877063/104627638-2ff79980-568f-11eb-96ac-31338ce8788a.png)
![Screenshot (202)](https://user-images.githubusercontent.com/55877063/104627634-2d953f80-568f-11eb-8e17-facc9da99e2b.png)

Shall I create a separate issue for this? It seems related but will be guided by devs.

**Comment by alice-mcandrew-development-initatives** [comment]
The report is published but the cms search function still does not seem to pick it: 
<img width="957" alt="2" src="https://user-images.githubusercontent.com/55877063/104944983-ede09780-59af-11eb-9d8a-b621a69af556.PNG">
This means you have to manually click through 14 pages to find it: 
<img width="958" alt="1" src="https://user-images.githubusercontent.com/55877063/104944894-cd184200-59af-11eb-80a1-c0d8894dabc6.PNG">

**Comment by davidebukali** [comment]
@alice-mcandrew-development-initatives we updated the index to auto update for every draft or published page. Kindly test on development server https://dev.devinit.org/admin/pages/352/

**Comment by alice-mcandrew-development-initatives** [comment]
@davidebukali, I can confirm this is working! Thank you very much. The staging site (as a whole) is loading incredibly slowly at the moment though. I'm not sure if this is just my poor internet connection or an actual issue.

**Comment by davidebukali** [comment]
@alice-mcandrew-development-initatives we had the same experience with slow loading on staging. Edwin fixed this recently with a redeployment https://dev.devinit.org/who-we-are/?nav=header

**Comment by alice-mcandrew-development-initatives** [comment]
It's much faster than it was. But some of the pages are still quite slow for me (using FireFox), such as:

- https://dev.devinit.org/who-we-are/?nav=header
- https://dev.devinit.org/what-we-do/?nav=header
- https://dev.devinit.org/how-we-work/?nav=header

Is anyone else having the same experience?

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives this is now live
