### ISSUE TITLE
Hero for executive summary pages don't match other child pages for longform publications

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#933]
**Summary**

The executive summary child page for longform publication pages currently doesn't match other child pages (the chapters) in that:
1. It is missing the publication title in the hero
2. It has hero text appearing on the child page (when this copy should only be visible on the parent page)

For example, it currently looks like this (https://devinit.org/admin/pages/2237/view_draft/):
![image](https://user-images.githubusercontent.com/55877063/97600840-682cfb80-1a01-11eb-8d9a-c108b39e1dcf.png)

But it should look more like this (https://devinit.org/admin/pages/2239/edit/preview/):
![image](https://user-images.githubusercontent.com/55877063/97601399-0a4ce380-1a02-11eb-8850-61e0db8cfee0.png)

**Part one**

Please can we update so that above the page title on each executive summary page we see: "[Publication title]: Executive summary" (as we have "[Publication title]: Chapter X" above).

**Part two**

Please can we also update so that the hero copy (example of where this is found in the cms below) only appears on the publication summary page.
![image](https://user-images.githubusercontent.com/55877063/97602093-ce664e00-1a02-11eb-8142-3bb141690552.png)

For example, on this publication (https://devinit.org/resources/uganda-disability-data-landscape-economic-inclusion-persons-with-disabilities/) the hero copy for the executive summary should only appear here:
![image](https://user-images.githubusercontent.com/55877063/97602240-fbb2fc00-1a02-11eb-9f97-b48dfaaf8942.png)

We're publishing two longform publications on Thursday 5 November so it'd be great if this could be changed by then. If that's not feasible, the deadline would be just as soon as you can, as it's taken this long for me to notice (!) so I presume it's not something our audience will be picking up on...

**Comment by edwinmp** [comment]
Hi @alice-mcandrew-development-initatives will have this ready for testing by end of day tomorrow.

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives using this as an example, you don't want the hero text to appear on this page?
https://devinit.org/resources/global-humanitarian-assistance-report-2020/executive-summary/

**Comment by alice-mcandrew-development-initatives** [comment]
Exactly, there should be no hero visible on any executive summary pages, including this one: https://devinit.org/resources/global-humanitarian-assistance-report-2020/executive-summary/ (It should only be visible on the longform publication summary)

Thanks for checking @edwinmp !

**Comment by edwinmp** [comment]
Hi @alice-mcandrew-development-initatives this has been deploy to staging for testing https://dev.devinit.org/resources/global-humanitarian-assistance-report-2020

**Comment by alice-mcandrew-development-initatives** [comment]
Looks great - thank you very @edwinmp :)
