### ISSUE TITLE
Maps are looking strange on the dI website

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#936]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X ] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
A clear and concise description of what the issue is.

Hi there, when we access this page 
https://devinit.org/who-we-are/?nav=header
The map isn't behaving as expected .... seems to be made up of large pixels. It's the same when I zoom in, and when I use my phone. 

Thanks
Simon

![image](https://user-images.githubusercontent.com/22001094/99700845-9e531d80-2a8b-11eb-89dd-bef8a4cacc12.png)

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.

**Expected Behaviour**
A clear and concise description of what you expected to happen

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: dd/MMM/YYYY

**Comment by benjamincoleman** [comment]
Also checked the pattern library and it appears the same there: http://development-initiatives.surge.sh/page-templates/03-who-we-are

**Comment by benjamincoleman** [comment]
@BenDarby it appears to be something to do with the styling of the water.

Looking at this file: https://github.com/devinit/DIwebsite-redesign/blob/develop/patterns/assets/js/utils/gmaps.js#L66

Removing these lines prevents the odd distortion effect.

```
        {
            "featureType": "water",
            "stylers": [
                {
                    "visibility": "off"
                }
            ]
        }
````

So, can you re-produce the style you wanted and add that back into the gmaps.js file please.

**Comment by davidebukali** [comment]
@SimonMurphyDI this is ready for testing on staging server https://dev.devinit.org/what-we-do/?nav=header

**Comment by SimonMurphyDI** [comment]
Looks good to me @davidebukali - thanks 👍 
Looks like the same issues will be fixed on this page: https://devinit.org/who-we-are/?nav=header
best
Simon

**Comment by davidebukali** [comment]
Thanks for the review @SimonMurphyDI I created issue #947 to fix the same problem on who we are page

**Comment by edwinmp** [comment]
@SimonMurphyDI this fix has been deployed live.
