### ISSUE TITLE
Data page menu not picking up content on page

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#938]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x ] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**

I feel like I might have raised this before (sorry if so!) but on the data page, there's content that the menu isn't picking up

![image](https://user-images.githubusercontent.com/22001094/99960316-7104b900-2d84-11eb-8205-97a020db27cc.png)

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.

**Expected Behaviour**
It would be ideal if the menu showed the user the page content up top to help them navigate

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: dd/MMM/YYYY

**Comment by edwinmp** [comment]
Hi @SimonMurphyDI what isn't the menu showing? It's currently showing child pages that have been checked as "Show in menus" ... If there's any more child pages you wish to appear here, please set them up to show in menus
![image](https://user-images.githubusercontent.com/5672438/99962487-52f98180-2da1-11eb-8e43-942b7a88b619.png)

**Comment by SimonMurphyDI** [comment]
Thanks @edwinmp - I wondered what that button does...! Do you know how to amend the order of the items on the menu (maybe it's generated by date....)


![image](https://user-images.githubusercontent.com/22001094/99962913-dfe41100-2d88-11eb-979b-e8c206cc4722.png)

**Comment by edwinmp** [comment]
Click the sort button then drag-drop the pages in the order you want them.

<img width="798" alt="Screenshot 2020-11-23 at 16 16 34" src="https://user-images.githubusercontent.com/5672438/99966562-8b9c5980-2da7-11eb-93fd-e3cbd561b829.png">

**Comment by SimonMurphyDI** [comment]
thanks so much
