### ISSUE TITLE
T8.1a - Place

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#94]
Created late on in the design process. 

Design - http://development-initiatives.surge.sh/page-templates/08-1a-place

Functional specification:

This template shows a single place.

We have the standard hero here, with page title and hero content, plus the image with credit if required.

There's the sidebar menu on the right, which has had a recent update to the way the title is spelled out "More about:" being the thing that has changed. What should happen there is the "More about:" will be fixed and the "What we do" will be the top page of the section that has this menu. So, What we do, Who we are etc. etc.

Under the hero we have a breadcrumb to aid wayfinding.

Under the breadcrumb we have standard editor content - text & images etc.

We have the ability to feature a country spotlight here. This modules consists of: 
- title
- content with formatting / links
- button with link
- image

Lastly, there is a "Related content" section. For this one that title should be editable, as we may want to have some fine grained control over that content. Then three items are selectable by the admin. These can pretty much be any type of content on the website.

**Comment by edwinmp** [comment]
**NB:** We shall use a standard page to create this, so there won't be a specific "Place" page ... i.e once I'm done with "Where we work", the individual place pages shall be created based on the Standard Page template.

**Comment by k8hughes** [comment]
And I have made a places page:  http://178.128.102.213/where-we-work/our-work-uganda/
I think there is some elements that are not the right way round
I expected the button to appear on the where we work page, next to a suggested place:  http://development-initiatives.surge.sh/page-templates/08a-where-we-work
instead it appears in the hero on the place page
this could be down to user error, but between these two templates I think you have some fields in the wrong place.

**Comment by Napho** [comment]
> http://178.128.102.213/where-we-work/our-work-uganda/

Its a usability issue, the hero section used is generic for any standard page. Some standard pages have page links (like the one you created) while others don't. If you don't need a page link leave the **hero_link** & **hero_link_caption** fields empty from the admin section. It will be omitted

**Comment by k8hughes** [comment]
Ok, this means the problem is with the parent page, I have mae a note on that issue.

**Comment by edwinmp** [comment]
There's no problem ... you just have to use the correct stream fields. In this case, you have to use section stream fields. Also, creating a places page doesn't automatically add it to the "where we work" page... that's not how FF planned it to be. In the "where we work" page, you have to manually select the pages you want to link.

![image](https://user-images.githubusercontent.com/5672438/63160885-88081780-c027-11e9-9434-820995350deb.png)
