### ISSUE TITLE
External author bio link

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#946]
**Problem:** Links to external author bios do not appear to be working

**Example:** https://devinit.org/blog/beyond-vested-interests-reforming-international-cooperation-post-covid-19/

**Expected behaviour:**
Clicking on name of author (if underline appears when hovering) takes user to the external webpage specified in the cms
![image](https://user-images.githubusercontent.com/55877063/104191328-48f51600-5415-11eb-9bfb-77d873f81512.png)
![image](https://user-images.githubusercontent.com/55877063/104191293-3d095400-5415-11eb-8442-62132622a406.png)

**What actually happens:**
User returns to same page, but with addition to end of URL
"?referrer=author": https://devinit.org/blog/beyond-vested-interests-reforming-international-cooperation-post-covid-19/?referrer=author

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives ready for review https://dev.devinit.org/blog/why-we-need-global-public-investment-after-covid-19/

**Comment by alice-mcandrew-development-initatives** [comment]
@edwinmp To test this I changed the link in the cms to an external page...
![image](https://user-images.githubusercontent.com/55877063/104461250-006d6200-55a7-11eb-9fcc-39c40d470dbd.png)
...and it still seems to be working, so thank you for making that update!

I am getting some odd behaviour on the [our team](https://dev.devinit.org/who-we-are/our-team/?nav=header?referrer=author) page though and not sure if this is a knock-on effect or something else:
![image](https://user-images.githubusercontent.com/55877063/104461395-314d9700-55a7-11eb-8865-42f2158d9ca0.png)

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives  That's happens cos we're missing several profile images on the dev version, so don't worry about it unless it's happening live.

**Comment by alice-mcandrew-development-initatives** [comment]
The live site looks fine @edwinmp - thanks for explaining that behaviour

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives this fix has been deployed live.
