### ISSUE TITLE
Related content on event pages

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#950]
Can we have the option to add other page types as related content for event pages?

For example, on this event page... https://devinit.org/admin/pages/2284/edit/
...we could like to be able to add this page as related content: https://devinit.org/what-we-do/what-we-are-working-on/data-support-disability-inclusion/

![Screenshot (199)](https://user-images.githubusercontent.com/55877063/104620684-2ff39b80-5687-11eb-9002-0a4045d51877.png)

**Comment by alice-mcandrew-development-initatives** [comment]
I believe we made a similar change for publication pages previously

**Comment by davidebukali** [comment]
@alice-mcandrew-development-initatives we deployed this to staging, kindly test when you get the chance https://dev.devinit.org/admin/pages/2091/edit/

**Comment by alice-mcandrew-development-initatives** [comment]
Thanks, @davidebukali. It seems to be working. I've successfully added this page as related content: 'Strengthening knowledge of humanitarian assistance'. The thumbnail isn't completely loading but I think this is just because my internet connection is bad at the moment so a problem my end rather than an issue with the development!

![image](https://user-images.githubusercontent.com/55877063/105486634-b4a57180-5ca6-11eb-9299-5f406a763c92.png)

**Comment by davidebukali** [comment]
@alice-mcandrew-development-initatives the staging server does not have images for some publications so occasional blank thumbnails is normal. Mainly text was imported from the live server.

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives I've added some new images and they thumbnails are now showing https://dev.devinit.org/what-we-do/events/stocktake-global-humanitarian-assistance-during-covid-19-pandemic/

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives this fix is live
