### ISSUE TITLE
Links on the website footer no longer lead to a PDF download

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#953]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
A clear and concise description of what the issue is.

On the hompage (or any page) clicking on the first three links highlighted below doesn't prompt the policy PDFs to download. The fourth link works as it should. We haven't made amends to the documents or the way this is set up in the CMS - can you take a look? 

Not very urgent, but important in case a potential funder wants to read our policies 

thanks
Simon

![image](https://user-images.githubusercontent.com/22001094/105834905-fc880980-5fc2-11eb-92d5-defd2b7acd4f.png)

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.

**Expected Behaviour**
A clear and concise description of what you expected to happen

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: dd/MMM/YYYY

**Comment by edwinmp** [comment]
@SimonMurphyDI I've tested all of them and they work fine ... @devinit/di-devs can anyone else replicate this issue?

**Comment by akmiller01** [comment]
Links are working for me @edwinmp , maybe this is a browser/screen specific CSS bug? If an invisible element is overlapping the top 3 links only for @SimonMurphyDI , that would explain why they're not working.

@SimonMurphyDI , if this happens to you again can you right-click on one of the non-working links, select "Inspect Element" and take a screenshot?

**Comment by SimonMurphyDI** [comment]
@akmiller01 

![image](https://user-images.githubusercontent.com/22001094/105848261-a3c26c00-5fd6-11eb-8751-b407f2fff773.png)

**Comment by SimonMurphyDI** [comment]
Update - it does work if I right click and ask to open in a new tab, but still doesn't if I just click in the list

**Comment by akmiller01** [comment]
Hmm, @edwinmp , the hyperlink is not HTTPS for some reason:

```
Mixed Content: The site at 'https://devinit.org/' was loaded over a secure connection, but the file at 'https://devinit.org/documents/664/Modern_slavery_and_human_trafficking_statement.pdf?nav=footer' was redirected through an insecure connection. This file should be served over HTTPS. This download will be blocked in future versions of Chrome. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.
```

**Comment by akmiller01** [comment]
@SimonMurphyDI 

CMS > Snippets > Footer Sections. You'll need to change the hard-coded `http` to `https` on the links:

![image](https://user-images.githubusercontent.com/2836840/105849544-8679a780-5fae-11eb-8054-7e4d2c901c01.png)

**Comment by akmiller01** [comment]
@SimonMurphyDI potentially anywhere where a hardcoded link could have been used should be HTTPS. Our website automatically redirects to HTTPS, so if you've copied them from the website itself, it should be correct already.

**Comment by edwinmp** [comment]
@SimonMurphyDI was this fixed for you? If so, please close.

**Comment by GeorgeCarver** [comment]
@edwinmp the footer snippets have now been updated so all use https. Thank you!
