### ISSUE TITLE
Resources type tags that should not be visible

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#958]
See the filter on 'Resources' page: https://devinit.org/resources/ 

![Screenshot (214)](https://user-images.githubusercontent.com/55877063/108387218-4c926e80-7205-11eb-87e4-3bc8e0922db5.png)
 
The following should not be visible on the drop-down menu for 'types' of resources:

- Case study [15 results]
- Crisis briefing [68 results]
- Tracker [0 results]

These are listed in the snippets for 'Resource type' but it seems like they have appeared after a recent change to the website was pushed live, rather than being added by anyone in the cms:

![Screenshot (216)](https://user-images.githubusercontent.com/55877063/108388415-844de600-7206-11eb-9f2c-a94ea8969fd5.png)

I'm reluctant to delete the snippets without understanding why/how they have appeared. I could go through and manually remove the tags in the cms for child pages which appear in the results for 'Case study' and 'Crisis briefing' (although this would be very time-consuming). But the 'Tracker' does not return any results, so that wouldn't even be possible:

![Screenshot (215)](https://user-images.githubusercontent.com/55877063/108387788-d6dad280-7205-11eb-9e50-5621119691f7.png)

Please could someone look into whether a change in the code could have caused this.

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives sorry for the delay on this. Not sure about Tracker, but the other two are legacy tags that have always been there.
There was an earlier task to exclude options that returned no results, but I can't find that code. Will add that to my todo for this issue.
Looking into the best way to exclude the others, especially since they're tied to existing publications.

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives I've added a field to the `Resource Types` to control which show up in the filter. It's called `Show in Filter` and is true by default. Please test on [staging](https://dev.devinit.org/) 
![image](https://user-images.githubusercontent.com/5672438/109029452-e8275180-76d3-11eb-91d9-9dabe30d21a4.png)

**Comment by alice-mcandrew-development-initatives** [comment]
@edwinmp just tested - this works well, thank you!

We've got different font for the drop-down and italics for the categories but presume this won't impact the main live site when you push the update through:
![Screenshot (218)](https://user-images.githubusercontent.com/55877063/109041799-531e5b80-76c7-11eb-960f-3a329ecb2928.png)

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives I'm not able to replicate that .. which browser is that?

**Comment by alice-mcandrew-development-initatives** [comment]
I was using Firefox @edwinmp

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives that's a browser disparity ... can add some styling to make it appear more like it does on Chrome, but can't promise it'll be exact.

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives this has been pushed live
