### ISSUE TITLE
Share function on blogs and new stories

### ISSUE THREAD

**Issue by sarahharries66** [devinit/DIwebsite-redesign#959]
At the moment you can ‘share’ Resources on the website (the option shown in the screengrab below).

But blogs and new stories don’t have this feature. It would be great if the same code can be implemented on those page type also

![screenshot](https://user-images.githubusercontent.com/69594823/108842860-cfcf0e00-75d1-11eb-9887-3f6b2c1bbb1b.jpg)

**Requested Delivery Date:** dd/MMM/YYYY

**Comment by edwinmp** [comment]
@davidebukali is my memory playing tricks on me or did you already build this?

**Comment by sarahharries66** [comment]
Hi Edwin! I’ll tag Simon here, I thought there was a request for something similar a while ago but can’t remember if it was specifically this!
Cheers,
Sarah

Sarah Harries | Creative Media Assistant
*Our offices are closed. Here is how to get in touch<https://www.devinit.org/contact-us/> while we are away*
Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK
T: +44 (0) 1179 272 505

DISCLAIMER: This email and any attachments are confidential and intended solely for the use of the individual or organisation to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Development Initiatives. If you have received this email in error, please delete it and notify the sender.

**Comment by davidebukali** [comment]
@edwinmp we added sharing to just events, blogs and stories sounds like a new feature

**Comment by edwinmp** [comment]
@sarahharries66 this has been deployed to [staging](http://dev.devinit.org/)

**Comment by sarahharries66** [comment]
Hi this seems to be working fine for me! @SimonMurphyDI did you want to check it?

**Comment by edwinmp** [comment]
@sarahharries66 this has been deployed live.
