### ISSUE TITLE
Remove 'Standard Page' child page option for Consultancy services

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#961]
Please can we remove the 'Standard Page' child page option for [Consultancy services ](https://devinit.org/what-we-do/consultancy-services/)?

We only need the 'General Page' so deleting the other option will avoid confusion and ensure consistency for us in the future when adding new pages here: 
![Screenshot (219)](https://user-images.githubusercontent.com/55877063/109042470-23238800-76c8-11eb-9e77-d233feed90cf.png)

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives this has been deployed to [staging](http://dev.devinit.org/)

**Comment by alice-mcandrew-development-initatives** [comment]
Looks great @edwinmp thanks!

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives this has been deployed live
