### ISSUE TITLE
Make it so all types of page can be featured at the bottom of blogs

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#964]
**Is your feature request related to a problem? Please describe.**

At the moment you can only pick resources or blogs as related content at the bottom of blogs. It would be amazing if we could have other page types there - like events, and pages.

This is a similar change to one that's already been made for 'events' and 'resources', I think 

Cheers
Simon

![image](https://user-images.githubusercontent.com/22001094/109786258-e3e3c280-7c04-11eb-916d-51715ec5ba53.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Requested Delivery Date:** dd/MMM/YYYY

**Comment by edwinmp** [comment]
@SimonMurphyDI deployed live
