### ISSUE TITLE
Video appearing small

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#965]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[ x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
A clear and concise description of what the issue is.
The video embeded on the strategy page is apearing really small.
 It seems to be extra small - looks to me like a setting in the video / embed as the player has the following style code: 
 max-width: calc(117.5vh); height: calc(85.1064vw);
 That’s actually limiting the width and height making the player look odd.

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to:  https://devinit.org/who-we-are/our-strategy/ 
2.. Scroll down to  the video and see it is really small

**Expected Behaviour**
A clear and concise description of what you expected to happen
 4:3 video is what Ben C suggested in his email to Anna

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Mac Big Sur 11.2.2
 - Browser [e.g. chrome, safari] Firefox

**Environment/Server:**
<pre><code>
- [ x] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: ASAP - Pin has sent out an email directing everyone to this page today

**Comment by edwinmp** [comment]
@AnnaHope I currently can't find a way to fix this since the issue is with the video, that is it's of a bad aspect ratio for where we want to display it. We can't style it differently on our end cos its rendered in an iFrame. Other vimeo videos display just fine. Not sure if there's a way to tweak it on vimeo.

**Comment by AnnaHope** [comment]
Thanks @edwinmp. @jamesharle can you fix this as you are producing the videos and may be able to make this change? Thanks!
