### ISSUE TITLE
Wrong address on page (and is hard-coded)

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#969]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[ X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
On this page (https://devinit.org/contact-us/?nav=footer), there's the UK and US office address. The UK address needs updating, but it's hardcoded so we can't edit it 
![image](https://user-images.githubusercontent.com/22001094/110508985-89150400-80f9-11eb-915f-cd27d5c4e132.png)

The new DI address for the UK is First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK

Please can you amend the page so we can correct this?

Thanks!
Simon

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.

**Expected Behaviour**
A clear and concise description of what you expected to happen

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: dd/MMM/YYYY

**Comment by edwinmp** [comment]
@SimonMurphyDI fix deployed live.
