### ISSUE TITLE
no cookies pop up when you visit the site?

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#999]
## I'm submitting a ...
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
When you visit our website you aren't informed what cookie settings the website has, and what options you have to change these.  

**To Reproduce**
1. Go to the website 

**Expected Behaviour**
On our previous website, when you arrived on the domain, you were given a pop-up that explained our cookie policy. I think we're legally required to explain what cookies the site is using. It would be good to let visitors know if they have the ability to amend the cookies we use. This may require dev if we don't have a pop up with the ability to amend cookie settings. I imagine we'd need this to work on mobile and desktop 

Richard Y has said he's writing text to sit in this box 

We do have a 'notice heading' on the homepage here - could we use this?
http://development-initiatives.surge.sh/page-templates/01-general-page

**Requested Delivery Date**:

This feels very urgent to me - Richard hasn't provided an estimated delivery date for his text

**Comment by edwinmp** [comment]
Hi @SimonMurphyDI, besides the google tag manager, do we have any other trackers that use cookies?

A simple message explaining that we use cookies, maybe with a link to a Wagtail page with our cookie policy would do. If you need one that gives users control over which cookies they allow, then I'll need to know what the cookies are first and see how to get it done.

**Comment by SimonMurphyDI** [comment]
Thanks @edwinmp! I know we use google tag manager and mouseflow. I don't know of any more than that, but think it would be worth confirming this in the chat - will do that

**Comment by edwinmp** [comment]
Hi @SimonMurphyDI, do we have the text that'll sit in this box? I'll be best to have the basic implementation done & deployed while we look into giving the user more control.

**Comment by LouiseSummerlring** [comment]
Hello @edwinmp! I'm helping Simon out with some website stuff at the moment. We do indeed have the text for the cookies pop-up box, and the new and improved cookie policy itself. The policy document is attached, and the text is below.

We use cookies on our website to help us understand how you use the site and to make improvements. These may be used to track your visit to our website or to enable us to personalise your browsing experience, and they may be shared with Google Analytics so that your data can be processed. For more information, please visit our Privacy and Cookie Policy here.”

On the word 'here', we should link to the policy document.
[Privacy_and_cookie_policy.pdf](https://github.com/devinit/DIwebsite-redesign/files/6710005/Privacy_and_cookie_policy.pdf)

Is that all OK? Any questions, just let me know :-)

**Comment by edwinmp** [comment]
That's perfect, thanks @LouiseSummerlring ... will schedule this for early next week if that's alright with you.

**Comment by LouiseSummerlring** [comment]
Wonderful, thanks Edwin!

**Comment by edwinmp** [comment]
Hi @SimonMurphyDI ... this is ready for testing on [dev](https://dev.devinit.org/)

**Comment by SimonMurphyDI** [comment]
@LouiseSummerlring let's have a look at this!

**Comment by SimonMurphyDI** [comment]
This looks good! Can I check how it's set up? 

I'm guessing those users that google tracks as 'returning users' who have seen and clicked off the warning won't see the notice next time they visit the site. But users who appear to be 'new users' will see it?

I also guess that the cookie pop up will appear on whatever page the user first encounters? So if a new visitor were to follow a direct link on Twitter to a report, they'd see the same pop up?

Thanks
Simon

**Comment by edwinmp** [comment]
There's a snippet `Cookie Notices` where the content is created... the rest is ironically handled by cookies.


> I also guess that the cookie pop up will appear on whatever page the user first encounters? So if a new visitor were to follow a direct link on Twitter to a report, they'd see the same pop up?

Yes, it'll appear on any page regardless of the source.

**Comment by SimonMurphyDI** [comment]
Looks good - thanks!

**Comment by edwinmp** [comment]
@SimonMurphyDI I've added the cookie notice to the live site ... please check on it when you have a moment.
